---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= NetApp-Lösung mit gemanagten Container-Plattform-Workloads von Red hat OpenShift
:allow-uri-read: 




== NetApp-Lösung mit gemanagten Container-Plattform-Workloads von Red hat OpenShift

[role="lead"]
Möglicherweise sind Kunden „aus der Cloud hervorgegangen“ oder bereits an einem Punkt der Modernisierung angelangt, wenn sie bereit sind, einige ausgewählte Workloads oder alle Workloads aus ihrem Datacenter in die Cloud zu verschieben. Sie können dafür wählen, von Providern gemanagte OpenShift-Container und von Providern gemanagten NetApp Storage in der Cloud zu verwenden, um ihre Workloads auszuführen. Sie sollten die verwalteten Container-Cluster von Red hat OpenShift in der Cloud planen und bereitstellen, um eine erfolgreiche produktionsbereite Umgebung für ihre Container-Workloads zu schaffen. NetApp bietet vollständig gemanagte Storage-Angebote für Managed Red hat Lösungen in allen drei führenden Public Clouds.

* Amazon FSX für NetApp ONTAP (FSX ONTAP)*

FSX ONTAP bietet Datensicherung, Zuverlässigkeit und Flexibilität für Container-Implementierungen in AWS. Trident dient als dynamische Storage-bereitstellung zur Nutzung des persistenten FSX ONTAP Storage für zustandsbehaftete Applikationen von Kunden.

DA ROSA im HA-Modus mit Knoten der Kontrollebene über mehrere Verfügbarkeitszonen hinweg implementiert werden kann, kann FSX ONTAP auch mit Multi-AZ-Option bereitgestellt werden, die hohe Verfügbarkeit bietet und AZ-Ausfälle schützt.

*Google Cloud NetApp Volumes*

Red hat OpenShift Dedicated ist eine vollständig gemanagte Anwendungsplattform, mit der Sie schnell Anwendungen in der gesamten Hybrid Cloud erstellen, bereitstellen und skalieren können. Google Cloud NetApp Volumes stellt persistente Volumes bereit, sodass OpenShift-Implementierungen in der Google Cloud über die gesamte Suite der Funktionen für Enterprise-Datenmanagement von ONTAP verfügen.
