---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Astra Control Center, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Wertversprechen von NetApp Hybrid-Multi-Cloud-Lösungen für Container-Workloads mit Red hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die meisten Kunden beginnen nicht nur mit der Entwicklung von Kubernetes-basierten Umgebungen ohne die vorhandene Infrastruktur. Möglicherweise handelt es sich bei ihnen um eine herkömmliche IT-Abteilung, die die meisten ihrer Enterprise-Applikationen auf Virtual Machines ausführt (z. B. in großen VMware-Umgebungen). Dann beginnen sie, kleine containerbasierte Umgebungen zu erstellen, die die Anforderungen ihrer modernen Applikationsentwicklungsteams erfüllen. Diese Initiativen beginnen in der Regel klein und werden immer mehr verbreitet, wenn die Teams diese neuen Technologien und Fähigkeiten erlernen und beginnen, die vielen Vorteile der Einführung zu erkennen. Die gute Nachricht für Kunden ist, dass NetApp die Anforderungen beider Umgebungen erfüllen kann. Mit diesen Lösungen für Hybrid-Multi-Clouds mit Red hat OpenShift können NetApp Kunden moderne Cloud-Technologien und -Services einführen, ohne die gesamte Infrastruktur und das gesamte Unternehmen überarbeiten zu müssen. Ganz gleich, ob Applikationen und Daten der Kunden lokal, in der Cloud, auf Virtual Machines oder in Containern gehostet werden – NetApp bietet konsistentes Datenmanagement, Sicherung, Sicherheit und Portabilität. Mit diesen neuen Lösungen wird derselbe Wert, den NetApp seit Jahrzehnten in On-Premises-Datacenter-Umgebungen bietet, für das gesamte Datenhorizont des Unternehmens verfügbar sein, ohne dass erhebliche Investitionen in die Tools, die Anschaffung neuer Fähigkeiten oder die Entwicklung neuer Teams erforderlich sind. NetApp unterstützt Kunden dabei, diese geschäftlichen Herausforderungen zu bewältigen – unabhängig von der aktuellen Phase des Cloud-Übergangs.

NetApp Hybrid-Multi-Cloud mit Red hat OpenShift:

* Die Lösung bietet Kunden validierte Designs und Verfahren, die zeigen, wie Kunden ihre Daten und Applikationen am besten managen, schützen, sichern und migrieren können, wenn sie Red hat OpenShift mit NetApp Storage-Lösungen einsetzen.
* Präsentieren von Best Practices für Kunden, die Red hat OpenShift mit NetApp Storage in VMware Umgebungen, Bare Metal-Infrastruktur oder einer Kombination aus beidem ausführen
* Strategien und Optionen sowohl für On-Premises- und Cloud-Umgebungen als auch für Hybrid-Umgebungen aufzeigen, in denen beide eingesetzt werden

