---
sidebar: sidebar 
permalink: xcp/xcp-bp-high-performance-computing-to-ontap-nfs.html 
keywords: use case, gpfs, nfs 
summary: Zur Migration der Daten von GPFS zu NFS verwendeten wir NetApp XCP, sodass GPUs die Daten verarbeiten können. Die KI verarbeitet typischerweise Daten aus einem Netzwerkdateisystem. 
---
= High-Performance-Computing für ONTAP NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-data-lake-to-ontap-nfs.html["Früher: Data Lake auf ONTAP NFS."]

Dieser Nutzungsfall basiert auf Anfragen von Field Organisations. Einige NetApp Kunden besitzen ihre Daten in einer High-Performance-Computing-Umgebung, die Datenanalysen für Trainingsmodelle bietet und Forschungseinrichtungen dabei unterstützt, mehr Einblicke und ein besseres Verständnis für große Mengen digitaler Daten zu gewinnen. NetApp Field Engineers benötigen ein detailliertes Verfahren, um die Daten aus IBM GPFS zu NFS zu extrahieren. Zur Migration der Daten von GPFS zu NFS verwendeten wir NetApp XCP, sodass GPUs die Daten verarbeiten können. Die KI verarbeitet typischerweise Daten aus einem Netzwerkdateisystem.

Weitere Informationen zum Anwendungsfall „High-Performance Computing für ONTAP NFS“, eine aufgezeichnete Demo und Testergebnisse finden Sie im https://blog.netapp.com/data-migration-xcp["Nutzung von XCP, um Daten von einem Data Lake und High-Performance-Computing zu ONTAP NFS zu verschieben"^] blog:

Detaillierte Schritte zum Verschieben von MapR-FS-Daten in ONTAP-NFS mithilfe von NetApp XCP finden Sie in Anhang A: GPFS zu NFS―Detaillierte Schritte in https://www.netapp.com/us/media/tr-4732.pdf["TR-4732: Big Data Analytics Data to Artificial Intelligence"^].

link:xcp-bp-using-the-xcp-data-mover-to-migrate-millions-of-small-files-to-flexible-storage.html["Weiter: Mit dem XCP Data Mover migrieren Sie Millionen von kleinen Dateien auf flexiblen Speicher."]
