---
sidebar: sidebar 
permalink: data-analytics/apache-spark-target-audience.html 
keywords: audience, data scientist, engineer, devops, cloud administrator, architect 
summary: In diesem Abschnitt wird beschrieben, wer an den Inhalten dieser Lösung interessiert sein könnte. 
---
= Zielgruppe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-solution-overview.html["Zurück: Lösungsübersicht."]

Die Welt der Analyse und Data Science hat unterschiedliche Disziplinen in DER IT und in den Bereichen Business zu berühren:

* Der Data Scientist benötigt die Flexibilität, ihre Tools und Bibliotheken einzusetzen.
* Der Data Engineer muss wissen, wie die Daten fließen und wo sie sich befinden.
* DevOps-Engineers benötigen die Tools, um neue KI- und ML-Applikationen in ihre CI- und CD-Pipelines zu integrieren.
* Cloud-Administratoren und -Architekten müssen in der Lage sein, Hybrid-Cloud-Ressourcen einzurichten und zu managen.
* Unternehmensbenutzer möchten Zugriff auf Analytics-, KI-, ML- und DL-Applikationen haben.


In diesem technischen Bericht werden, wie NetApp AFF, E-Series, StorageGRID, NFS Direct Access, Apache Spark, Horovod und Keras helfen dabei, jede dieser Rollen dem Unternehmen einen Mehrwert zu bieten.

link:apache-spark-solution-technology.html["Als Nächstes: Lösungstechnologie."]
