---
sidebar: sidebar 
permalink: data-analytics/apache-spark-conclusion.html 
keywords: conclusion 
summary: Dieser Abschnitt fasst dieses Dokument zu den NetApp Storage-Lösungen für Apache Spark zusammen. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:apache-spark-python-scripts-for-each-major-use-case.html["Früher: Python-Skripte für jeden größeren Anwendungsfall."]

[role="lead"]
In diesem Dokument befassen wir uns mit der Apache Spark Architektur, mit Kundenanwendungsfällen und dem NetApp Storage-Portfolio, bezogen auf Big Data, moderne Analysen sowie KI, ML und DL. Bei unseren Performance-Validierungstests, die auf branchenüblichen Benchmark-Tools und Kundennachfrage basieren, haben die NetApp Spark-Lösungen eine überragende Performance im Vergleich zu nativen Hadoop Systemen gezeigt. Anhand einer Kombination aus in diesem Bericht vorgestellten Kundenanwendungsfällen und Performance-Ergebnissen können Sie eine passende Spark-Lösung für Ihre Implementierung auswählen.

link:apache-spark-where-to-find-additional-information.html["Weiter: Wo finden Sie zusätzliche Informationen."]
