---
sidebar: sidebar 
permalink: data-analytics/bda-ai-business-benefits.html 
keywords: business, benefits 
summary: In diesem Abschnitt werden die Geschäftsvorteile dieser Lösung beschrieben. 
---
= Geschäftsvorteile
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Das Verschieben von Daten von Big Data-Analysen zu KI bietet folgende Vorteile:

* Daten aus verschiedenen Hadoop Filesystemen und GPFS in ein einheitliches NFS-Storage-System extrahieren
* Hadoop – integrierte und automatisierte Möglichkeit zum Datentransfer
* Einsparungen bei der Bibliotheksentwicklung beim Verschieben von Daten von Hadoop Filesystemen
* Maximale Performance durch aggregierten Durchsatz mehrerer Netzwerkschnittstellen aus einer einzigen Datenquelle mithilfe von NIPAM
* Geplante und On-Demand-Methoden zum Datentransfer
* Storage-Effizienz und Managementfunktionalität der Enterprise-Klasse für Unified NFS-Daten mithilfe von ONTAP Datenmanagement-Software
* Mit der Hadoop Methode zur Datenübertragung entstehen keine Kosten für Datenverschiebungen

