---
sidebar: sidebar 
permalink: data-analytics/bda-ai-customer-challenges.html 
keywords: customer, challenge, data lake, repository, syncing, moving data 
summary: Auf dieser Seite werden die Herausforderungen erläutert, denen sich Kunden beim Zugriff auf Daten aus Big-Data-Analysen für den KI-Betrieb stellen müssen. 
---
= Herausforderungen für Kunden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:bda-ai-introduction.html["Zurück: Einführung."]

Beim Zugriff auf Daten aus Big-Data-Analysen für den KI-Betrieb könnten Kunden die folgenden Herausforderungen bewältigen:

* Kundendaten liegen in einem Data-Lake-Repository. Der Data Lake kann verschiedene Datentypen enthalten, darunter strukturierte, unstrukturierte, halbstrukturierte, Log-Dateien und Machine-to-Machine-Daten. Alle diese Datentypen müssen in KI-Systemen verarbeitet werden.
* Die KI ist nicht mit Hadoop-Dateisystemen kompatibel. Eine typische KI-Architektur kann nicht direkt auf HDFS- und HCFS-Daten zugreifen, die in ein KI-verständliches File-System (NFS) verschoben werden müssen.
* Die Verschiebung von Data-Lake-Daten in die KI erfordert normalerweise spezielle Prozesse. Die Datenmenge im Data Lake kann sehr groß sein. Ein Kunde muss über eine effiziente, hohe Durchsatzleistung und eine kostengünstige Möglichkeit verfügen, Daten in KI-Systeme zu verschieben.
* Synchronisieren von Daten Wenn ein Kunde Daten zwischen der Big Data-Plattform und der KI synchronisieren möchte, können die über KI verarbeiteten Daten manchmal mit Big Data für die analytische Verarbeitung verwendet werden.


link:bda-ai-data-mover-solution.html["Als Nächstes: Data Mover-Lösung."]
