---
sidebar: sidebar 
permalink: data-analytics/bda-ai-abstract.html 
keywords:  
summary:  
---
= Zusammenfassung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In diesem Dokument wird beschrieben, wie Daten aus Big-Data-Analysen und HPC-Systemen (High-Performance-Computing) verschoben und in AI-Workflows (künstliche Intelligenz) genutzt werden können. KI verarbeitet NFS-Daten in der Regel durch NFS-Exporte. Möglicherweise liegen die KI-Daten jedoch auf einer Plattform für Big-Data-Analysen und High-Performance-Computing (HPC) vor. Dies können Hadoop Distributed File System (HDFS), ein Binary Large Object (Blob), S3 Storage oder das General Parallel File System (GPFS) von IBM sein. In diesem Dokument beschreiben wir, wie Daten von einer Big-Data-Analyseplattform und GPFS mit Hadoop-nativen Befehlen, dem NetApp in-Place Analytics Module (NIPAM) und NetApp XCP verschoben werden. In diesem Dokument werden außerdem die geschäftlichen Vorteile erläutert, die das Verschieben von Daten von Big Data und HPC hin zur KI mit sich bringt.
