---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-solution-overview.html 
keywords: tr4967, 4967, introduction, overview 
summary: Data Scientists und Engineers müssen häufig auf Daten zugreifen, die im NFS-Format gespeichert sind. Der Zugriff auf diese Daten direkt aus dem S3-Protokoll in AWS SageMaker kann jedoch eine Herausforderung darstellen, da AWS nur S3-Bucket-Zugriff unterstützt. NetApp ONTAP bietet jedoch eine Lösung durch die Aktivierung des dualen Protokollzugriffs für NFS und S3. Mit dieser Lösung können Data Scientists und Engineers über S3 Buckets von NetApp Cloud Volumes ONTAP auf NFS-Daten von AWS SageMaker Notebooks zugreifen. Dieser Ansatz ermöglicht den einfachen Zugriff auf dieselben Daten von NFS und S3, ohne dass zusätzliche Software erforderlich ist. 
---
= TR-4967: Cloud-Datenmanagement mit NetApp File-Object Dualität und AWS SageMaker
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam, NetApp

[role="lead"]
Data Scientists und Engineers müssen häufig auf Daten zugreifen, die im NFS-Format gespeichert sind. Der Zugriff auf diese Daten direkt aus dem S3-Protokoll in AWS SageMaker kann jedoch eine Herausforderung darstellen, da AWS nur S3-Bucket-Zugriff unterstützt. NetApp ONTAP bietet jedoch eine Lösung durch die Aktivierung des dualen Protokollzugriffs für NFS und S3. Mit dieser Lösung können Data Scientists und Engineers über S3 Buckets von NetApp Cloud Volumes ONTAP auf NFS-Daten von AWS SageMaker Notebooks zugreifen. Dieser Ansatz ermöglicht den einfachen Zugriff auf dieselben Daten von NFS und S3, ohne dass zusätzliche Software erforderlich ist.
