---
sidebar: sidebar 
permalink: data-analytics/cdm-fod-conclusion.html 
keywords: conclusion 
summary: Basierend auf dieser Validierung können Data Scientists und Engineers über S3 Buckets von NetApp Cloud Volumes ONTAP auf NFS-Daten von AWS SageMaker Jupyter Notebooks zugreifen. Dieser Ansatz ermöglicht den einfachen Zugriff auf dieselben Daten von NFS und S3, ohne dass zusätzliche Software erforderlich ist. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:cdm-fod-data-duality-for-data-scientists-and-other-applications.html["Früher: Datendualität für Data Scientists und andere Anwendungen."]

[role="lead"]
Basierend auf dieser Validierung können Data Scientists und Engineers über S3 Buckets von NetApp Cloud Volumes ONTAP auf NFS-Daten von AWS SageMaker Jupyter Notebooks zugreifen. Dieser Ansatz ermöglicht den einfachen Zugriff auf dieselben Daten von NFS und S3, ohne dass zusätzliche Software erforderlich ist.



== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Textklassifizierung mit SageMaker BlazingText
+
https://["https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html"^]

* ONTAP-Versionsunterstützung für S3 Objekt-Storage
+
https://["https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html"^]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | April 2023 | Erste Version 
|===