---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-conclusion.html 
keywords: conclusion 
summary: Dieses Dokument enthält Best Practice-Richtlinien zum Einsatz von Kafka mit NetApp Storage. Hierzu zählen Conflient Kafka Zertifizierungstests, Performance-Ergebnisse, Tuning, Kafka Connectors und die Funktion zur selbstständigen Ausbalancierung. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:confluent-kafka-sizing.html["Zurück: Dimensionierung."]

Dieses Dokument enthält Best Practices für die Verwendung von Confluent Tiered Storage mit NetApp Storage, einschließlich Verifizierungstests, Tiered Storage-Performance-Ergebnissen, Tuning, Conflient S3-Konnektoren und der Self-Balancing-Funktion. Der NetApp StorageGRID Objekt-Storage zieht ILM-Richtlinien in Betracht, bietet fließende Performance mit mehreren Performance-Tests zur Verifizierung und S3 APIs nach Branchenstandard. Dies ist eine optimale Wahl für Conflient Tiered Storage.



== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Was ist Apache Kafka
+
https://www.confluent.io/what-is-apache-kafka/["https://www.confluent.io/what-is-apache-kafka/"^]

* NetApp Produktdokumentation
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* S3-Sink Parameterdetails
+
https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html["https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html#s3-configuration-options"^]

* Apache Kafka
+
https://en.wikipedia.org/wiki/Apache_Kafka["https://en.wikipedia.org/wiki/Apache_Kafka"^]

* Infinite Storage in Conflient Plattform
+
https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/["https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/"^]

* Confluent Tiered Storage – Best Practices und Sizing
+
https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations["https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations"^]

* Amazon S3 Spülenanschluss für Confluent Platform
+
https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html["https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html"^]

* Kafka – Größen
+
https://eventsizer.io["https://eventsizer.io"]

* StorageGRID Dimensionierung
+
https://fusion.netapp.com/["https://fusion.netapp.com/"^]

* Anwendungsfälle für Kafka
+
https://kafka.apache.org/uses["https://kafka.apache.org/uses"^]

* Kafka-Cluster mit Selbstausgleich in Plattform 6.0
+
https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/["https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/"^]

+
https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/["https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/"^]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | Dezember 2021 | Erste Version. 
|===