---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-introduction.html 
keywords: introduction, best practices, dremio, lakehouse 
summary: Dieses Dokument beschreibt die Best-Practice-Richtlinien für den Einsatz von Dremio auf einem NetApp Storage Controller. 
---
= Die hybride Iceberg Lakehouse Lösung der nächsten Generation von NetApp und Dremio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Dokument besprechen wir die Implementierungsdetails von Dremio mit verschiedenen Datenquellen von NetApp Storage Controllern, einschließlich ONTAP S3, NAS und StorageGRID. Während der Bereitstellung verwendeten wir das TPC-DS Benchmark-Tool, um 99 SQL-Abfragen über verschiedene Quellen hinweg auszuführen. In diesem Dokument werden auch Anwendungsfälle für NetApp erläutert sowie ein Anwendungsfall mit Kunden aus dem Bereich Automobilvertrieb.

*Autoren*

Karthikeyan Nagalingam, Principal Architect, NetApp, Inc. Roger Frey, VP, Alliances, Dremio Corporation. Mark Shainman, Principal Product Marketing Manager.Dremio Corporation.
