---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: In diesem Abschnitt wird die für die dremio-Zertifizierung verwendete Hardware und Software beschrieben. Diese Informationen gelten für die Bereitstellung von dremio mit NetApp-Speicher. 
---
= Lösungsüberblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Hybrid Iceberg Lakehouse Lösung bietet einzigartige Vorteile bei der Bewältigung der Herausforderungen von Data-Lake-Kunden. Durch Nutzung der Dremio Unified Lakehouse-Plattform sowie von NetApp ONTAP-, StorageGRID- und NetApp-Lösungen können Unternehmen ihren Geschäftsbetrieb wesentlich voranbringen. Die Lösung bietet nicht nur Zugriff auf mehrere Datenquellen, einschließlich NetApp-Quellen, sondern verbessert auch die gesamte analytische Leistung und hilft Unternehmen, geschäftliche Einblicke zu gewinnen, die zu geschäftlichem Wachstum führen.



== Übersicht über NetApp

* Die NetApp Angebote wie ONTAP und StorageGRID ermöglichen die Trennung von Storage und Computing und ermöglichen somit eine optimale Ressourcenauslastung je nach spezifischen Anforderungen. Dank dieser Flexibilität sind Kunden in der Lage, ihren Storage mithilfe von NetApp Storage-Lösungen unabhängig zu skalieren
* Mithilfe der Storage Controller von NetApp können Kunden ihre Vektordatenbank mithilfe der NFS- und S3-Protokolle effizient mit Daten versorgen. Diese Protokolle erleichtern die Speicherung der Kundendaten und das Management des Vektordatenbankindexes, sodass nicht mehr mehrere Kopien von Daten benötigt werden, auf die über Datei- und Objektmethoden zugegriffen wird.
* NetApp ONTAP bietet nativen Support für NAS und Objekt-Storage bei führenden Cloud-Service-Providern wie AWS, Azure und Google Cloud. Diese breite Kompatibilität gewährleistet eine nahtlose Integration und ermöglicht damit Datenmobilität für Kunden, globale Verfügbarkeit, Disaster Recovery, dynamische Skalierbarkeit und hohe Performance.




=== StorageGRID

Unser branchenführender Objekt-Storage-StorageGRID bietet eine leistungsstarke Richtlinien-Engine für automatisierte Datenablage, flexible Implementierungsoptionen und unübertroffene Beständigkeit dank mehrstufigem Codierungsverfahren zur Fehlerkorrektur. Es verfügt über eine skalierbare Architektur, die Milliarden Objekte und Petabyte an Daten in einem Single Namespace unterstützt. Die Lösung ermöglicht eine Hybrid-Cloud-Integration und Daten-Tiering auf wichtige Cloud-Plattformen. Ein Bericht von IDC MarketScape Worldwide Object-Based Vendor Assessment 2019 belegt die Spitzenposition.

Darüber hinaus zeichnet sich StorageGRID durch das Management unstrukturierter Daten nach Bedarf mit softwaredefiniertem Objekt-Storage, Geo-Redundanz und Multi-Site-Funktionen aus. Sie umfasst richtlinienbasiertes Information Lifecycle Management und bietet Funktionen zur Cloud-Integration wie Spiegelung und Suche. Es verfügt über verschiedene Zertifizierungen, darunter Common Criteria, NF203 Digital Safe Component, ISO/IEC 25051, KPMG und Cohasset Compliance Assessment.

Zusammengefasst bietet NetApp StorageGRID leistungsstarke Funktionen, Skalierbarkeit, Hybrid-Cloud-Integration und Compliance-Zertifizierungen für ein effizientes Management unstrukturierter Daten jeder Größenordnung.



=== NetApp ONTAP

NetApp ONTAP ist eine robuste Storage-Lösung, die eine breite Palette an Enterprise-Funktionen bietet. Es umfasst Snapshot, das applikationskonsistente und manipulationssichere sofortige Backups bietet. SnapRestore ermöglicht eine nahezu sofortige Wiederherstellung von Backups nach Bedarf, während SnapMirror integrierte Funktionen für Remote Backup und Disaster Recovery bietet. Darüber hinaus bietet die Lösung Autonomous Ransomware Protection (ARP) und sorgt mit Funktionen wie der Verifizierung durch mehrere Administratoren, der Verschlüsselung von Daten im Ruhezustand mit FIPS-Zertifizierung, Verschlüsselung von Daten auf der Übertragungsstrecke, Multi-Faktor-Authentifizierung (MFA) und rollenbasierter Zugriffssteuerung (Role Based Access Control, RBAC) für Datensicherheit. Umfassende Funktionen für Protokollierung, Revision, integriertes und externes Verschlüsselungsmanagement, sicheres Löschen und sicheres Management mehrerer Mandanten sorgen für zusätzliche Datensicherheit und Compliance.

NetApp ONTAP verfügt außerdem über SnapLock, das die Einhaltung gesetzlicher Vorschriften ermöglicht und ein hohes Maß an Integrität, Performance und Aufbewahrung bei niedrigen Gesamtbetriebskosten bietet. Es ist vollständig in NetApp ONTAP® 9 integriert und bietet Schutz vor böswilligen Handlungen, böswilligen Administratoren und Ransomware.

Die Lösung umfasst NSE/NVE-Verschlüsselung für die Verschlüsselung von Daten im Ruhezustand und im Übertragungsprozess, Multi-Faktor-Administratorzugriff und die Verifizierung durch mehrere Administratoren. Active IQ bietet auf KI-Basis prädiktive Analysen und Korrekturmaßnahmen. QoS sorgt dabei für Workload-Kontrolle der Servicequalität. Die Management- und Automatisierungsintegration ist intuitiv dank SysMgr/GUI/CLI/API. FabricPool ermöglicht automatisches Daten-Tiering, und die Lösung bietet Effizienz durch Inline-Datenkomprimierung, Deduplizierung und Data-Compaction. NetApp garantiert dem Kunden das kostenlose Erreichen der Workload-Effizienzziele.

NetApp ONTAP unterstützt verschiedene Protokolle, darunter NVMe/FC, FC, NVMe/TCP, iSCSI, NFS, SMB und S3, wodurch es sich zu einer Unified-Storage-Lösung entwickelt. Insgesamt bietet NetApp ONTAP umfangreiche Enterprise-Funktionen sowie robuste Sicherheit, Compliance, Effizienz und Vielseitigkeit, um verschiedenste Storage-Anforderungen zu erfüllen.



== Dremio Übersicht

Dremio ist die Unified Lakehouse Plattform für Self-Service-Analysen und KI. Die Dremio Unified Analytics Platform bringt die Benutzer näher an die Daten heran und bietet Flexibilität, Skalierbarkeit und Performance am See zu einem Bruchteil der Kosten älterer Data Warehouse-Lösungen. Dremio ermöglicht „Shift-Left“-Analysen zur Eliminierung komplexer und teurer Datenintegration und ETL und ermöglicht nahtlose Analysen auf Unternehmensebene, ohne Daten verschieben zu müssen. Dremio bietet außerdem:

* Benutzerfreundliche Self-Service-Analyse über eine universelle semantische Ebene und eine eng integrierte, hochleistungsfähige SQL-Abfrageengine, die das Verbinden, Steuern und Analysieren aller Daten sowohl in der Cloud als auch On-Premises vereinfacht.
* Die nativen Lakehouse-Management-Funktionen von Dremio in Apache Iceberg vereinfachen die Datenerkennung und automatisieren die Datenoptimierung. Sie ermöglichen hochperformante Analysen mit von Git inspirierter Data-Versionierung.
* Dremio basiert auf Open Source und offenen Standards und ermöglicht es Unternehmen, sich nicht an eine Bindung zu binden und für Innovationen positioniert zu bleiben. Enterprise-Unternehmen vertrauen auf Dremio als am einfachsten zu verwendende Lakehouse-Plattform mit dem besten Preis-Leistungs-Verhältnis für alle Workloads.




== Welchen Nutzen bietet die hybride Iceberg Lakehouse Lösung von Dremio und NetApp den Kunden?

* *Verbessertes Datenmanagement und Zugänglichkeit*: Dremio ist bekannt für seine Data Lakehouse-Plattform, mit der Unternehmen Daten direkt aus ihren Data Lakes mit hoher Geschwindigkeit abfragen können. NetApp hingegen ist ein führender Anbieter von Cloud-Datenservices und Storage-Lösungen. Dieses gemeinsame Angebot bietet Kunden eine umfassende Lösung zum Speichern, Managen, Abrufen und Analysieren ihrer Unternehmensdaten auf effiziente und effiziente Weise.
* *Performance-Optimierung*: Mit der Expertise von NetApp in den Bereichen Datenspeicher und Dremio in der Data Processing- und Datenoptimierung bietet die Partnerschaft eine Lösung, die die Performance von Datenvorgängen verbessert, Latenz reduziert und schnellere Geschäftseinblicke ermöglicht. Dremio hat sogar der internen IT-Analyseinfrastruktur von NetApp Performance-Vorteile gebracht.
* *Skalierbarkeit*: Sowohl Dremio als auch NetApp bieten eine skalierbare Lösung. Diese gemeinsame Lösung bietet Kunden hochskalierbare Storage-, Datenmanagement- und Analyseumgebungen. In einer hybriden Iceberg Lakehouse-Umgebung bietet die Dremio SQL-Abfrageengine in Kombination mit NetApp StorageGRID eine unvergleichliche Skalierbarkeit, Parallelität und Abfrageleistung, die den analytischen Anforderungen jedes Unternehmens gerecht wird.
* *Datensicherheit und Governance*: Beide Unternehmen haben einen starken Fokus auf Datensicherheit und Governance. Gemeinsam bieten sie robuste Sicherheits- und Data Governance-Funktionen, die den Schutz der Daten und die Einhaltung der Data Governance-Anforderungen sicherstellen. Funktionen wie rollenbasierte und fein abgestufte Zugriffskontrollen, umfassende Audits, End-to-End-Datenlieferungslinie, einheitliches Identitätsmanagement und SSO mit einem umfassenden Compliance- und Sicherheits-Framework sorgen dafür, dass die analytischen Datenumgebungen in Unternehmen sicher und geregelt sind.
* *Kosteneffizienz*: Durch die Integration der Data Lake Engine von Dremio in die Storage-Lösungen von NetApp können Kunden die Kosten für Datenmanagement und Datenverschiebung senken. Unternehmen sind außerdem in der Lage, von bestehenden Data Lake-Umgebungen auf eine modernere Lakehouse-Lösung mit NetApp und Dremio umzusteigen. Diese Hybrid-Lösung von Iceberg Lakehouse bietet eine ultraschnelle Abfrageperformance und marktführende Abfrageparallelität, wodurch die TCO gesenkt und die Zeit bis zu geschäftlichen Einblicken verkürzt wird.

