---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-conclusion.html 
keywords: conclusion, summary, data protection, hadoop, more information, Acknowledgements, version history 
summary: Dieser Abschnitt enthält eine Zusammenfassung der von NetApp zur Erfüllung verschiedener Hadoop Datensicherungsanforderungen bereitgestellten Anwendungsfälle und Lösungen. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:hdcs-sh-use-case-5--accelerate-analytic-workloads.html["Zurück: Anwendungsfall 5 – Beschleunigen Sie Analyse-Workloads."]

[role="lead"]
Dieser Abschnitt enthält eine Zusammenfassung der von NetApp zur Erfüllung verschiedener Hadoop Datensicherungsanforderungen bereitgestellten Anwendungsfälle und Lösungen. Mit der Data Fabric von NetApp profitieren Kunden von folgenden Vorteilen:

* Dank der umfassenden Datenmanagement-Funktionen und der Integration in native Hadoop Workflows können die passenden Datensicherungslösungen flexibel gewählt werden.
* Reduzieren Sie das Backup-Fenster für Hadoop Cluster um beinahe 70 %.
* Keine Performance-Auswirkungen durch Hadoop Cluster-Backups
* Datensicherung und Datenzugriff über mehrere Clouds gleichzeitig von verschiedenen Cloud-Providern für eine zentrale Quelle der Analysedaten
* Schnelle und platzsparende Hadoop Cluster-Kopien mit FlexClone Technologie




== Wo Sie weitere Informationen finden

Weitere Informationen zu den in diesem Dokument beschriebenen Daten finden Sie in den folgenden Dokumenten bzw. auf den folgenden Websites:

* NetApp Big-Data-Analyselösungen
+
https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx["https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx"^]

* Apache Spark Workload mit NetApp Storage
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf["https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf"^]

* NetApp Storage-Lösungen für Apache Spark
+
https://www.netapp.com/media/16864-tr-4570.pdf["https://www.netapp.com/media/16864-tr-4570.pdf"^]

* Apache Hadoop on Data Fabric basiert auf NetApp
+
https://www.netapp.com/media/16877-tr-4529.pdf["https://www.netapp.com/media/16877-tr-4529.pdf"^]





== Danksagungen

* Paul Burland, Vertriebsmitarbeiter, Vertrieb Australien/Victoria District, NetApp
* Hoseb Dermanilian, Business Development Manager, NetApp
* Lee Dorrier, Director MPSG, NetApp
* David Thiessen, Systems Engineer, ANZ Victoria District SE, NetApp




== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | Januar 2018 | Erste Version 


| Version 2.0 | Oktober 2021 | Aktualisiert mit Anwendungsfall #5: Analytics-Workloads beschleunigen 


| Version 3.0 | November 2023 | NIPAM-Details wurden entfernt 
|===