---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-overview-of-hadoop-data-protection-use-cases.html 
keywords: summary, overview, backup, devtest, data protection 
summary: 'Dieser Abschnitt enthält eine ausführliche Beschreibung der Anwendungsfälle für die Datensicherung, die den Schwerpunkt dieses Dokuments bilden. Die verbleibenden Abschnitte enthalten ausführlichere Angaben zu den einzelnen Anwendungsfällen, z. B. zum Kundenproblem (Szenario), den Anforderungen und Herausforderungen sowie zu Lösungen.' 
---
= Übersicht über Anwendungsfälle für die Datensicherung in Hadoop
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:hdcs-sh-hadoop-data-protection-and-netapp.html["Früher Hadoop Datensicherung und NetApp."]

[role="lead"]
Dieser Abschnitt enthält eine ausführliche Beschreibung der Anwendungsfälle für die Datensicherung, die den Schwerpunkt dieses Dokuments bilden. Die verbleibenden Abschnitte enthalten ausführlichere Angaben zu den einzelnen Anwendungsfällen, z. B. zum Kundenproblem (Szenario), den Anforderungen und Herausforderungen sowie zu Lösungen.



== Anwendungsfall 1: Sichern von Hadoop Daten

In diesem Use Case konnte ein großes Finanzinstitut mit in-Place-Analyse die Zeit, in der die langen Backup-Zeitfenster von über 24 Stunden auf weniger als wenige Stunden verkürzt wurden.



== Anwendungsfall 2: Backup und Disaster Recovery aus der Cloud in On-Premises-Systeme

Durch den Einsatz der Data Fabric von NetApp als Bausteine konnte ein großes Rundfunkunternehmen seine Anforderung erfüllen, Backups von Cloud-Daten auf seinem lokalen Datacenter zu erstellen, je nach unterschiedlichen Übertragungsmodi wie On-Demand, unmittelbar Oder auf Basis der Hadoop/Spark-Cluster-Last



== Anwendungsfall 3: Enabling DevTest on Existing Hadoop Data

NetApp Lösungen halfen einem Online-Musikdistributor, schnell mehrere platzsparende Hadoop Cluster in verschiedenen Niederlassungen aufzubauen, um mithilfe von geplanten Richtlinien Berichte zu erstellen und tägliche DevTest-Aufgaben auszuführen.



== Anwendungsfall 4: Datensicherung und Multi-Cloud-Konnektivität

Ein großer Service-Provider nutzte die Data Fabric von NetApp, um seinen Kunden aus verschiedenen Cloud-Instanzen Multi-Cloud-Analysen zu liefern.



== Anwendungsfall 5: Schnellere Analyse-Workloads

Eine der größten Finanzdienstleistungsbanken und Investmentbanken setzte die Network-Attached Storage-Lösung von NetApp ein, um die I/O-Wartezeit zu verringern und die Plattform für quantitative Finanzanalysen zu beschleunigen.

link:hdcs-sh-use-case-1--backing-up-hadoop-data.html["Weiter: Anwendungsfall 1 – Sicherung von Hadoop Daten."]
