---
sidebar: sidebar 
permalink: data-analytics/kafka-nfs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Wo Sie weitere Informationen finden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-nfs-conclusion.html["Zurück: Schlussfolgerung."]

[role="lead"]
Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Was ist Apache Kafka?
+
https://["https://www.confluent.io/what-is-apache-kafka/"^]

* Was ist dumme Umbenennung?
+
https://["https://linux-nfs.org/wiki/index.php/Server-side_silly_rename"^]

* ONATP wird für Streaming-Anwendungen gelesen.
+
https://["https://www.netapp.com/blog/ontap-ready-for-streaming-applications/"^]

* Dumm- Benennen Sie Problem mit Kafka.
+
https://["https://sbg.technology/2018/07/10/kafka-nfs/"^]

* NetApp Produktdokumentation
+
https://["https://www.netapp.com/support-and-training/documentation/"^]

* Was ist NFS?
+
https://["https://en.wikipedia.org/wiki/Network_File_System"^]

* Was ist die Kafka-Partitionsumverteilung?
+
https://["https://docs.cloudera.com/runtime/7.2.10/kafka-managing/topics/kafka-manage-cli-reassign-overview.html"^]

* Was ist der OpenMessaging Benchmark?
+
https://["https://openmessaging.cloud/"^]

* Wie migrieren Sie einen Kafka-Broker?
+
https://["https://medium.com/@sanchitbansal26/how-to-migrate-kafka-cluster-with-no-downtime-58c216129058"^]

* Wie überwachen Sie den Kafka-Broker mit Prometheus?
+
https://[]

* Managed Platform für Apache Kafka
+
https://[]

* Unterstützung für Apache Kafka
+
https://[]

* Beratungsdienstleistungen für Apache Kafka
+
https://[]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | März 2023 | Erste Version. 
|===