---
sidebar: sidebar 
permalink: data-analytics/kafka-nfs-conclusion.html 
keywords: conclusion 
summary: Die NetApp Lösung für das „albern“-Problem bietet eine einfache, kostengünstige und zentral gemanagte Storage-Form für Workloads, die zuvor mit NFS nicht kompatibel waren. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:kafka-nfs-performance-overview-and-validation-with-aff-on-premises.html["Zurück: Performance-Übersicht und Validierung mit AFF On-Premises."]

[role="lead"]
Die NetApp Lösung für das „albern“-Problem bietet eine einfache, kostengünstige und zentral gemanagte Storage-Form für Workloads, die zuvor mit NFS nicht kompatibel waren. Mit diesem neuen Paradigma erstellen Sie leichter managebare Kafka-Cluster, die sich einfacher migrieren und für Disaster Recovery und Datensicherung spiegeln lassen. Zudem konnten wir feststellen, dass NFS zusätzliche Vorteile bietet, wie z. B. geringere CPU-Auslastung, schnellere Recovery-Zeiten, deutlich höhere Storage-Effizienz und eine bessere Performance durch NetApp ONTAP.

link:kafka-nfs-where-to-find-additional-information.html["Weiter: Wo finden Sie zusätzliche Informationen."]
