---
sidebar: sidebar 
permalink: data-analytics/kafka-ontap-overview.html 
keywords: tr4941, 4941, introduction 
summary: Dieses Dokument beschreibt die Performance-Benchmarks für die Confluent Plattform auf NetApp ONTAP mithilfe eines Tiered Storage Benchmark Kits. 
---
= TR-4941: Fließend mit den NetApp ONTAP Storage Controllern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthikeyan Nagalingam, Joe Scott, NetApp Rankesh Kumar, Confluent

[role="lead"]
Damit die Confluent Platform skalierbarer und flexibler wird, muss sie in der Lage sein, Workloads sehr schnell zu skalieren und auszugleichen. Durch Tiered Storage können große Datenmengen in Conflient gemanagt werden, indem diese Betriebskosten reduziert werden. Eine wesentliche Idee besteht darin, den Storage von der Datenverarbeitung zu trennen, wodurch jede unabhängig voneinander skaliert werden kann.

Mit zahlreichen branchenführenden Innovationen vereint die Datenmanagement-Software NetApp ONTAP vielfältige Vorteile in jedem Bereich der Daten.

Dieses Dokument beschreibt die Performance-Benchmarks für die Confluent Plattform auf NetApp ONTAP mithilfe eines Tiered Storage Benchmark Kits.

link:kafka-sc-solution.html["Als Nächstes: Lösung."]
