---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-conclusion.html 
keywords: conclusion, references 
summary: Splunk Enterprise ist die marktführende SIEM-Lösung für Resultate in Sicherheits-, IT- und DevOps-Teams. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Splunk Enterprise ist die marktführende SIEM-Lösung für Resultate in Sicherheits-, IT- und DevOps-Teams. Der Einsatz von Splunk ist in allen Unternehmen unserer Kunden deutlich gestiegen. Daher müssen mehr Datenquellen hinzugefügt und die Daten für einen längeren Zeitraum beibehalten werden, was die Splunk Infrastruktur belastet.

Die Kombination aus Splunk SmartStore und NetApp StorageGRID wurde entwickelt, um eine skalierbare Architektur für Unternehmen bereitzustellen, die eine höhere Aufnahme-Performance mit SmartStore und StorageGRID Objekt-Storage sowie die höhere Skalierbarkeit für eine Splunk Umgebung über mehrere geografische Regionen hinweg erzielen kann.



== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* https://docs.netapp.com/us-en/storagegrid-family/["NetApp StorageGRID Dokumentationsmaterialien"^]
* https://docs.netapp.com["NetApp Produktdokumentation"^]
* https://docs.splunk.com/Documentation/Splunk["Splunk Enterprise-Dokumentation"^]
* https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore["Splunk Enterprise über SmartStore"^]
* https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview["Splunk Enterprise Distributed Deployment Guide"^]
* https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers["Splunk Enterprise Management von Indexern und Indexern"^]

