---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-benefits-of-this-solution.html 
keywords: benefits, performance, multisite, scalability, capacity, availability, cache 
summary: Die Lösung ermöglicht es, Computing-, Hot Storage- oder S3-Ressourcen hinzuzufügen, um den wachsenden Bedarf an Benutzern oder Aufnahmeraten über einzelne oder standortübergreifende Implementierungen hinweg zu decken. 
---
= Vorteile dieser Lösung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die Lösung ermöglicht es, Computing-, Hot Storage- oder S3-Ressourcen hinzuzufügen, um den wachsenden Bedarf an Benutzern oder Aufnahmeraten über einzelne oder standortübergreifende Implementierungen hinweg zu decken.

* *Performance.* durch die Kombination aus Splunk SmartStore und NetApp StorageGRID können Daten mithilfe des Objekt-Storage schnell zwischen Hot Buckets und warmen Buckets migriert werden. StorageGRID beschleunigt den Migrationsprozess, da sie schnelle Performance für große Objekt-Workloads bietet.
* *Standortfähig.* mit der verteilten StorageGRID Architektur kann Splunk SmartStore die Implementierung über einen einzigen globalen Namespace auf einzelne und mehrere Standorte ausweiten. Dort können Daten unabhängig vom Speicherort der Daten von jedem Standort aus abgerufen werden.
* *Bessere Skalierbarkeit.* Storage-Ressourcen können unabhängig von den Computing-Ressourcen skaliert werden, um den wachsenden Anforderungen in der Splunk Umgebung gerecht zu werden. Damit wird die TCO verbessert.
* *Kapazität.* schnell wachsende Volumes werden in Splunk Implementierungen mit StorageGRID durch Skalierung eines Single Namespace auf über 560 PB gerecht.
* *Datenverfügbarkeit.* Datenverfügbarkeit, Performance, geografische Verteilung, Aufbewahrung, Schutz, Und Storage-Kosten mithilfe von metadatengestützten Richtlinien, die sich dem geschäftlichen Nutzen der Daten dynamisch anpassen.


Steigern Sie die Performance mit dem SmartStore-Cache, der eine Komponente des Indexers ist, der die Übertragung von Bucket-Kopien zwischen lokalem (heißem) und externem (warmem) Storage verarbeitet. Die Splunk Dimensionierung für diese Lösung basiert auf der https://docs.splunk.com/Documentation/Splunk/8.0.5/Capacity/Summaryofperformancerecommendations["Von Splunk bereitgestellter Richtlinien"^]. Die Lösung ermöglicht es, Computing-, Hot Storage- oder S3-Ressourcen hinzuzufügen, um den wachsenden Bedarf an Benutzern oder Aufnahmeraten über einzelne oder standortübergreifende Implementierungen hinweg zu decken.
