---
sidebar: sidebar 
permalink: data-analytics/tr-4623-link.html 
keywords:  
summary:  
---
= TR-4623: NetApp E-Series E5700 und Splunk Enterprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mitch Blackburn, NetApp

TR-4623 beschreibt die integrierte Architektur des Designs NetApp E-Series und Splunk. Optimiert für Storage-Verteilung auf die Nodes, Zuverlässigkeit, Performance, Storage-Kapazität und Dichte Dieses Design nutzt das Splunk Clustered Index-Node-Modell mit höherer Skalierbarkeit und niedrigeren Gesamtbetriebskosten. Die Trennung von Storage und Computing ermöglicht die getrennte Skalierung und spart so die Kosten einer Überprovisionierung. Darüber hinaus enthält dieses Dokument eine Zusammenfassung der Performance-Testergebnisse, die mit einem Splunk Tool zur Computerprotokoll-Simulation erzielt wurden.

link:https://www.netapp.com/pdf.html?item=/media/16851-tr-4623pdf.pdf["TR-4623: NetApp E-Series E5700 und Splunk Enterprise"^]
