---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: Die Lösung enthält die Schritte, die für die Bereitstellung von Hyper-V auf NetApp-Speicher erforderlich sind 
---
= Bereitstellung von Microsoft Hyper-V auf NetApp-Speicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Windows Server-Plattform verwendet die Hyper-V-Rolle zur Bereitstellung von Virtualisierungstechnologie. Hyper-V ist eine von vielen optionalen Rollen, die mit Windows Server angeboten werden.



== Überblick

Die Hyper-V-Rolle ermöglicht es uns, mithilfe der in Windows Server integrierten Virtualisierungstechnologie eine virtualisierte Computing-Umgebung zu erstellen und zu managen. Die Hyper-V-Technologie virtualisiert Hardware, um eine Umgebung bereitzustellen, in der Sie mehrere Betriebssysteme gleichzeitig auf einem physischen Computer ausführen können. Mit Hyper-V können Sie virtuelle Maschinen und deren Ressourcen erstellen und verwalten. Jede virtuelle Maschine ist ein isoliertes, virtualisiertes Computersystem, das ein eigenes Betriebssystem ausführen kann. Hyper-V stellt eine Infrastruktur zur Virtualisierung von Anwendungen und Workloads bereit, die eine Vielzahl von Geschäftszielen unterstützt, die darauf abzielen, die Effizienz zu verbessern und Kosten zu senken. Dies ist eine perfekte Alternative zu VMware® vSphere, insbesondere wenn Unternehmen auf der Suche nach einer Koexistenz mehrerer Hypervisoren unter den aktuellen Marktbedingungen sind.



== Zielgruppe

Dieses Dokument beschreibt die Architektur und Bereitstellungsverfahren für die Hyper-V-Cluster-Konfiguration mit den NetApp ONTAP-Systemen. Dieses Dokument richtet sich an Vertriebsmitarbeiter, Berater im Außendienst, Professional Services-Mitarbeiter, IT-Manager, Techniker von Partnern, und Kunden, die Hyper-V als primären oder alternativen Hypervisor einsetzen möchten.



== Der Netapp Architektur Sind

Die in diesem Dokument beschriebene Architektur umfasst insbesondere Microsoft® Windows Server® 2022 und Hyper-V® Virtualisierung. NetApp empfiehlt für jede Implementierung besonders Virtualisierungssoftware und Infrastruktur-Management-Software. Die Konfiguration verwendet die Best Practices für jede Komponente, um eine zuverlässige Infrastruktur der Enterprise-Klasse zu ermöglichen.



== Zusammenfassung Des Anwendungsfalls

Dieses Dokument beschreibt die Implementierungsverfahren und Best Practices für die Einrichtung eines Hyper-V Clusters für eine optimale Performance als Workload auf Microsoft Windows Server 2022 mit NetApp All-Flash FAS- und ASA-Array-Modellen. Das Server-Betriebssystem/Hypervisor ist Microsoft Windows Server 2022. Die Leitlinien decken NetApp Storage-Systeme ab, die Daten über SAN- (Storage Area Network) und NAS-Protokolle (Network-Attached Storage) bereitstellen.
