---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy-conclusion.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization 
summary: Die Lösung enthält die Schritte, die für die Bereitstellung von Hyper-V auf NetApp-Speicher erforderlich sind 
---
= Deploying Microsoft Hyper-V on NetApp Storage: Fazit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP bildet die optimale Shared Storage-Grundlage zur Implementierung einer Vielzahl an IT Workloads. ONTAP AFF- oder ASA-Plattformen sind flexibel und skalierbar für eine Vielzahl von Anwendungsfällen und Applikationen. Windows Server 2022 und Hyper-V aktiviert ist ein gängiger Anwendungsfall als die Virtualisierungslösung, die in diesem Dokument beschrieben wird. Dank der Flexibilität und Skalierbarkeit von ONTAP Storage und den zugehörigen Funktionen haben Kunden die Möglichkeit, mit einer Storage-Ebene der richtigen Größe zu starten, die mit den sich ändernden Geschäftsanforderungen wächst und sich an diese anpasst. Unter den aktuellen Marktbedingungen bietet Hyper-V eine perfekte alternative Hypervisor-Option, die die meisten Funktionen, die VMware zur Verfügung gestellt wurde, bereitstellt.
