---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation für NetApp Lösungen
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: Enterprise Applications
    entries:
    - title: SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: FlexPod Lösungen
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Alte NetApp HCI-Lösungen
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Änderungsprotokoll
    url: "/change-log-display.html"
  - title: Über NetApp Lösungen
    url: "/about.html"
  - title: Rechtliche Hinweise
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Einführung
    links:
    - title: Informationen zu diesem Repository
      url: about.html
    - title: Änderungsverlauf
      url: change-log-display.html
    - title: Blogs
      url: blogs.html
    - title: Videos Demos
      url: videos.html
    - title: Rechtliche Hinweise
      url: legal-notices.html
  - title: Lösungs-Landing Pages
    links:
    - title: Künstliche Intelligenz
      url: ai/index.html
    - title: Container
      url: containers/index.html
    - title: Enterprise-Datenbanken
      url: databases/index.html
    - title: Moderne Datenanalysen
      url: data-analytics/index.html
    - title: NetApp Hybrid-Multi-Cloud mit VMware
      url: ehc/index.html
    - title: NetApp Hybrid-Multi-Cloud mit Red hat
      url: rhhc/index.html
    - title: SAP UND SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/index.html
    - title: Einheitliche
      url: virtualization/index.html
  - title: Lösungsautomatisierung
    links:
    - title: Einführung
      url: automation/automation_introduction.html
    - title: Erste Schritte
      url: automation/getting-started.html
    - title: Anfrageautomatisierung
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: FlexPod – Eine Cisco NetApp Lösung
    links:
    - title: Technische Inhalte zu FlexPod Lösungen
      url: https://docs.netapp.com/us-en/flexpod/
    - title: FlexPod Vertriebsseite
      url: https://flexpod.com
    - title: Videos und Demos
      url: https://tv.netapp.com/search?q=flexpod
    - title: Blogs
      url: https://blog.netapp.com/tag/FlexPod/
  - title: Feedback Geben
    links:
    - title: Schlagen Sie eine neue Lösung vor
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: Feedback Zu Lösungen Geben
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
