---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation für NetApp Lösungen
    url: index.html
  - section: ai
  - section: data-analytics
  - section: cloud
  - section: virtualization
  - section: containers
  - section: databases
  - title: SAP HANA
    url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - title: FlexPod Lösungen
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Änderungsprotokoll
    url: change-log-display.html
  - title: Über NetApp Lösungen
    url: about.html
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
