---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation für NetApp Lösungen
    url: index.html
  - section: ai
  - section: containers
  - section: data-access
  - title: Enterprise Applications
    entries:
    - title: SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: vmw-sc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: FlexPod Lösungen
    url: https://docs.netapp.com/us-en/flexpod/
  - title: Alte NetApp HCI-Lösungen
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Änderungsprotokoll
    url: change-log-display.html
  - title: Über NetApp Lösungen
    url: about.html
  - title: Rechtliche Hinweise
    url: legal-notices.html
