---
sidebar: sidebar 
permalink: videos.html 
summary: Hier finden Sie eine Videoserie und Demos, in der die Funktionen vieler NetApp Lösungen vorgestellt werden 
keywords: netapp, solutions, videos, demos 
---
= NetApp Lösungen: Videos und Demos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
Überblick über die Videos und Demos, in denen die Besonderheiten vieler NetApp Lösungen hervorgehoben werden.

.Künstliche Intelligenz (KI) und moderne Datenanalysen
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["NetApp KI-Lösungen"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps"^]


====
.Enterprise-Applikationen und -Datenbanken
[#db%collapsible]
====
[Unterstreichen]#*Videos für Open Source-Datenbanken*#

[cols="5a, 5a, 5a"]
|===


 a| 
Automatisierte Implementierung nach PostgreSQL, HA/DR-Replizierungseinrichtung, Failover, Resync

 a| 
 a| 

|===
[Unterstreichen]#*Videos für die Modernisierung von Oracle mit Hybrid Cloud in AWS und FSX*#

[cols="5a, 5a, 5a"]
|===


 a| 
Teil 1: Anwendungsfall und Lösungsarchitektur

 a| 
Teil 2a: Datenbankmigration von lokalen in AWS mittels automatisierter PDB-Verlagerung bei maximaler Verfügbarkeit

 a| 
Teil 2b: Datenbankmigration von lokalen Systemen zu AWS mithilfe der BlueXP Konsole über SnapMirror




 a| 
Teil 3: Automatisiertes Setup für Datenbank-HA/DR-Replizierung, Failover, Neusynchronisierung

 a| 
Teil 4a: Datenbankklon für Entwicklung/Tests mit der UI von SnapCenter aus replizierter Standby-Kopie

 a| 
Teil 4b - Datenbank Backup, Wiederherstellung, Klonen mit SnapCenter UI




 a| 
Teil 4c - Datenbank Backup, Wiederherstellung mit BlueXP SaaS Apps Backup und Recovery

 a| 
 a| 

|===
[Unterstreichung]#*Videos für SQL Server-Datenbank*#

[cols="5a, 5a, 5a"]
|===


 a| 
Implementieren Sie SQL Server auf AWS EC2 mit Amazon FSX für NetApp ONTAP

 a| 
Klonen Sie Mit Der Oracle Multi-Tenant Pluggable Database Unter Verwendung Von Storage Snapshots

video::krzMWjrrMb0[youtube,width=360] a| 
Automatisierte Oracle 19c RAC-Implementierung auf FlexPod mit Ansible

video::VcQMJIRzhoY[youtube,width=360]
|===
*Fallstudie*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["SAP auf Azure NetApp Files"^]


====
.Hybrid-Multi-Cloud (HMC)
[#hmc%collapsible]
====
[Unterstreichung]#*Videos für AWS/VMC*#

[cols="5a, 5a, 5a"]
|===


 a| 
Windows Guest Connected Storage mit FSX ONTAP über iSCSI

 a| 
Linux Guest Connected Storage with FSX ONTAP Using NFS

 a| 
VMware Cloud auf AWS TCO-Einsparungen mit Amazon FSX für NetApp ONTAP




 a| 
VMware Cloud auf AWS zusätzlicher Datastore mit Amazon FSX für NetApp ONTAP

 a| 
VMware HCX Deployment and Configuration Setup für VMC

 a| 
Demo für die Migration von vMotion mit VMware HCX für VMC und FSxN




 a| 
Demonstration zur Cold-Migration mit VMware HCX für VMC und FSxN

 a| 
 a| 

|===
[Unterstreichung]#*Videos für Azure/AVS*#

[cols="5a, 5a, 5a"]
|===


 a| 
Übersicht über die Azure VMware Lösung zusätzlichen Datastore mit Azure NetApp Files

 a| 
Azure VMware Lösung für DR mit Cloud Volumes ONTAP, SnapCenter und JetStream

 a| 
Demonstration zur Cold-Migration mit VMware HCX für AVS und ANF




 a| 
VMotion-Demo mit VMware HCX für AVS und ANF

 a| 
Massenmigration mit VMware HCX für AVS und ANF

 a| 

|===
====
.Hybrid-Multi-Cloud mit Red hat OpenShift
[#rhhc%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
ROSA DR verwendet den Astra Control Service

 a| 
Integration von FSxN mit Astra Trident

 a| 
Failover und Failback von Apps auf ROSA mit FSxN




 a| 
DR über das Astra Control Center

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["Auf NetAppTV ansehen"]
 a| 
 a| 

|===
====
.Einheitliche
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["VMware Video Collection"]


====
.Container/Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["NetApp mit Google Anthos Videos"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["NetApp with VMware Tanzu Videos"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["Videos von NetApp für DevOps"]
* link:containers/rh-os-n_videos_and_demos.html["Videos von NetApp mit Red hat OpenShift"]


====
.Lösungsautomatisierung
[#automation%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Automatisierte Oracle 19c RAC-Implementierung auf FlexPod mit Ansible

video::VcQMJIRzhoY[youtube,width=360] a| 
 a| 

|===
====