---
sidebar: sidebar 
permalink: ehc/aws-storage-options.html 
keywords: aws, netapp, fsxn, storage, options, nfs, supplemental, cvo 
summary: NetApp-Speicher kann mit dem Azure VMware-Dienst als Gast-verbundenen oder ergänzenden Speicher verbunden werden. 
---
= Amazon Web Services: Optionen zur Nutzung von NetApp Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp-Speicher kann an Amazon Web Services als mit dem Gast verbundenen oder ergänzenden Speicher angebunden werden.



== Amazon FSX for NetApp ONTAP (FSX ONTAP) als ergänzender NFS-Datastore

Amazon FSX ONTAP bietet ausgezeichnete Optionen für die Implementierung und das Management von Applikations-Workloads zusammen mit Fileservices und senkt gleichzeitig die TCO, da Datenanforderungen nahtlos in die Applikationsebene integriert werden können. Ganz gleich, wie der Anwendungsfall ist: Wählen Sie VMware Cloud on AWS zusammen mit Amazon FSX ONTAP, um die Vorteile der Cloud, konsistente Infrastruktur und Betrieb von On-Premises-Systemen bis zu AWS, bidirektionale Portabilität von Workloads sowie Kapazität und Performance der Enterprise-Klasse schnell zu realisieren. Es handelt sich dabei um denselben bekannten Prozess und dieselben Verfahren für die Verbindung von Speicher.

Weitere Informationen finden Sie unter:

* link:aws-native-overview.html["FSX ONTAP als ergänzenden NFS-Datenspeicher: Übersicht"]
* link:aws-native-nfs-datastore-option.html["Amazon FSX for ONTAP als Ergänzungsdatenspeicher"]




== Amazon FSX for NetApp ONTAP als Gast-verbundenen Storage

Amazon FSX ONTAP ist ein vollständig gemanagter Service, der äußerst zuverlässigen, skalierbaren, hochperformanten und funktionsreichen File-Storage bietet, der auf dem beliebten ONTAP-Filesystem von NetApp basiert. FSX ONTAP kombiniert die bekannten Funktionen, Performance, Funktionen und API-Operationen von NetApp-Filesystemen mit der Agilität, Skalierbarkeit und Einfachheit eines vollständig gemanagten AWS-Services.

FSX ONTAP bietet funktionsreichen, schnellen und flexiblen Shared-File-Storage, der über Linux-, Windows- und macOS-Computing-Instanzen, die in AWS oder lokal ausgeführt werden, allgemein zugänglich ist. FSX ONTAP bietet hochperformanten SSD-Storage (Solid State Drive) mit einer Latenz von unter einer Millisekunde. Mit FSX ONTAP können Sie SSD-Performance für Ihren Workload erzielen und gleichzeitig SSD-Storage für nur einen kleinen Bruchteil Ihrer Daten bezahlen.

Das Management Ihrer Daten mit FSX ONTAP ist einfacher, da Sie mit nur einem Klick Snapshots erstellen, klonen und replizieren können. Darüber hinaus führt FSX ONTAP automatisch das Tiering Ihrer Daten auf kostengünstigen, elastischen Storage durch. Das Provisioning und Management von Kapazität wird damit entlastet.

FSX ONTAP bietet außerdem hochverfügbaren und langlebigen Storage mit vollständig gemanagten Backups und Support für regionsübergreifende Disaster Recovery. Damit Sie Ihre Daten einfacher schützen und sichern können, unterstützt FSX ONTAP beliebte Datensicherheits- und Virenschutzanwendungen.

Weitere Informationen finden Sie unter link:aws-guest.html#fsx-ontap["FSX ONTAP als Storage mit Anbindung des Gastsystems"]



== Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff

Cloud Volumes ONTAP oder CVO ist die branchenführende Cloud-Datenmanagement-Lösung auf Basis der Storage-Software ONTAP von NetApp. Sie ist nativ auf Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform (GCP) verfügbar.

Es handelt sich um eine softwaredefinierte Version von ONTAP, die Cloud-nativen Storage nutzt, sodass Sie dieselbe Storage-Software in der Cloud und vor Ort nutzen können. Dadurch müssen SIE Ihre IT-Mitarbeiter nicht mehr in komplett neue Methoden zum Datenmanagement Schulen.

Mit CVO können Kunden Daten nahtlos vom Edge- zum Datacenter, zur Cloud und zurück verschieben und so Ihre Hybrid Cloud zusammen – all das wird über eine zentrale Managementkonsole, NetApp Cloud Manager, gemanagt.

CVO ist von Grund auf für höchste Performance und erweiterte Datenmanagementfunktionen konzipiert, um auch die anspruchsvollsten Applikationen in der Cloud zu unterstützen.

Weitere Informationen finden Sie unter link:aws-guest.html#aws-cvo["CVO als Storage mit Gastverbunden"].
