---
sidebar: sidebar 
permalink: ehc/ehc-solutions.html 
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst 
summary:  
---
= NetApp Lösungen für VMware bei Hyperscalern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Lösungen, die NetApp die VMware Umgebung in allen Hyperscalern zur Verfügung stellt: Migration von Workflows, Erweiterung/Bursting in die Cloud, Backup/Restore und Disaster Recovery.



== NetApp Lösungen für VMware Umgebungen

Egal, ob Sie in einem Hybrid-Cloud-Modell oder einem „Cloud First“-Modell arbeiten: NetApp bietet eine breite Palette an Lösungen für die gängigsten Anwendungsfälle für das Management von Workloads in einer Cloud oder einer Hybrid-Cloud-Modell.

Darüber hinaus bietet NetApp Lösungen für Storage, der als Gast-Storage (mit Anbindung an den Gast) oder als zusätzlicher NFS-Datenspeicher in jedem der Hyperscaler bereitgestellt wird. Alle Lösungen werden im Einklang mit der Klassifizierung von Cloud-Workloads durch VMware kategorisiert. Zu diesen Klassifizierungen gehören:

* Schutz (sowohl Disaster Recovery als auch Backup/Restore)
* Migrieren
* Erweitern


Weitere Informationen zu den für die einzelnen Hyperscaler verfügbaren Lösungen finden Sie unter:

* link:aws-solutions.html["Lösungen für AWS/VMC"]
* link:azure-solutions.html["Lösungen für Azure / AVS"]
* link:gcp-solutions.html["Lösungen für GCP/GCVE"]

