---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= NetApp Storage-Optionen für Public-Cloud-Provider
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Entdecken Sie die Optionen für NetApp als Storage in den drei wichtigsten Hyperscalern.

[role="tabbed-block"]
====
.AWS/VMC
--
AWS unterstützt NetApp Storage in den folgenden Konfigurationen:

* FSX ONTAP als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* FSX ONTAP als zusätzlichen NFS-Datastore


Details anzeigen link:aws/aws-guest.html["Storage-Optionen für VMC für Gastverbindung"]. Details anzeigen link:aws/aws-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für VMC"].

--
.Azure/AVS
--
Azure unterstützt NetApp Storage in den folgenden Konfigurationen:

* Azure NetApp Files (ANF) als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Azure NetApp Files (ANF) als zusätzlicher NFS-Datastore


Details anzeigen link:azure/azure-guest.html["Gastanbindung Speicheroptionen für AVS"]. Details anzeigen link:azure/azure-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für AVS"].

--
.GCP/GCVE
--
Google Cloud unterstützt NetApp Storage in den folgenden Konfigurationen:

* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Cloud Volumes Service (CVS) als Storage mit Gastverbunden
* Cloud Volumes Service (CVS) als zusätzlicher NFS Datastore


Details anzeigen link:gcp/gcp-guest.html["Speicheroptionen für die Gastverbindung für GCVE"].

Weitere Informationen link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Unterstützung von NetApp Cloud Volumes Service Datastores für die Google Cloud VMware Engine"^]

--
====