---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= NetApp Storage-Optionen für Public-Cloud-Provider
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entdecken Sie die Optionen für NetApp als Storage in den drei wichtigsten Hyperscalern.

[role="tabbed-block"]
====
.AWS/VMC
--
AWS unterstützt NetApp Storage in den folgenden Konfigurationen:

* FSX ONTAP als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* FSX ONTAP als zusätzlichen NFS-Datastore


Details anzeigen link:aws-guest.html["Storage-Optionen für VMC für Gastverbindung"]. Details anzeigen link:aws-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für VMC"].

--
.Azure/AVS
--
Azure unterstützt NetApp Storage in den folgenden Konfigurationen:

* Azure NetApp Files (ANF) als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Azure NetApp Files (ANF) als zusätzlicher NFS-Datastore


Details anzeigen link:azure-guest.html["Gastanbindung Speicheroptionen für AVS"]. Details anzeigen link:azure-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für AVS"].

--
.GCP/GCVE
--
Google Cloud unterstützt NetApp Storage in den folgenden Konfigurationen:

* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Google Cloud NetApp Volumes (NetApp Volumes) als über das Gastsystem verbundenen Storage
* Google Cloud NetApp Volumes (NetApp Volumes) als ergänzender NFS-Datastore


Sehen Sie sich die detaillierten link:gcp-guest.html["Speicheroptionen für die Gastverbindung für GCVE"]. Sehen Sie sich die detaillierten link:gcp-ncvs-datastore.html["Zusätzliche NFS-Datastore-Optionen für GCVE"].

Lesen Sie mehr über link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Unterstützung von Google Cloud NetApp Volumes Datastore für Google Cloud VMware Engine (NetApp Blog)"^] oder link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Verwenden von Google Cloud NetApp Volumes als Datastores für die Google Cloud VMware Engine (Google Blog)"^]

--
====