---
sidebar: sidebar 
permalink: ehc/ehc-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= Zusammenfassung und Schlussfolgerung: Warum NetApp Hybrid Multicloud mit VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Cloud Volumes bietet zusammen mit VMware Lösungen für die wichtigsten Hyperscaler ein großes Potenzial für Unternehmen, die Hybrid Cloud nutzen möchten. Der Rest dieses Abschnitts enthält die Nutzungsfälle, in denen die Integration von NetApp Cloud Volumes echte Hybrid-Multi-Cloud-Funktionen ermöglicht.



== Anwendungsfall #1: Storage-Optimierung

Bei einer Größenbemessung mit RVTools-Ausgabe ist es immer offensichtlich, dass die leistungsstarke Skalierung (vCPU/Vmem) parallel zum Storage erfolgt. Viele Unternehmen stellen sich in einer Situation wieder fest, dass durch den Storage-Platzbedarf die Größe des Clusters deutlich größer ist als für jede Leistung nötig.

Durch die Integration von NetApp Cloud Volumes können Unternehmen eine auf vSphere basierende Cloud-Lösung mit einem einfachen Migrationsansatz realisieren, ohne dass eine neue Plattform erforderlich ist oder IP-Änderungen vorgenommen werden müssen. Zudem ermöglicht diese Optimierung eine Skalierung des Storage-Platzbedarfs, während die Host-Anzahl auf die geringste Menge in vSphere beschränkt wird, jedoch keine Änderung der Storage-Hierarchie, der Sicherheit oder der verfügbaren Dateien vorgenommen werden muss. Somit können Sie die Implementierung optimieren und die Gesamtbetriebskosten um 35 bis 45 % senken. Dank dieser Integration ist außerdem die Möglichkeit möglich, in Sekundenschnelle Storage von warmen Storage-Ressourcen auf Produktionsebene zu skalieren.



== Anwendungsfall #2: Cloud-Migration

Unternehmen stehen unter dem Druck, Applikationen aus verschiedenen Gründen von lokalen Datacentern in die Public Cloud zu migrieren: Zu einem bevorstehenden Ablauf des Leasing-Vertrags, zu einer Finanzrichtlinie zur Ausgabenübernahme (Investitions-) in Betriebskosten oder einfach zu einem Top-down-Auftrag, um alles in die Cloud zu verschieben.

Wenn Geschwindigkeit entscheidend ist, ist nur ein optimierter Migrationsansatz möglich, da die Rekonfiguration und Refakturierung von Anwendungen zur Anpassung an die spezielle IaaS-Plattform der Cloud langsam und teuer ist und oft Monate in Anspruch nimmt. Durch die Kombination von NetApp Cloud Volumes mit der bandbreiteneffizienten SnapMirror Replizierung für Storage mit Anbindung an den Gast-Storage (einschließlich RDMs in Verbindung mit applikationskonsistenten Snapshot Kopien und HCX, Cloud-spezifische Migration (z. B. Azure Migrate) oder Produkte von Drittanbietern zur Replizierung von VMs) ist dieser Wechsel noch einfacher, als auf zeitaufwändige I/O-Filtermechanismen zurückgreifen zu müssen.



== Anwendungsfall #3: Datacenter-Erweiterung

Wenn in einem Datacenter aufgrund von saisonalen Bedarfsspitzen oder einem stabilen organischen Wachstum Kapazitätsgrenzen erreicht werden, ist der Wechsel zu VMware in Cloud-Umgebungen zusammen mit NetApp Cloud Volumes eine einfache Lösung. Der Einsatz von NetApp Cloud Volumes ermöglicht das sehr einfache Erstellen, Replizieren und erweitern von Storage, da über Verfügbarkeitszonen hinweg Hochverfügbarkeit und dynamische Skalierungsfunktionen sichergestellt sind. Mithilfe von NetApp Cloud Volumes minimieren Sie die Host-Cluster-Kapazität, da es dafür keine Stretch-Cluster mehr braucht.



== Anwendungsfall #4: Disaster Recovery in der Cloud

Bei einem herkömmlichen Ansatz würden im Falle eines Ausfalls die in die Cloud replizierten VMs vor der Wiederherstellung auf die Cloud eigene Hypervisor-Plattform umgewandelt werden müssen – und das in einer Krise nicht.

Durch den Einsatz von NetApp Cloud Volumes für miteinander verbundenen Storage mit SnapCenter und SnapMirror Replizierung aus lokalen Systemen sowie mit Public-Cloud-Virtualisierungslösungen lässt sich ein besserer Disaster-Recovery-Ansatz entwickeln, der die Wiederherstellung von VM-Replikaten in einer vollständig konsistenten VMware SDDC-Infrastruktur sowie Cloud-spezifischen Recovery-Tools (z. B. Azure Site Recovery) oder vergleichbare Tools anderer Hersteller wie Veeam Dieser Ansatz unterstützt Sie auch bei der schnellen Durchführung von Disaster-Recovery-Prozessen und Recovery von Ransomware. Außerdem lassen sich dank bedarfsorientierter Hosts die gesamte Produktion zu Testzwecken oder bei einem Ausfall skalieren.



== Anwendungsfall #5: Applikationsmodernisierung

Sobald Applikationen in der Public Cloud bereitgestellt wurden, möchten Unternehmen die zahlreichen leistungsstarken Cloud-Services nutzen, um sie zu modernisieren und zu erweitern. Mit NetApp Cloud Volumes ist eine Modernisierung ein einfacher Prozess, da die Applikationsdaten nicht in vSAN geschützt sind. Außerdem ermöglicht sie Datenmobilität für zahlreiche Anwendungsfälle, einschließlich Kubernetes.



== Schlussfolgerung

Egal, ob Sie eine All-Cloud oder eine Hybrid Cloud abzielen – NetApp Cloud Volumes bietet Ihnen hervorragende Optionen für die Implementierung und das Management von Applikations-Workloads zusammen mit Fileservices und Blockprotokollen. Gleichzeitig reduziert es die TCO, indem die Datenanforderungen nahtlos auf die Applikationsebene übertragen werden.

Welche Anwendungsfälle auch immer sind: Wählen Sie Ihre bevorzugten Cloud/Hyperscaler zusammen mit NetApp Cloud Volumes, um schnell von den Vorteilen der Cloud zu profitieren, konsistente Infrastruktur und Abläufe zwischen On-Premises- und diversen Clouds, bidirektionaler Portabilität von Workloads sowie Kapazität und Performance der Enterprise-Klasse zu profitieren.

Es handelt sich dabei um denselben bekannten Prozess und dieselben Verfahren, mit denen der Speicher verbunden wird. Denken Sie daran, es ist nur die Position der Daten, die sich mit neuen Namen geändert haben. NetApp Cloud Volumes bleiben dieselben Tools und Prozesse, und NetApp Cloud Volumes helfen bei der Optimierung der generellen Implementierung.
