---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= Anwendungsfälle für NetApp Hybrid-Multi-Cloud mit VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ein Überblick über die Anwendungsfälle, die für DIE IT-Abteilung bei der Planung von Hybrid-Cloud- oder Cloud-First-Implementierungen von Bedeutung sind



== Gängige Anwendungsfälle

Anwendungsfälle:

* Disaster Recovery,
* Hosting von Workloads während der Rechenzentrumswartung, * schneller Burst, in dem zusätzliche Ressourcen über die im lokalen Rechenzentrum bereitgestellten Ressourcen erforderlich sind,
* VMware-Site-Erweiterung,
* Schnelle Migration in die Cloud,
* Entwicklung/Test und
* Modernisierung von Applikationen mithilfe von zusätzlichen Cloud-Technologien


In der gesamten Dokumentation werden die Referenzen für Cloud-Workloads anhand der VMware Anwendungsfälle detailliert beschrieben. Anwendungsfälle sind:

* Schutz (sowohl Disaster Recovery als auch Backup/Restore)
* Migrieren
* Erweitern




=== In DER IT-Entwicklung

Die meisten Unternehmen befinden sich auf dem Weg zur Transformation und Modernisierung. Im Rahmen dieses Prozesses versuchen Unternehmen, ihre vorhandenen VMware Investitionen zu nutzen und gleichzeitig von den Vorteilen der Cloud zu profitieren und Möglichkeiten für eine nahtlose Migration zu entdecken. Durch diesen Ansatz würde sich ihre Modernisierungsbemühungen sehr vereinfachen, da sich die Daten bereits in der Cloud befinden.

Die einfachste Antwort auf dieses Szenario sind die Angebote von VMware in jedem Hyperscaler. Wie bei NetApp Cloud Volumes bietet VMware eine Möglichkeit, lokale VMware Umgebungen in jede Cloud zu verschieben oder zu erweitern. So können Sie vorhandene Ressourcen, Fachkenntnisse und Tools weiterhin nutzen, während Sie Workloads nativ in der Cloud ausführen. Das verringert die Risiken, da keine Serviceunterbrechungen oder IP-Änderungen erforderlich sind. Das IT-Team kann so unter Verwendung vorhandener Fachkenntnisse und Tools vor Ort Verfahren. Dies ermöglicht beschleunigte Cloud-Migrationen und einen viel reibungsloseren Übergang zu einer Hybrid Multi Cloud Architektur.



=== Bedeutung von zusätzlichen NFS-Storage-Optionen

Während VMware in jeder Cloud seinen Kunden einzigartige Hybrid-Funktionen bietet, haben begrenzte zusätzliche NFS-Storage-Optionen den Nutzen für Unternehmen mit Storage-lastigen Workloads eingeschränkt. Da Storage direkt an Hosts gebunden ist, besteht die einzige Möglichkeit zur Skalierung von Storage darin, weitere Hosts hinzuzufügen. Die Kosten können bei Storage-intensiven Workloads um 35 bis 40 % oder mehr gesenkt werden. Diese Workloads erfordern nur zusätzlichen Storage und keine zusätzliche Leistung. Aber das bedeutet, dass zusätzliche Hosts bezahlt werden.

Betrachten wir das folgende Szenario:

Ein Kunde benötigt nur fünf Hosts für CPU und Arbeitsspeicher, hat aber hohe Storage-Anforderungen und benötigt 12 Hosts, um die Storage-Anforderungen zu erfüllen. Diese Anforderung kippt letztlich in Richtung Finanzskalierung, indem sie zusätzliche Leistung kaufen müssen, wenn sie nur den Storage erhöhen müssen.

Wenn Sie Cloud-Einführung und -Migrationen planen, ist es immer wichtig, den besten Ansatz zu bewerten und den einfachsten Weg zu gehen, der die Gesamtinvestitionen reduziert. Der gängigste und einfachste Ansatz für jede Applikationsmigration besteht in Rehosting (auch bekannt als „Lift and Shift“), in dem keine Virtual Machine (VM) oder Datenkonvertierung vorhanden ist. NetApp Cloud Volumes mit dem softwaredefinierten Datacenter (SDDC) von VMware und ergänzen vSAN und bieten eine einfache „Lift-and-Shift“-Option.
