---
sidebar: sidebar 
permalink: ehc/evs-mount-fsxn-conclusion.html 
keywords: Amazon, AWS, EVS, Elastic VMware Service, ONTAP, FSx 
summary: Dieser Artikel enthält Anweisungen zum Einrichten von FSx für ONTAP als externer Speicher für Amazon EVS zur Verwendung mit den Protokollen NFS und iSCSI. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieses Dokument enthält Anweisungen zum Einrichten von FSx für ONTAP als externer Speicher für Amazon EVS zur Verwendung mit den Protokollen NFS und iSCSI.

Die Verwendung von FSx for ONTAP als externer Speicher für Amazon EVS bietet klare betriebliche und geschäftliche Vorteile. Es bietet verbesserte Datenstabilität, Schutz, Replikation und Kosteneffizienz durch die ONTAP-Technologie und optimiert die Gesamtbetriebskosten dank der Entkopplung der hyperkonvergenten VMware-Architektur. Mit FSx for ONTAP können Amazon EVS-Nutzer den Speicher skalieren, ohne zusätzliche Rechenressourcen hinzuzufügen und ohne die Kosten zu erhöhen. Dadurch wird das volle Elastizitäts- und Skalierbarkeitspotenzial der AWS Cloud ausgeschöpft.

Weitere Informationen finden Sie in der Ankündigung zu den Neuerungen von Amazon: link:https://aws.amazon.com/about-aws/whats-new/2025/06/amazon-elastic-vmware-service-fsx-netapp-ontap/["Amazon EVS ist jetzt in FSx für ONTAP integriert"] und das NetApp-Blog: link:https://www.netapp.com/blog/amazon-elastic-vmware-service-fsx-ontap/["Amazon EVS kündigt Unterstützung für FSx für ONTAP an"] .
