---
sidebar: sidebar 
permalink: ehc/gcp-regions.html 
keywords: NetApp Solutions, google cloud, gcp, gcve, regions 
summary:  
---
= Regionale Verfügbarkeit – ergänzender NFS-Datastore für Google Cloud Platform (GCP)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Erfahren Sie mehr über die Unterstützung der Global Region für GCP, GCVE und CVS.


NOTE: NFS-Datastore wird in Regionen verfügbar sein, in denen beide Services (GCVE und CVS Performance) verfügbar sind.

Zusätzlicher NFS-Datastore für GCVE wird von NetApp Cloud Volume Service unterstützt.


NOTE: Für den GCVE NFS Datastore können nur CVS-Performance Volumes verwendet werden.
Informationen zum verfügbaren Speicherort finden Sie unter link:https://bluexp.netapp.com/cloud-volumes-global-regions#cvsGc["Globale Regionalkarte"]

Die Google Cloud VMware Engine ist an folgenden Speicherorten verfügbar::gcve_Regions_Mar2023.png[] um die Latenz zu minimieren, sollten sich das NetApp CVS-Volume und GCVE, wo Sie das Volume mounten möchten, in derselben Verfügbarkeitszone befinden. Arbeiten Sie mit Google und NetApp Solution Architects zusammen, um Verfügbarkeit und TCO-Optimierung zu optimieren.
