---
sidebar: sidebar 
permalink: ehc/gcp-storage-options.html 
keywords: gcp, gcve, gcnv, nfs, supplemental, datastore, vcenter, vmware, cvo, storage, options 
summary: NetApp Storage kann an die Google Cloud Virtualization Engine als mit dem Gast verbundenen oder ergänzenden Storage angebunden werden. 
---
= Google Cloud VMware Engine: Optionen zur Nutzung von NetApp Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Storage kann an die Google Cloud Virtualization Engine als mit dem Gast verbundenen oder ergänzenden Storage angebunden werden.



== Google Cloud NetApp Volumes (NetApp Volumes) als ergänzender NFS-Datastore

Kunden, die in ihrer Google Cloud VMware Engine (GCVE) Umgebung zusätzliche Storage-Kapazität benötigen, können Google Cloud NetApp Volumes zum Mounten als ergänzenden NFS-Datastore nutzen. Durch das Speichern von Daten in Google Cloud NetApp Volumes können Kunden zwischen Regionen replizieren, um vor Diastern zu schützen.

Weitere Informationen finden Sie unter link:gcp-ncvs-datastore.html["Google Cloud NetApp Volumes (NetApp Volumes) als ergänzender NFS-Datastore"]



== NetApp CVO als Gast-vernetzter Storage

Cloud Volumes ONTAP oder CVO ist die branchenführende Cloud-Datenmanagement-Lösung auf Basis der Storage-Software ONTAP von NetApp. Sie ist nativ auf Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform (GCP) verfügbar.

Es handelt sich um eine softwaredefinierte Version von ONTAP, die Cloud-nativen Storage nutzt, sodass Sie dieselbe Storage-Software in der Cloud und vor Ort nutzen können. Dadurch müssen SIE Ihre IT-Mitarbeiter nicht mehr in komplett neue Methoden zum Datenmanagement Schulen.

Mit CVO können Kunden Daten nahtlos vom Edge- zum Datacenter, zur Cloud und zurück verschieben und so Ihre Hybrid Cloud zusammen – all das wird über eine zentrale Managementkonsole, NetApp Cloud Manager, gemanagt.

CVO ist von Grund auf für höchste Performance und erweiterte Datenmanagementfunktionen konzipiert, um auch die anspruchsvollsten Applikationen in der Cloud zu unterstützen.

Weitere Informationen finden Sie unter link:gcp-guest.html#gcp-cvo["NetApp CVO als Gast-vernetzter Storage"]



== Google Cloud NetApp Volumes (NetApp Volumes) als Storage mit Gastverbindung

Google Cloud NetApp Volumes Shares können von VMs gemountet werden, die in der VMware Engine Umgebung erstellt werden. Die Volumes können auch auf dem Linux-Client gemountet und im Windows Client zugeordnet werden, da Google Cloud NetApp Volumes SMB- und NFS-Protokolle unterstützt. Die Einrichtung von Google Cloud NetApp Volumes besteht in einfachen Schritten.

Google Cloud NetApp Volumes und die Google Cloud VMware Engine Private Cloud müssen sich in derselben Region befinden.

Weitere Informationen finden Sie unter link:gcp-guest.html#gcnv["Google Cloud NetApp Volumes (NetApp Volumes) als Storage mit Gastverbindung"]
