---
sidebar: sidebar 
permalink: ehc/ncvs-gc-security-considerations-and-attack-surfaces.html 
keywords: secure logins, cluster administration, upgrades, data at-rest, mitigation 
summary: Der erste Schritt zum Verständnis der Datensicherung besteht darin, die Risiken und potenziellen Angriffsflächen zu identifizieren. 
---
= Sicherheitsüberlegungen und Angriffsflächen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der erste Schritt zum Verständnis der Datensicherung besteht darin, die Risiken und potenziellen Angriffsflächen zu identifizieren.

Dazu gehören (aber nicht beschränkt auf) die folgenden:

* Administration und Anmeldung
* Daten im Ruhezustand
* Genutzte Daten
* Netzwerk und Firewalls
* Ransomware, Malware und Viren


Das Verständnis von Angriffsflächen kann Ihnen helfen, Ihre Umgebungen besser zu schützen. Google Cloud NetApp Volumes in Google Cloud werden bereits viele dieser Themen berücksichtigt und standardmäßig Sicherheitsfunktionen ohne administrativen Eingriff implementiert.



== Sichere Anmeldungen sicherstellen

Bei der Sicherung Ihrer kritischen Infrastrukturkomponenten ist es von größter Wichtigkeit, sicherzustellen, dass nur genehmigte Benutzer sich einloggen und Ihre Umgebungen managen können. Wenn fehlerhafte Akteure die Anmeldedaten in Ihrem System verletzen, haben sie die Schlüssel zum Schloss und können alles tun, was sie wollen: Konfigurationen ändern, Volumes und Backups löschen, Backdoors erstellen oder Snapshot-Zeitpläne deaktivieren.

Google Cloud NetApp Volumes für Google Cloud bieten Schutz vor nicht autorisierten administrativen Anmeldungen durch die Verschleierung von Storage-als-Service (StaaS). Google Cloud NetApp Volumes wird vollständig vom Cloud-Provider verwaltet. Eine externe Anmeldung ist nicht möglich. Alle Setup- und Konfigurationsvorgänge sind vollautomatisiert, sodass ein Administrator in seltenen Fällen nie mit den Systemen interagieren muss.

Wenn Anmeldung erforderlich ist, sichert Google Cloud NetApp Volumes in Google Cloud Anmeldungen, indem eine sehr kurze Liste vertrauenswürdiger Administratoren bereithält, die zum Anmelden an den Systemen zugreifen können. Diese Gatekeeping hilft, die Anzahl potenzieller schlechter Akteure mit Zugriff zu reduzieren. Darüber hinaus verbirgt das Google Cloud-Netzwerk die Systeme hinter Schichten der Netzwerksicherheit und legt nur das, was für die Außenwelt benötigt wird, offen. Weitere Informationen zur Google Cloud und zur Architektur von Google Cloud NetApp Volumes finden Sie im Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html["„Google Cloud NetApp Volumes Architektur“"]



== Cluster-Administration und Upgrades

Zu den zwei Bereichen mit potenziellen Sicherheitsrisiken zählen die Clusterverwaltung (was passiert, wenn ein schlechter Akteur Administratorzugriff hat) und Upgrades (was passiert, wenn ein Software-Image beeinträchtigt wird).



=== Sicherung der Storage-Administration

Der als Service bereitgestellte Storage beseitigt das zusätzliche Risiko, dass Administratoren diesem Zugriff nicht mehr an Anwender außerhalb des Cloud-Datacenters ausgesetzt sind. Stattdessen gilt die einzige Konfiguration für die Datenzugriffsebene durch Kunden. Jeder Mandant managt seine eigenen Volumes, sodass kein Mandant andere Instanzen von Google Cloud NetApp Volumes erreichen kann. Der Service wird durch Automatisierung gemanagt. In einer sehr kleinen Liste vertrauenswürdiger Administratoren wird durch die im Abschnitt beschriebenen Prozesse auf die Systeme zugegriffen link:ncvs-gc-service-operation.html["„Service-Betrieb“."]

Der Servicetyp NetApp Volumes-Performance bietet regionsübergreifende Replizierung, um bei einem Ausfall der Region die Datensicherung in einer anderen Region zu ermöglichen. In diesen Fällen kann für Google Cloud NetApp Volumes ein Failover in die nicht betroffene Region durchgeführt werden, um den Datenzugriff aufrechtzuerhalten.



=== Service-Upgrades

Updates helfen, gefährdete Systeme zu schützen. Jedes Update bietet Verbesserungen der Sicherheit und Fehlerbehebungen zur Minimierung von Angriffsflächen. Software-Updates werden aus zentralen Repositorys heruntergeladen und validiert, bevor die Updates überprüft werden, ob offizielle Bilder verwendet werden und dass die Upgrades nicht durch fehlerhafte Akteure beeinträchtigt werden.

Mit Google Cloud NetApp Volumes werden Updates von Cloud-Provider-Teams durchgeführt. Damit besteht keine Gefahr für Administratoren, da Experten mit viel Erfahrung in Konfigurationen und Upgrades angeboten werden, die den Prozess automatisiert und vollständig getestet haben. Upgrades sind unterbrechungsfrei und Google Cloud NetApp Volumes hält die neuesten Updates für beste allgemeine Ergebnisse bereit.

Informationen über das Administrator-Team, das diese Service-Upgrades durchführt, finden Sie im Abschnitt link:ncvs-gc-service-operation.html["„Service-Betrieb“."]



== Sicherheit von Daten im Ruhezustand

Die Verschlüsselung ruhender Daten ist wichtig, um sensible Daten bei Diebstahl, Rückgabe oder neuer Verwendung einer Festplatte zu schützen. Daten in Google Cloud NetApp Volumes werden mithilfe der softwarebasierten Verschlüsselung im Ruhezustand geschützt.

* Für die NetApp Volumes-SW werden die von Google erzeugten Schlüssel verwendet.
* Für NetApp Volumes-Performance werden die Schlüssel pro Volume in einem in Google Cloud NetApp Volumes integrierten Schlüsselmanager gespeichert, der mithilfe von NetApp ONTAP CryptoMod AES-256-Verschlüsselungen generiert. CryptoMod ist in der nach FIPS 140-2 validierten CMVP-Modulliste aufgeführt. Siehe https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144["FIPS 140-2 Zertifikat #4144"^].


Im November 2021 wurde die Vorschau für die Funktionalität der vom Kunden gemanagten Verschlüsselung (Customer-Managed Encryption, CMEK) für NetApp Volumes-Performance verfügbar gemacht. Diese Funktionalität ermöglicht Ihnen die Verschlüsselung der Schlüssel pro Volume mit Master-Schlüsseln für einzelne Projekte und Regionen, die im Google Key Management Service (KMS) gehostet werden. KMS ermöglicht es Ihnen, externe Schlüsselmanager anzubinden.

Für Details über die Konfiguration von KMS für NetApp Volumes-Performance, https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Weitere Informationen finden Sie in der Dokumentation zu Google Cloud NetApp Volumes"^].

Weitere Informationen zur Architektur finden Sie im Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html["„Google Cloud NetApp Volumes Architektur“"]



=== Sicherheit der aktiven Daten

Neben der Sicherung von Daten im Ruhezustand müssen Sie in der Lage sein, Daten bei der Übertragung zwischen der Google Cloud NetApp Volumes-Instanz und einem Client oder Replizierungsziel zu sichern. Google Cloud NetApp Volumes bietet Verschlüsselung für Daten während der Übertragung über NAS-Protokolle. Dazu werden Verschlüsselungsmethoden wie SMB-Verschlüsselung mit Kerberos, das Signieren/Versiegeln von Paketen und NFS Kerberos 5p für End-to-End-Verschlüsselung von Datentransfers verwendet.

Bei der Replizierung von Google Cloud NetApp Volumes wird TLS 1.2 verwendet, das von den AES-GCM-Verschlüsselungsmethoden profitiert.

Die unsicheres in-Flight-Protokolle wie Telnet, NDMP usw. sind standardmäßig deaktiviert. DNS wird jedoch nicht von Google Cloud NetApp Volumes verschlüsselt (keine DNS-sec-Unterstützung) und sollte nach Möglichkeit mit externer Netzwerkverschlüsselung verschlüsselt werden. Weitere Informationen zum Sichern von Daten bei der Übertragung finden Sie im Abschnittlink:ncvs-gc-data-encryption-in-transit.html["„Datenverschlüsselung während der Übertragung“"].

Informationen zur Verschlüsselung von NAS-Protokollen finden Sie im Abschnitt link:ncvs-gc-data-encryption-in-transit.html#nas-protocols["„NAS-Protokolle“."]



== Benutzer und Gruppen für NAS-Berechtigungen

Bei der Sicherung Ihrer Daten in der Cloud ist eine ordnungsgemäße Benutzer- und Gruppenauthentifizierung erforderlich, wobei die Benutzer, die auf die Daten zugreifen, als echte Benutzer in der Umgebung überprüft werden und die Gruppen gültige Benutzer enthalten. Diese Benutzer und Gruppen bieten ersten Zugriff auf Freigabe und Export sowie Berechtigungsvalidierung für Dateien und Ordner im Speichersystem.

Google Cloud NetApp Volumes nutzt die standardmäßige Active Directory-basierte Windows-Benutzer- und Gruppenauthentifizierung für SMB-Freigaben und Windows-ähnliche Berechtigungen. Der Service kann auch UNIX Identitätsanbieter wie LDAP für UNIX Benutzer und Gruppen für NFS-Exporte, NFSv4 ID-Validierung, Kerberos-Authentifizierung und NFSv4 ACLs nutzen.


NOTE: Für die LDAP-Funktion von Google Cloud NetApp Volumes wird derzeit nur Active Directory LDAP unterstützt.



== Erkennung, Verhinderung und Minimierung von Ransomware, Malware und Viren

Ransomware, Malware und Viren sind für Administratoren eine persistente Bedrohung. Die Erkennung, das Vorbeugen und die Minimierung dieser Bedrohungen steht für Unternehmen immer im Mittelpunkt. Ein einzelnes Ransomware-Ereignis auf einem kritischen Datensatz kann potenziell Millionen US-Dollar kosten. Daher ist es vorteilhaft, alles zu tun, um das Risiko zu minimieren.

Google Cloud NetApp Volumes umfasst derzeit keine nativen Erkennungs- oder Präventionsmaßnahmen wie einen Virenschutz oder https://www.netapp.com/blog/prevent-ransomware-spread-ONTAP/["Automatische Ransomware-Erkennung"^]. Es gibt jedoch Möglichkeiten, nach einem Ransomware-Ereignis schnell eine Wiederherstellung durch regelmäßige Snapshot Zeitpläne zu ermöglichen. Snapshot-Kopien sind unveränderliche und schreibgeschützte Verweise auf geänderte Blöcke im Filesystem, werden praktisch sofort erzeugt, haben minimale Auswirkungen auf die Performance und verbrauchen nur Speicherplatz, wenn Daten geändert oder gelöscht werden. Sie können Zeitpläne für Snapshot Kopien einrichten, die auf Ihre gewünschte akzeptable Recovery Point Objective (RPO)/Recovery Time Objective (RTO) abgestimmt sind und bis zu 1,024 Snapshot Kopien pro Volume aufbewahren.

Der Snapshot-Support ist ohne zusätzliche Kosten enthalten (über die Storage-Gebühren für geänderte Blöcke/Daten, die in Snapshot-Kopien gespeichert wurden) für Google Cloud NetApp Volumes und kann im Falle eines Ransomware-Angriffs für ein Rollback auf eine Snapshot-Kopie vor dem Angriff verwendet werden. Snapshot Wiederherstellungen dauern nur wenige Sekunden und Daten können wieder wie gewohnt bereit sein. Weitere Informationen finden Sie unter https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745["NetApp Lösung gegen Ransomware"^].

Die Auswirkungen von Ransomware auf Ihr Unternehmen zu verhindern, ist ein mehrschichtiger Ansatz erforderlich, der einen oder mehrere der folgenden Elemente umfasst:

* Endpoint-Schutz
* Schutz vor externen Bedrohungen durch Netzwerk-Firewalls
* Erkennung von Datenanomalien
* Mehrere Backups (vor Ort und extern) kritischer Datensätze
* Regelmäßige Restore-Tests von Backups
* Unveränderliche schreibgeschützte NetApp Snapshot Kopien
* Multi-Faktor-Authentifizierung für kritische Infrastrukturen
* Sicherheitsprüfungen von Systemanmeldungen


Diese Liste ist bei weitem nicht erschöpfend, aber ist eine gute Blaupause, wenn man mit dem Potential der Ransomware-Angriffe zu folgen. Google Cloud NetApp Volumes in Google Cloud bietet verschiedene Möglichkeiten, sich vor Ransomware-Ereignissen zu schützen und ihre Auswirkungen zu verringern.



=== Unveränderliche Snapshot Kopien

Google Cloud NetApp Volumes bietet nativ unveränderliche, schreibgeschützte Snapshot Kopien, die nach einem anpassbaren Zeitplan für eine schnelle zeitpunktgenaue Recovery erstellt werden, wenn Daten gelöscht werden oder ein ganzes Volume von einem Ransomware-Angriff angegriffen wurde. Snapshots können zu vorherigen guten Snapshot Kopien schnell wiederhergestellt werden und minimieren Datenverluste aufgrund der Aufbewahrungsdauer Ihrer Snapshot-Zeitpläne und RTO/RPO. Der Performance-Effekt mit der Snapshot Technologie ist zu vernachlässigen.

Da Snapshot Kopien in Google Cloud NetApp Volumes schreibgeschützt sind, können sie erst dann durch Ransomware infiziert werden, wenn die Ransomware unbemerkt in den Datensatz übergegangen ist und Snapshot Kopien der von Ransomware infizierten Daten erstellt wurden. Deshalb ist es notwendig, auf der Basis von Datenanomalien auch Ransomware-Erkennung in Betracht zu ziehen. Google Cloud NetApp Volumes bieten derzeit keine native Erkennung, doch Sie können externe Monitoring-Software verwenden.



=== Backups und Restores

Google Cloud NetApp Volumes bietet standardmäßige NAS-Client-Backup-Funktionen (z. B. Backups über NFS oder SMB).

* NetApp Volumes-Performance bietet regionsübergreifende Volume-Replizierung auf andere NetApp Volumes mit Performance. Weitere Informationen finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/volume-replication?hl=en_US["Volume-Replizierung"^] in der Dokumentation zu Google Cloud NetApp Volumes.
* NetApp Volumes-SW bietet Service-native Volume-Backup-/Restore-Funktionen. Weitere Informationen finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Cloud-Backup"^] in der Dokumentation zu Google Cloud NetApp Volumes.


Die Volume-Replizierung liefert eine exakte Kopie des Quell-Volumes für schnelles Failover im Falle eines Ausfalls, einschließlich Ransomware-Ereignissen.



=== Regionsübergreifende Replizierung

Mit NetApp Volumes-Performance können Sie Volumes über Google Cloud Regionen hinweg für Datensicherung und Archivierung sicher replizieren. Dazu wird die TLS1.2 AES 256 GCM-Verschlüsselung in einem durch NetApp kontrollierten Back-End-Service-Netzwerk verwendet, und zwar über spezifische Schnittstellen, die für die im Netzwerk von Google ausgeführte Replizierung verwendet werden. Ein primäres Volume (Quell-Volume) enthält die aktiven Produktionsdaten und repliziert auf ein sekundäres Volume (Ziel-Volume), um ein exaktes Replikat des primären Datensatzes zu erstellen.

Bei der anfänglichen Replizierung werden alle Blöcke übertragen, jedoch werden nur die geänderten Blöcke in einem primären Volume übertragen. Wird beispielsweise eine Datenbank mit 1 TB auf einem primären Volume auf das sekundäre Volume repliziert, so werden bei der ersten Replizierung 1 TB Speicherplatz übertragen. Wenn diese Datenbank einige hundert Zeilen (hypothetisch einige MB) hat, die zwischen der Initialisierung und dem nächsten Update wechseln, werden nur die Blöcke mit den geänderten Zeilen auf das sekundäre (wenige MB) repliziert. So wird sichergestellt, dass die Übertragungszeiten niedrig bleiben und die Replizierungskosten sinken.

Alle Berechtigungen für Dateien und Ordner werden auf das sekundäre Volume repliziert, aber die Zugriffsberechtigungen für die Freigabe (wie Exportrichtlinien und Regeln oder SMB-Freigaben und ACLs für die Freigabe) müssen separat gehandhabt werden. Bei einem Site-Failover sollte der Zielstandort dieselben Namensdienste und Active Directory-Domänenverbindungen nutzen, um eine konsistente Handhabung von Benutzer- und Gruppenidentitäten und -Berechtigungen zu ermöglichen. Sie können ein sekundäres Volume im Notfall als Failover-Ziel verwenden, indem Sie die Replizierungsbeziehung unterbrechen, die das sekundäre Volume in Lese- und Schreibvorgänge konvertiert.

Volume-Replikate sind schreibgeschützt, d. h. eine unveränderliche Kopie der Daten an einem externen Standort zur schnellen Recovery von Daten in Instanzen, in denen ein Virus infizierte Daten hat oder Ransomware den primären Datensatz verschlüsselt hat. Nur-Lese-Daten werden nicht verschlüsselt, aber, wenn das primäre Volume betroffen ist und Replikation auftritt, die infizierten Blöcke replizieren auch. Zur Wiederherstellung können Sie ältere, nicht betroffene Snapshot Kopien verwenden. Je nachdem, wie schnell ein Angriff erkannt wird, fallen jedoch unter Umständen die versprochenen RTO/RPO-Vorgaben aus.

Darüber hinaus können Sie mit dem Management der regionsübergreifenden Replizierung (CRR) in Google Cloud böswillige Administratoraktionen, wie z. B. Volume-Löschungen, Snapshot-Löschungen oder Änderungen bei Snapshot-Planungen, verhindern. Dazu werden benutzerdefinierte Rollen erstellt, die Volume-Administratoren trennen, die Quell-Volumes löschen, aber keine Spiegelungen unterbrechen und daher keine Ziel-Volumes von CRR-Administratoren löschen können, die keine Volume-Vorgänge ausführen können.  https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Überlegungen Zur Sicherheit"^]In der Dokumentation zu Google Cloud NetApp Volumes finden Sie Informationen zu den von den einzelnen Administratorgruppen zulässigen Berechtigungen.



=== Google Cloud NetApp Volumes Backup

Google Cloud NetApp Volumes bietet zwar eine hohe Datenaufbewahrung, aber externe Ereignisse können zu Datenverlusten führen. Falls es zu Sicherheitsereignisse wie Viren oder Ransomware kommt, werden Backups und Restores so wichtig, dass der Datenzugriff rechtzeitig wiederaufgenommen werden kann. Ein Administrator könnte versehentlich ein Google Cloud NetApp Volumes-Volume löschen. Oder Benutzer möchten einfach noch viele Monate Backup-Versionen ihrer Daten aufbewahren und den zusätzlichen Speicherplatz für Snapshot-Kopien innerhalb des Volumes zu einer Kostenanforderung machen. Snapshot-Kopien sollten die bevorzugte Methode sein, Backup-Versionen für die letzten Wochen zu behalten, um verlorene Daten von ihnen wiederherzustellen, sie befinden sich jedoch im Volume und gehen verloren, wenn das Volume entfernt wird.

Aus all diesen Gründen bietet Google Cloud NetApp Volumes Backup-Services über https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Google Cloud NetApp Volumes Backup"^]an.

Google Cloud NetApp Volumes Backup erzeugt eine Kopie des Volumes auf Google Cloud Storage (GCS). Es sichert nur die tatsächlichen Daten, die innerhalb des Volume gespeichert sind, nicht den freien Speicherplatz. Es funktioniert wie immer inkrementell, d. h., es überträgt den Volume-Inhalt einmal und von dort auf wird nur geänderte Daten gesichert. Im Vergleich zu klassischen Backup-Konzepten mit mehreren vollständigen Backups spart das Unternehmen viel Storage und senkt dadurch die Kosten. Da der monatliche Preis von Backup-Speicherplatz im Vergleich zu einem Volume niedriger ist, ist es der ideale Ort, um Backup-Versionen länger zu halten.

Anwender können mit einem Google Cloud NetApp Volumes Backup jede Backup-Version auf dasselbe oder ein anderes Volume innerhalb derselben Region wiederherstellen. Wenn das Quell-Volume gelöscht wird, werden die Backup-Daten aufbewahrt und müssen unabhängig gemanagt werden (beispielsweise gelöscht).

Google Cloud NetApp Volumes Backup ist optional in Google Cloud NetApp Volumes integriert. Benutzer können entscheiden, welche Volumes sie schützen, indem sie Google Cloud NetApp Volumes Backup pro Volume aktivieren. Weitere https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Google Cloud NetApp Volumes Backup-Dokumentation"^] Informationen zu Backups, der, Planung und https://cloud.google.com/architecture/partners/netapp-cloud-volumes/costs?hl=en_US["Preisgestaltung"^]finden Sie im https://cloud.google.com/architecture/partners/netapp-cloud-volumes/resource-limits-quotas?hl=en_US["Anzahl der maximal unterstützten Backup-Versionen"^] .

Alle Backup-Daten eines Projekts werden innerhalb eines GCS-Buckets gespeichert, der durch den Service gemanagt wird und für den Benutzer nicht sichtbar ist. Jedes Projekt verwendet einen anderen Bucket. Derzeit befinden sich die Buckets in derselben Region wie die Google Cloud NetApp Volumes, aber es gibt noch mehr Optionen. In der Dokumentation finden Sie den aktuellen Status.

Der Datentransport von einem Google Cloud NetApp Volumes Bucket zu GCS nutzt serviceinterne Google-Netzwerke mit HTTPS und TLS1.2. Die Daten werden im Ruhezustand mit von Google gemanagten Schlüsseln verschlüsselt.

Für das Management von Google Cloud NetApp Volumes-Backups (Erstellen, Löschen und Wiederherstellen von Backups) muss ein Benutzer über die entsprechende Rolle verfügen https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Rollen/netappCloudVolumes.admin"^].
