---
sidebar: sidebar 
permalink: ehc/ncvs-gc-data-encryption-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: Alle Volumes in Google Cloud NetApp Volumes werden im Ruhezustand mittels AES-256-Verschlüsselung verschlüsselt. Dies bedeutet, dass alle auf Medien geschriebenen Benutzerdaten verschlüsselt und nur mit einem Schlüssel pro Volume entschlüsselt werden können. 
---
= Verschlüsselung von Daten im Ruhezustand
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Alle Volumes in Google Cloud NetApp Volumes werden im Ruhezustand mittels AES-256-Verschlüsselung verschlüsselt. Dies bedeutet, dass alle auf Medien geschriebenen Benutzerdaten verschlüsselt und nur mit einem Schlüssel pro Volume entschlüsselt werden können.

* Für NetApp Volumes-SW kommen Google-generierte Schlüssel zum Einsatz.
* Bei NetApp Volumes-Performance werden die Schlüssel pro Volume in einem Schlüsselmanager gespeichert, der in den Google Cloud NetApp Volumes integriert ist.


Ab November 2021 wurde eine Vorschau auf die Funktionalität der vom Kunden gemanagten Verschlüsselungsschlüssel (CMEK) bereitgestellt. So können Sie die Schlüssel pro Volume mit einem in einzelnen Projekten und Regionen gehosteten Master-Schlüssel verschlüsseln https://cloud.google.com/kms/docs["Google Key Management Service (KMS):"^] KMS ermöglicht es Ihnen, externe Schlüsselmanager anzubinden.

Informationen zum Konfigurieren von KMS für NetApp-Volumenkaleistung finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Einrichten von vom Kunden gemanagten Verschlüsselungsschlüsseln"^].
