---
sidebar: sidebar 
permalink: ehc/ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html 
keywords: secure, architecture, tenancy model, identity management, control plane, security hardening, encryption, zero trust, ransomware 
summary: Google Cloud NetApp Volumes in Google Cloud bietet eine Vielzahl von Möglichkeiten, Ihre Daten nativ zu sichern. 
---
= So schützen Google Cloud NetApp Volumes in Google Cloud Ihre Daten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes in Google Cloud bietet eine Vielzahl von Möglichkeiten, Ihre Daten nativ zu sichern.



== Sichere Architektur und Mandantenmodell

Google Cloud NetApp Volumes bietet eine sichere Architektur in Google Cloud durch Segmentierung von Service-Management (Kontrollebene) und Datenzugriff (Datenebene) über verschiedene Endpunkte hinweg, sodass keine der beiden sich auf den anderen auswirken kann (siehe Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html["„Google Cloud NetApp Volumes Architektur“"]). Die Bereitstellung des Service erfolgt über das Framework von Google https://cloud.google.com/vpc/docs/private-services-access?hl=en_US["Zugang zu privaten Services"^] (PSA). Dieses Framework unterscheidet zwischen dem Serviceanbieter, der von NetApp bereitgestellt und betrieben wird, und dem Serviceverbraucher, der eine virtuelle Private Cloud (VPC) in einem Kundenprojekt ist, das die Clients hostet, die auf die Dateifreigaben für Google Cloud NetApp Volumes zugreifen möchten.

In dieser Architektur link:ncvs-gc-cloud-volumes-service-architecture.html#tenancy-model["„Tenancy model“"]werden Mandanten (siehe Abschnitt ) als Google Cloud-Projekte definiert, die vollständig voneinander isoliert sind, sofern sie nicht ausdrücklich vom Nutzer verbunden sind. Mandanten ermöglichen mithilfe der Google Cloud NetApp Volumes Volume-Plattform eine vollständige Isolierung von Daten-Volumes, externen Name Services und anderen wichtigen Teilen der Lösung von anderen Mandanten. Da die Google Cloud NetApp Volumes Plattform über VPC-Peering verbunden ist, gilt diese Isolation auch für die Plattform. Mit einer Shared-VPC (siehe Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html#shared-vpcs["„Gemeinsame VPCs“"]) können Sie die Freigabe von Google Cloud NetApp Volumes zwischen mehreren Projekten aktivieren. Zugriffssteuerung kann auf SMB-Freigaben und NFS-Exporte angewendet werden, um zu beschränken, wer bzw. welche Datensätze angezeigt oder geändert werden können.



== Starkes Identitätsmanagement für die Kontrollebene

Auf der Kontrollebene, in der die Konfiguration von Google Cloud NetApp Volumes erfolgt, wird das Identitätsmanagement mithilfe von gemanagt https://cloud.google.com/iam/docs/overview["Identitäts-Zugriffsmanagement (Identity Access Management, IAM)"^]. IAM ist ein Standardservice, mit dem die Authentifizierung (Logins) und Autorisierung (Berechtigungen) für Google Cloud-Projektinstanzen gesteuert werden kann. Die gesamte Konfiguration wird mit Google Cloud NetApp Volumes APIs über einen sicheren HTTPS-Transport mit TLS 1.2-Verschlüsselung durchgeführt, und die Authentifizierung wird zur Sicherheit mithilfe von JWT-Token durchgeführt. Die Google-Konsolen-UI für Google Cloud NetApp Volumes übersetzt die Benutzereingabe in Google Cloud NetApp Volumes API-Aufrufe.



== Sicherheitshärtung – Begrenzung von Angriffsflächen

Ein Teil der effektiven Sicherheit ist die Begrenzung der Anzahl der Angriffsflächen, die in einem Service verfügbar sind. Angriffsflächen können eine Vielzahl von Dingen umfassen, beispielsweise Daten im Ruhezustand, Übertragungs- und Logins während der Übertragung und die Datensätze selbst.

Ein Managed Service entfernt einige Angriffsflächen inhärent in seinem Design. Das im Abschnitt beschriebene Infrastruktur-Management link:ncvs-gc-service-operation.html["„Service-Betrieb“,"]wird von einem dedizierten Team übernommen und ist automatisiert, um die Anzahl an Konfigurationen zu reduzieren, die ein Mensch tatsächlich berührt, wodurch sich die Anzahl absichtlicher und unabsichtlicher Fehler verringert. Die Netzwerkumgebung ist abgezäunt, sodass nur erforderliche Services aufeinander zugreifen können. Verschlüsselung ist in den Storage integriert, und nur die Datenebene erfordert Aufmerksamkeit der Administratoren von Google Cloud NetApp Volumes. Wenn Sie den Großteil der Verwaltung hinter einer API-Schnittstelle verbergen, wird die Sicherheit durch Begrenzung der Angriffsflächen erreicht.



== Zero-Trust-Modell

In der Vergangenheit BESTAND DIE IT-Sicherheitsphilosophie darin, Vertrauen zu geben, zu verifizieren und zu manifestieren, dass sie sich ausschließlich auf externe Mechanismen (wie Firewalls und Intrusion Detection Systems) zur Minderung von Bedrohungen verlassen. Angriffe und Verstöße wurden jedoch entwickelt, um die Verifizierung in Umgebungen durch Phishing, Social Engineering, Bedrohungen von innen und andere Methoden zu umgehen, die die Verifizierung in Netzwerke und Verwüstung ermöglichen.

Zero Trust hat sich zu einer neuen Sicherheitsmethode entwickelt, wobei das aktuelle Mantra „Vertrauen Sie nichts, während Sie noch alles überprüfen“ ist. Daher ist standardmäßig kein Zugriff zulässig. Dieses Mantra wird auf verschiedene Arten durchgesetzt, darunter Standard-Firewalls und Intrusion Detection-Systeme (IDS) sowie folgende Methoden:

* Starke Authentifizierungsmethoden (z. B. AES-verschlüsselte Kerberos- oder JWT-Token)
* Einzelne, starke Identifikationsquellen (z. B. Windows Active Directory, Lightweight Directory Access Protocol (LDAP) und Google IAM)
* Netzwerksegmentierung und sichere Mandantenfähigkeit (standardmäßig sind nur Mandanten Zugriff erlaubt)
* Granulare Zugriffssteuerung mit den geringsten Zugriffsrichtlinien
* Kleine exklusive Listen von engagierten, vertrauenswürdigen Administratoren mit digitalen Audit- und Papiertrails


Google Cloud NetApp Volumes, die in Google Cloud ausgeführt werden, entspricht dem Zero-Trust-Modell und implementiert die Haltung „Trust nothing, verify Everything“.



== Verschlüsselung

Verschlüsselung von Daten im Ruhezustand (siehe Abschnitt link:ncvs-gc-data-encryption-at-rest.html["„Datenverschlüsselung im Ruhezustand“"]) Mit XTS-AES-256-Chiffren mit NetApp Volume Encryption (NVE) und im Flight mit link:ncvs-gc-data-encryption-in-transit.html#smb-encryption["„SMB-Verschlüsselung“"] Oder NFS Kerberos 5p-Support. Regionsübergreifende Replizierungstransfers sind durch TLS 1.2-Verschlüsselung geschützt (siehe Abschnitt Link:ncvs-gc-Security-recidentions-and-Attack-surfaces.HTML#Erkennung, Prävention und Minderung von Ransomware, Malware und Viren#regionsübergreifende Replizierung[„regionsübergreifende Replizierung“]). Darüber hinaus bietet Google Networking auch verschlüsselte Kommunikation (siehe Abschnitt link:ncvs-gc-data-encryption-in-transit.html["„Datenverschlüsselung während der Übertragung“"]) Für eine zusätzliche Schutzschicht gegen Angriffe. Weitere Informationen zur Transportverschlüsselung finden Sie im Abschnitt link:ncvs-gc-data-encryption-in-transit.html#google-cloud-network["„Google Cloud-Netzwerk“"].



== Datensicherung und Backups

Bei der Sicherheit geht es nicht nur um die Verhinderung von Angriffen. Es geht auch darum, wie wir nach Angriffen eine Wiederherstellung durchführen, wenn sie auftreten. Diese Strategie umfasst Datenschutz und -Backups. Google Cloud NetApp Volumes bietet Methoden zur Replizierung in andere Regionen im Falle von Ausfällen (siehe Abschnitt link:ncvs-gc-security-considerations-and-attack-surfaces.html#cross-region-replication["„Regionenübergreifende Replikation“"]) oder wenn ein Datensatz von einem Ransomware-Angriff betroffen ist. Die IT kann mithilfe von auch asynchrone Backups von Daten an Standorte außerhalb der Instanz von Google Cloud NetApp Volumes durchführenlink:ncvs-gc-security-considerations-and-attack-surfaces.html#cloud-volumes-service-backup["Google Cloud NetApp Volumes Backup"]. Mit regelmäßigen Backups kann das Abmildern von Sicherheitsereignissen Zeit in Anspruch nehmen, Geld und Aufwand für Administratoren einsparen.



== Schnelle Abwehr von Ransomware mit branchenführenden Snapshot Kopien

Zusätzlich zu Datensicherung und Backups unterstützt Google Cloud NetApp Volumes unveränderliche Snapshot Kopien (siehe Abschnitt link:ncvs-gc-security-considerations-and-attack-surfaces.html#immutable-snapshot-copies["„Unveränderliche Snapshot Kopien“"]) von Volumes, die eine Wiederherstellung nach Ransomware-Angriffen ermöglichen (siehe Abschnitt ) link:ncvs-gc-service-operation.html["„Service-Betrieb“"]innerhalb von Sekunden nach der Erkennung des Problems und mit minimalen Unterbrechungen. Die Recovery-Zeit und -Auswirkungen hängen vom Snapshot Zeitplan ab. Allerdings können Snapshot-Kopien erstellt werden, die bei Ransomware-Angriffen nur eine Stunde Deltawerte liefern. Snapshot Kopien haben nahezu unmerkliche Auswirkungen auf die Performance und Kapazitätsauslastung und stellen einen Ansatz mit niedrigem Risiko und hoher Rendite zum Schutz Ihrer Datensätze dar.
