---
sidebar: sidebar 
permalink: ehc/ncvs-gc-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: Das Google Cloud NetApp Volumes Team managt die Back-End-Services in Google Cloud und verwendet mehrere Strategien, um die Plattform zu sichern und unerwünschten Zugriff zu verhindern. 
---
= Service-Betrieb
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Google Cloud NetApp Volumes Team managt die Back-End-Services in Google Cloud und verwendet mehrere Strategien, um die Plattform zu sichern und unerwünschten Zugriff zu verhindern.

Jeder Kunde erhält ein eigenes Subnetz, das standardmäßig von anderen Kunden abgetrennt ist und jeder Mandant in Google Cloud NetApp Volumes erhält seinen eigenen Namespace und VLAN zur vollständigen Datenisolierung. Nachdem ein Benutzer authentifiziert wurde, kann die Service Delivery Engine (SDE) nur noch Konfigurationsdaten für diesen Mandanten lesen.



== Physische Sicherheit

Mit entsprechender Vorabgenehmigung haben nur Techniker vor Ort und NetApp Außendiensttechniker (Field Support Engineers, FSEs) Zugriff auf den Käfig und die Racks für physische Arbeiten. Storage- und Netzwerk-Management ist nicht zulässig. Nur diese Ressourcen vor Ort sind in der Lage, Hardware-Wartungsarbeiten durchzuführen.

Für Techniker vor Ort wird ein Ticket für die Leistungsbeschreibung (Statement of Work, SOW) angehoben, das die Rack-ID und den Standort des Geräts (RU) enthält. Alle weiteren Details sind im Ticket enthalten. Bei NetApp FSEs muss ein Besuchsticket vor Ort mit COLO GELEGT werden, und das Ticket enthält die Daten, das Datum und die Zeit der Besucher zu Audit-Zwecken. Das SOW für den FSE wird intern an NetApp kommuniziert.



== Operations Team

Das Betriebsteam für Google Cloud NetApp Volumes besteht aus Production Engineering und einem Site Reliability Engineer (SRE) für Google Cloud NetApp Volumes sowie NetApp Field Support Engineers und Partnern für Hardware. Alle Mitglieder des Betriebsteams sind für die Arbeit in Google Cloud akkreditiert und für jedes angehobene Ticket werden detaillierte Arbeitsunterlagen aufbewahrt. Darüber hinaus gibt es einen strengen Änderungskontroll- und Genehmigungsprozess, um sicherzustellen, dass jede Entscheidung angemessen überprüft wird.

Das SRE-Team verwaltet die Kontrollebene und das Umleiten der Daten von UI-Anforderungen an die Back-End-Hardware und -Software in Google Cloud NetApp Volumes. Das SRE-Team verwaltet außerdem Systemressourcen, wie z. B. die maximale Anzahl von Volumes und Inode. SRES dürfen nicht mit Kundendaten interagieren oder Zugriff haben. Darüber hinaus koordiniert SRES mit Return Material Authorizations (RMAs), wie z. B. neue Festplatten- oder Speicherersatzanfragen für die Backend-Hardware.



== Mitwirkungspflichten des Kunden

Kunden von Google Cloud NetApp Volumes managen das Active Directory und das Benutzerrollenmanagement ihrer Unternehmen sowie das Volume und die Datenvorgänge. Kunden können über Administratorrollen verfügen und Berechtigungen an andere Endbenutzer innerhalb desselben Google Cloud-Projekts delegieren. Dabei werden die beiden vordefinierten Rollen verwendet, die NetApp und Google Cloud (Administrator und Viewer) bereitstellen.

Der Administrator kann eine beliebige VPC im Kundenprojekt von Google Cloud NetApp Volumes abgleichen, die der Kunde für angemessen erlegt. Der Kunde ist selbst dafür verantwortlich, den Zugriff auf sein Google Cloud Marketplace Abonnement zu managen und die VPCs zu managen, die Zugriff auf die Datenebene haben.



== Bösartiger SRE-Schutz

Eine mögliche Sorge ist, wie sich Google Cloud NetApp Volumes vor Szenarien schützen, in denen eine schädliche SRE vorhanden ist oder die SRE-Anmeldedaten kompromittiert wurden?

Der Zugang zur Produktionsumgebung ist nur mit einer begrenzten Anzahl von SRE-Einzelpersonen möglich. Darüber hinaus sind Administratorrechte auf eine Handvoll erfahrener Administratoren beschränkt. Alle Aktionen, die von jedem in der Google Cloud NetApp Volumes-Produktionsumgebung durchgeführt werden, werden protokolliert und alle Anomalien bei der Baseline oder verdächtigen Aktivitäten werden von unserer SIEM-Plattform (Security Information and Event Management) zur Bedrohungserkennung erkannt. So können bösartige Aktionen nachverfolgt und abgemildert werden, bevor am Back-End von Google Cloud NetApp Volumes zu viel Schaden angerichtet wird.



== Volumenlebenszyklus

Google Cloud NetApp Volumes managt nur die Objekte innerhalb des Service, nicht die Daten innerhalb der Volumes. Nur Clients, die auf die Volumes zugreifen, können die Daten, ACLs, Dateieigentümer usw. managen. Die Daten in diesen Volumes werden im Ruhezustand verschlüsselt und der Zugriff ist auf Mandanten der Google Cloud NetApp Volumes-Instanz beschränkt.

Der Volume-Lebenszyklus von Google Cloud NetApp Volumes ist create-Update-delete. Volumes behalten Snapshot Kopien von Volumes vor, bis die Volumes gelöscht werden. Nur validierte NetApp Volumes von Google Cloud können Volumes in Google Cloud NetApp Volumes löschen. Wenn ein Administrator eine Volume-Löschung angefordert hat, muss ein zusätzlicher Schritt zur Eingabe des Volume-Namens erforderlich sein, um die Löschung zu überprüfen. Nachdem ein Volume gelöscht wurde, ist das Volume verschwunden und kann nicht wiederhergestellt werden.

Für den Fall, dass ein Google Cloud NetApp Volumes-Vertrag beendet wird, kennzeichnet NetApp Volumes zum Löschen nach einem bestimmten Zeitraum. Bevor dieser Zeitraum abläuft, können Sie Volumes auf Kundenwunsch wiederherstellen.



== Zertifizierungen

Google Cloud NetApp Volumes für Google Cloud ist derzeit nach ISO/IEC 27001:2013 und ISO/IEC 27018:2019 zertifiziert. Der Service erhielt kürzlich auch seinen SOC2 Type I Attestation Report. Informationen zur NetApp Verpflichtung zu Datensicherheit und Datenschutz finden Sie unter https://www.netapp.com/company/trust-center/compliance/["Compliance: Datensicherheit und Datenschutz"^].



== DSGVO

Unsere Verpflichtung zu Datenschutz und Einhaltung der DSGVO steht in mehreren unserer zahlreichen verfügbar  https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["Kundenverträge"^], Wie unsere https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["Ergänzung Zur Kundendatenverarbeitung"^], Das beinhaltet die  https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["Standardvertragsklauseln"^] Von der Europäischen Kommission bereitgestellt. Diese Verpflichtungen stellen wir auch in unserer Datenschutzrichtlinie ein, die durch die zentralen Werte unseres Unternehmenskodex eingehalten wird.
