---
sidebar: sidebar 
permalink: ehc/ncvs-gc-nas-protocols_overview.html 
keywords: nas, nfs, smb, cifs 
summary: 'Die NAS-Protokolle umfassen NFS (v3 und v4.1) und SMB/CIFS (2.x und 3.x). Mithilfe dieser Protokolle ermöglicht NetApp Volumes den gemeinsamen Zugriff auf Daten über mehrere NAS-Clients hinweg. Darüber hinaus können Google Cloud NetApp Volumes (Dual-Protokoll) gleichzeitig auf NFS- und SMB/CIFS-Clients zugreifen und dabei alle Identitäts- und Berechtigungseinstellungen für Dateien und Ordner in den NAS-Freigaben erfüllen.' 
---
= Übersicht über NAS-Protokolle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die NAS-Protokolle umfassen NFS (v3 und v4.1) und SMB/CIFS (2.x und 3.x). Mithilfe dieser Protokolle ermöglicht NetApp Volumes den gemeinsamen Zugriff auf Daten über mehrere NAS-Clients hinweg. Darüber hinaus können Google Cloud NetApp Volumes (Dual-Protokoll) gleichzeitig auf NFS- und SMB/CIFS-Clients zugreifen und dabei alle Identitäts- und Berechtigungseinstellungen für Dateien und Ordner in den NAS-Freigaben erfüllen. Für eine höchstmögliche Sicherheit bei der Datenübertragung unterstützt Google Cloud NetApp Volumes die Protokollverschlüsselung bei der Übertragung mithilfe von SMB-Verschlüsselung und NFS Kerberos 5p.


NOTE: Die Dual-Protokoll-Funktion ist nur mit NetApp Volumes-Performance verfügbar.
