---
sidebar: sidebar 
permalink: ehc/ncvs-gc-architecture_overview.html 
keywords: architecture overview, control plane, data plane 
summary: Als Teil des Vertrauens einer Cloud-Lösung müssen Sie die Architektur und die Art und Weise der Sicherheit kennen. In diesem Abschnitt werden verschiedene Aspekte der Google Cloud NetApp Volumes-Architektur in Google erläutert, um potenzielle Bedenken hinsichtlich der Datensicherung zu zerstreuen und Bereiche aufzurufen, in denen zusätzliche Konfigurationsschritte für die sicherste Implementierung erforderlich sein könnten. 
---
= Überblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Als Teil des Vertrauens einer Cloud-Lösung müssen Sie die Architektur und die Art und Weise der Sicherheit kennen. In diesem Abschnitt werden verschiedene Aspekte der Google Cloud NetApp Volumes-Architektur in Google erläutert, um potenzielle Bedenken hinsichtlich der Datensicherung zu zerstreuen und Bereiche aufzurufen, in denen zusätzliche Konfigurationsschritte für die sicherste Implementierung erforderlich sein könnten.

Die allgemeine Architektur von Google Cloud NetApp Volumes lässt sich in zwei Hauptkomponenten aufteilen: Die Kontrollebene und die Datenebene.



== Kontrollebene

Die Kontrollebene in Google Cloud NetApp Volumes ist die Back-End-Infrastruktur, die von Administratoren von Google Cloud NetApp Volumes und der nativen Automatisierungssoftware NetApp gemanagt wird. Diese Ebene ist für Endbenutzer vollständig transparent und umfasst Netzwerke, Storage-Hardware, Softwareupdates usw., um einer Cloud-residenten Lösung wie Google Cloud NetApp Volumes einen Mehrwert zu bieten.



== Datenebene

Die Datenebene in Google Cloud NetApp Volumes umfasst die tatsächlichen Daten-Volumes und die gesamte Konfiguration von Google Cloud NetApp Volumes (z. B. Zugriffssteuerung, Kerberos-Authentifizierung usw.). Die Datenebene steht vollständig unter der Kontrolle von Endbenutzern und den Verbrauchern der Plattform Google Cloud NetApp Volumes.

Es gibt unterschiedliche Arten, wie jede Ebene gesichert und verwaltet wird. In den folgenden Abschnitten werden diese Unterschiede behandelt. Beginnen Sie dabei mit einer Übersicht über die Architektur von Google Cloud NetApp Volumes.
