---
sidebar: sidebar 
permalink: ehc/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: Die Sicherheit – insbesondere in der Cloud, wo die Infrastruktur außerhalb der Kontrolle der Storage-Administratoren liegt – ist entscheidend, wenn es um die Übergabe der Daten an die von Cloud-Providern angebotenen Service-Angebote geht. Dieses Dokument bietet eine Übersicht über die Sicherheitsangebote von Google Cloud NetApp Volumes in der Google Cloud. 
---
= TR-4918: Sicherheitsübersicht – Google Cloud NetApp Volumes in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Oliver Krause, Justin Parisi, NetApp

[role="lead"]
Die Sicherheit – insbesondere in der Cloud, wo die Infrastruktur außerhalb der Kontrolle der Storage-Administratoren liegt – ist entscheidend, wenn es um die Übergabe der Daten an die von Cloud-Providern angebotenen Service-Angebote geht. Dieses Dokument bietet einen Überblick über die Sicherheitsangebote, die https://cloud.netapp.com/cloud-volumes-service-for-gcp["Google Cloud NetApp Volumes bietet Funktionen in Google Cloud"^].



== Zielgruppe

Die Zielgruppe dieses Dokuments umfasst die folgenden Rollen:

* Cloud Provider
* Storage-Administratoren
* Storage-Architekten
* Feldressourcen
* Geschäftliche Entscheidungsträger


Wenn Sie Fragen zum Inhalt dieses technischen Berichts haben, finden Sie im Abschnitt link:ncvs-gc-additional-information.html#contact-us["„Kontaktieren Sie uns.“"]

|===
| Abkürzung | Definition 


| NetApp Volumes-SW | Google Cloud NetApp Volumes, Servicetyp NetApp Volumes 


| NetApp Volumes-Performance | NetApp Volumes Service, Servicetyp Cloud Volumes-Performance 


| PSA |  
|===