---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_advanced.html 
keywords: Advanced Configuration, Load Balancers 
summary: Dieser Abschnitt richtet sich an Anpassungen, die reale Benutzer wahrscheinlich bei der Implementierung dieser Lösung in der Produktion ausführen müssen, wie z. B. die Implementierung benutzerdefinierter Load Balancer Instanzen. 
---
= Erweiterte Konfigurationsoptionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
In der Regel ist die am einfachsten zu implementierende Lösung am besten. In einigen Fällen sind jedoch erweiterte Anpassungen erforderlich, um die Anforderungen oder Spezifikationen einer bestimmten Applikation oder der Umgebung zu erfüllen, in der die Lösung implementiert wird. Zu diesem Zweck ermöglicht die Lösung Red hat OpenShift mit NetApp die folgenden Anpassungen, um diese Anforderungen zu erfüllen.


NOTE: In diesem Abschnitt haben wir einige erweiterte Konfigurationsoptionen dokumentiert, wie zum Beispiel Loadbalancer von Drittanbietern oder eine private Registry für das Hosting benutzerdefinierter Container-Images, die beide Voraussetzungen für die Installation des NetApp Astra Control Center sind.

Auf den folgenden Seiten sind zusätzliche Informationen zu den erweiterten Konfigurationsoptionen verfügbar, die in Red hat OpenShift mit NetApp validiert sind:

link:a-w-n_load_balancers.html["Nächster Abschnitt: Die Möglichkeiten Des Lastverteiler Erkunden."]
