---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_LB_SeeSaw.html 
summary: Auf dieser Seite sind die Installations- und Konfigurationsanweisungen für den Seesaw-Load-Balancer aufgeführt. 
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer 
---
= Installieren von Seesaw-Load-Balancer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Auf dieser Seite werden die Installations- und Konfigurationsanweisungen für den vom Seesaw verwalteten Load Balancer aufgeführt.

Seesaw ist der Standard-verwaltete Netzwerk-Load-Balancer, der in einer Anthos-Cluster-Umgebung von Version 1.6 bis 1.10 installiert ist.



== Installieren des Load Balancer für die Seifentäfer

Der Seesaw Load Balancer ist vollständig mit Anthos Clusters auf VMware integriert und hat eine automatisierte Implementierung als Teil der Admin- und User-Cluster-Setups durchgeführt. Im befinden sich Textblöcke `cluster.yaml` Konfigurationsdateien, die geändert werden müssen, um Informationen zum Load Balancer bereitzustellen. Vor der Cluster-Bereitstellung ist dann ein zusätzlicher Schritt erforderlich, um den Load Balancer mit dem integrierten bereitzustellen `gkectl` Werkzeug.


NOTE: Seesaw Load Balancer können im HA- oder Non-HA-Modus eingesetzt werden. Im Rahmen dieser Validierung wurde der Seesaw-Load-Balancer im Non-HA-Modus eingesetzt, der Standardeinstellung. Für die Produktion empfiehlt NetApp die Implementierung von Seesaw in einer HA-Konfiguration, um Fehlertoleranz und Zuverlässigkeit zu gewährleisten.



== Integration in Anthos

In jeder Konfigurationsdatei gibt es einen Abschnitt, bzw. für das Admin-Cluster. In jedem Benutzer-Cluster können Sie den Load Balancer so konfigurieren, dass er von Anthos On-Premises gemanagt wird.

Der folgende Text ist ein Beispiel aus der Konfiguration der Partition für das GKE-Admin-Cluster. Die Werte, die nicht kommentiert und geändert werden müssen, werden in Fettdruck unten gesetzt:

[listing, subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----
Der Seesaw-Load-Balancer hat ebenfalls eine separate statische `seesaw-block.yaml` Datei, die Sie für jede Cluster-Implementierung bereitstellen müssen. Diese Datei muss sich im selben Verzeichnis im Verhältnis zum befinden `cluster.yaml` Die Bereitstellungsdatei oder der vollständige Pfad müssen im Abschnitt oben angegeben werden.

Eine Auswahl der `admin-seesaw-block.yaml` Die Datei sieht wie das folgende Skript aus:

[listing, subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: Diese Datei stellt das Gateway und die Netmask für das Netzwerk bereit, das der Load Balancer für das zugrunde liegende Cluster bereitstellt, sowie die Management-IP und den Hostnamen für die virtuelle Maschine, die zur Ausführung des Load Balancer bereitgestellt wird.
