---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: NetApp bietet verschiedene Produkte, die unsere Kunden bei der Orchestrierung und dem Management persistenter Daten in Container-basierten Umgebungen wie Anthos unterstützen. 
---
= Überblick über die NetApp Storage-Integration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== Anthos Ready Storage-Partnerprogramm.

Google Cloud bittet regelmäßig um aktualisierte Validierungen der Integration von Partner-Storage mit neuen Versionen von Anthos. Eine Liste der derzeit validierten Storage-Lösungen, CSI-Treiber, verfügbaren Funktionen und der unterstützten Versionen von Anthos finden Sie https://cloud.google.com/anthos/docs/resources/partner-storage["Hier"^].

NetApp hält vierteljährlich regelmäßige Compliance aufrecht. Dabei werden Anfragen zur Validierung des CSI-konformen Storage-Orchestrators Astra Trident sowie unseres ONTAP Storage-Systems mit Anthos-Versionen gestellt.

Die folgende Tabelle enthält die von NetApp und NetApp Partner Engineers getesteten Anthos Versionen zur Validierung von NetApp Astra Trident CSI-Treibern und -Funktionen im Rahmen des Anthos Ready Storage-Partnerprogramms:

|===


| Bereitstellungstyp | Version | Storage-System | Astra Trident Version | Protokoll | Funktionen 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | Multiwriter, Volume-Erweiterung, Snapshots, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | San | RAW-Block, Volume-Erweiterung, Snapshots, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | Multiwriter, Volume-Erweiterung, Snapshots, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | San | RAW-Block, Volume-Erweiterung, Snapshots, PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | Multiwriter, Volume Expansion, Snapshots 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | San | RAW Block, Volume-Erweiterung, Snapshots 


| VMware | 1.11 | Element 12.3 | 22.04 | San | RAW Block, Volume-Erweiterung, Snapshots 


| Bare Metal | 1.10 | ONTAP 9.8 | 22.01 | NAS | Multiwriter, Volume Expansion, Snapshots 


| Bare Metal | 1.10 | ONTAP 9.8 | 22.01 | San | RAW Block, Volume-Erweiterung, Snapshots 
|===


== NetApp Storage-Integrationen

NetApp bietet verschiedene Produkte, mit denen Sie persistente Daten in Container-basierten Umgebungen wie Anthos orchestrieren und managen können.

NetApp Astra Trident ist ein vollständig unterstützter Open-Source-Orchestrator für Container und Kubernetes-Distributionen, einschließlich Anthos. Weitere Informationen finden Sie auf der Astra Trident Website https://docs.netapp.com/us-en/trident/index.html["Hier"].

Die folgenden Seiten enthalten zusätzliche Informationen zu NetApp Produkten, die für das Management von Applikationen und persistentem Storage in Anthos mit NetApp Lösung validiert wurden.

link:a-w-n_overview_trident.html["Als Nächstes: Überblick über NetApp Astra Trident"]
