---
sidebar: sidebar 
permalink: vmw-sc/sc-overview.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= Überblick über VMware Sovereign Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das Konzept der Souveränität wird für viele Unternehmen, die hochsensible Daten verarbeiten und pflegen, als notwendige Komponente des Cloud-Computing entwickelt, wie z. B. nationale und staatliche Behörden sowie stark regulierte Branchen wie Finanzen und Gesundheitswesen. Nationale Regierungen wollen außerdem die digitale Wirtschaft erweitern und die Abhängigkeit von multinationalen Unternehmen bei ihren Cloud-Services verringern.



== VMware Sovereign Cloud Initiative

VMware definiert eine souveräne Cloud als eine, die:

* Schutz und Freischaltung von wichtigen Daten (z. B. nationale, Unternehmensdaten und personenbezogene Daten) für private und öffentliche Einrichtungen
* Bereitstellung einer nationalen Leistungsfähigkeit für die digitale Wirtschaft
* Sicherung von Daten durch geprüfte Sicherheitskontrollen
* Gewährleistet die Einhaltung von Datenschutzgesetzen
* Verbessert die Kontrolle über die Daten durch die Bereitstellung von Daten-Residency und Datenhoheit mit vollständiger Kontrolle durch die Gerichtsbarkeit




== Zusammenarbeit mit einem zuverlässigen VMware Sovereign Cloud Service Provider

Um den Erfolg sicherzustellen, müssen Unternehmen mit Partnern zusammenarbeiten, denen sie vertrauen und die in der Lage sind, authentische und autonome souveräne Cloud-Plattformen zu hosten. VMware Cloud-Provider, die im Rahmen der VMware Sovereign Cloud-Initiative anerkannt sind, verpflichten sich, Cloud-Lösungen auf der Grundlage moderner, softwaredefinierter Architekturen zu entwerfen und zu betreiben, die die wichtigsten Prinzipien und Best Practices des VMware Sovereign Cloud-Frameworks verkörpern.

* *Datensouveränität und Rechtsprechungskontrolle* – Alle Daten sind wohnhaft und unterliegen der ausschließlichen Kontrolle und Autorität des Nationalstaats, in dem diese Daten erfasst wurden. Der Betrieb wird vollständig innerhalb der Gerichtsbarkeit verwaltet
* *Datenzugriff und -Integrität* – die Cloud-Infrastruktur ist ausfallsicher und an mindestens zwei Standorten innerhalb der Gerichtsbarkeit mit sicheren und privaten Verbindungsoptionen verfügbar.
* *Datensicherheit und Compliance* – die Kontrolle der Informationssicherheitsmanagementsysteme ist nach einem branchenweit anerkannten globalen (oder regionalen) Standard zertifiziert und regelmäßig geprüft.
* *Datenunabhängigkeit und -Mobilität* – Unterstützung moderner Anwendungsarchitekturen, um eine Anbieterbindung zu verhindern und Anwendungsportabilität und -Unabhängigkeit zu ermöglichen


Weitere Informationen von VMware finden Sie unter:

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["VMware Sovereign Cloud Overview"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["Was ist VMware Sovereign Cloud?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["Die neue VMware Sovereign Cloud Initiative"]
* link:https://www.vmware.com/content/dam/learn/en/amer/fy22/pdf/1173457_Sovereign_Cloud_Technical_Whitepaper_V3.pdf["VMware Sovereign Cloud: Technisches Whitepaper"]

