---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= NetApp mit VMware Sovereign Cloud: Anwendungsfälle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp unterstützt VMware Sovereign Cloud-Konzepte durch die Integration mehrerer NetApp-Technologien.

Über die folgenden Links können Sie mehr über die Integration von NetApp-Technologien in VMware Sovereign Cloud erfahren:

* link:#storageGRID["NetApp StorageGRID als Objektspeicher-Erweiterung"]




== NetApp StorageGRID als Objektspeicher-Erweiterung

NetApp hat zusammen mit VMware NetApp StorageGRID in VMware Cloud Director integriert, um Unterstützung für den VMware Sovereign Cloud zu erhalten. Mit diesem Plug-in für VMware Cloud Director können Service-Provider StorageGRID als Objekt-Storage-Angebot nutzen (unabhängig vom Anwendungsfall) und StorageGRID Management über dieselbe mandantenfähige VMware Lösung (VMware Cloud Director) nutzen, die von Service-Providern verwendet wird, um andere Teile des Angebotskatalogs zu managen.

Partner, die VMware Sovereign Clouds bereitstellen, können sich für NetApp StorageGRID entscheiden, um sie beim Management und bei der Wartung von Cloud-Umgebungen mit unstrukturierten Daten zu unterstützen. Die universelle Kompatibilität mit nativem Support für Standard-APIs wie Amazon S3 API gewährleistet eine reibungslose Interoperabilität in verschiedenen Cloud-Umgebungen. Einzigartige Innovationen wie automatisiertes Lifecycle Management sorgen für einen kosteneffizienteren Schutz, Storage und langfristige Aufbewahrung unstrukturierter Kundendaten.

Die Sovereign Cloud-Integration von NetApp mit Cloud Director Anbieterlösungen überzeugen durch:

* Gewissheit, dass sensible Daten, einschließlich Metadaten, souverän kontrolliert werden und gleichzeitig den Zugriff ausländischer Behörden verhindern, die Datenschutzgesetze verletzen könnten.
* Höhere Sicherheit und Compliance, die Applikationen und Daten vor sich schnell entwickelnden Angriffsvektoren schützt und gleichzeitig die kontinuierliche Compliance mit einem vertrauenswürdigen lokalen Standort gewährleistet. Infrastruktur, integrierte Frameworks und lokale Experten.
* Zukunftssichere Infrastruktur, um schnell auf veränderte Datenschutzvorschriften, Sicherheitsbedrohungen und Geopolitik reagieren zu können
* Möglichkeit, mit sicherer Datenfreigabe und Analyse den Mehrwert von Daten freizusetzen, um Innovationen voranzutreiben, ohne gegen Datenschutzgesetze zu verstoßen. Die Datenintegrität ist so geschützt, dass genaue Einblicke gewährleistet sind.


Weitere Informationen zur Integration von StorageGRID finden Sie hier:

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["NetApp-Ankündigung"]

