---
sidebar: sidebar 
permalink: containers/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: Dieses Referenzdokument bietet eine Implementierungsvalidierung für Anthos mit NetApp Lösung, die in Umgebungen mit mehreren Datacentern implementiert wird, wie von NetApp und unseren Engineering-Partnern validiert. 
---
= NVA-1165: Anthos mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Banu Sundhar und Suresh Thoppay, NetApp

[role="lead"]
Dieses Referenzdokument bietet eine Implementierungsvalidierung von Anthos mit NetApp Lösung für Partner von NetApp, wenn sie in mehreren Datacenter-Umgebungen implementiert wird. Außerdem wird über das Trident Storage-Orchestrator für das Management von persistentem Storage die Storage-Integration in NetApp Storage-Systeme detailliert beschrieben. Und schließlich untersuchen und dokumentieren wir eine Reihe von Validierungen und Anwendungsfällen aus der Praxis.



== Anwendungsfälle

Die Architektur der Anthos with NetApp Lösung bietet Kunden mit folgenden Anwendungsfällen einen hervorragenden Mehrwert:

* Anthos Umgebung lässt sich einfach implementieren und managen, wenn sie bereitgestellt wird `bmctl` Werkzeug auf blankem Metall oder dem `gkectl` Tool auf VMware vSphere.
* Kombinierte Leistung von Enterprise-Containern und virtualisierten Workloads mit Anthos praktisch auf vSphere oder Bare Metal mit https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["Kubevirt"^].
* Praktische Konfigurationen und Anwendungsfälle, die Anthos-Funktionen hervorheben, wenn sie mit NetApp-Storage und Trident, dem Open-Source-Storage-Orchestrator für Kubernetes, verwendet werden.




== Geschäftlicher Nutzen

Unternehmen führen zunehmend DevOps-Praktiken ein, um neue Produkte zu erstellen, Release-Zyklen zu verkürzen und neue Funktionen hinzuzufügen. Dank ihrer angeborenen Agilität spielen Container und Microservices eine entscheidende Rolle bei der Unterstützung von DevOps-Praktiken. Das Praktizieren von DevOps auf Produktionsskala in einer Enterprise-Umgebung stellt jedoch ihre eigenen Herausforderungen und stellt bestimmte Anforderungen an die zugrunde liegende Infrastruktur, wie beispielsweise die folgenden:

* Hochverfügbarkeit auf allen Ebenen im Stack
* Einfache Implementierungsverfahren
* Unterbrechungsfreier Betrieb und Upgrades
* API-gestützte, programmierbare Infrastruktur, um die Flexibilität von Microservices Schritt zu halten
* Mandantenfähigkeit mit garantierter Performance
* Gleichzeitige Ausführung virtualisierter und containerisierter Workloads
* Die Möglichkeit, die Infrastruktur unabhängig von den Workload-Anforderungen zu skalieren


Anthos with NetApp ist eine Lösung für diese Herausforderungen. Sie stellt eine Lösung vor, mit der alle Bedenken zerlegt werden können, indem Anthos On-Premises in der gewünschten Datacenter-Umgebung des Kunden vollständig automatisiert implementiert wird.



== Technologieüberblick

Die Anthos Lösung mit NetApp besteht aus den folgenden Hauptkomponenten:



=== Anthos Vor Ort

Anthos On Prem ist eine vollständig unterstützte Kubernetes-Plattform für Unternehmen, die im VMware vSphere Hypervisor oder in einer Bare-Metal-Infrastruktur Ihrer Wahl implementiert werden kann.

Weitere Informationen zu Anthos finden Sie auf der Website von Anthos https://cloud.google.com/anthos["Hier"^].



=== NetApp Storage-Systeme

NetApp verfügt über verschiedene Storage-Systeme, die sich perfekt für Enterprise Datacenter und Hybrid-Cloud-Implementierungen eignen. Das NetApp Portfolio umfasst NetApp ONTAP, Cloud Volumes ONTAP, Cloud Volumes Service, Azure NetApp Files und FSxN für NetApp ONTAP Storage-Systeme, die persistenten Storage für Container-Applikationen bereitstellen können.

Weitere Informationen finden Sie auf der NetApp Website https://www.netapp.com["Hier"].



=== NetApp Storage-Integrationen

Trident ist ein Open-Source- und vollständig unterstützter Storage-Orchestrator für Container und Kubernetes-Distributionen, einschließlich Anthos.

Weitere Informationen finden Sie auf der Trident-Website https://docs.netapp.com/us-en/trident/index.html["Hier"].



== Erweiterte Konfigurationsoptionen

Dieser Abschnitt richtet sich an Anpassungen, die reale Benutzer wahrscheinlich bei der Implementierung dieser Lösung in der Produktion ausführen müssen, wie z. B. die Erstellung einer dedizierten privaten Image-Registrierung oder die Implementierung benutzerdefinierter Load Balancer-Instanzen.



== Aktuelle Support-Matrix für validierte Versionen

Siehe https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["Hier"] Für die Support-Matrix für validierte Releases.
