---
sidebar: sidebar 
permalink: containers/dwn_solution_overview.html 
keywords: DevOps, Netapp, Astra Trident, Astra Control, Astra 
summary: Dieser technische Bericht erläutert, wie NetApp DevOps im Einsatz von Container-Applikationen einfach und effizient in diversen Bereichen unterstützt. Am Anfang werden die NetApp Storage-Systeme und ihre Integration mit Kubernetes-Plattformen mithilfe des Astra Portfolios detailliert erläutert. Abschließend werden eine Reihe von Validierungen von Lösungen und Anwendungsbeispiele aus der Praxis untersucht und dokumentiert. 
---
= TR-4919: DevOps mit NetApp Astra
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/
:k8s_distribution_name: Red Hat OpenShift, VMware Tanzu, Anthos by Google Cloud etc.


[role="lead"]
Dieser technische Bericht erläutert, wie NetApp DevOps im Einsatz von Container-Applikationen einfach und effizient in diversen Bereichen unterstützt. Am Anfang werden die NetApp Storage-Systeme und ihre Integration mit Kubernetes-Plattformen mithilfe des Astra Portfolios detailliert erläutert. Abschließend werden eine Reihe von Validierungen von Lösungen und Anwendungsbeispiele aus der Praxis untersucht und dokumentiert.

Alan Cowles und Nikhil M Kulkarni, NetApp



== Anwendungsfälle

Die Architektur von DevOps mit NetApp Astra bietet Kunden mit den folgenden Anwendungsfällen einen hervorragenden Mehrwert:

* Einfaches Implementieren und Managen von Applikationen und Entwicklungsumgebungen, die auf unterstützten Kubernetes-Distributionen ausgeführt werden.
* Diskussion über reale Anwendungsfälle für DevOps-Workflows und Beispiele für Tools und Methoden, die NetApp bereitstellen kann, um die Einführung und Nutzung dieser Methoden zu vereinfachen
* Die Untersuchung, wie applikationskonsistente Snapshots, Backups und Klone verwendet werden können, um die DevOps-Erfahrung zu verbessern




== Geschäftlicher Nutzen

Unternehmen führen zunehmend DevOps-Praktiken ein, um neue Produkte zu erstellen, Release-Zyklen zu verkürzen und neue Funktionen hinzuzufügen. Dank ihrer angeborenen Agilität spielen Container und Microservices eine entscheidende Rolle bei der Unterstützung von DevOps-Praktiken. Das Praktizieren von DevOps auf Produktionsskala in einer Enterprise-Umgebung stellt jedoch ihre eigenen Herausforderungen und stellt bestimmte Anforderungen an die zugrunde liegende Infrastruktur, wie beispielsweise die folgenden:

* Hochverfügbarkeit auf allen Ebenen im Stack, damit Workflows nie unterbrochen werden.
* Einfache Implementierung und einfaches Management für Endbenutzer.
* API-gestützte, programmierbare Infrastruktur, um mit Microservices und Entwicklerflexibilität Schritt zu halten
* Möglichkeit, Infrastruktur unabhängig und automatisiert zu skalieren, um sie an Workload-Anforderungen anzupassen
* Durch den Schutz von Applikationen und die Sicherung persistenter Datensätze für DevOps-Workflows wird die Markteinführung beschleunigt, da keine Reimplementierungen oder manuelles Kopieren von Daten erforderlich sind.


In diesem technischen Bericht werden diese Funktionen und Herausforderungen erkannt und erläutert, wie sich DevOps-Anwendungsfälle für Container-Applikationen mithilfe des umfassenden Portfolios von NetApp Produkten verbessern und vereinfachen lassen.



== Technologieüberblick

Die Lösung DevOps mit NetApp umfasst die folgenden Hauptkomponenten:



=== DevOps-Praktiken

DevOps-Praktiken konzentrieren sich auf automatisierte, wiederholbare und leicht zu verwaltende Vorgänge, die den Entwicklungs-Workflow verbessern, da Endbenutzer die Umgebung steuern können, in der sie ihren Code entwickeln. Diese Lösung enthält mehrere Beispiele und Anwendungsfälle, in denen sich NetApp Technologie für einen solchen Betrieb am meisten eignet.



=== Container-Orchestrierung

Derzeit sind zahlreiche Container-Orchestrierungsplattformen im Einsatz. Obwohl die meisten dieser Plattformen auf Kubernetes basieren, besitzen beide vor- und Nachteile. Es ist also wichtig, bei der Auswahl einer Container-Orchestrierungsplattform für DevOps-Workflows Funktionsgruppen und Integrationen zu kennen. Mit der NetApp Astra Suite unterstützen wir die folgenden Plattformen für vollwertige DevOps-Anwendungsfälle:

* https://www.redhat.com/en/technologies/cloud-computing/openshift["Red hat OpenShift"] 4.6.8 oder höher
* https://rancher.com/["Rancher"] 2.5 und höher
* https://kubernetes.io/["Kubernetes"] 1.20 und höher
* https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/index.html["VMware Tanzu Kubernetes Grid"] 1.4 und höher
* https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid-Integrated-Edition/index.html["VMware Tanzu Kubernetes Grid Integrated Edition"] 1.12.2 und höher




=== NetApp Storage-Systeme

NetApp verfügt über verschiedene Storage-Systeme, die sich perfekt für Enterprise Datacenter und Hybrid-Cloud-Implementierungen eignen. Das NetApp Portfolio umfasst NetApp ONTAP, NetApp Element und NetApp E-Series Storage-Systeme, die persistenten Storage für Container-Applikationen bereitstellen können.

Weitere Informationen finden Sie auf der NetApp Website https://www.netapp.com["Hier"].



=== NetApp Storage-Integrationen

Das NetApp Astra Control Center bietet umfassende Storage- und applikationsorientierte Datenmanagement-Services für zustandsorientierte Kubernetes-Workloads, die in einer On-Premises-Umgebung implementiert und mit der bewährten NetApp Datensicherungstechnologie unterstützt werden.

Weitere Informationen finden Sie auf der NetApp Astra Website https://cloud.netapp.com/astra["Hier"].

Astra Trident ist ein Open-Source- und vollständig unterstützter Storage-Orchestrator für Container und Kubernetes-Distributionen wie {k8s_Distribution_Name}.

Weitere Informationen finden Sie auf der Astra Trident Website https://docs.netapp.com/us-en/trident/index.html["Hier"].
