---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_advanced_cluster_management_deployment_prerequisites.html 
keywords: OpenShift, OCP, Astra Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes 
summary: Erweitertes Cluster Management für Kubernetes auf Red hat OpenShift mit NetApp 
---
= Implementieren Sie Advanced Cluster Management für Kubernetes
:allow-uri-read: 




== Voraussetzungen

. Ein Red hat OpenShift-Cluster (größer als Version 4.5) für den Hub-Cluster
. Red hat OpenShift-Cluster (mehr als Version 4.4.3) für verwaltete Cluster
. Cluster-Admin-Zugriff auf den Red hat OpenShift-Cluster
. Eine Red hat Subskription für Advanced Cluster Management für Kubernetes


Advanced Cluster Management ist ein Add-On für den OpenShift-Cluster. Es gibt daher bestimmte Anforderungen und Einschränkungen für die Hardwareressourcen, die auf den Funktionen basieren, die auf dem Hub und den verwalteten Clustern verwendet werden. Sie müssen diese Probleme bei der Dimensionierung der Cluster berücksichtigen. Siehe Dokumentation https://["Hier"] Entnehmen.

Wenn optional der Hub-Cluster dedizierte Nodes für das Hosting von Infrastrukturkomponenten hat und erweiterte Cluster-Management-Ressourcen nur auf diesen Nodes installiert werden sollen, müssen diesen Nodes entsprechend Tolerationen und Selektoren hinzugefügt werden. Weitere Informationen finden Sie in der Dokumentation https://["Hier"].

link:rh-os-n_use_case_advanced_cluster_management_deployment.html["Als Nächstes: Installation."]
