---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Videos und Demos: Red hat OpenShift mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


In den folgenden Videos werden einige der in diesem Dokument dokumentierten Funktionen gezeigt:

[cols="5a, 5a, 5a"]
|===


 a| 
Beschleunigte Softwareentwicklung mit Astra Control und NetApp FlexClone Technologie – Red hat OpenShift mit NetApp

 a| 
Nutzen Sie NetApp Astra Control, um eine Analyse nach der Sterblichen durchzuführen und Ihre Applikation Restores durchzuführen

 a| 
Datensicherung in CI/CD-Pipeline mit Astra Control Center




 a| 
Workload-Migration mit Astra Control Center – Red hat OpenShift mit NetApp

 a| 
Workload-Migration – Red hat OpenShift mit NetApp

 a| 
Installation von OpenShift Virtualization – Red hat OpenShift mit NetApp




 a| 
Bereitstellen einer virtuellen Maschine mit OpenShift-Virtualisierung – Red hat OpenShift mit NetApp

 a| 
NetApp HCI für Red hat OpenShift auf Red hat Virtualization

 a| 

|===
link:rh-os-n_additional_information.html["Weiter: Weitere Informationen: Red hat OpenShift mit NetApp"]
