---
sidebar: sidebar 
permalink: containers/rh-os-n_overview_advanced.html 
keywords: Advanced Configuration, Load Balancers, Custom Registry 
summary: Dieser Abschnitt enthält Anpassungen, die reale Benutzer wahrscheinlich bei der Implementierung dieser Lösung in der Produktion ausführen müssen, z. B. die Erstellung einer dedizierten Image-Registrierung oder die Implementierung benutzerdefinierter Load Balancer-Instanzen. 
---
= Erweiterte Konfigurationsoptionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In der Regel ist die am einfachsten zu implementierende Lösung am besten. In einigen Fällen sind jedoch erweiterte Anpassungen erforderlich, um die Anforderungen oder Spezifikationen einer bestimmten Applikation oder der Umgebung zu erfüllen, in der die Lösung implementiert wird. Zu diesem Zweck ermöglicht die Lösung Red hat OpenShift mit NetApp die folgenden Anpassungen, um diese Anforderungen zu erfüllen.


NOTE: In diesem Abschnitt haben wir einige erweiterte Konfigurationsoptionen dokumentiert, z. B. die Verwendung von Load Balancern von Drittanbietern oder die Erstellung einer privaten Registrierung zum Hosten benutzerdefinierter Container-Images, die beide Voraussetzungen für die Installation von NetApp Trident Protect sind.

Auf den folgenden Seiten sind zusätzliche Informationen zu den erweiterten Konfigurationsoptionen verfügbar, die in Red hat OpenShift mit NetApp validiert sind:

* link:rh-os-n_load_balancers.html["Informationen Zu Load Balancer Options"]
* link:rh-os-n_private_registry.html["Konfigurieren Von Privaten Bildregistrien"]

