---
sidebar: sidebar 
permalink: containers/rh-os-n_load_balancers.html 
keywords: Advanced Configuration, Load Balancers, MetalLB 
summary: In diesem Abschnitt werden Optionen zur Lastverteilung für Benutzer untersucht, die ihre Red hat OpenShift mit NetApp Implementierung anpassen möchten. 
---
= Load Balancer-Optionen: Red hat OpenShift mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In den meisten Fällen stellt Red hat OpenShift Anwendungen für die Außenwelt über Routen zur Verfügung. Ein Service wird durch die Angabe eines extern zugänglichen Host-Namens zugänglich gemacht. Die definierte Route und die vom Dienst identifizierten Endpunkte können von einem OpenShift-Router genutzt werden, um diese benannte Verbindung externen Clients bereitzustellen.

In einigen Fällen müssen jedoch Applikationen zum Einsatz kommen und eine Konfiguration von angepassten Lastausgleich erforderlich sein, um die entsprechenden Services bereitzustellen. Ein Beispiel dafür ist NetApp Trident Protect. Um diesem Bedarf gerecht zu werden, haben wir eine Reihe von benutzerdefinierten Load Balancer-Optionen evaluiert. Die Installation und Konfiguration der Lösung wird in diesem Abschnitt beschrieben.

Auf den folgenden Seiten sind zusätzliche Informationen zu den in Red hat OpenShift mit NetApp validierten Load Balancer-Optionen verfügbar:

* link:rh-os-n_LB_MetalLB.html["MetalLB"]
* link:rh-os-n_LB_F5BigIP.html["F5 BIG-IP"]

