---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= Videos und Demos: Red hat OpenShift mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In den folgenden Videos werden einige der in diesem Dokument dokumentierten Funktionen gezeigt:

.Cloud Insights-Integration in OpenShift-Virtualisierung
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.Mit Red hat MTV VMs zu OpenShift-Virtualisierung mit NetApp ONTAP-Speicher migrieren
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.Beschleunigte Softwareentwicklung mit Astra Control und NetApp FlexClone Technologie – Red hat OpenShift mit NetApp
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.Nutzen Sie NetApp Astra Control, um eine Analyse nach der Sterblichen durchzuführen und Ihre Applikation Restores durchzuführen
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Datensicherung in CI/CD-Pipeline mit Astra Control Center
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.Workload-Migration mit Astra Control Center – Red hat OpenShift mit NetApp
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.Workload-Migration – Red hat OpenShift mit NetApp
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.Installation von OpenShift Virtualization – Red hat OpenShift mit NetApp
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.Bereitstellen einer virtuellen Maschine mit OpenShift-Virtualisierung – Red hat OpenShift mit NetApp
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.NetApp HCI für Red hat OpenShift auf Red hat Virtualization
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]