---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_use_cases.html 
keywords: Use cases, target audience 
summary: Mit einer hybriden VDI mit NetApp VDS können Service-Provider und Virtual Desktop-Administratoren der Enterprise-Klasse Ressourcen problemlos auf andere Cloud-Umgebungen erweitern, ohne ihre Benutzer zu beeinträchtigen. Wenn On-Premises-Ressourcen mit NetApp HCI verfügbar sind, können die GPU-Ressourcen besser kontrolliert und Computing- oder Storage-Nodes nach Bedarf erweitert werden. 
---
= Anwendungsfälle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Mit einer hybriden VDI mit NetApp VDS können Service-Provider und Virtual Desktop-Administratoren der Enterprise-Klasse Ressourcen problemlos auf andere Cloud-Umgebungen erweitern, ohne ihre Benutzer zu beeinträchtigen. Das Vorhandensein von On-Premises-Ressourcen ermöglicht eine bessere Kontrolle von Ressourcen und bietet umfassende Auswahl an Optionen (Computing, GPU, Storage und Netzwerk) zur Erfüllung der Anforderungen.

Diese Lösung trifft auf folgende Anwendungsfälle zu:

* Wechsel zur Cloud aufgrund von rasant anstiegendem Bedarf an Remote-Desktops und -Applikationen
* Reduzieren der TCO für lange ausgeführte Remote-Desktops und Applikationen, indem sie lokal mit Flash-Storage- und GPU-Ressourcen gehostet werden
* Einfaches Management von Remote-Desktops und -Applikationen in Cloud-Umgebungen
* Erleben Sie Remote-Desktops und -Applikationen mit einem Software-als-Service-Modell mit On-Premises-Ressourcen




== Zielgruppe

Die Zielgruppe für die Lösung umfasst die folgenden Gruppen:

* EUC-/VDI-Architekten, die die Anforderungen an ein hybrides VDS verstehen möchten
* NetApp Partner, die Kunden bei ihren Remote-Desktop- und -Applikationsanforderungen unterstützen möchten
* Vorhandene NetApp HCI Kunden, die Remote-Desktop- und -Applikationsanforderungen erfüllen möchten

