---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: Bei Verwendung eines H610C oder H615C muss die Lizenz für die GPU von einem dafür autorisierten NVIDIA-Partner erworben werden. 
---
= NVIDIA-Lizenzierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Bei Verwendung eines H610C oder H615C muss die Lizenz für die GPU von einem dafür autorisierten NVIDIA-Partner erworben werden. NVIDIA-Partner finden Sie mit dem https://www.nvidia.com/object/partner-locator.html["PARTNERFINDER"^]. Suche nach Kompetenzen wie Virtual GPU (vGPU) oder Tesla

Die NVIDIA vGPU-Software ist in vier Editionen verfügbar:

* NVIDIA GRID Virtual PC (GRID vPC)
* NVIDIA GRID Virtual Applikationen (GRID vApps)
* NVIDIA Quadro Virtual Data Center Workstation (Quadro VDWS)
* NVIDIA Virtual ComputeServer (vComputeServer)




== GRID Virtual PC

Dieses Produkt ist ideal für Benutzer, die einen virtuellen Desktop benötigen, der eine hohe Benutzerfreundlichkeit für Microsoft Windows Applikationen, Browser, HD-Video und Unterstützung für mehrere Monitore bietet. NVIDIA GRID Virtual PC bietet ein natives Arbeiten in einer virtuellen Umgebung, sodass Sie alle PC-Applikationen ohne jede Einschränkung ausführen können.



== GRID Virtual Applikationen

GRID vApps richten sich an Unternehmen, die einen RDSH (Remote Desktop Session Host) oder andere Applikations-Streaming- oder sitzungsbasierte Lösungen einsetzen. Auf Windows-Servern gehostete RDSH-Desktops, auf denen Microsoft Windows-Applikationen ohne Leistungseinschränkungen laufen, werden von GRID vApps ebenfalls unterstützt.



== Quadro Virtual Data Center Workstation

Diese Edition eignet sich ideal für große und anspruchsvolle Designer, die leistungsstarke Anwendungen zur Erstellung von 3D-Inhalten wie Dassault CATIA, SOLIDWORKS, 3DEXCITE, Siemens NX, PTC Creo, Schlumberger Petrel oder Autodesk Maya. NVIDIA Quadro VDWS ermöglicht es Nutzern, überall und auf jedem Gerät auf ihre professionellen Grafik-Applikationen mit vollständigen Funktionen und Performance zuzugreifen.



== NVIDIA Virtual ComputeServer

In vielen Unternehmen werden rechenintensive Server-Workloads wie künstliche Intelligenz (KI), Deep Learning (DL) und Data Science ausgeführt. In diesen Einsatzbereichen virtualisiert die NVIDIA vComputeServer-Software die NVIDIA-GPU, die rechenintensive Server-Workloads mit Funktionen wie Fehlerkorrektur-Code, Page Retirement, Peer-to-Peer über NVLink und Multi-vGPU beschleunigt.


NOTE: Eine Quadro VDWS-Lizenz berechtigt Sie zur Nutzung VON GRID vPC und NVIDIA vComputeServer.
