---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html 
keywords: TR-4861, VDS, Windows Virtual Desktop, Remote Desktop Services, Virtual Desktop Services, 
summary: 'Der NetApp Virtual Desktop Service (VDS) orchestriert die Remote Desktop Services (RDS) in führenden Public Clouds sowie auf Private Clouds. VDS unterstützt Windows Virtual Desktop (WVD) unter Microsoft Azure. VDS automatisiert viele Aufgaben, die nach der Implementierung von WVD oder RDS ausgeführt werden müssen, einschließlich der Einrichtung von SMB-Dateifreigaben (für Benutzerprofile, gemeinsam genutzte Daten und das Benutzer-Home-Laufwerk) sowie der Aktivierung von Windows-Funktionen, Applikations- und Agent-Installation, Firewall sowie Richtlinien usw.' 
---
= TR-4861: Hybrid Cloud VDI mit Virtual Desktop Service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Suresh ThopPay, NetApp

[role="lead"]
Der NetApp Virtual Desktop Service (VDS) orchestriert die Remote Desktop Services (RDS) in führenden Public Clouds sowie auf Private Clouds. VDS unterstützt Windows Virtual Desktop (WVD) unter Microsoft Azure. VDS automatisiert viele Aufgaben, die nach der Implementierung von WVD oder RDS ausgeführt werden müssen, einschließlich der Einrichtung von SMB-Dateifreigaben (für Benutzerprofile, gemeinsam genutzte Daten und das Benutzer-Home-Laufwerk) sowie der Aktivierung von Windows-Funktionen, Applikations- und Agent-Installation, Firewall sowie Richtlinien usw.

Benutzer nutzen VDS für dedizierte Desktops, Shared Desktops und Remote-Applikationen. VDS bietet skriptbasierte Ereignisse zur Automatisierung des Anwendungsmanagements für Desktops und verringert die Anzahl der zu verwaltenden Images.

VDS bietet ein zentrales Management-Portal für den Umgang mit Implementierungen über Public und Private Cloud-Umgebungen hinweg.



== Mehrwert Für Den Kunden

Die explosionsartige Zunahme der Mitarbeiter an Remote-Standorten im Jahr 2020 hat die Anforderungen an Business Continuity geändert. IT-Abteilungen stehen bei der schnellen Bereitstellung virtueller Desktops vor neuen Herausforderungen. Sie müssen daher flexible Lösungen bei der Bereitstellung, Remote-Management und die TCO-Vorteile einer Hybrid Cloud benötigen, was die Bereitstellung von On-Premises- und Cloud-Ressourcen vereinfacht. Sie benötigen eine Hybrid-Cloud-Lösung mit folgenden Vorteilen:

* Adressiert die Realität des Post-COVID-Arbeitsbereichs, um flexible Arbeitsmodelle mit globaler Dynamik zu ermöglichen
* Schichtarbeit wird ermöglicht, indem die Bereitstellung von Arbeitsumgebungen für alle Mitarbeiter vereinfacht und beschleunigt wird, von Task Workers bis hin zu Power Usern
* Mobilisiert Ihre Mitarbeiter, indem Sie umfassende, sichere VDI-Ressourcen bereitstellen, unabhängig vom physischen Standort
* Vereinfachte Hybrid-Cloud-Implementierung
* Automatisiert und vereinfacht das Management zur Risikominimierung

