---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_conclusion.html 
keywords: VDS, Virtual Desktop Service, HCI, conclusion 
summary: Der NetApp Virtual Desktop Service bietet eine einfach zu nutzende Umgebung, in der virtuelle Desktop-Computer und Applikationen leicht zu belegen sind, und konzentriert sich auf geschäftliche Herausforderungen. Durch die Erweiterung von VDS mit NetApp HCI lassen sich leistungsstarke NetApp Funktionen in einer VDS-Umgebung nutzen, einschließlich Inline-Deduplizierung, Data-Compaction, Thin Provisioning und Komprimierung. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Der NetApp Virtual Desktop Service bietet eine einfach zu nutzende Umgebung, in der virtuelle Desktop-Computer und Applikationen leicht zu belegen sind, und konzentriert sich auf geschäftliche Herausforderungen. Durch die Erweiterung von VDS auf die lokale ONTAP Umgebung können Unternehmen leistungsstarke NetApp Funktionen in einer VDS-Umgebung nutzen, darunter Rapid Clone, Inline-Deduplizierung, Data-Compaction, Thin Provisioning Und Komprimierung. Diese Funktionen senken die Storage-Kosten und verbessern die Performance mit All-Flash-Storage. Mit VMware vSphere Hypervisor, der die Server-Bereitstellung durch die Verwendung von Virtual Volumes und vSphere API für die Array-Integration auf ein Minimum reduziert Mithilfe der Hybrid Cloud wählen Kunden die richtige Umgebung für ihre anspruchsvollen Workloads und sparen Geld. Die Desktop-Session, bei der lokale Systeme ausgeführt wird, kann richtlinienbasiert auf Cloud-Ressourcen zugreifen.
