---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: Grafikarbeitsplätze werden typischerweise in Branchen eingesetzt, zum Beispiel Fertigung, Gesundheitswesen, Energie, Medien und Unterhaltung, Bildung, Und so weiter. Häufig ist die Mobilität für grafikintensive Applikationen eingeschränkt. 
---
= Lösungen für die Branche
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Grafikarbeitsplätze werden typischerweise in Branchen eingesetzt, zum Beispiel Fertigung, Gesundheitswesen, Energie, Medien und Unterhaltung, Bildung, Und so weiter. Häufig ist die Mobilität für grafikintensive Applikationen eingeschränkt.

Um das Problem der Mobilität zu lösen, bieten Virtual Desktop Services eine Desktop-Umgebung für alle Arten von Mitarbeitern, von Task Workers bis hin zu Experteneinsätzen, die Hardware-Ressourcen in der Cloud oder mit NetApp HCI verwenden, einschließlich Optionen für flexible GPU-Konfigurationen. MIT VDS können Benutzer von überall aus mit Laptops, Tablets und anderen mobilen Geräten auf ihre Arbeitsumgebung zugreifen.

Zur Ausführung von Produktions-Workloads mit Software wie ANSYS Fluent, ANSYS Mechanical, Autodesk AutoCAD, Autodesk Inventor, Autodesk 3ds Max, Dassault Systèmes SOLIDWORKS, Dassault Systèmes CATIA, PTC Creo, Siemens PLM NX usw., Die in verschiedenen Clouds verfügbaren GPUs (Stand Januar 2021) sind in der folgenden Tabelle aufgeführt.

[cols="20,20,20,20,20"]
|===
| GPU-Modell | Microsoft Azure | Google Compute (GCP) | Amazon Web Services (AWS) | On-Premises (NetApp HCI) 


| NVIDIA M60 | Ja. | Ja. | Ja. | Nein 


| NVIDIA T4 | Nein | Ja. | Ja. | Ja. 


| NVIDIA P100 | Nein | Ja. | Nein | Nein 


| NVIDIA P4 | Nein | Ja. | Nein | Nein 
|===
Darüber hinaus sind auch gemeinsame Desktop-Sitzungen mit anderen Benutzern und dedizierte persönliche Desktops verfügbar. Virtual Desktops können über eine oder vier GPUs verfügen oder mit NetApp HCI TeilaufGPUs nutzen. Die NVIDIA T4 ist eine vielseitige GPU-Karte, die sich den Anforderungen eines breiten Spektrums an Benutzer-Workloads anpasst. Jede GPU-Karte auf dem NetApp HCI H615C verfügt über 16 GB Frame-Puffer-Speicher und drei Karten pro Server. Die Anzahl der Benutzer, die auf einem einzelnen H615C Server gehostet werden können, hängt von der Benutzer-Workload ab.

[cols="25,25,25,25"]
|===
| Benutzer/Server | Licht (4 GB) | Mittel (8 GB) | Schwer (16 GB) 


| H615C | 12 | 6 | 3 
|===
Zur Ermittlung des Benutzertyps führen Sie das GPU-Profiler-Tool aus, während Benutzer mit Anwendungen arbeiten, die typische Aufgaben ausführen. Der GPU-Profiler erfasst die Speicheranforderungen, die Anzahl der Anzeigen und die Auflösung, die Benutzer benötigen. Sie können dann das vGPU-Profil auswählen, das Ihre Anforderungen erfüllt.

Virtuelle Desktops mit GPUs können eine Anzeigeauflösung von bis zu 8 KB unterstützen. Das Utility nView kann einen einzelnen Monitor in Regionen aufteilen und mit unterschiedlichen Datensätzen arbeiten.

ONTAP File Storage bietet folgende Vorteile:

* Ein Single Namespace kann bis zu 20 PB Storage mit 400 Milliarden Dateien anwachsen und dabei keinen großen administrativen Aufwand haben
* Ein Namespace, der sich mit einem globalen File Cache weltweit erstrecken kann
* Sichere Mandantenfähigkeit mit gemanagtem NetApp Storage
* Migration von kalten Daten zu Objektspeichern mit NetApp FabricPool
* Schnelle Dateistatistiken mit Dateisystemanalysen
* Storage-Cluster auf bis zu 24 Nodes skalieren, was Kapazität und Performance erhöht
* Storage-Platzbedarf lässt sich mithilfe von Kontingenten und garantierter Performance mit QoS-Limits kontrollieren
* Sicherung von Daten durch Verschlüsselung
* Erfüllen umfassender Anforderungen an Datensicherung und Compliance
* Flexible Business Continuity-Optionen


link:vdi-vds/hcvdivds_conclusion.html["Weiter: Fazit"]
