---
sidebar: sidebar 
permalink: vdi-vds/vdi-index.html 
keywords: vdi, vds, virtual desktop, end use computing, 
summary: Task Worker können schnell eine Anwendung aus der Liste der ihnen zur Verfügung gestellten Anwendungen starten. App Services veröffentlichen Anwendungen von den Remote Desktop Services-Sitzungshosts. Mit WVD bieten Anwendungsgruppen ähnliche Funktionen aus Windows 10-Hostpools mit mehreren Sitzungen. 
---
= EUC-/VDI-Lösungen (End User Computing)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Egal, ob Sie Virtual Desktops lokal oder in der Cloud implementieren: NetApp verfügt über zahlreiche EUC-/VDI-Lösungen, die Ihre Anforderungen erfüllen.



== NetApp Virtual Desktop Services (VDS)

Der NetApp Virtual Desktop Service (VDS) orchestriert die Remote Desktop Services (RDS) in führenden Public Clouds sowie auf Private Clouds.

Verfügbare Lösungen für VDS:

* link:hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html["Hybrid-Cloud-VDI mit NetApp Virtual Desktop Service"]




== End User Computing with VMware Horizon

NetApp verfügt über verifizierte Architekturen für VMware Horizon mit verschiedenen Computing-Konfigurationen. Zu den verfügbaren Lösungen gehören:

* link:https://www.netapp.com/pdf.html?item=/media/7123-nva1129designpdf.pdf["End User Computing with VMware (Design Guide)"]
* link:https://www.netapp.com/us/media/nva-1129-design.pdf["End User Computing with VMware and NVIDIA GPUs (Design Guide)"]
* link:https://www.netapp.com/pdf.html?item=/media/7124-nva-1129-deploy.pdf["End User Computing with VMware and NVIDIA GPUs (Deployment Guide)"]
* link:https://www.netapp.com/pdf.html?item=/media/7125-tr4792pdf.pdf["Endbenutzer-Computing mit VMware für 3D-Grafik"]

