---
sidebar: sidebar 
permalink: virtualization/vmware-vcf-overview.html 
keywords: netapp, vmware, cloud, foundation, vcf, flexpod 
summary:  
---
= VMware Cloud Foundation
:allow-uri-read: 




== VMware Cloud Foundation

[role="lead"]
VMware Cloud Foundation (VCF) ist eine Reihe von Technologien, die einen einfachen Zugang zu einer Hybrid-Cloud-Umgebung ermöglichen. Innerhalb der VCF-Lösung werden sowohl native Kubernetes- als auch Virtual Machine-basierte Workloads unterstützt. Wesentliche Services wie VMware vSphere, VMware vSAN, VMware NSX-T Data Center und VMware vRealize Cloud Management sind Bestandteile des VCF-Pakets. Zusammen bilden diese Services eine softwaredefinierte Infrastruktur, die Computing-, Storage-, Netzwerk-, Sicherheits- und Cloud-Management unterstützt. Diese kollektive Infrastruktur bietet eine hybride Nutzung, bei der das VCF-Framework die Umgebung vom Datacenter vor Ort auf Amazon Web Services (AWS), Azure und Google Cloud erweitert.



=== Dokumentationsressourcen

Detaillierte Informationen zu NetApp Angeboten für VMware Cloud Foundation finden Sie in der folgenden Blog-Reihe mit vier (4) Teilen:

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-getting-started/["NetApp und VMware Cloud Foundation leicht gemacht Teil 1: Die ersten Schritte"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-ontap-principal-storage/["NetApp und VMware Cloud Foundation leicht gemacht Teil 2: VCF und ONTAP Principal Storage"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-element-principal-storage/["NetApp und VMware Cloud Foundation leicht gemacht Teil 3: VCF und Element Principal Storage"]
* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-supplemental-storage/["NetApp und VMware Cloud Foundation leicht gemacht – Teil 4: ONTAP-Tools für VMware und ergänzenden Storage"]


*NetApp FlexPod Lösungen für VMware Cloud Foundation*

* link:https://www.netapp.com/blog/expanding-flexpod-hybrid-cloud-with-vmware-cloud-foundation/["Erweiterung der FlexPod Hybrid Cloud mit VMware Cloud Foundation"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf.html["FlexPod als Workload-Domäne für VMware Cloud Foundation verwendet"]
* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf_design.html["FlexPod as a Workload Domain for VMware Cloud Foundation – Designleitfaden"]

