---
sidebar: sidebar 
permalink: virtualization/vmware-scv-overview.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= SnapCenter Plug-in für VMware vSphere
:allow-uri-read: 




== SnapCenter Plug-in für VMware vSphere

[role="lead"]
Das SnapCenter Plug-in für VMware vSphere ermöglicht schnelle, effiziente und VM-konsistente Backup- und Restore-Vorgänge für Virtual Machines (VMs), Datastores und VMDKs. Es funktioniert zusammen mit SnapCenter Server und ermöglicht applikationsbasierte Backup- und Restore-Funktionen für applikationsspezifische SnapCenter Plug-ins.



=== Dokumentationsressourcen

Detaillierte Informationen finden Sie in den folgenden Dokumentationsressourcen.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Dokumentation zum SnapCenter Plug-in für VMware vSphere"]




=== Lösungsressourcen

Weitere Informationen finden Sie in der folgenden 3-2-1-1 Backup-Lösung mit SnapCenter Plug-in für VMware vSphere sowie BlueXP Backup und Recovery für VMs.

Technischer Bericht: link:../ehc/bxp-scv-hybrid-solution.html["3-2-1 Datensicherung für VMware mit SnapCenter Plug-in und BlueXP Backup und Recovery für VMs"]

Tech OnTap-Blog: link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["3-2-1 Datensicherung für VMware mit SnapCenter Plug-in und BlueXP Backup und Recovery für VMs"]



=== Videoressourcen

.SnapCenter Plug-in für VMware vSphere – Voranforderungen für eine Lösung
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in für VMware vSphere – Implementierung
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in für VMware vSphere – Backup-Workflow
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in für VMware vSphere – Workflow wiederherstellen
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - SQL Restore-Workflow
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]