---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Auf dieser Seite finden Sie Videos und Tutorials. 
---
= Virtualisierungsvideos und -Demos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sehen Sie sich die folgenden Videos und Demos an, in denen die spezifischen Funktionen von Hybrid Cloud-, Virtualisierungs- und Container-Lösungen vorgestellt werden.

.NetApp ONTAP Tools für VMware vSphere
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
ONTAP Tools für VMware - Übersicht

 a| 
Bereitstellung von VMware iSCSI-Datenspeichern mit ONTAP

 a| 
Bereitstellung von VMware NFS-Datenspeichern mit ONTAP


|===
====
.VMware Cloud auf AWS mit AWS FSX für NetApp ONTAP
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Windows Guest Connected Storage mit FSX ONTAP über iSCSI

 a| 
Linux Guest Connected Storage with FSX ONTAP Using NFS

 a| 
VMware Cloud auf AWS TCO-Einsparungen mit Amazon FSX für NetApp ONTAP




 a| 
VMware Cloud auf AWS zusätzlicher Datastore mit Amazon FSX für NetApp ONTAP

 a| 
VMware HCX Deployment and Configuration Setup für VMC

 a| 
Demo für die Migration von vMotion mit VMware HCX für VMC und FSxN




 a| 
Demonstration zur Cold-Migration mit VMware HCX für VMC und FSxN

 a| 
 a| 

|===
====
.Azure VMware-Services auf Azure mit Azure NetApp Files (ANF)
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Übersicht über die Azure VMware Lösung zusätzlichen Datastore mit Azure NetApp Files

 a| 
Azure VMware Lösung für DR mit Cloud Volumes ONTAP, SnapCenter und JetStream

 a| 
Demonstration zur Cold-Migration mit VMware HCX für AVS und ANF




 a| 
VMotion-Demo mit VMware HCX für AVS und ANF

 a| 
Massenmigration mit VMware HCX für AVS und ANF

 a| 

|===
====
.SnapCenter Plug-in für VMware vSphere
[%collapsible]
====
Die NetApp SnapCenter Software ist eine unkomplizierte Enterprise-Plattform, die die Koordination und das Management der Datensicherung für alle Applikationen, Datenbanken und Filesysteme sicher gestaltet.

Das SnapCenter Plug-in für VMware vSphere ermöglicht Ihnen Backup-, Wiederherstellungs- und Anschlussvorgänge für VMs sowie Backup- und Mount-Vorgänge für Datastores, die bei SnapCenter direkt in VMware vCenter registriert sind.

Weitere Informationen zum NetApp SnapCenter Plug-in für VMware vSphere finden Sie im link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Überblick über NetApp SnapCenter Plug-in für VMware vSphere"].

[cols="5a, 5a, 5a"]
|===


 a| 
SnapCenter Plug-in für VMware vSphere – Voranforderungen für eine Lösung

 a| 
SnapCenter Plug-in für VMware vSphere – Implementierung

 a| 
SnapCenter Plug-in für VMware vSphere – Backup-Workflow




 a| 
SnapCenter Plug-in für VMware vSphere – Workflow wiederherstellen

 a| 
SnapCenter - SQL Restore-Workflow

 a| 

|===
====
.NetApp mit VMware Tanzu
[%collapsible]
====
Mit VMware Tanzu können Kunden ihre Kubernetes-Umgebung über vSphere oder VMware Cloud Foundation implementieren, managen und managen. Mit diesem VMware Portfolio können Kunden alle relevanten Kubernetes Cluster über eine einzige Kontrollebene managen. Dazu wählen sie die für sie am besten geeignete VMware Tanzu Edition.

Weitere Informationen zu VMware Tanzu finden Sie im https://tanzu.vmware.com/tanzu["VMware Tanzu Overview"^]. Diese Überprüfung behandelt Anwendungsfälle, verfügbare Ergänzungen und mehr über VMware Tanzu.

[cols="5a, 5a, 5a"]
|===


 a| 
Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 1

video::ZtbXeOJKhrc[youtube,width=360] a| 
Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 2

video::FVRKjWH7AoE[youtube,width=360] a| 
Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 3

video::Y-34SUtTTtU[youtube,width=360]
|===
====