---
sidebar: sidebar 
permalink: virtualization/vsphere_ontap_auto_block.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, iSER, iSCSI, FCoE,SAN, ONTAP tools 
summary: Auf dieser Seite finden Sie Schritte zur Bereitstellung eines NetApp ONTAP Storage iSCSI VMFS-Datenspeichers in einer VMware vSphere Umgebung. 
---
= VSphere herkömmliche Block-Storage-Bereitstellung mit ONTAP
:allow-uri-read: 


[role="lead"]
VMware vSphere unterstützt die folgenden VMFS-Datastore-Optionen, wobei die Unterstützung für das ONTAP-SAN-Protokoll angegeben ist.

[cols="50,50"]
|===
| VMFS-Datenspeicher-Optionen | Unterstützte ONTAP SAN-Protokolle 


| link:vsphere_ontap_auto_block_fc.html["Fibre Channel (FC)"] | ja 


| link:vsphere_ontap_auto_block_fcoe.html["Fibre Channel over Ethernet (FCoE)"] | ja 


| link:vsphere_ontap_auto_block_iscsi.html["ISCSI"] | ja 


| ISCSI-Erweiterungen für RDMA (iSER) | Nein 


| link:vsphere_ontap_auto_block_nvmeof.html["NVMe over Fabric mit FC (NVMe/FC)"] | ja 


| NVMe over Fabric mit RDMA over Converged Ethernet (NVMe/RoCE) | Nein 
|===

NOTE: Wenn iSER- oder NVMe/RoCE-VMFS erforderlich ist, prüfen Sie SANtricity-basierte Storage-Systeme.
