---
sidebar: sidebar 
permalink: virtualization/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Auf dieser Seite werden die Best Practices zur Implementierung einer NetApp ONTAP Storage-Lösung in einer VMware vSphere Umgebung beschrieben. 
---
= Einführung in ONTAP für vSphere Administratoren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Warum ONTAP für vSphere?

NetApp ONTAP vereinfacht das Storage- und Datenmanagement und ergänzt VMware Umgebungen deutlich, ob On-Premises oder in der Cloud bereitgestellt werden. Zu den Gründen, warum sich Zehntausende Kunden für ONTAP als Storage-Lösung für vSphere Implementierungen entschieden haben, zählen erstklassige Datensicherung, Innovationen zur Storage-Effizienz und herausragende Performance in SAN- und NAS-basierten VMware Architekturen.

NetApp bietet zahlreiche VMware Plug-ins, Validierungen und Qualifikationen verschiedener VMware Produkte, um Kunden bei der Administration einer Virtualisierungsumgebung zu unterstützen. NetApp bietet für das Storage- und Datenmanagement, was VMware für die Virtualisierung ist. Kunden können sich auf ihre Kernkompetenzen konzentrieren, anstatt auf das Management von physischem Storage. Die fast 20 Jahre andauernde Partnerschaft zwischen VMware und NetApp entwickelt sich weiter und steigert den Mehrwert für Kunden als neue Technologien wie VMware Cloud Foundation und Tanzu. Dabei unterstützt NetApp auch weiterhin die Basis von vSphere.

Zu den wichtigsten Faktoren für Kunden gehören:

* *Unified Storage*
* * Storage-Effizienz*
* *Virtuelle Volumes und richtlinienbasiertes Storage-Management*
* *Hybrid Cloud*


Weitere Informationen zu unterstützten NetApp und VMware Lösungen finden Sie in den folgenden Ressourcen:

* https://mysupport.netapp.com/matrix/#welcome["Das NetApp Interoperabilitäts-Matrix-Tool"^] (IMT). Das IMT definiert die qualifizierten Komponenten und Versionen der FC/FCoE-, iSCSI-, NFS- und CIFS-Konfigurationen.
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Der VMware Compatibility Guide"^]. Im VMware Compatibility Guide sind die System-, I/O-, Storage/SAN- und Backup-Kompatibilität mit VMware-Infrastruktur- und Softwareprodukten aufgeführt
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["NetApp ONTAP Tools für VMware"^]. ONTAP Tools für VMware vSphere ist ein einzelnes vCenter Server Plug-in, das die Erweiterungen VSC, VASA Provider und Storage Replication Adapter (SRA) enthält.

