---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: Auf dieser Seite finden Sie Videos und Tutorials. 
---
= Hybrid Cloud, Virtualisierung und Container Videos und Demos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sehen Sie sich die folgenden Videos und Demos an, in denen die spezifischen Funktionen von Hybrid Cloud-, Virtualisierungs- und Container-Lösungen vorgestellt werden.

.NetApp ONTAP Tools für VMware vSphere
[%collapsible]
====
.ONTAP Tools für VMware - Übersicht
[%collapsible]
=====
video::otv_overview.mp4[]
=====
.Bereitstellung von VMware iSCSI-Datenspeichern mit ONTAP
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====
.Bereitstellung von VMware NFS-Datenspeichern mit ONTAP
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====
====
.VMware Cloud auf AWS mit AWS FSX für NetApp ONTAP
[%collapsible]
====
.Windows Guest Connected Storage mit FSX ONTAP über iSCSI
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.Linux Guest Connected Storage with FSX ONTAP Using NFS
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.VMware Cloud auf AWS TCO-Einsparungen mit Amazon FSX für NetApp ONTAP
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.VMware Cloud auf AWS zusätzlicher Datastore mit Amazon FSX für NetApp ONTAP
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.VMware Cloud auf AWS Migration mit FSxN, VMware HCX
[%collapsible]
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.Azure VMware-Services auf Azure mit Azure NetApp Files (ANF)
[%collapsible]
====
.Übersicht über die Azure VMware Lösung zusätzlichen Datastore mit Azure NetApp Files
[%collapsible]
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.Azure VMware Lösung für DR mit Cloud Volumes ONTAP, SnapCenter und JetStream
[%collapsible]
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.Migration der Azure VMware Lösung mit ANF, VMware HCX
[%collapsible]
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.SnapCenter Plug-in für VMware vSphere
[%collapsible]
====
Die NetApp SnapCenter Software ist eine unkomplizierte Enterprise-Plattform, die die Koordination und das Management der Datensicherung für alle Applikationen, Datenbanken und Filesysteme sicher gestaltet.

Das SnapCenter Plug-in für VMware vSphere ermöglicht Ihnen Backup-, Wiederherstellungs- und Anschlussvorgänge für VMs sowie Backup- und Mount-Vorgänge für Datastores, die bei SnapCenter direkt in VMware vCenter registriert sind.

Weitere Informationen zum NetApp SnapCenter Plug-in für VMware vSphere finden Sie im link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Überblick über NetApp SnapCenter Plug-in für VMware vSphere"].

.SnapCenter Plug-in für VMware vSphere – Voranforderungen für eine Lösung
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====
.SnapCenter Plug-in für VMware vSphere – Implementierung
[%collapsible]
=====
video::scv_deployment.mp4[]
=====
.SnapCenter Plug-in für VMware vSphere – Backup-Workflow
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====
.SnapCenter Plug-in für VMware vSphere – Workflow wiederherstellen
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====
.SnapCenter - SQL Restore-Workflow
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====
====
.NetApp mit VMware Tanzu
[%collapsible]
====
Mit VMware Tanzu können Kunden ihre Kubernetes-Umgebung über vSphere oder VMware Cloud Foundation implementieren, managen und managen. Mit diesem VMware Portfolio können Kunden alle relevanten Kubernetes Cluster über eine einzige Kontrollebene managen. Dazu wählen sie die für sie am besten geeignete VMware Tanzu Edition.

Weitere Informationen zu VMware Tanzu finden Sie im https://tanzu.vmware.com/tanzu["VMware Tanzu Overview"^]. Diese Überprüfung behandelt Anwendungsfälle, verfügbare Ergänzungen und mehr über VMware Tanzu.

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 1"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 2"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 3"^]


====
.NetApp mit Red hat OpenShift
[%collapsible]
====
Red hat OpenShift, eine Kubernetes-Plattform für Unternehmen, ermöglicht die Ausführung von Container-basierten Applikationen mit einer offenen Hybrid-Cloud-Strategie. Red hat OpenShift ist als Cloud-Service auf führenden Public Clouds oder als eigenständige Software verfügbar und bietet Kunden die Flexibilität, die sie beim Entwurf ihrer containerbasierten Lösung benötigen.

Weitere Informationen zu Red hat OpenShift finden Sie hier https://www.redhat.com/en/technologies/cloud-computing/openshift["Übersicht über Red hat OpenShift"^]. Weitere Informationen zu Red hat OpenShift finden Sie in der Produktdokumentation und den Bereitstellungsoptionen.

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["Workload-Migration – Red hat OpenShift mit NetApp"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["Red hat OpenShift Deployment on RHV: Red hat OpenShift mit NetApp"^]


====