---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_additional_information.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, additional, information 
summary: Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren. 
---
= Weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* TR-4597: VMware vSphere für ONTAPhttps://["https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html"^]
* TR-4400: VMware vSphere Virtual Volumes with ONTAPhttps://["https://www.netapp.com/pdf.html?item=/media/13555-tr4400.pdf"^]
* TR-4015 SnapMirror Configuration Best Practice Guide für ONTAP 9https://[]
* RBAC Benutzer-Creator für ONTAPhttps://["https://mysupport.netapp.com/site/tools/tool-eula/rbac"^]
* ONTAP Tools für VMware vSphere Ressourcenhttps://["https://mysupport.netapp.com/site/products/all/details/otv/docsandkb-tab"^]
* VMware Site Recovery Manager - Dokumentationhttps://["https://docs.vmware.com/en/Site-Recovery-Manager/index.html"^]


Siehe http://["Interoperabilitäts-Matrix-Tool (IMT)"^] Überprüfen Sie auf der NetApp Support-Website, ob die in diesem Dokument angegebenen Produktversionen und Funktionen in Ihrer IT-Umgebung unterstützt werden. Das NetApp IMT definiert die Produktkomponenten und -Versionen, die für von NetApp unterstützte Konfigurationen verwendet werden können. Die spezifischen Ergebnisse hängen von der Installation des jeweiligen Kunden gemäß den technischen Daten ab.
