---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_conclusion.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, vcenter, disaster 
summary: Bei VMware vCenter Site Recovery Manager handelt es sich um ein Disaster Recovery-Angebot, das eine automatisierte Orchestrierung und unterbrechungsfreies Testen zentralisierter Recovery-Pläne bietet, um das Disaster Recovery Management aller virtualisierten Applikationen zu vereinfachen. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Bei VMware vCenter Site Recovery Manager handelt es sich um ein Disaster Recovery-Angebot, das eine automatisierte Orchestrierung und unterbrechungsfreies Testen zentralisierter Recovery-Pläne bietet, um das Disaster Recovery Management aller virtualisierten Applikationen zu vereinfachen.

Durch die Implementierung von Site Recovery Manager auf NetApp ONTAP Systemen können Sie die Kosten und die Komplexität des Disaster Recovery deutlich senken. Mit hochperformanten, einfach zu managenden und skalierbaren Storage-Appliances und dem Angebot an leistungsstarker Software bietet NetApp flexible Storage- und Datenmanagement-Lösungen zur Unterstützung von vSphere Umgebungen.

Die in diesem Leitfaden enthaltenen Best Practices und Empfehlungen sind keine Einheitslösung. Dieses Dokument enthält eine Sammlung von Best Practices und Empfehlungen, die Richtlinien für die Planung, Implementierung und das Management von SRM DR-Plänen bereitstellen. Wenden Sie sich bei der Planung und Implementierung von VMware vCenter Site Recovery-Umgebungen auf NetApp Storage an einen örtlichen NetApp VMware Experten. NetApp VMware Experten können die Bedürfnisse und Anforderungen jeder vSphere Umgebung rasch identifizieren und die Storage-Lösung entsprechend anpassen.
