---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_conclusion.html 
keywords: bare metal, infrastructure, stateful, Trident 
summary: Anthos auf Bare Metal mit NetApp bietet eine robuste Plattform zur effizienten Ausführung containerbasierter Workloads durch die Anpassung der implementierten Infrastruktur. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Anthos auf Bare Metal mit NetApp bietet eine robuste Plattform zur effizienten Ausführung containerbasierter Workloads durch die Anpassung der implementierten Infrastruktur. Kunden können die Server-Infrastruktur und ein unterstütztes Betriebssystem ihrer Wahl nutzen oder die Lösung sogar in ihrer vorhandenen Infrastruktur implementieren. Die Leistung und Flexibilität dieser Umgebungen steigt erheblich durch die Integration von NetApp ONTAP und NetApp Astra Trident. Sie unterstützt statusorientierte Applikations-Workloads durch eine effiziente Bereitstellung und das effiziente Management von persistentem Storage für Container. Wenn Kunden das Potenzial von Google Cloud auf der Basis von NetApp Systemen ihrem Datacenter ausschöpfen, profitieren sie von den Vorteilen einer vollständig unterstützten, hochverfügbaren, einfach skalierbaren und vollständig gemanagten Kubernetes-Lösung zur Entwicklung und Produktion ihrer Applikations-Workloads.

link:bmanthos_where_to_find_additional_information.html["Weiter: Wo finden Sie zusätzliche Informationen."]
