---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: 'NetApp und Google Cloud arbeiten seit mehreren Jahren eng zusammen: NetApp stellt gemeinsam mit Cloud Volumes ONTAP und Cloud Volumes Service Cloud-Datenservices vor, die erstmals in Google Cloud verfügbar sind. Anschließend wird die On-Premises-NetApp HCI-Plattform für Google Cloud Anthos validiert – eine Hypervisor-basierte Kubernetes-Lösung für Multi-Cloud-Umgebungen auf VMware vSphere. NetApp hat Anthos Ready Qualification für NetApp Astra Trident, ONTAP und das NFS-Protokoll bestanden, um dynamischen persistenten Storage für Container bereitzustellen.' 
---
= WP-7337: Anthos auf Bare Metal
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


Alan Cowles und Nikhil M Kulkarni, NetApp

NetApp und Google Cloud arbeiten seit mehreren Jahren eng zusammen: NetApp stellt gemeinsam mit Cloud Volumes ONTAP und Cloud Volumes Service Cloud-Datenservices für Google Cloud vor. Anschließend wird die On-Premises-NetApp HCI-Plattform für Google Cloud Anthos validiert – eine Hypervisor-basierte Kubernetes-Lösung für Multi-Cloud-Umgebungen auf VMware vSphere. NetApp hat Anthos Ready Qualification für NetApp Astra Trident, ONTAP und das NFS-Protokoll bestanden, um dynamischen persistenten Storage für Container bereitzustellen.

Anthos kann jetzt direkt auf Bare-Metal-Servern in der Kundenumgebung installiert werden, was eine zusätzliche Option für Kunden zur Erweiterung von Google Cloud in ihre lokalen Rechenzentren ohne Hypervisor bietet. Durch die Nutzung der Funktionen des Storage-Betriebssystems NetApp ONTAP und des NetApp Astra Trident können Sie die Funktionen Ihrer Plattform erweitern, indem Sie persistenten Storage für Container integrieren.

Mit dieser Kombination können Sie das volle Potenzial Ihrer Server, Ihres Storage und Ihres Netzwerks ausschöpfen sowie Support, Service Level, monatliche Abrechnung und bedarfsgerechte Flexibilität wie Google Cloud bieten. Da Sie Ihre eigene Hardware, Ihr Netzwerk und Ihren eigenen Storage verwenden, haben Sie die direkte Kontrolle über Applikationsskala, Sicherheit und Netzwerklatenz sowie die Vorteile von gemanagten und containerisierten Applikationen mit Anthos auf Bare Metal.

link:bmanthos_solution_overview.html["Weiter: Lösungsübersicht."]
