= 
:allow-uri-read: 


. 8575c02ec176b0f64904bcbd79e81cba
. Klonen Sie das GitHub Repository, das Ansible-Inhalte hostet.
+
[source, cli]
----
git clone https://github.com/NetApp-Automation/na_astra_control_suite.git
----
. Melden Sie sich bei der NetApp Support-Website an und laden Sie die neueste Version des NetApp Astra Control Center herunter. Dazu ist eine Lizenz erforderlich, die an Ihr NetApp Konto angehängt ist. Nach dem Download des Tarballs, übertragen Sie es auf die Workstation.
+

NOTE: Um mit einer Testlizenz für Astra Control zu beginnen, besuchen Sie die https://["Astra: Anmelde-Website"^].

. Erstellen oder beziehen Sie die kubeconfg-Datei mit Administratorzugriff auf das {k8s_usercluster_Name}-Cluster, auf dem Astra Control Center installiert werden soll.
. Ändern Sie das Verzeichnis in `na_astra_control_suite`.
+
[source, cli]
----
cd na_astra_control_suite
----
. Bearbeiten Sie das `vars/vars.yml` Datei und füllen Sie die Variablen mit den erforderlichen Informationen aus.
+
[source, cli]
----
#Define whether or not to push the Astra Control Center images to your private registry [Allowed values: yes, no]
push_images: yes

#The directory hosting the Astra Control Center installer
installer_directory: /home/admin/

#Specify the ingress type. Allowed values - "AccTraefik" or "Generic"
#"AccTraefik" if you want the installer to create a LoadBalancer type service to access ACC, requires MetalLB or similar.
#"Generic" if you want to create or configure ingress controller yourself, installer just creates a ClusterIP service for traefik.
ingress_type: "AccTraefik"

#Name of the Astra Control Center installer (Do not include the extension, just the name)
astra_tar_ball_name: astra-control-center-22.04.0

#The complete path to the kubeconfig file of the kubernetes/openshift cluster Astra Control Center needs to be installed to.
hosting_k8s_cluster_kubeconfig_path: /home/admin/cluster-kubeconfig.yml

#Namespace in which Astra Control Center is to be installed
astra_namespace: netapp-astra-cc

#Astra Control Center Resources Scaler. Leave it blank if you want to accept the Default setting.
astra_resources_scaler: Default

#Storageclass to be used for Astra Control Center PVCs, it must be created before running the playbook [Leave it blank if you want the PVCs to use default storageclass]
astra_trident_storageclass: basic

#Reclaim Policy for Astra Control Center Persistent Volumes [Allowed values: Retain, Delete]
storageclass_reclaim_policy: Retain

#Private Registry Details
astra_registry_name: "docker.io"

#Whether the private registry requires credentials [Allowed values: yes, no]
require_reg_creds: yes

#If require_reg_creds is yes, then define the container image registry credentials
#Usually, the registry namespace and usernames are same for individual users
astra_registry_namespace: "registry-user"
astra_registry_username: "registry-user"
astra_registry_password: "password"

#Kuberenets/OpenShift secret name for Astra Control Center
#This name will be assigned to the K8s secret created by the playbook
astra_registry_secret_name: "astra-registry-credentials"

#Astra Control Center FQDN
acc_fqdn_address: astra-control-center.cie.netapp.com

#Name of the Astra Control Center instance
acc_account_name: ACC Account Name

#Administrator details for Astra Control Center
admin_email_address: admin@example.com
admin_first_name: Admin
admin_last_name: Admin
----
. Nutzen Sie das Playbook zur Implementierung des Astra Control Center. Für bestimmte Konfigurationen sind Root-Berechtigungen erforderlich.
+
Führen Sie den folgenden Befehl aus, um das Playbook auszuführen, wenn der Benutzer, der das Playbook ausführt, root ist oder passwortlose sudo konfiguriert ist.

+
[source, cli]
----
ansible-playbook install_acc_playbook.yml
----
+
Wenn der Benutzer passwortbasierten sudo-Zugriff konfiguriert hat, führen Sie den folgenden Befehl aus, um das Playbook auszuführen und geben Sie dann das sudo-Passwort ein.

+
[source, cli]
----
ansible-playbook install_acc_playbook.yml -K
----

