= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
In diesem Abschnitt wird beschrieben, wie Sie VMware Cloud auf AWS SDDC einrichten und managen und es in Kombination mit den verfügbaren Optionen zur Verbindung von NetApp Storage nutzen.


NOTE: Der in-Guest Storage ist die einzige unterstützte Methode zur Verbindung von Cloud Volumes ONTAP mit AWS VMC.

Der Einrichtungsvorgang kann in die folgenden Schritte unterteilt werden:

* Implementieren und Konfigurieren von VMware Cloud für AWS
* Verbinden Sie VMware Cloud mit FSX ONTAP


Details anzeigen link:aws-setup.html["Konfigurationsschritte für VMC"].

Details anzeigen link:aws-setup.html["Konfigurationsschritte für VMC"].

--
.Azure/AVS
--
In diesem Abschnitt wird beschrieben, wie Sie Azure VMware Lösung einrichten und managen und in Kombination mit den verfügbaren Optionen für die Verbindung von NetApp Storage verwenden.


NOTE: Der in-Guest-Speicher ist die einzige unterstützte Methode zur Verbindung von Cloud Volumes ONTAP mit Azure VMware-Lösung.

Der Einrichtungsvorgang kann in die folgenden Schritte unterteilt werden:

* Registrieren Sie den Ressourcenanbieter und erstellen Sie eine Private Cloud
* Stellen Sie eine Verbindung zu einem neuen oder vorhandenen virtuellen ExpressRoute Netzwerk-Gateway her
* Netzwerkverbindung validieren und auf Private Cloud zugreifen


Details anzeigen link:azure-setup.html["Konfigurationsschritte für AVS"].

Details anzeigen link:azure-setup.html["Konfigurationsschritte für AVS"].

--
.GCP/GCVE
--
In diesem Abschnitt wird beschrieben, wie Sie GCVE einrichten und managen und in Kombination mit den verfügbaren Optionen zum Verbinden von NetApp Storage verwenden.


NOTE: Der in-Guest-Speicher ist die einzige unterstützte Methode zum Verbinden von Cloud Volumes ONTAP und Cloud Volumes Services mit GCVE.

Der Einrichtungsvorgang kann in die folgenden Schritte unterteilt werden:

* Bereitstellen und Konfigurieren von GCVE
* Aktivieren Sie den privaten Zugriff auf GCVE


Details anzeigen link:gcp-setup.html["Konfigurationsschritte für GCVE"].

Details anzeigen link:gcp-setup.html["Konfigurationsschritte für GCVE"].

--
====