= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS unterstützt NetApp Storage in den folgenden Konfigurationen:

* FSX ONTAP als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* FSX ONTAP als zusätzlichen NFS-Datastore


Details anzeigen link:aws/aws-guest.html["Storage-Optionen für VMC für Gastverbindung"]. Details anzeigen link:aws/aws-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für VMC"].

Details anzeigen link:aws-guest.html["Storage-Optionen für VMC für Gastverbindung"]. Details anzeigen link:aws-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für VMC"].

--
.Azure/AVS
--
Azure unterstützt NetApp Storage in den folgenden Konfigurationen:

* Azure NetApp Files (ANF) als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Azure NetApp Files (ANF) als zusätzlicher NFS-Datastore


Details anzeigen link:azure/azure-guest.html["Gastanbindung Speicheroptionen für AVS"]. Details anzeigen link:azure/azure-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für AVS"].

Details anzeigen link:azure-guest.html["Gastanbindung Speicheroptionen für AVS"]. Details anzeigen link:azure-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für AVS"].

--
.GCP/GCVE
--
Google Cloud unterstützt NetApp Storage in den folgenden Konfigurationen:

* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Cloud Volumes Service (CVS) als Storage mit Gastverbunden
* Cloud Volumes Service (CVS) als zusätzlicher NFS Datastore


Details anzeigen link:gcp/gcp-guest.html["Speicheroptionen für die Gastverbindung für GCVE"].

Details anzeigen link:gcp-guest.html["Speicheroptionen für die Gastverbindung für GCVE"].

Weitere Informationen link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Unterstützung von NetApp Cloud Volumes Service Datastores für die Google Cloud VMware Engine"^]

--
====