---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_deploy_intro.html 
summary: Dieses Whitepaper enthält einen Überblick und eine Validierung der Lösung für AWS angepasste Oracle RDS Datenbank-HA und -DR unter Nutzung des AWS FSX Storage-Service in einer Implementierung mit mehreren Verfügbarkeitszonen. 
keywords: HA, DR, database, Oracle, RDS, AWS 
---
= WP-7357: Einführung zu Oracle Database Deployment auf EC2 und FSX Best Practices
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


Allen Cao, Niyaz Mohamed, Jeffrey Steiner, NetApp

[role="lead"]
Viele geschäftskritische Oracle Datenbanken der Enterprise-Klasse werden nach wie vor lokal gehostet, und viele Unternehmen möchten diese Oracle Datenbanken in eine Public Cloud migrieren. Häufig sind diese Oracle-Datenbanken Applikationsorientierung vorhanden und benötigen daher benutzerspezifische Konfigurationen. Diese Funktionen fehlen bei vielen Public-Cloud-Angeboten für Datenbanken als Service. Aus diesem Grund erfordert die aktuelle Datenbanklandschaft eine Public-Cloud-basierte Oracle Datenbanklösung, die auf einem hochperformanten, skalierbaren Computing- und Storage-Service aufbaut und individuelle Anforderungen erfüllt. AWS EC2 Computing-Instanzen und der AWS FSX Storage-Service sind möglicherweise die fehlenden Bestandteile dieses Puzzles, das Sie zum Erstellen und Migrieren Ihrer geschäftskritischen Oracle Datenbank-Workloads in eine Public Cloud nutzen können.

Amazon Elastic Compute Cloud (Amazon EC2) ist ein Web-Service, der eine sichere, anpassbare Computing-Kapazität in der Cloud bietet. Es wurde entwickelt, um Unternehmen das webbasierte Cloud-Computing zu erleichtern. Über die einfache Amazon EC2 Web-Service-Schnittstelle erhalten und konfigurieren Sie Kapazitäten mit minimalem Reibungsaufwand. Es bietet Ihnen die vollständige Kontrolle über Ihre Computing-Ressourcen und ermöglicht Ihnen, auf Amazon bewährten Computing-Umgebung laufen.

Amazon FSX für ONTAP ist ein AWS Storage-Service, der branchenführende NetApp ONTAP Block- und File-Storage verwendet, der NFS, SMB und iSCSI aufdeckt. Dank einer derart leistungsstarken Storage Engine war es noch nie einfacher, geschäftskritische Oracle Datenbankapplikationen mit Reaktionszeiten von unter einer Millisekunde, einem Durchsatz von mehreren GBit/s und mehr als 100,000 IOPS pro Datenbankinstanz in AWS zu verschieben. Der FSX Storage-Service verfügt außerdem über native Replizierungsfunktionen, mit denen Sie Ihre Oracle Datenbanken problemlos zu AWS migrieren oder Ihre geschäftskritische Oracle Datenbank zu einer sekundären AWS Verfügbarkeitszone für HA oder DR zu replizieren.

Ziel dieser Dokumentation ist es, Schritt-für-Schritt-Prozesse, Verfahren und Best Practice-Anleitungen zur Implementierung und Konfiguration einer Oracle Datenbank mit FSX Storage und einer EC2 Instanz zu liefern, die eine Performance ähnlich wie ein lokales System bietet. NetApp stellt zudem ein Automatisierungs-Toolkit bereit, das die meisten Aufgaben für die Implementierung, Konfiguration und das Management Ihres Oracle Datenbank-Workloads in der AWS Public Cloud automatisiert.

In folgendem Video erfahren Sie mehr über die Lösung und den Anwendungsfall:

link:https://www.netapp.tv/insight/details/30000?playlist_id=275&mcid=04891225598830484314259903524057913910["Modernisieren Sie Ihre Oracle-Datenbank mit Hybrid Cloud in AWS und FSX ONTAP, Part1 – Anwendungsfall und Lösungsarchitektur"^]
