---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_migration.html 
summary: Dieser Abschnitt enthält detaillierte Informationen zu Faktoren, die bei der Migration von Oracle Datenbanken von lokalen zu AWS EC2 Instanzen und FSX Storage berücksichtigt werden müssen. 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= Datenbankmigration von lokalen Systemen in die Public Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:aws_ora_fsx_ec2_mgmt.html["Früher: Datenbankmanagement."]

[role="lead"]
Die Migration der Datenbank stellt auf jeden Fall eine Herausforderung dar. Die Migration einer Oracle Datenbank von On-Premises-Systemen in die Cloud ist keine Ausnahme.

In den folgenden Abschnitten werden die wichtigsten Faktoren aufgeführt, die Sie bei der Migration von Oracle Datenbanken in die AWS Public Cloud mit AWS EC2 Computing- und FSX Storage-Plattform berücksichtigen sollten.



== ONTAP Storage ist vor Ort verfügbar

Wenn die lokale Oracle Datenbank sich auf einem ONTAP Storage Array befindet, lässt sich die Replizierung für die Datenbankmigration dank der in AWS FSX ONTAP Storage integrierten NetApp SnapMirror Technologie einfacher einrichten. Der Migrationsprozess kann über die NetApp BlueXP Konsole orchestriert werden.

. Erstellung einer EC2 Ziel-Computing-Instanz, die zur lokalen Instanz passt
. Stellen Sie passende Datenbank-Volumes gleicher Größe über die FSX-Konsole bereit.
. Mounten Sie die FSX-Datenbank-Volumes in die EC2-Instanz.
. Einrichten der SnapMirror Replizierung zwischen den lokalen Datenbank-Volumes und den FSX Ziel-Datenbank-Volumes Die erste Synchronisierung benötigt möglicherweise etwas Zeit, um die primären Quelldaten zu verschieben, aber die folgenden inkrementellen Updates sind viel schneller.
. Beenden Sie zum Zeitpunkt der Umschaltung die primäre Applikation, um alle Transaktionen zu beenden. Führen Sie über die Oracle sqlplus CLI-Schnittstelle einen Oracle Online-Protokollschalter aus und erlauben Sie SnapMirror Sync, das letzte archivierte Protokoll auf das Ziel-Volume zu übertragen.
. Untergliedern Sie die gespiegelten Volumes, führen Sie Oracle Recovery am Ziel aus und bringen Sie die Datenbank für den Service auf.
. Weisen Sie Applikationen auf die Oracle Datenbank in der Cloud zu.


Im folgenden Video wird gezeigt, wie eine Oracle Datenbank mithilfe der NetApp BlueXP Konsole und SnapMirror Replizierung von On-Premises zu AWS FSX/EC2 migriert wird.

link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8["Oracle Datenbankmigration von lokalen Systemen zu FSX/EC2 über SnapMirror und BlueXP"^]



== ONTAP Storage ist vor Ort nicht verfügbar

Wenn die lokale Oracle Datenbank auf Storage anderer Anbieter als ONTAP gehostet wird, basiert die Datenbankmigration auf dem Restore einer Backup-Kopie einer Oracle Datenbank. Sie müssen das Archivprotokoll wiedergeben, um es vor dem Umschalten aktuell zu machen.

AWS S3 kann als Staging-Storage-Bereich für das Verschieben und Migrieren von Datenbanken verwendet werden. Für diese Methode sind die folgenden übergeordneten Schritte zu beachten:

. Bereitstellung einer neuen, übereinstimmenden EC2 Instanz, die mit der lokalen Instanz vergleichbar ist
. Stellen Sie gleich große Datenbank-Volumes vom FSX Storage bereit und mounten Sie die Volumes auf die EC2 Instanz.
. Erstellen einer Oracle Backup-Kopie auf Festplattenebene
. Die Backup-Kopie kann in AWS S3 Storage verschoben werden.
. Stellen Sie die Oracle-Kontrolldatei wieder her und stellen Sie die Datenbank wieder her, indem Sie Daten und das Archivprotokoll aus dem S3-Storage ziehen.
. Synchronisieren der Oracle Zieldatenbank mit der lokalen Quelldatenbank
. Fahren Sie beim Switchover die Applikation und die Oracle Quelldatenbank herunter. Kopieren Sie die letzten paar Archivprotokolle und wenden Sie sie auf die Oracle Zieldatenbank an, um sie auf den neuesten Stand zu bringen.
. Starten Sie die Zieldatenbank für den Benutzerzugriff.
. Umleiten der Applikation zur Zieldatenbank, um die Umschaltung abzuschließen.




== Migrieren Sie lokale Oracle Datenbanken mithilfe von PDB-Verschiebungen mit maximaler Verfügbarkeit zu AWS FSX/EC2

Dieser Migrationsansatz eignet sich am besten für Oracle Datenbanken, die bereits im mandantenfähigen PDB/CDB-Modell implementiert sind. ONTAP-Storage steht vor Ort nicht zur Verfügung. Bei der Methode zur Verschiebung der PDB wird mithilfe der Oracle PDB-Technologie Hot-Clone-Datenbanken zwischen einer Quell-CDB und einer Ziel-CDB verschoben. Gleichzeitig werden Serviceunterbrechungen minimiert.

Erstellen Sie zunächst CDB in der AWS FSX/EC2 mit ausreichend Storage, um PDBs zu hosten und von lokalen Standorten aus zu migrieren. Mehrere on-Premises-PDBs können nacheinander umgezogen werden.

. Wenn die lokale Datenbank in einer einzelnen Instanz statt im mandantenfähigen PDB/CDB-Modell implementiert wird, befolgen Sie die Anweisungen in link:https://docs.netapp.com/us-en/netapp-solutions/databases/azure_ora_nfile_migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["Konvertieren einer einzelnen nicht-CDB-Instanz in eine PDB in einer mandantenfähigen CDB"^] Um die einzelne Instanz in mandantenfähige PDB/CDB zu konvertieren. Folgen Sie dann dem nächsten Schritt, um die konvertierte PDB zu CDB in AWS FSX/EC2 zu migrieren.
. Wenn die lokale Datenbank bereits im mandantenfähigen PDB/CDB-Modell implementiert ist, befolgen Sie die Anweisungen in link:https://docs.netapp.com/us-en/netapp-solutions/databases/azure_ora_nfile_migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["Migrieren Sie lokale Oracle-Datenbanken in die Cloud mit PDB-Verschiebung"^] Für die Durchführung der Migration.


Im folgenden Video wird gezeigt, wie eine Oracle Database (PDB) mithilfe von PDB-Verschiebungen mit maximaler Verfügbarkeit auf FSX/EC2 migriert werden kann.

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["Migrieren Sie die lokale Oracle PDB zu AWS CDB mit maximaler Verfügbarkeit"^]


NOTE: Obwohl die Anweisungen in Schritt 1 und 2 im Kontext der Public Cloud von Azure dargestellt werden, gelten die Verfahren für die AWS Cloud ohne Änderungen.

Das NetApp Solutions Automation Team bietet ein Migrations-Toolkit, das die Migration von Oracle Datenbanken vor Ort in die AWS Cloud erleichtert. Verwenden Sie den folgenden Befehl, um das Oracle Database Migration Toolkit für die PDB-Verschiebung herunterzuladen.

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----