---
sidebar: sidebar 
permalink: databases/db_protection_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Auf dieser Seite wird die automatisierte Methode zur Implementierung von Oracle19c auf NetApp ONTAP Storage beschrieben. 
---
= Lösungsüberblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Automatisierte Datensicherung für Oracle Datenbanken

Unternehmen automatisieren ihre Umgebungen, um die Effizienz zu steigern, Implementierungen zu beschleunigen und manuelle Aufgaben zu reduzieren. Konfigurationsmanagement-Tools wie Ansible werden zur Optimierung der Abläufe in Unternehmensdatenbanken eingesetzt. Diese Lösung zeigt, wie Sie mit Ansible die Datensicherung von Oracle mit NetApp ONTAP automatisieren können. Storage-Administratoren, Systemadministratoren und DBAs können die Datenreplizierung konsistent und schnell auf ein externes Datacenter oder in die Public Cloud einrichten. Sie profitieren von folgenden Vorteilen:

* Vermeiden Sie Designkomplexität und menschliche Fehler und implementieren Sie eine wiederholbare, konsistente Implementierung und Best Practices
* Verkürzung der Zeit für die Konfiguration von Intercluster-Replizierung, CVO Instanziation und Recovery von Oracle-Datenbanken
* Erhöhen Sie die Produktivität von Datenbank-Administratoren, -Systemen und -Storage-Administratoren
* Bietet Datenbank-Recovery-Workflow zum einfachen Testen eines DR-Szenarios.


NetApp bietet Kunden validierte Ansible-Module und -Rollen, um die Implementierung, Konfiguration und das Lifecycle-Management Ihrer Oracle-Datenbankumgebung zu beschleunigen. Diese Lösung bietet Anweisungen und Ansible-Playbook-Code, um Sie bei folgenden Aufgaben zu unterstützen:



=== Replizierung vor Ort und in On-Premises-Umgebungen

* Erstellen von Intercluster-Libs an Quelle und Ziel
* Cluster- und vServer-Peering einrichten
* SnapMirror von Oracle Volumes erstellen und initialisieren
* Erstellen Sie einen Replikationszeitplan über AWX/Tower für Oracle-Binärdateien, -Datenbanken und -Protokolle
* Stellen Sie Oracle DB auf dem Ziel wieder her und bringen Sie die Datenbank in den Online-Modus




=== Von On-Premises zu CVO in AWS

* AWS Connector erstellen
* CVO-Instanz in AWS erstellen
* Hinzufügen eines On-Premises-Clusters zu Cloud Manager
* Erstellen von Intercluster-Libs auf der Quelle
* Cluster- und vServer-Peering einrichten
* SnapMirror von Oracle Volumes erstellen und initialisieren
* Erstellen Sie einen Replikationszeitplan über AWX/Tower für Oracle-Binärdateien, -Datenbanken und -Protokolle
* Stellen Sie Oracle DB auf dem Ziel wieder her und bringen Sie die Datenbank in den Online-Modus


Weitere Informationen erhalten Sie in den Übersichtsvideos unten.



=== AWX/Tower-Implementierungen

* Teil 1: Noch ausstehend
+
Video::


* Teil 2: Noch ausstehend
+
Video:: Klicken Sie anschließend auf link:db_protection_getting_started.html["Hier sind erste Schritte mit der Lösung"].



