---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prerequisite.html 
summary: Bestimmte Voraussetzungen müssen sowohl On-Premises als auch in der Cloud konfiguriert werden, bevor die Ausführung von Hybrid-Cloud-Datenbank-Workloads ausgeführt wird. Der folgende Abschnitt bietet einen allgemeinen Überblick über diesen Prozess und die folgenden Links führen zu weiteren Informationen über die erforderliche Systemkonfiguration. 
keywords: workflow, prerequisites, licensing, networking, security 
---
= Konfiguration der Voraussetzungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_requirements.html["Früher: Lösungsanforderungen."]

Bestimmte Voraussetzungen müssen sowohl On-Premises als auch in der Cloud konfiguriert werden, bevor die Ausführung von Hybrid-Cloud-Datenbank-Workloads ausgeführt wird. Der folgende Abschnitt bietet einen allgemeinen Überblick über diesen Prozess und die folgenden Links führen zu weiteren Informationen über die erforderliche Systemkonfiguration.



== On-Premises

* Installation und Konfiguration von SnapCenter
* Storage-Konfiguration des lokalen Datenbankservers
* Lizenzierungsanforderungen
* Networking und Sicherheit
* Automatisierung




== Public Cloud

* NetApp Cloud Central Anmeldung
* Netzwerkzugriff über einen Webbrowser zu mehreren Endpunkten
* Ein Netzwerkspeicherort für einen Anschluss
* Berechtigungen für Cloud-Provider
* Vernetzung für einzelne Services


Wichtige Überlegungen:

. Wo wird der Cloud Manager Connector bereitgestellt?
. Sizing und Architektur für Cloud Volume ONTAP
. Single Node oder Hochverfügbarkeit?


Die folgenden Links bieten weitere Einzelheiten:

link:hybrid_dbops_snapcenter_prereq_onprem.html["On-Premises"]

link:hybrid_dbops_snapcenter_prereq_cloud.html["Public Cloud"]

link:hybrid_dbops_snapcenter_prereq_onprem.html["Als Nächstes: Vor Ort Voraussetzungen schaffen."]
