---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_getting_started.html 
summary: Dieser Abschnitt enthält eine Zusammenfassung der Aufgaben, die erfüllt werden müssen, um die Anforderungen zu erfüllen, wie im vorherigen Abschnitt beschrieben. Der folgende Abschnitt enthält eine allgemeine Aufgabenliste für den Betrieb am Standort sowie in der Public Cloud. Auf die detaillierten Prozesse und Verfahren kann durch Anklicken der entsprechenden Links zugegriffen werden. 
keywords: introduction, workflow 
---
= Erste Schritte – Übersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt enthält eine Zusammenfassung der Aufgaben, die erfüllt werden müssen, um die Anforderungen zu erfüllen, wie im vorherigen Abschnitt beschrieben. Der folgende Abschnitt enthält eine allgemeine Aufgabenliste für den Betrieb am Standort sowie in der Public Cloud. Auf die detaillierten Prozesse und Verfahren kann durch Anklicken der entsprechenden Links zugegriffen werden.



== On-Premises

* Einrichten des Datenbank-Admin-Benutzers in SnapCenter
* Installationsvoraussetzungen für das SnapCenter Plug-in
* SnapCenter Host Plug-in-Installation
* DB-Ressourcenerkennung
* Storage-Cluster-Peering und DB-Volume-Replizierung einrichten
* Fügen Sie die CVO Datenbank-Storage-SVM zu SnapCenter hinzu
* Backup-Richtlinie für Datenbanken in SnapCenter einrichten
* Backup-Richtlinie zum Schutz der Datenbank implementieren
* Backup validieren




== AWS Public Cloud

* Scheck vor dem Flug
* Schritte zur Implementierung von Cloud Manager und Cloud Volumes ONTAP in AWS
* Implementieren Sie EC2 Computing-Instanz für Datenbank-Workloads


Details finden Sie unter folgenden Links:

link:hybrid_dbops_snapcenter_getting_started_onprem.html["On-Premises"], link:hybrid_dbops_snapcenter_getting_started_aws.html["Public Cloud – AWS"]
