---
sidebar: sidebar 
permalink: databases/marketing_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: Auf dieser Seite wird die automatisierte Methode zur Implementierung von Oracle19c auf NetApp ONTAP Storage beschrieben. 
---
= Lösungsüberblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Automated Deployment of Oracle19c for ONTAP on NFS

Unternehmen automatisieren ihre Umgebungen, um die Effizienz zu steigern, Implementierungen zu beschleunigen und manuelle Aufgaben zu reduzieren. Konfigurationsmanagement-Tools wie Ansible werden zur Optimierung der Abläufe in Unternehmensdatenbanken eingesetzt. Diese Lösung zeigt, wie sich mit Ansible die Bereitstellung und Konfiguration von Oracle 19c mit NetApp ONTAP automatisieren lässt. Da Storage-Administratoren, Systemadministratoren und DBAs in der Lage sind, neuen Storage konsistent und schnell bereitzustellen, Datenbankserver zu konfigurieren und Oracle 19c Software zu installieren, profitieren Sie von folgenden Vorteilen:

* Vermeiden Sie Designkomplexität und menschliche Fehler und implementieren Sie eine wiederholbare, konsistente Implementierung und Best Practices
* Verkürzung der Zeit für Provisionierung von Speicher, Konfiguration von DB-Hosts sowie für Oracle-Installation
* Erhöhen Sie die Produktivität von Datenbank-Administratoren, -Systemen und -Storage-Administratoren
* Vereinfachen Sie die Skalierung von Storage und Datenbanken


NetApp bietet Kunden validierte Ansible-Module und -Rollen, um die Implementierung, Konfiguration und das Lifecycle-Management Ihrer Oracle-Datenbankumgebung zu beschleunigen. Diese Lösung bietet Anweisungen und Ansible-Playbook-Code, um Sie bei folgenden Aufgaben zu unterstützen:

* Erstellen und Konfigurieren von ONTAP-NFS-Storage für Oracle-Datenbank
* Installation von Oracle 19c auf RedHat Enterprise Linux 7/8 oder Oracle Linux 7/8
* Konfiguration von Oracle 19c auf ONTAP NFS Storage


Weitere Informationen erhalten Sie in den Übersichtsvideos unten.



=== AWX/Tower-Implementierungen

Teil 1: Erste Schritte, Anforderungen, Automatisierungsdetails und erste AWX/Tower-Konfiguration


Teil 2: Variablen und Ausführen des Playbooks




=== CLI-Implementierung

Teil 1: Erste Schritte, Anforderungen, Automatisierungsdetails und Ansible Control Host Setup


Teil 2: Variablen und Ausführen des Playbooks

