---
sidebar: sidebar 
permalink: databases/sql-srv-anf_conclusion.html 
keywords: takeaways, hybrid-cloud 
summary: Ganz gleich, ob Sie mit Stretch-Datenbanken auf eine All-Cloud oder Hybrid Cloud setzen – Azure NetApp Files bietet Ihnen hervorragende Optionen für die Implementierung und das Management von Datenbank-Workloads und reduziert gleichzeitig die TCO, da die Datenanforderungen nahtlos auf die Applikationsebene reduziert werden. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Ganz gleich, ob Sie mit Stretch-Datenbanken auf eine All-Cloud oder Hybrid Cloud setzen – Azure NetApp Files bietet Ihnen hervorragende Optionen für die Implementierung und das Management von Datenbank-Workloads und reduziert gleichzeitig die TCO, da die Datenanforderungen nahtlos auf die Applikationsebene reduziert werden.

Dieses Dokument behandelt Empfehlungen für die Planung, Entwicklung, Optimierung und Skalierung von Microsoft SQL Server Implementierungen mit Azure NetApp Files, die zwischen Implementierungen stark variieren können. Die richtige Lösung hängt sowohl von den technischen Details der Implementierung als auch von den geschäftlichen Anforderungen ab, die für das Projekt ausschlaggebend sind.



== Erkenntnisse Aus

Zu den wichtigsten Punkten dieses Dokuments gehören:

* Sie können nun Azure NetApp Files verwenden, um die Datenbank und den Dateifreigabenzeuge für das SQL Server Cluster zu hosten.
* Sie können die Reaktionszeiten von Applikationen verkürzen und eine Verfügbarkeit von 99.9999 % erzielen, um Zugriff auf SQL Server-Daten zu jeder Zeit und an jedem Ort zu ermöglichen.
* Sie können die Gesamtkomplexität der SQL Server-Bereitstellung und des fortlaufenden Managements, wie RAID-Striping, durch einfache und sofortige Anpassung vereinfachen.
* Mit intelligenten Funktionen lassen sich SQL Server Datenbanken in Minutenschnelle implementieren und Entwicklungszyklen verkürzen.
* Wenn Azure Cloud Ziel ist, ist Azure NetApp Files die richtige Storage-Lösung für eine optimierte Implementierung.

