---
sidebar: sidebar 
permalink: databases/tr-4250-link.html 
keywords:  
summary:  
---
= TR-4250: SAP with Oracle on UNIX and NFS with NetApp Clustered Data ONTAP and SnapManager for SAP 3.4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer, NetApp

TR-4250 erläutert die Herausforderungen bei der Entwicklung von Storage-Lösungen zur Unterstützung von SAP Business Suite Produkten unter Verwendung einer Oracle Database. Das Hauptaugenmerk dieses Dokuments liegt auf dem allgemeinen Bedarf an Storage-Infrastruktur-Design, -Implementierung, -Betrieb und -Management-Herausforderungen. Geschäftliche und IT-Führungskräfte stehen dabei vor der Herausforderung, die auf der neuesten Generation von SAP-Lösungen basieren. Die Empfehlungen in diesem Dokument sind allgemein, nicht spezifisch für eine SAP-Anwendung oder Größe und Umfang der SAP-Implementierung. TR-4250 geht davon aus, dass der Leser über die grundlegenden Kenntnisse der Technologie und des Betriebs der NetApp- und SAP-Produkte verfügt. TR-4250 wurde entwickelt nach dem Zusammenspiel des technischen Personals von NetApp, SAP, Oracle und unseren Kunden.

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf"^]
