---
sidebar: sidebar 
permalink: databases/tr-4722.html 
keywords:  
summary:  
---
= TR-4722: Best Practices für MySQL Datenbanken auf NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Anup Bharti, Manohar Kulkarni, Jeffrey Steiner NetApp

MySQL und seine Varianten, darunter MariaDB und Percona, sind weit verbreitet für viele Unternehmensanwendungen. Diese Anwendungen reichen von globalen Websites sozialer Netzwerke und massiven E-Commerce-Systemen bis hin zu SMB-Hosting-Systemen mit Tausenden von Datenbankinstanzen. Dieses Dokument beschreibt die Konfigurationsanforderungen und bietet Anleitung zum Tuning und zur Speicherkonfiguration für die Bereitstellung von MySQL auf NetApp® ONTAP® Datenmanagement-Software. Um zu ermitteln, ob die in diesem Bericht angegebene Umgebung, die Konfigurationen und Versionen Ihre Umgebung unterstützen, finden Sie im Interoperabilitäts-Matrix-Tool (IMT).

link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf["TR-4722: Best Practices für MySQL Datenbanken auf NetApp ONTAP"^]
