---
sidebar: sidebar 
permalink: ehc/dro/azure-dro-overview.html 
keywords: NetApp Solutions, hybrid, multicloud, multi cloud, hyperscalers, vmware, disaster recovery orchestrator, DRO 
summary:  
---
= TR-4955: Disaster Recovery with Azure NetApp Files (ANF) and Azure VMware Solution (AVS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Niyaz Mohamed, NetApp



== Überblick



== Erste Schritte



== DRO-Installation



== DRO-Konfiguration



== Vorteile

* Nutzung der effizienten und robusten SnapMirror Replizierung.
* Recovery zu jedem verfügbaren Zeitpunkt mit Aufbewahrung von Snapshot Kopien
* Vollständige Automatisierung aller erforderlichen Schritte zur Wiederherstellung von Hunderten bis Tausenden VMs in den Schritten für Storage, Computing, Netzwerk und Applikationen
* Workload Recovery mit ONTAP FlexClone Technologie mit einer Methode, bei der das replizierte Volume nicht geändert wird.
+
** Vermeidung des Risikos einer Beschädigung von Daten bei Volumes oder Snapshot Kopien
** Keine Replizierungsunterbrechungen während der DR-Test-Workflows
** Potenzielle Nutzung von DR-Daten mit Cloud-Computing-Ressourcen für Workflows über DR hinaus, wie z. B. DevTest, Sicherheitstests, Patch- oder Upgrade-Tests und Korrekturtests


* CPU- und RAM-Optimierung zur Senkung der Cloud-Kosten durch Recovery auf kleinere Computing-Cluster.

