---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html 
keywords: secure, architecture, tenancy model, identity management, control plane, security hardening, encryption, zero trust, ransomware 
summary: Cloud Volumes Service in Google Cloud bietet zahlreiche Möglichkeiten zur nativen Sicherung Ihrer Daten. 
---
= Wie Cloud Volumes Service in Google Cloud Ihre Daten sichert
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-overview.html["Zurück: Übersicht."]

Cloud Volumes Service in Google Cloud bietet zahlreiche Möglichkeiten zur nativen Sicherung Ihrer Daten.



== Sichere Architektur und Mandantenmodell

Cloud Volumes Service bietet eine sichere Architektur in Google Cloud, indem das Service-Management (Kontrollebene) und der Datenzugriff (Datenebene) über verschiedene Endpunkte segmentiert werden, sodass keine Auswirkung auf den anderen Endpunkte besteht (siehe Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html["„Cloud Volumes Service Architecture“"]). Sie verwendet Googles https://cloud.google.com/vpc/docs/private-services-access?hl=en_US["Zugang zu privaten Services"^] (PSA) Framework zur Bereitstellung des Service. In diesem Rahmen wird zwischen dem von NetApp bereitgestellten und betriebenen Service-Produzenten unterschieden. Dabei handelt es sich um eine Virtual Private Cloud (VPC) in einem Kundenprojekt, in dem die Clients gehostet werden, die auf Cloud Volumes Service-Dateifreigaben zugreifen möchten.

In dieser Architektur finden Mandanten (siehe Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html#tenancy-model["„Tenancy model“"]) Sind als Google Cloud-Projekte definiert, die vollständig voneinander getrennt sind, es sei denn, der Benutzer hat ausdrücklich eine Verbindung. Mandanten ermöglichen durch die Cloud Volumes Service Volume-Plattform die vollständige Isolierung von Daten-Volumes, externen Name Services und anderen wichtigen Lösungselementen von anderen Mandanten. Da die Cloud Volumes Service Plattform über VPC Peering verbunden ist, gilt diese Isolierung auch für die IT. Sie können die Freigabe von Cloud Volumes Service Volumes zwischen mehreren Projekten mithilfe einer gemeinsam genutzten VPC aktivieren (siehe Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html#tenancy-model#shared-vpcs["„Gemeinsame VPCs“"]). Zugriffssteuerung kann auf SMB-Freigaben und NFS-Exporte angewendet werden, um zu beschränken, wer bzw. welche Datensätze angezeigt oder geändert werden können.



== Starkes Identitätsmanagement für die Kontrollebene

In der Kontrollebene, auf der die Cloud Volumes Service-Konfiguration stattfindet, wird das Identitätsmanagement mit verwaltet https://cloud.google.com/iam/docs/overview["Identitäts-Zugriffsmanagement (Identity Access Management, IAM)"^]. IAM ist ein Standardservice, mit dem die Authentifizierung (Logins) und Autorisierung (Berechtigungen) für Google Cloud-Projektinstanzen gesteuert werden kann. Die gesamte Konfiguration erfolgt über Cloud Volumes Service APIs über einen sicheren HTTPS-Transport mithilfe der TLS 1.2-Verschlüsselung. Die Authentifizierung erfolgt über JWT-Token für zusätzliche Sicherheit. Die Google-Konsole-Benutzeroberfläche für Cloud Volumes Service übersetzt Benutzereingaben in Cloud Volumes Service-API-Aufrufe.



== Sicherheitshärtung – Begrenzung von Angriffsflächen

Ein Teil der effektiven Sicherheit ist die Begrenzung der Anzahl der Angriffsflächen, die in einem Service verfügbar sind. Angriffsflächen können eine Vielzahl von Dingen umfassen, beispielsweise Daten im Ruhezustand, Übertragungs- und Logins während der Übertragung und die Datensätze selbst.

Ein Managed Service entfernt einige Angriffsflächen inhärent in seinem Design. Infrastruktur-Management, wie im Abschnitt beschrieben link:ncvs-gc-service-operation.html["„Service-Betrieb“,"] Wird von einem dedizierten Team durchgeführt und verringert automatisch die Anzahl der Male, die ein Mensch tatsächlich bei Konfigurationen berührt, wodurch die Anzahl vorsätzlicher und unbeabsichtigter Fehler reduziert wird. Die Netzwerkumgebung ist abgezäunt, sodass nur erforderliche Services aufeinander zugreifen können. Die Verschlüsselung wird in den Datenspeicher integriert. Cloud Volumes Service Administratoren benötigen lediglich die Datenebene Sicherheitsaspekte. Wenn Sie den Großteil der Verwaltung hinter einer API-Schnittstelle verbergen, wird die Sicherheit durch Begrenzung der Angriffsflächen erreicht.



== Zero-Trust-Modell

In der Vergangenheit BESTAND DIE IT-Sicherheitsphilosophie darin, Vertrauen zu geben, zu verifizieren und zu manifestieren, dass sie sich ausschließlich auf externe Mechanismen (wie Firewalls und Intrusion Detection Systems) zur Minderung von Bedrohungen verlassen. Angriffe und Verstöße wurden jedoch entwickelt, um die Verifizierung in Umgebungen durch Phishing, Social Engineering, Bedrohungen von innen und andere Methoden zu umgehen, die die Verifizierung in Netzwerke und Verwüstung ermöglichen.

Zero Trust hat sich zu einer neuen Sicherheitsmethode entwickelt, wobei das aktuelle Mantra „Vertrauen Sie nichts, während Sie noch alles überprüfen“ ist. Daher ist standardmäßig kein Zugriff zulässig. Dieses Mantra wird auf verschiedene Arten durchgesetzt, darunter Standard-Firewalls und Intrusion Detection-Systeme (IDS) sowie folgende Methoden:

* Starke Authentifizierungsmethoden (z. B. AES-verschlüsselte Kerberos- oder JWT-Token)
* Einzelne, starke Identifikationsquellen (z. B. Windows Active Directory, Lightweight Directory Access Protocol (LDAP) und Google IAM)
* Netzwerksegmentierung und sichere Mandantenfähigkeit (standardmäßig sind nur Mandanten Zugriff erlaubt)
* Granulare Zugriffssteuerung mit den geringsten Zugriffsrichtlinien
* Kleine exklusive Listen von engagierten, vertrauenswürdigen Administratoren mit digitalen Audit- und Papiertrails


Cloud Volumes Service läuft in Google Cloud hält sich an das Zero-Trust-Modell durch die Umsetzung der "Vertrauen nichts, alles überprüfen" Haltung.



== Verschlüsselung

Verschlüsselung von Daten im Ruhezustand (siehe Abschnitt link:ncvs-gc-data-encryption-at-rest.html["„Datenverschlüsselung im Ruhezustand“"]) Mit XTS-AES-256-Chiffren mit NetApp Volume Encryption (NVE) und im Flight mit link:ncvs-gc-data-encryption-in-transit.html#nas-protocols#smb-encryption["„SMB-Verschlüsselung“"] Oder NFS Kerberos 5p-Support. Gut zu wissen, dass regionsübergreifende Replikationstransfers durch TLS 1.2-Verschlüsselung geschützt sind (siehe Abschnitt link:ncvs-gc-security-considerations-and-attack-surfaces.html#detection,-prevention-and-mitigation-of-ransomeware,-malware,-and-viruses#cross-region-replication["„Regionenübergreifende Replikation“"]). Darüber hinaus bietet Google Networking auch verschlüsselte Kommunikation (siehe Abschnitt link:ncvs-gc-data-encryption-in-transit.html["„Datenverschlüsselung während der Übertragung“"]) Für eine zusätzliche Schutzschicht gegen Angriffe. Weitere Informationen zur Transportverschlüsselung finden Sie im Abschnitt link:ncvs-gc-data-encryption-in-transit.html#google-cloud-network["„Google Cloud-Netzwerk“"].



== Datensicherung und Backups

Bei der Sicherheit geht es nicht nur um die Verhinderung von Angriffen. Es geht auch darum, wie wir nach Angriffen eine Wiederherstellung durchführen, wenn sie auftreten. Diese Strategie umfasst Datenschutz und -Backups. Cloud Volumes Service bietet Methoden zur Replizierung in andere Regionen bei Ausfällen (siehe Abschnitt link:ncvs-gc-security-considerations-and-attack-surfaces.html#detection,-prevention-and-mitigation-of-ransomeware,-malware,-and-viruses#cross-region-replication["„Regionenübergreifende Replikation“"]) Oder wenn ein Datensatz von einem Ransomware-Angriff betroffen ist. Sie kann auch asynchrone Daten-Backups von Standorten außerhalb der Cloud Volumes Service Instanz mithilfe von durchführen link:ncvs-gc-security-considerations-and-attack-surfaces.html#detection,-prevention-and-mitigation-of-ransomeware,-malware,-and-viruses#cloud-volumes-service-backup["Cloud Volumes Service-Backup"]. Mit regelmäßigen Backups kann das Abmildern von Sicherheitsereignissen Zeit in Anspruch nehmen, Geld und Aufwand für Administratoren einsparen.



== Schnelle Abwehr von Ransomware mit branchenführenden Snapshot Kopien

Zusätzlich zu Datensicherung und Backups unterstützt Cloud Volumes Service auch unveränderliche Snapshot Kopien (siehe Abschnitt link:ncvs-gc-security-considerations-and-attack-surfaces.html#detection,-prevention-and-mitigation-of-ransomeware,-malware,-and-viruses#immutable-snapshot-copies["„Unveränderliche Snapshot Kopien“"]) Von Volumes, die eine Wiederherstellung nach Ransomware-Angriffen ermöglichen (siehe Abschnitt link:ncvs-gc-service-operation.html["„Service-Betrieb“"]Innerhalb von Sekunden nach der Entdeckung des Problems und mit minimaler Unterbrechung. Die Recovery-Zeit und -Auswirkungen hängen vom Snapshot Zeitplan ab. Allerdings können Snapshot-Kopien erstellt werden, die bei Ransomware-Angriffen nur eine Stunde Deltawerte liefern. Snapshot Kopien haben nahezu unmerkliche Auswirkungen auf die Performance und Kapazitätsauslastung und stellen einen Ansatz mit niedrigem Risiko und hoher Rendite zum Schutz Ihrer Datensätze dar.

link:ncvs-gc-security-considerations-and-attack-surfaces.html["Als Nächstes: Sicherheitsüberlegungen und Angriffsflächen."]
