---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: Cloud Volumes Service legt mehrere TCP Ports für NFS- und SMB-Freigaben bereit. 
---
= Firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-data-encryption-at-rest.html["Früher: Verschlüsselung von Daten im Ruhezustand."]

[role="lead"]
Cloud Volumes Service legt mehrere TCP Ports für NFS- und SMB-Freigaben bereit:

* https://["Für NFS-Zugriff erforderliche Ports"^]
* https://["Für SMB-Zugriff erforderliche Ports"^]


Außerdem erfordern SMB, NFS mit LDAP, einschließlich Kerberos und Dual-Protokoll-Konfigurationen den Zugriff auf eine Windows Active Directory Domain. Active Directory-Verbindungen müssen sein https://["Konfiguriert"^] Pro Region. Active Directory-Domänencontroller (DC) werden mithilfe identifiziert https://["DNS-basierte DC-Erkennung"^] Verwenden der angegebenen DNS-Server. Alle zurückgegebenen Datacenter werden genutzt. Die Liste der geeigneten DCs kann durch Angabe einer Active Directory-Site beschränkt werden.

Cloud Volumes Service erreicht mit IP-Adressen aus dem CIDR-Bereich, der dem zugewiesen ist `gcloud compute address` Befehl während https://["On-Boarding the Cloud Volumes Service"^]. Sie können dieses CIDR als Quelladressen verwenden, um eingehende Firewalls für Ihre Active Directory-Domänencontroller zu konfigurieren.

Active Directory-Domänencontroller müssen https://["Legen Sie wie hier erwähnt Ports den Cloud Volumes Service-CIDRs offen"^].

link:ncvs-gc-nas-protocols_overview.html["Weiter: Übersicht über NAS-Protokolle"]
