---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-nas-protocols_overview.html 
keywords: nas, nfs, smb, cifs 
summary: 'Die NAS-Protokolle umfassen NFS (v3 und v4.1) und SMB/CIFS (2.x und 3.x). Mit diesen Protokollen ermöglicht CVS gemeinsamen Zugriff auf Daten über mehrere NAS Clients hinweg. Darüber hinaus ermöglicht Cloud Volumes Service den gleichzeitigen Zugriff auf NFS- und SMB/CIFS-Clients (Dual-Protokoll), während sämtliche Identitäts- und Berechtigungseinstellungen auf Dateien und Ordnern in den NAS-Freigaben berücksichtigt werden.' 
---
= Übersicht über NAS-Protokolle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-firewall.html["Früher: Firewall."]

Die NAS-Protokolle umfassen NFS (v3 und v4.1) und SMB/CIFS (2.x und 3.x). Mit diesen Protokollen ermöglicht CVS gemeinsamen Zugriff auf Daten über mehrere NAS Clients hinweg. Darüber hinaus ermöglicht Cloud Volumes Service den gleichzeitigen Zugriff auf NFS- und SMB/CIFS-Clients (Dual-Protokoll), während sämtliche Identitäts- und Berechtigungseinstellungen auf Dateien und Ordnern in den NAS-Freigaben berücksichtigt werden. Cloud Volumes Service unterstützt die Protokollverschlüsselung im laufenden Betrieb mit SMB-Verschlüsselung und NFS Kerberos 5p, um die höchstmögliche Sicherheit bei Datentransfers zu gewährleisten.


NOTE: Das Dual-Protokoll ist nur mit CVS-Performance verfügbar.

link:ncvs-gc-basics-of-nas-protocols.html["Weiter: Grundlagen der NAS-Protokolle."]
