---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-dual-protocol-multiprotocol.html 
keywords: access control, user mapping, permission model 
summary: Cloud Volumes Service bietet die Möglichkeit, dieselben Datensätze sowohl für SMB- als auch für NFS-Clients zu nutzen, während das Dual-Protokoll für ordnungsgemäße Zugriffsberechtigungen besteht. Dies geschieht durch die Koordinierung der Identitätszuordnung zwischen Protokollen und die Verwendung eines zentralen Backend-LDAP-Servers zur Bereitstellung der UNIX-Identitäten an Cloud Volumes Service. Sie können Windows Active Directory verwenden, um sowohl Windows- als auch UNIX-Benutzer zur Benutzerfreundlichkeit bereitzustellen. 
---
= Dual-Protokoll/Multiprotokoll
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-smb.html["Früher: SMB."]

Cloud Volumes Service bietet die Möglichkeit, dieselben Datensätze sowohl für SMB- als auch für NFS-Clients zu nutzen, ohne dass die Zugriffsberechtigungen dafür unterbrochen werden (https://cloud.google.com/architecture/partners/netapp-cloud-volumes/managing-dual-protocol-access["Dual-Protokoll"^]). Dies geschieht durch die Koordinierung der Identitätszuordnung zwischen Protokollen und die Verwendung eines zentralen Backend-LDAP-Servers zur Bereitstellung der UNIX-Identitäten an Cloud Volumes Service. Sie können Windows Active Directory verwenden, um sowohl Windows- als auch UNIX-Benutzer zur Benutzerfreundlichkeit bereitzustellen.



== Zugriffssteuerung

* *Zugriffskontrollen freigeben.* Bestimmen Sie, welche Clients und/oder Benutzer und Gruppen auf eine NAS-Freigabe zugreifen können. Für NFS kontrollieren Exportrichtlinien und Regeln den Client-Zugriff auf Exporte. NFS-Exporte werden von der Cloud Volumes Service Instanz gemanagt. SMB nutzt CIFS/SMB-Freigaben und ACLs für die Freigabe von ACLs und ermöglicht eine granularere Kontrolle auf Benutzer- und Gruppenebene. Sie können ACLs auf Share-Ebene nur über SMB-Clients konfigurieren https://library.netapp.com/ecmdocs/ECMP1401220/html/GUID-C1772CDF-8AEE-422B-AB87-CFCB7E50FF94.html["MMC/Computer-Management"^] Mit einem Konto, das über Administratorrechte auf der Cloud Volumes Service-Instanz verfügt (siehe Abschnitt link:ncvs-gc-smb.html#accounts-with-local/builtin-administrator/backup-rights["„Konten mit lokalen/BUILTIN-Administrator/Backup-Rechten.“"]).
* *Dateizugriffssteuerung.* Kontrollieren Sie Berechtigungen auf Datei- oder Ordnerebene und werden immer vom NAS-Client verwaltet. NFS Clients können die traditionellen Modus-Bits (rwx) oder NFSv4 ACLs nutzen. SMB-Clients nutzen NTFS-Berechtigungen.


Die Zugriffssteuerung für Volumes, die Daten sowohl für NFS als auch für SMB bereitstellen, hängt vom verwendeten Protokoll ab. Informationen zu Berechtigungen mit Dual-Protokoll finden Sie im Abschnitt „ model.“



== Benutzerzuordnung

Wenn ein Client auf ein Volume zugreift, versucht Cloud Volumes Service, den eingehenden Benutzer in die entgegengesetzte Richtung einem gültigen Benutzer zuzuordnen. Dies ist notwendig, damit ein ordnungsgemäßer Zugriff über verschiedene Protokolle hinweg festgestellt werden kann und sicherzustellen ist, dass der Benutzer, der Zugriff beantragt, tatsächlich derjenige ist, der von ihm behauptet wird.

Beispiel: Wenn ein Windows-Benutzer mit dem Namen `joe` Versucht über SMB den Zugriff auf ein Volume mit UNIX-Berechtigungen, dann führt Cloud Volumes Service eine Suche durch, um einen entsprechenden UNIX-Benutzer zu finden `joe`. Ist eine vorhanden, so werden Dateien, die als Windows Benutzer in eine SMB-Freigabe geschrieben werden `joe` Wird als UNIX-Benutzer angezeigt `joe` Von NFS-Clients.

Alternativ können Sie auch festlegen, ob ein UNIX-Benutzer den Namen hat `joe` Versucht, auf ein Cloud Volumes Service-Volume mit Windows-Berechtigungen zuzugreifen, dann muss der UNIX-Benutzer in der Lage sein, einem gültigen Windows-Benutzer zuzuordnen. Andernfalls wird der Zugriff auf das Volume verweigert.

Derzeit wird nur Active Directory für das externe UNIX-Identitätsmanagement mit LDAP unterstützt. Weitere Informationen zum Konfigurieren des Zugriffs auf diesen Dienst finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes["Erstellen einer AD-Verbindung"^].



== Berechtigungsmodell

Bei der Verwendung von Dual-Protokoll-Setups verwendet Cloud Volumes Service Sicherheitsformate für Volumes, um den Typ der ACL zu bestimmen. Diese Sicherheitsstile werden basierend auf bestimmten NAS-Protokollen oder bei einem dualen Protokoll festgelegt. Sie sollten zur Zeit der Cloud Volumes Service Volume-Erstellung gewählt werden.

* Wenn Sie nur NFS verwenden, verwenden Cloud Volumes Service-Volumes UNIX-Berechtigungen.
* Wenn Sie nur SMB verwenden, verwenden Cloud Volumes Service Volumes NTFS-Berechtigungen.


Wenn Sie ein Dual-Protokoll-Volume erstellen, können Sie bei der Volume-Erstellung den ACL-Stil wählen. Diese Entscheidung sollte auf der Grundlage der gewünschten Berechtigungsverwaltung getroffen werden. Wenn Ihre Benutzer Berechtigungen von Windows-/SMB-Clients verwalten, wählen Sie NTFS. Wenn Ihre Benutzer NFS-Clients und chmod/chown verwenden möchten, verwenden Sie UNIX-Sicherheitsmethoden.

link:ncvs-gc-considerations-creating-active-directory-connections.html["Weiter: Überlegungen zum Erstellen von Active Directory-Verbindungen."]
