---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-data-encryption-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: Alle Volumes in Cloud Volumes Service werden im Ruhezustand mit AES-256-Verschlüsselung verschlüsselt, d. h. alle auf das Medium geschriebenen Benutzerdaten werden verschlüsselt und können nur mit einem Schlüssel pro Volume entschlüsselt werden. 
---
= Verschlüsselung von Daten im Ruhezustand
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-data-encryption-in-transit.html["Früher: Datenverschlüsselung während der Übertragung."]

Alle Volumes in Cloud Volumes Service werden im Ruhezustand mit AES-256-Verschlüsselung verschlüsselt, d. h. alle auf das Medium geschriebenen Benutzerdaten werden verschlüsselt und können nur mit einem Schlüssel pro Volume entschlüsselt werden.

* Für CVS-SW werden von Google generierte Schlüssel verwendet.
* Die Schlüssel für CVS-Performance werden in einem im Cloud Volumes Service integrierten Schlüsselmanager gespeichert, der die Schlüssel pro Volume enthält.


Ab November 2021 wurde eine Vorschau auf die Funktionalität der vom Kunden gemanagten Verschlüsselungsschlüssel (CMEK) bereitgestellt. So können Sie die Schlüssel pro Volume mit einem in einzelnen Projekten und Regionen gehosteten Master-Schlüssel verschlüsseln https://cloud.google.com/kms/docs["Google Key Management Service (KMS):"^] KMS ermöglicht es Ihnen, externe Schlüsselmanager anzubinden.

Informationen zur Konfiguration von KMS für CVS-Performance finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Einrichten von vom Kunden gemanagten Verschlüsselungsschlüsseln"^].

link:ncvs-gc-firewall.html["Als Nächstes: Firewall."]
