---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-overview.html 
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition 
summary: Die Sicherheit – insbesondere in der Cloud, wo die Infrastruktur außerhalb der Kontrolle der Storage-Administratoren liegt – ist entscheidend, wenn es um die Übergabe der Daten an die von Cloud-Providern angebotenen Service-Angebote geht. Dieses Dokument bietet einen Überblick über die Sicherheitsangebote, die NetApp Cloud Volumes Service in der Google Cloud zur Verfügung stellt. 
---
= TR-4918: Sicherheitsübersicht - NetApp Cloud Volumes Service in Google Cloud
:allow-uri-read: 


Oliver Krause, Justin Parisi, NetApp



== Dokumentumfang

Die Sicherheit – insbesondere in der Cloud, wo die Infrastruktur außerhalb der Kontrolle der Storage-Administratoren liegt – ist entscheidend, wenn es um die Übergabe der Daten an die von Cloud-Providern angebotenen Service-Angebote geht. Dieses Dokument bietet einen Überblick über die Sicherheitsangebote von NetApp https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service bietet in Google Cloud"^].



== Zielgruppe

Die Zielgruppe dieses Dokuments umfasst die folgenden Rollen:

* Cloud Provider
* Storage-Administratoren
* Storage-Architekten
* Feldressourcen
* Geschäftliche Entscheidungsträger


Wenn Sie Fragen zum Inhalt dieses technischen Berichts haben, finden Sie im Abschnitt link:ncvs-gc-additional-information.html#contact-us["„Kontaktieren Sie uns.“"]

|===
| Abkürzung | Definition 


| CVS-SW | Cloud Volumes Service, Diensttyp CVS 


| CVS-Performance | Cloud Volume Service, Servicetyp CVS-Performance 


| PSA |  
|===
link:ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html["Im nächsten Schritt: Wie Cloud Volumes Service in Google Cloud Ihre Daten sichert."]
