---
sidebar: sidebar 
permalink: ehc/ncvs/ncvs-gc-security-considerations-and-attack-surfaces.html 
keywords: secure logins, cluster administration, upgrades, data at-rest, mitigation 
summary: Der erste Schritt zum Verständnis der Datensicherung besteht darin, die Risiken und potenziellen Angriffsflächen zu identifizieren. 
---
= Sicherheitsüberlegungen und Angriffsflächen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html["Wie Cloud Volumes Service in Google Cloud Ihre Daten sichert."]

Der erste Schritt zum Verständnis der Datensicherung besteht darin, die Risiken und potenziellen Angriffsflächen zu identifizieren. Dazu gehören (aber nicht beschränkt auf) die folgenden:

* Administration und Anmeldung
* Daten im Ruhezustand
* Genutzte Daten
* Netzwerk und Firewalls
* Ransomware, Malware und Viren


Das Verständnis von Angriffsflächen kann Ihnen helfen, Ihre Umgebungen besser zu schützen. Cloud Volumes Service in Google Cloud berücksichtigt bereits viele dieser Themen und implementiert Sicherheitsfunktionen standardmäßig ohne administrative Eingriffe.



== Sichere Anmeldungen sicherstellen

Bei der Sicherung Ihrer kritischen Infrastrukturkomponenten ist es von größter Wichtigkeit, sicherzustellen, dass nur genehmigte Benutzer sich einloggen und Ihre Umgebungen managen können. Wenn fehlerhafte Akteure die Anmeldedaten in Ihrem System verletzen, haben sie die Schlüssel zum Schloss und können alles tun, was sie wollen: Konfigurationen ändern, Volumes und Backups löschen, Backdoors erstellen oder Snapshot-Zeitpläne deaktivieren.

Cloud Volumes Service für Google Cloud bietet Schutz vor unautorisierten administrativen Anmeldungen durch den Ausfall von Storage als Service (StaaS). Cloud Volumes Service wird vom Cloud-Provider komplett gewartet, ohne dass eine externe Anmeldung verfügbar ist. Alle Setup- und Konfigurationsvorgänge sind vollautomatisiert, sodass ein Administrator in seltenen Fällen nie mit den Systemen interagieren muss.

Wenn Anmeldung erforderlich ist, sichert Cloud Volumes Service in Google Cloud Anmeldungen, indem eine sehr kurze Liste vertrauenswürdiger Administratoren geführt wird, die Zugriff haben, um sich bei den Systemen anzumelden. Diese Gatekeeping hilft, die Anzahl potenzieller schlechter Akteure mit Zugriff zu reduzieren. Darüber hinaus verbirgt das Google Cloud-Netzwerk die Systeme hinter Schichten der Netzwerksicherheit und legt nur das, was für die Außenwelt benötigt wird, offen. Weitere Informationen zur Google Cloud- und Cloud Volumes Service-Architektur finden Sie im Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html["„Cloud Volumes Service Architecture“."]



== Cluster-Administration und Upgrades

Zu den zwei Bereichen mit potenziellen Sicherheitsrisiken zählen die Clusterverwaltung (was passiert, wenn ein schlechter Akteur Administratorzugriff hat) und Upgrades (was passiert, wenn ein Software-Image beeinträchtigt wird).



=== Sicherung der Storage-Administration

Der als Service bereitgestellte Storage beseitigt das zusätzliche Risiko, dass Administratoren diesem Zugriff nicht mehr an Anwender außerhalb des Cloud-Datacenters ausgesetzt sind. Stattdessen gilt die einzige Konfiguration für die Datenzugriffsebene durch Kunden. Jeder Mandant managt seine eigenen Volumes, und ein Mandant kann andere Cloud Volumes Service Instanzen nicht erreichen. Der Service wird durch Automatisierung gemanagt, wobei in einer sehr kleinen Liste vertrauenswürdiger Administratoren über die im Abschnitt behandelten Prozesse Zugriff auf die Systeme gewährt wird link:ncvs-gc-service-operation.html["„Service-Betrieb“."]

Der Servicetyp CVS-Performance bietet regionenübergreifende Replizierung als Option zur Sicherung von Daten für eine andere Region bei Ausfall. In diesen Fällen kann ein Failover der Cloud Volumes Service in die nicht betroffene Region durchgeführt werden, um den Datenzugriff zu gewährleisten.



=== Service-Upgrades

Updates helfen, gefährdete Systeme zu schützen. Jedes Update bietet Verbesserungen der Sicherheit und Fehlerbehebungen zur Minimierung von Angriffsflächen. Software-Updates werden aus zentralen Repositorys heruntergeladen und validiert, bevor die Updates überprüft werden, ob offizielle Bilder verwendet werden und dass die Upgrades nicht durch fehlerhafte Akteure beeinträchtigt werden.

Mit Cloud Volumes Service werden Updates von den Cloud-Provider-Teams durchgeführt, die Risiken für Administratoren abschaffen, indem Experten versiert in Konfiguration und Upgrades sind, die den Prozess automatisiert und vollständig getestet haben. Upgrades werden unterbrechungsfrei durchgeführt und Cloud Volumes Service behält die neuesten Updates bei, um optimale Ergebnisse zu erzielen.

Informationen über das Administrator-Team, das diese Service-Upgrades durchführt, finden Sie im Abschnitt link:ncvs-gc-service-operation.html["„Service-Betrieb“."]



== Sicherheit von Daten im Ruhezustand

Die Verschlüsselung ruhender Daten ist wichtig, um sensible Daten bei Diebstahl, Rückgabe oder neuer Verwendung einer Festplatte zu schützen. Daten in Cloud Volumes Service werden mithilfe von softwarebasierter Verschlüsselung im Ruhezustand gesichert.

* Google-generierte Schlüssel werden für CVS-SW verwendet.
* Für die CVS-Performance werden die Schlüssel pro Volume in einem in Cloud Volumes Service integrierten Schlüsselmanager gespeichert, der mit NetApp ONTAP CryptoMod die AES-256-Verschlüsselung generiert. CryptoMod ist in der nach FIPS 140-2 validierten CMVP-Modulliste aufgeführt. Siehe https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144["FIPS 140-2 Zertifikat #4144"^].


Im November 2021 wurde eine Vorschau auf die Funktionalität Customer-Managed Encryption (CMEK) für CVS-Performance bereitgestellt. Diese Funktionalität ermöglicht Ihnen die Verschlüsselung der Schlüssel pro Volume mit Master-Schlüsseln für einzelne Projekte und Regionen, die im Google Key Management Service (KMS) gehostet werden. KMS ermöglicht es Ihnen, externe Schlüsselmanager anzubinden.

Details zur Konfiguration von KMS für CVS-Performance finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Weitere Informationen finden Sie in der Cloud Volumes Service-Dokumentation"^].

Weitere Informationen zur Architektur finden Sie im Abschnitt link:ncvs-gc-cloud-volumes-service-architecture.html["„Cloud Volumes Service Architecture“."]



=== Sicherheit der aktiven Daten

Sie müssen nicht nur Daten im Ruhezustand sichern, sondern auch bei laufender Übertragung zwischen der Cloud Volumes Service Instanz und einem Client oder Replizierungsziel sichern können. Cloud Volumes Service bietet Verschlüsselung von Daten auf der Übertragungsstrecke über NAS-Protokolle. Dabei kommen Verschlüsselungsmethoden wie SMB-Verschlüsselung mit Kerberos, das Signing/Sealing von Paketen und NFS Kerberos 5p für die End-to-End-Verschlüsselung von Datentransfers zum Einsatz.

Die Replizierung von Cloud Volumes Service Volumes verwendet TLS 1.2, die von AES-GCM-Verschlüsselungsmethoden profitiert.

Die unsicheres in-Flight-Protokolle wie Telnet, NDMP usw. sind standardmäßig deaktiviert. DNS ist jedoch nicht durch Cloud Volumes Service verschlüsselt (keine DNS-sec-Unterstützung) und sollte, wenn möglich, mit externer Netzwerkverschlüsselung verschlüsselt werden. Siehe Abschnitt link:ncvs-gc-data-encryption-in-transit.html["„Datenverschlüsselung während der Übertragung“"] Finden Sie weitere Informationen über die Sicherung Ihrer aktiven Daten.

Informationen zur Verschlüsselung von NAS-Protokollen finden Sie im Abschnitt link:ncvs-gc-data-encryption-in-transit.html#nas-protocols["„NAS-Protokolle“."]



== Benutzer und Gruppen für NAS-Berechtigungen

Bei der Sicherung Ihrer Daten in der Cloud ist eine ordnungsgemäße Benutzer- und Gruppenauthentifizierung erforderlich, wobei die Benutzer, die auf die Daten zugreifen, als echte Benutzer in der Umgebung überprüft werden und die Gruppen gültige Benutzer enthalten. Diese Benutzer und Gruppen bieten ersten Zugriff auf Freigabe und Export sowie Berechtigungsvalidierung für Dateien und Ordner im Speichersystem.

Cloud Volumes Service verwendet die standardmäßige, auf Active Directory basierende Windows-Benutzer- und Gruppenauthentifizierung für SMB-Freigaben und Windows-artige Berechtigungen. Der Service kann auch UNIX Identitätsanbieter wie LDAP für UNIX Benutzer und Gruppen für NFS-Exporte, NFSv4 ID-Validierung, Kerberos-Authentifizierung und NFSv4 ACLs nutzen.


NOTE: Derzeit wird mit Cloud Volumes Service nur Active Directory LDAP zur LDAP-Funktionalität unterstützt.



== Erkennung, Verhinderung und Minimierung von Ransomware, Malware und Viren

Ransomware, Malware und Viren sind für Administratoren eine persistente Bedrohung. Die Erkennung, das Vorbeugen und die Minimierung dieser Bedrohungen steht für Unternehmen immer im Mittelpunkt. Ein einzelnes Ransomware-Ereignis auf einem kritischen Datensatz kann potenziell Millionen US-Dollar kosten. Daher ist es vorteilhaft, alles zu tun, um das Risiko zu minimieren.

Obwohl Cloud Volumes Service derzeit nicht schließt native Detection oder Prävention Maßnahmen, wie Virenschutz oder https://www.netapp.com/blog/prevent-ransomware-spread-ONTAP/["Automatische Ransomware-Erkennung"^], Es gibt Möglichkeiten, nach einem Ransomware-Ereignis schnell wiederherzustellen, indem es regelmäßige Snapshot-Zeitpläne ermöglicht. Snapshot-Kopien sind unveränderliche und schreibgeschützte Verweise auf geänderte Blöcke im Filesystem, werden praktisch sofort erzeugt, haben minimale Auswirkungen auf die Performance und verbrauchen nur Speicherplatz, wenn Daten geändert oder gelöscht werden. Sie können Zeitpläne für Snapshot Kopien einrichten, die auf Ihre gewünschte akzeptable Recovery Point Objective (RPO)/Recovery Time Objective (RTO) abgestimmt sind und bis zu 1,024 Snapshot Kopien pro Volume aufbewahren.

Snapshot Support ist ohne zusätzliche Kosten enthalten (Storage-Kosten für veränderte Blöcke/Daten, die von Snapshot Kopien aufbewahrt Cloud Volumes Service werden) und kann bei einem Ransomware-Angriff genutzt werden, um ein Rollback auf eine Snapshot Kopie vor dem Angriff durchzuführen. Snapshot Wiederherstellungen dauern nur wenige Sekunden und Daten können wieder wie gewohnt bereit sein. Weitere Informationen finden Sie unter https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745["NetApp Lösung gegen Ransomware"^].

Die Auswirkungen von Ransomware auf Ihr Unternehmen zu verhindern, ist ein mehrschichtiger Ansatz erforderlich, der einen oder mehrere der folgenden Elemente umfasst:

* Endpoint-Schutz
* Schutz vor externen Bedrohungen durch Netzwerk-Firewalls
* Erkennung von Datenanomalien
* Mehrere Backups (vor Ort und extern) kritischer Datensätze
* Regelmäßige Restore-Tests von Backups
* Unveränderliche schreibgeschützte NetApp Snapshot Kopien
* Multi-Faktor-Authentifizierung für kritische Infrastrukturen
* Sicherheitsprüfungen von Systemanmeldungen


Diese Liste ist bei weitem nicht erschöpfend, aber ist eine gute Blaupause, wenn man mit dem Potential der Ransomware-Angriffe zu folgen. Cloud Volumes Service in Google Cloud bietet verschiedene Möglichkeiten zum Schutz vor Ransomware-Ereignissen und zur Reduzierung der Auswirkungen.



=== Unveränderliche Snapshot Kopien

Cloud Volumes Service bietet native unveränderliche, schreibgeschützte Snapshot Kopien, die in einem anpassbaren Zeitplan erstellt werden, um schnelle zeitpunktgenaue Recovery beim Löschen von Daten zu ermöglichen oder wenn ein gesamtes Volume durch einen Ransomware-Angriff zu Opfer gebracht wurde. Snapshots können zu vorherigen guten Snapshot Kopien schnell wiederhergestellt werden und minimieren Datenverluste aufgrund der Aufbewahrungsdauer Ihrer Snapshot-Zeitpläne und RTO/RPO. Der Performance-Effekt mit der Snapshot Technologie ist zu vernachlässigen.

Da Snapshot Kopien in Cloud Volumes Service schreibgeschützt sind, können diese nicht durch Ransomware infiziert werden, wenn die Ransomware nicht in den Datensatz „unbemerkt“ und Snapshot-Kopien der von Ransomware infizierten Daten erstellt wurde. Deshalb ist es notwendig, auf der Basis von Datenanomalien auch Ransomware-Erkennung in Betracht zu ziehen. Cloud Volumes Service bietet derzeit keine native Erkennung, Sie können jedoch externe Überwachungssoftware verwenden.



=== Backups und Restores

Cloud Volumes Service bietet standardmäßige NAS-Client-Backup-Funktionen (z. B. Backups über NFS oder SMB).

* CVS-Performance bietet regionenübergreifende Volume-Replizierung zu anderen CVS-Performance Volumes. Weitere Informationen finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/volume-replication?hl=en_US["Volume-Replizierung"^] In der Cloud Volumes Service-Dokumentation.
* CVS-SW bietet Service-native Backup-/Restore-Funktionen für Volumes. Weitere Informationen finden Sie unter https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Cloud-Backup"^] In der Cloud Volumes Service-Dokumentation.


Die Volume-Replizierung liefert eine exakte Kopie des Quell-Volumes für schnelles Failover im Falle eines Ausfalls, einschließlich Ransomware-Ereignissen.



=== Regionsübergreifende Replizierung

CVS-Performance ermöglicht die sichere Replizierung von Volumes über Google Cloud Regionen hinweg zur Datensicherung und Archivierung von Anwendungsfällen. Dazu wird mit TLS1.2 AES 256 GCM-Verschlüsselung auf einem von NetApp gesteuerten Backend-Service-Netzwerk über spezifische Schnittstellen verwendet, die für die Replizierung im Google-Netzwerk verwendet werden. Ein primäres Volume (Quell-Volume) enthält die aktiven Produktionsdaten und repliziert auf ein sekundäres Volume (Ziel-Volume), um ein exaktes Replikat des primären Datensatzes zu erstellen.

Bei der anfänglichen Replizierung werden alle Blöcke übertragen, jedoch werden nur die geänderten Blöcke in einem primären Volume übertragen. Wird beispielsweise eine Datenbank mit 1 TB auf einem primären Volume auf das sekundäre Volume repliziert, so werden bei der ersten Replizierung 1 TB Speicherplatz übertragen. Wenn diese Datenbank einige hundert Zeilen (hypothetisch einige MB) hat, die zwischen der Initialisierung und dem nächsten Update wechseln, werden nur die Blöcke mit den geänderten Zeilen auf das sekundäre (wenige MB) repliziert. So wird sichergestellt, dass die Übertragungszeiten niedrig bleiben und die Replizierungskosten sinken.

Alle Berechtigungen für Dateien und Ordner werden auf das sekundäre Volume repliziert, aber die Zugriffsberechtigungen für die Freigabe (wie Exportrichtlinien und Regeln oder SMB-Freigaben und ACLs für die Freigabe) müssen separat gehandhabt werden. Bei einem Site-Failover sollte der Zielstandort dieselben Namensdienste und Active Directory-Domänenverbindungen nutzen, um eine konsistente Handhabung von Benutzer- und Gruppenidentitäten und -Berechtigungen zu ermöglichen. Sie können ein sekundäres Volume im Notfall als Failover-Ziel verwenden, indem Sie die Replizierungsbeziehung unterbrechen, die das sekundäre Volume in Lese- und Schreibvorgänge konvertiert.

Volume-Replikate sind schreibgeschützt, d. h. eine unveränderliche Kopie der Daten an einem externen Standort zur schnellen Recovery von Daten in Instanzen, in denen ein Virus infizierte Daten hat oder Ransomware den primären Datensatz verschlüsselt hat. Nur-Lese-Daten werden nicht verschlüsselt, aber, wenn das primäre Volume betroffen ist und Replikation auftritt, die infizierten Blöcke replizieren auch. Zur Wiederherstellung können Sie ältere, nicht betroffene Snapshot Kopien verwenden. Je nachdem, wie schnell ein Angriff erkannt wird, fallen jedoch unter Umständen die versprochenen RTO/RPO-Vorgaben aus.

Darüber hinaus können Sie mit dem Management der regionsübergreifenden Replizierung (CRR) in Google Cloud böswillige Administratoraktionen, wie z. B. Volume-Löschungen, Snapshot-Löschungen oder Änderungen bei Snapshot-Planungen, verhindern. Dazu werden benutzerdefinierte Rollen erstellt, die Volume-Administratoren trennen, die Quell-Volumes löschen, aber keine Spiegelungen unterbrechen und daher keine Ziel-Volumes von CRR-Administratoren löschen können, die keine Volume-Vorgänge ausführen können. Siehe https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Überlegungen Zur Sicherheit"^] In der Cloud Volumes Service-Dokumentation finden Sie Berechtigungen, die von den einzelnen Administratorgruppen zulässig sind.



=== Cloud Volumes Service-Backup

Cloud Volumes Service bietet zwar eine hohe Datenaufbewahrung, externe Ereignisse können jedoch zu Datenverlusten führen. Falls es zu Sicherheitsereignisse wie Viren oder Ransomware kommt, werden Backups und Restores so wichtig, dass der Datenzugriff rechtzeitig wiederaufgenommen werden kann. Ein Administrator kann ein Cloud Volumes Service Volume versehentlich löschen. Oder Benutzer möchten einfach noch viele Monate Backup-Versionen ihrer Daten aufbewahren und den zusätzlichen Speicherplatz für Snapshot-Kopien innerhalb des Volumes zu einer Kostenanforderung machen. Snapshot-Kopien sollten die bevorzugte Methode sein, Backup-Versionen für die letzten Wochen zu behalten, um verlorene Daten von ihnen wiederherzustellen, sie befinden sich jedoch im Volume und gehen verloren, wenn das Volume entfernt wird.

Aus allen diesen Gründen bietet NetApp Cloud Volumes Service Backup-Services über an https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Cloud Volumes Service-Backup"^].

Cloud Volumes Service Backup erzeugt eine Kopie des Volumes auf Google Cloud Storage (GCS). Es sichert nur die tatsächlichen Daten, die innerhalb des Volume gespeichert sind, nicht den freien Speicherplatz. Es funktioniert wie immer inkrementell, d. h., es überträgt den Volume-Inhalt einmal und von dort auf wird nur geänderte Daten gesichert. Im Vergleich zu klassischen Backup-Konzepten mit mehreren vollständigen Backups spart das Unternehmen viel Storage und senkt dadurch die Kosten. Da der monatliche Preis von Backup-Speicherplatz im Vergleich zu einem Volume niedriger ist, ist es der ideale Ort, um Backup-Versionen länger zu halten.

Benutzer können ein Cloud Volumes Service Backup verwenden, um jede Backup-Version auf demselben oder einem anderen Volume innerhalb derselben Region wiederherzustellen. Wenn das Quell-Volume gelöscht wird, werden die Backup-Daten aufbewahrt und müssen unabhängig gemanagt werden (beispielsweise gelöscht).

Cloud Volumes Service Backup ist optional in Cloud Volumes Service integriert. Benutzer legen fest, welche Volumes gesichert werden sollen, indem Cloud Volumes Service Backup für einzelne Volumes aktiviert wird. Siehe https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Cloud Volumes Service Backup-Dokumentation"^] Weitere Informationen zu Backups finden Sie im https://cloud.google.com/architecture/partners/netapp-cloud-volumes/resource-limits-quotas?hl=en_US["Anzahl der maximal unterstützten Backup-Versionen"^], Planung, und https://cloud.google.com/architecture/partners/netapp-cloud-volumes/costs?hl=en_US["Preisgestaltung"^].

Alle Backup-Daten eines Projekts werden innerhalb eines GCS-Buckets gespeichert, der durch den Service gemanagt wird und für den Benutzer nicht sichtbar ist. Jedes Projekt verwendet einen anderen Bucket. Derzeit befinden sich die Buckets im gleichen Bereich wie die Cloud Volumes Service Volumes, es werden jedoch noch weitere Optionen erläutert. In der Dokumentation finden Sie den aktuellen Status.

Der Datentransport von einem Cloud Volumes Service-Bucket zu GCS nutzt Service-interne Google-Netzwerke mit HTTPS und TLS1.2. Die Daten werden im Ruhezustand mit von Google gemanagten Schlüsseln verschlüsselt.

Um Cloud Volumes Service-Backups zu managen (Backups erstellen, löschen und wiederherstellen), muss ein Benutzer über die verfügen https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["Rollen/netappCloudVolumes.admin"^] Rolle:

link:ncvs-gc-architecture_overview.html["Weiter: Architekturübersicht."]
