---
sidebar: sidebar 
permalink: ehc/azure/azure-avs.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= NetApp Funktionen für Azure AVS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Erfahren Sie mehr über die Funktionen, die NetApp in die Azure VMware Lösung (AVS) bietet: Von NetApp als Storage-Gerät mit Anbindung an den Gast oder über einen zusätzlichen NFS Datastore für die Migration von Workflows, über Erweiterung/Bursting in die Cloud, Backup/Wiederherstellung und Disaster Recovery.

Springen Sie zum Abschnitt zum gewünschten Inhalt, indem Sie eine der folgenden Optionen auswählen:

* link:#config["AVS wird in Azure konfiguriert"]
* link:#datastore["NetApp Storage-Optionen für AVS"]
* link:#solutions["NetApp/VMware Cloud-Lösungen"]




== AVS wird in Azure konfiguriert

Wie bei lokalen Systemen ist die Planung einer Cloud-basierten Virtualisierungsumgebung eine entscheidende Voraussetzung für eine erfolgreiche, sofort einsatzbereite Umgebung zum Erstellen von VMs und Migrationen.

In diesem Abschnitt wird beschrieben, wie Sie Azure VMware Lösung einrichten und managen und in Kombination mit den verfügbaren Optionen für die Verbindung von NetApp Storage verwenden.


NOTE: Der in-Guest-Speicher ist die einzige unterstützte Methode zur Verbindung von Cloud Volumes ONTAP mit Azure VMware-Lösung.

Der Einrichtungsvorgang kann in die folgenden Schritte unterteilt werden:

* Registrieren Sie den Ressourcenanbieter und erstellen Sie eine Private Cloud
* Stellen Sie eine Verbindung zu einem neuen oder vorhandenen virtuellen ExpressRoute Netzwerk-Gateway her
* Netzwerkverbindung validieren und auf Private Cloud zugreifen


Details anzeigen link:azure-setup.html["Konfigurationsschritte für AVS"].



== NetApp Storage-Optionen für AVS

NetApp Storage kann innerhalb von Azure AVS auf verschiedene Arten genutzt werden – entweder als angebundenen oder als zusätzlicher NFS-Datenspeicher.

Besuchen Sie link:../ehc-support-configs.html["Unterstützte NetApp Storage-Optionen"] Finden Sie weitere Informationen.

Azure unterstützt NetApp Storage in den folgenden Konfigurationen:

* Azure NetApp Files (ANF) als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Azure NetApp Files (ANF) als zusätzlicher NFS-Datastore


Details anzeigen link:azure-guest.html["Gastanbindung Speicheroptionen für AVS"]. Details anzeigen link:azure-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für AVS"].



== Anwendungsfälle Für Lösungen

Mit Cloud-Lösungen von NetApp und VMware können viele Anwendungsfälle problemlos in Azure AVS implementiert werden. se-Fälle werden für jeden der von VMware definierten Cloud-Bereiche definiert:

* Schutz (sowohl Disaster Recovery als auch Backup/Restore)
* Erweitern
* Migrieren


link:azure-solutions.html["Die NetApp Lösungen für Azure AVS"]
