---
sidebar: sidebar 
permalink: ehc/aws/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= NetApp Funktionen für AWS VMC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Erfahren Sie mehr über die Funktionen, die NetApp für die AWS VMware Cloud (VMC) zur Verfügung stellt – von NetApp als Storage-Gerät mit Gastverbunden oder als zusätzlicher NFS-Datastore für die Migration von Workflows, Erweiterung/Bursting in die Cloud, Backup/Wiederherstellung und Disaster Recovery.

Springen Sie zum Abschnitt zum gewünschten Inhalt, indem Sie eine der folgenden Optionen auswählen:

* link:#config["Konfiguration von VMC in AWS"]
* link:#datastore["NetApp Storage-Optionen für VMC"]
* link:#solutions["NetApp/VMware Cloud-Lösungen"]




== Konfiguration von VMC in AWS

Wie bei lokalen Systemen ist die Planung einer Cloud-basierten Virtualisierungsumgebung eine entscheidende Voraussetzung für eine erfolgreiche, sofort einsatzbereite Umgebung zum Erstellen von VMs und Migrationen.

In diesem Abschnitt wird beschrieben, wie Sie VMware Cloud auf AWS SDDC einrichten und managen und es in Kombination mit den verfügbaren Optionen zur Verbindung von NetApp Storage nutzen.


NOTE: Der in-Guest Storage ist die einzige unterstützte Methode zur Verbindung von Cloud Volumes ONTAP mit AWS VMC.

Der Einrichtungsvorgang kann in die folgenden Schritte unterteilt werden:

* Implementieren und Konfigurieren von VMware Cloud für AWS
* Verbinden Sie VMware Cloud mit FSX ONTAP


Details anzeigen link:aws-setup.html["Konfigurationsschritte für VMC"].



== NetApp Storage-Optionen für VMC

NetApp Storage kann innerhalb der AWS VMC auf verschiedene Arten genutzt werden – entweder als angebundenen oder als zusätzlicher NFS-Datenspeicher.

Besuchen Sie link:../ehc-support-configs.html["Unterstützte NetApp Storage-Optionen"] Finden Sie weitere Informationen.

AWS unterstützt NetApp Storage in den folgenden Konfigurationen:

* FSX ONTAP als Storage mit Gastverbunden
* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* FSX ONTAP als zusätzlichen NFS-Datastore


Details anzeigen link:aws-guest.html["Storage-Optionen für VMC für Gastverbindung"]. Details anzeigen link:aws-native-nfs-datastore-option.html["Zusätzliche NFS-Datastore-Optionen für VMC"].



== Anwendungsfälle Für Lösungen

Mit Cloud-Lösungen von NetApp und VMware sind viele Anwendungsfälle einfach in AWS VMC zu implementieren. Anwendungsfälle sind für jeden der von VMware definierten Cloud-Bereiche definiert:

* Schutz (sowohl Disaster Recovery als auch Backup/Restore)
* Erweitern
* Migrieren


link:aws-solutions.html["NetApp Lösungen für AWS VMC"]
