---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-snapcenter-overview.html 
keywords: overview, dr, snapcenter, data replication, snapmirror 
summary: In dieser Lösung bietet SnapCenter applikationskonsistente Snapshots für SQL Server und Oracle Applikationsdaten. Diese Konfiguration sorgt in Kombination mit der SnapMirror Technologie für ultraschnelle Datenreplizierung zwischen unserem lokalen AFF und FSX ONTAP Cluster. Darüber hinaus bietet Veeam Backup & Replication Backup- und Restore-Funktionen für unsere Virtual Machines. 
---
= Übersicht - Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-cloud-backup-tools.html["Früher: Cloud-Backup-Tools."]

In dieser Lösung bietet SnapCenter applikationskonsistente Snapshots für SQL Server und Oracle Applikationsdaten. Diese Konfiguration sorgt in Kombination mit der SnapMirror Technologie für ultraschnelle Datenreplizierung zwischen unserem lokalen AFF und FSX ONTAP Cluster. Darüber hinaus bietet Veeam Backup & Replication Backup- und Restore-Funktionen für unsere Virtual Machines.

In diesem Abschnitt werden die Konfiguration von SnapCenter, SnapMirror und Veeam für Backups und auch für Restores erläutert.

In den folgenden Abschnitten werden die Konfiguration und die erforderlichen Schritte zum Abschluss eines Failover am sekundären Standort behandelt:

* Konfiguration von SnapMirror und Aufbewahrungszeitplänen (Sekundär-Storage)
* Implementieren und konfigurieren Sie Windows SnapCenter Server vor Ort.
* Veeam Backup & Replication Server vor Ort implementieren und konfigurieren
* Cloud-Backup-Tools, SnapCenter und Veeam implementieren und konfigurieren
* Backup von SnapCenter Datenbanken für Disaster Recovery.
* SnapCenter Datenbank-Restore an einem sekundären Standort
* Wiederherstellung der Virtual Machines von Applikationen mit Veeam Backup & Replication
* Stellen Sie SQL Server Applikationsdaten wieder her.
* Stellen Sie Oracle Applikationsdaten wieder her.


link:aws-guest-dr-config-snapmirror.html["Weiter: SnapMirror Beziehungen und Aufbewahrungszeitpläne konfigurieren."]
