---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-tools.html 
keywords: deployment, backup tools, snapcenter server, Veeam server, 
summary: Für das Failover unserer Applikations-VMs und Datenbank-Volumes auf VMware Cloud Volume Services unter AWS musste eine laufende Instanz von SnapCenter Server sowie Veeam Backup and Replication Server installiert und konfiguriert werden. Nach Abschluss des Failover müssen diese Tools auch so konfiguriert werden, dass sie den normalen Backup-Betrieb fortsetzen, bis ein Failback zum lokalen Datacenter geplant und ausgeführt wird. 
---
= Cloud-Backup-Tools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-compute.html["Früher: Computing."]

Für das Failover unserer Applikations-VMs und Datenbank-Volumes auf VMware Cloud Volume Services unter AWS musste eine laufende Instanz von SnapCenter Server sowie Veeam Backup and Replication Server installiert und konfiguriert werden. Nach Abschluss des Failover müssen diese Tools auch so konfiguriert werden, dass sie den normalen Backup-Betrieb fortsetzen, bis ein Failback zum lokalen Datacenter geplant und ausgeführt wird.



== Implementierung von Backup-Tools

Der SnapCenter-Server und der Veeam Backup & Replication Server können im VMware Cloud SDDC installiert werden oder auf EC2 Instanzen in einer VPC mit Netzwerkkonnektivität zur VMware Cloud Umgebung installiert werden.



=== SnapCenter Server

Die SnapCenter Software ist über die NetApp Support Site erhältlich und kann auf Microsoft Windows Systemen installiert werden, die sich entweder in einer Domäne oder einer Arbeitsgruppe befinden. Ein detaillierter Planungsleitfaden und Installationsanweisungen finden Sie unter link:https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["NetApp Dokumentationszentrum"^].

Die Software von SnapCenter finden Sie unter https://mysupport.netapp.com["Dieser Link"^].



=== Veeam Backup & Replication Server

Sie können den Veeam Backup & Replication Server auf einem Windows-Server in VMware Cloud auf AWS oder einer EC2-Instanz installieren. Eine detaillierte Anleitung zur Implementierung finden Sie im https://www.veeam.com/documentation-guides-datasheets.html["Technische Dokumentation Des Veeam Help Center"^].



== Backup-Tools und -Konfiguration

Nach der Installation müssen SnapCenter und Veeam Backup & Replication konfiguriert werden, um die notwendigen Aufgaben zur Wiederherstellung von Daten in VMware Cloud auf AWS auszuführen.



=== SnapCenter-Konfiguration

Zum Wiederherstellen von Applikationsdaten, die auf FSX ONTAP gespiegelt wurden, müssen Sie zuerst eine vollständige Wiederherstellung der lokalen SnapCenter-Datenbank durchführen. Nach Abschluss dieses Prozesses wird die Kommunikation mit den VMs wieder hergestellt, und Backups von Applikationen können nun mithilfe von FSX ONTAP als Primärspeicher wieder aufgenommen werden.

Eine Liste der Schritte, die auf dem SnapCenter-Server in AWS ausgefüllt werden sollen, finden Sie im Abschnitt link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-windows-snapcenter-server["Implementieren Sie sekundären Windows SnapCenter-Server"].



=== Konfiguration von Veeam Backup & Replication

Zum Wiederherstellen von Virtual Machines, die auf Amazon S3 Storage gesichert wurden, muss Veeam Server auf einem Windows-Server installiert und für die Kommunikation mit VMware Cloud, FSX ONTAP und dem S3-Bucket konfiguriert werden, der das ursprüngliche Backup-Repository enthält. Darüber hinaus muss auf FSX ONTAP ein neues Backup Repository konfiguriert werden, um nach der Wiederherstellung neue Backups der VMs durchzuführen.

Eine vollständige Liste der Schritte, die zum vollständigen Failover der Applikations-VMs erforderlich sind, finden Sie im Abschnitt link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-veeam-backup-&-replication-server["Bereitstellung sekundärer Veeam Backup  Amp; Replication Server"].

link:aws-guest-dr-snapcenter-overview.html["Als Nächstes: Überblick - Disaster Recovery."]
