---
sidebar: sidebar 
permalink: vmware/netapp-vsphere8.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= NetApp Unterstützung für vSphere 8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Partnerschaft von NetApp und VMware ist die einzige Partnerschaft, in der ein einziges Storage-System alle wichtigen Nutzungsfälle erfüllt, die durch VMware definiert wurden.



== Moderner All-Flash mit Cloud-Integration für vSphere 8

ONTAP Implementierungen werden auf verschiedenen Plattformen ausgeführt, z. B. von NetApp entwickelte Appliances, Standard-Hardware und in der Public Cloud. ONTAP bietet Unified Storage für den Zugriff über SAN- oder NAS-Protokolle und in Konfigurationen, von Hochgeschwindigkeits-Flash über kostengünstigere Medien bis hin zu Cloud-basiertem Storage. NetApp bietet auch speziell entwickelte Flash-Plattformen, die Ihre Storage-Anforderungen ohne Datensilos vereinfachen und in Segmente stellen. Darüber hinaus bietet NetApp Software, die das Verschieben von Daten zwischen On-Premises-Systemen und der Cloud ermöglicht. NetApp BlueXP bietet eine einzige Konsole für das Management all dieser Beziehungen und Ihres Storage-Platzbedarfs.

* link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["NetApp Plattformen"]
* link:../ehc/index.html["NetApp Hybrid-Multi-Cloud mit VMware Lösungen"]

