---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Bereitstellung der VCF-Umgebung mit Principal Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP Storage ist eine ideale Storage-Lösung für das Management von VMware Cloud Foundation (VCF) und VI-Workload-Domänen. Sie bietet hohe Performance, Skalierbarkeit, erweitertes Datenmanagement und nahtlose Integration und trägt somit zu einer höheren betrieblichen Effizienz und Datensicherung bei.

In den folgenden Lösungen finden Sie die technischen Details zur Bereitstellung einer VCF-Umgebung in der entsprechenden Domäne und mit dem entsprechenden Protokoll.

* link:vmw-vcf-mgmt-principal-fc.html["Management-Domäne mit FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Management Domain mit NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Virtual Infrastructure Workload Domain mit FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Virtual Infrastructure Workload Domain mit NFS"]

