---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-supplemental-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS auf FC als zusätzlicher Speicher für VI-Workloads und Managementdomänen mit ONTAP-Tools für VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Szenario wird die Implementierung von VMFS Datastores mit einem Fibre Channel Back-End (FC) für Management- und Workload-Domänen mit ONTAP Tools demonstriert.



== Vorteile von Fibre Channel

*High Performance:* FC bietet Hochgeschwindigkeits-Datenübertragungsraten, wodurch es ideal für Anwendungen ist, die schnellen und zuverlässigen Zugriff auf große Datenmengen benötigen.

*Niedrige Latenz:* sehr niedrige Latenz, die für Performance-kritische Anwendungen wie Datenbanken und virtualisierte Umgebungen entscheidend ist.

*Zuverlässigkeit:* FC-Netzwerke sind bekannt für ihre Robustheit und Zuverlässigkeit, mit Features wie integrierter Redundanz und Fehlerkorrektur.

*Dedicated Bandwidth:* FC stellt dedizierte Bandbreite für Speicherdatenverkehr zur Verfügung, wodurch das Risiko von Netzwerküberlastung verringert wird.

Weitere Informationen zur Verwendung von Fibre Channel mit NetApp-Speichersystemen finden Sie unter https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["SAN-Provisionierung mit FC"].



== Szenarioübersicht

Der VCF Supplemental Datastore wird im Rahmen von Day-2 Operations mit vCenter bereitgestellt. Dieses Szenario umfasst die folgenden grundlegenden Schritte:

* Bereitstellung von ONTAP-Tools auf Managementdomäne
* Registrieren Sie vCenter Server mit VI-Workloads in ONTAP Tools
* Definieren Sie das Storage Back-End auf dem ONTAP Tools Plug-in für VMware vSphere
* Bereitstellung von VMFS auf FC-Transport




== Voraussetzungen

Dieses Szenario erfordert die folgenden Komponenten und Konfigurationen:

* Ein ONTAP AFF oder ASA Storage-System mit mit FC-Ports, die mit FC-Switches verbunden sind.
* SVM wurde mit FC-Leben erstellt.
* VSphere mit FC HBAs, die mit FC-Switches verbunden sind.
* Das Zoning für ein einzelnes Initiator-Ziel ist auf FC-Switches konfiguriert.
+

NOTE: Nutzen Sie die logische SVM-FC-Schnittstelle in der Zonenkonfiguration statt physischer FC-Ports in ONTAP Systemen.



NetApp empfiehlt Multipath für FC LUNs.

Umfassende Informationen zur Konfiguration von Fibre Channel auf ONTAP-Speichersystemen finden Sie https://docs.netapp.com/us-en/ontap/san-management/index.html["SAN-Storage-Management"] in der Dokumentation zu ONTAP 9.

Weitere Informationen zur Verwendung von VMFS mit ONTAP-Speichersystemen finden Sie im https://docs.netapp.com/us-en/netapp-solutions/vmware/vmfs-deployment.html["Implementierungsleitfaden für VMFS"].



== Implementierungsschritte für VI-Workload-Domänen

Um ONTAP Tools zu implementieren und sie zum Erstellen eines VMFS Datenspeichers in der VCF VI Workload-Domäne zu verwenden, führen Sie die folgenden Schritte aus:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Registrieren Sie VI-Workload vCenter, um das vCenter Plug-in zu aktivieren"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Storage-Backend mit vSphere Client-Schnittstelle definieren"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["Stellen Sie VMFS auf FC bereit"]




== Weitere Informationen

Informationen zum Konfigurieren von ONTAP-Speichersystemen finden Sie im link:https://docs.netapp.com/us-en/ontap["ONTAP 9-Dokumentation"] Zentrieren.

Informationen zum Konfigurieren von VCF finden Sie unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Dokumentation zu VMware Cloud Foundation"].



== Video-Demo für diese Lösung

.VMFS(FC) Datastore als ergänzender Speicher für VCF Management Domain
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]