---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= Hochverfügbarkeit mit VMware vSphere Metro Storage Cluster (vMSC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP Hochverfügbarkeit ist in VMware vSphere Metro Storage Cluster (vMSC) integriert und stellt eine robuste Lösung für das Management von VMware Cloud Foundation (VCF) und VI-Workload-Domänen dar.

Diese Kombination gewährleistet eine kontinuierliche Datenverfügbarkeit, nahtloses Failover und Disaster Recovery über geografisch verteilte Standorte hinweg und verbessert so die Ausfallsicherheit und betriebliche Kontinuität für kritische Workloads. SnapMirror Active Sync: Ermöglicht Business-Services auch bei einem vollständigen Standortausfall den Betrieb weiter und unterstützt Applikationen bei einem transparenten Failover mithilfe einer sekundären Kopie. Für die Auslösung eines Failover mit SnapMirror Active Sync sind keine manuellen Eingriffe oder benutzerdefinierten Skripts erforderlich.

Weitere Details finden Sie in den folgenden Lösungen.

* link:vmw-vcf-vmsc-mgmt-smas.html["Stretch-Cluster für Management-Domain unter Verwendung von SnapMirror Active Sync"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["Stretch-Cluster für die Verwaltungsdomäne mit MetroCluster"]
* link:vmw-vcf-vmsc-viwld-smas.html["Stretch Cluster für VI Workload Domain unter Verwendung der aktiven SnapMirror Synchronisierung"]
* link:vmw-vcf-vmsc-viwld-mcc.html["Stretch-Cluster für VI-Workload-Domäne mithilfe von MetroCluster"]

