---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= Hybrid-Multi-Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Hybrid-Multi-Cloud-Architekturen mit NetApp ermöglichen eine nahtlose Integration zwischen On-Premises-Infrastruktur und Public-Cloud-Services, indem sie Flexibilität und Skalierbarkeit bieten.



== Einführung

Dieser Ansatz ermöglicht Unternehmen, Workloads problemlos zu migrieren, die Ressourcenauslastung zu optimieren und für einen konsistenten Betrieb über beide Umgebungen hinweg zu sorgen.

Weitere Informationen zu Hybrid-Cloud-Szenarien mit VMware und NetApp finden Sie unter link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["Überblick über NetApp Hybrid-Multi-Cloud mit VMware"].



== VMware-Implementierungsszenarien mit NetApp

In diesem Abschnitt werden verschiedene Implementierungsoptionen für VMware-Umgebungen in lokalen und Public Clouds beschrieben. Jeder der Cloud-Provider unterstützt ein VMware SDDC (Software Defined Data Center) und/oder VMware Cloud Foundation (VCF) Stack in ihren jeweiligen Public-Cloud-Angeboten.

* *VMware on-premises*


Die lokale Nutzung von VMware mit NetApp bietet eine robuste, skalierbare und flexible Virtualisierungsumgebung. Durch die Kombination der erweiterten Datenmanagement-Funktionen von NetApp wie Deduplizierung, Komprimierung und effiziente Snapshots mit dem passenden Storage-System mit ONTAP können Kunden die Plattform wählen, die ihren Anforderungen gerecht wird. Diese Kombination sorgt für hohe Performance, Zuverlässigkeit und vereinfachtes Management für virtualisierte Workloads und verbessert so die Datacenter-Effizienz insgesamt.

* *Azure-VMware-Lösung*


Azure VMware Lösung ist ein Hybrid-Cloud-Service, der VMware SDDC innerhalb der Public Cloud Microsoft Azure vollständig nutzt. Azure VMware Solution ist eine Komplettlösung, die vollständig von Microsoft gemanagt und unterstützt wird und die von VMware unter Verwendung der Azure Infrastruktur verifiziert wurde. Das heißt, Unternehmen können bei der Implementierung der Azure VMware Lösung ESXi für Computing-Virtualisierung nutzen, vSAN für hyperkonvergenten Storage. NSX für Networking und Sicherheit, gleichzeitig aber auch die globale Präsenz von Microsoft Azure, erstklassige Datacenter-Einrichtungen und die Nähe zum umfassenden Ecosystem aus nativen Azure-Services und -Lösungen.

* *VMware Cloud on AWS*


VMware Cloud auf AWS ermöglicht die Software SDDC der Enterprise-Klasse von VMware in der AWS Cloud mit optimiertem Zugriff auf native AWS Services. VMware Cloud auf AWS basiert auf VMware Cloud Foundation und integriert die Computing-, Storage- und Netzwerkvirtualisierungsprodukte von VMware (VMware vSphere, VMware vSAN und VMware NSX) in Kombination mit dem VMware vCenter Server-Management, das für die Ausführung auf einer dedizierten, flexiblen Bare-Metal-Infrastruktur von AWS optimiert ist.

* *Google Cloud VMware Engine*


Google Cloud VMware Engine ist ein IaaS-Angebot (Infrastruktur als Service), das auf der äußerst performanten, skalierbaren Infrastruktur von Google Cloud und dem VMware Cloud Foundation Stack basiert – VMware vSphere, vCenter, vSAN und NSX-T. dieser Service eröffnet einen schnellen Weg in die Cloud und ermöglicht die nahtlose Migration oder Erweiterung vorhandener VMware-Workloads von On-Premises-Umgebungen zur Google Cloud Platform – ohne die Kosten, den Aufwand oder das Risiko, Applikationen neu oder Tools einzurichten. Es handelt sich um einen Service, der von Google vertrieben und unterstützt wird und eng mit VMware zusammenarbeitet.
