---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-sc.html 
keywords: vmware, vcf, protect, snapcenter 
summary:  
---
= Schützen Sie Workloads mit SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in für VMware vSphere verbessert die VMware Cloud Foundation durch Vereinfachung von Backup und Recovery, Gewährleistung applikationskonsistenter Backups und Optimierung des Storage-Systems durch die Effizienztechnologien von NetApp.

Es unterstützt automatisierte Workflows und skalierbare Abläufe und ermöglicht eine nahtlose Integration mit dem vSphere Client. SnapMirror Replizierung liefert sekundäres Backup lokal oder in der Cloud. Damit bietet sie robuste Datensicherung und betriebliche Effizienz in virtualisierten Umgebungen.

Weitere Details finden Sie in den folgenden Lösungen.

* link:vmw-vcf-scv-wkld.html["Schutz der VCF Workload Domain"]
* link:vmw-vcf-scv-multiwkld.html["Sicherung mehrerer VCF Workload-Domänen"]
* link:vmw-vcf-scv-nvme.html["Schutz von VCF Workload Domain durch NVMe"]
* link:vmw-vcf-scv-321.html["3-2-1 Datensicherung für VMware mit SnapCenter Plug-in und BlueXP Backup und Recovery für VMs"]

