---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary:  
---
= Erweitern Sie die VCF-Umgebung um zusätzlichen Speicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation (VCF) unterstützt eine Vielzahl zusätzlicher Storage-Optionen zur Erweiterung von Storage auf VCF-Management- und VI-Workload-Domänen.

Die ONTAP Tools für VMware vSphere von NetApp bieten eine effiziente Lösung für diese Erweiterung, indem NetApp Storage nahtlos in die VCF Umgebung integriert wird. ONTAP Tools vereinfachen die Einrichtung und das Management von Datastores, sodass Administratoren Storage direkt über den vSphere Client bereitstellen und managen können. Erweiterte Funktionen von ONTAP wie Snapshots, Klonen und Datensicherung zur Verbesserung der Storage-Performance, Effizienz und Skalierbarkeit innerhalb der VCF-Umgebung

Technische Details zur Erweiterung der VCF-Umgebung finden Sie in den folgenden Lösungen.

* link:vmw-vcf-mgmt-supplemental-iscsi.html["Management-Domain mit iSCSI"]
* link:vmw-vcf-mgmt-supplemental-fc.html["Management-Domäne mit FC"]
* link:vmw-vcf-viwld-supplemental-vvols.html["Virtual Infrastructure Workload Domain mit VVols (iSCSI)"]
* link:vmw-vcf-viwld-supplemental-nfs-vvols.html["Virtual Infrastructure Workload Domain mit VVols (NFS)"]
* link:vmw-vcf-viwld-supplemental-nvme.html["Workload-Domäne der virtuellen Infrastruktur mit NVMe/TCP"]
* link:vmw-vcf-viwld-supplemental-fc.html["Virtual Infrastructure Workload Domain mit FC"]

