---
sidebar: sidebar 
permalink: vmware/vmw-vcf-migrate.html 
keywords: vmware, vcf, migrate, import 
summary:  
---
= Migrieren Sie Ihre vorhandene Infrastruktur zu VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei der Konvertierung einer vSphere Umgebung mit vorhandenen Datastores, die auf ONTAP ausgeführt werden, in eine VMware Cloud Foundation (VCF) Umgebung wird die vorhandene Infrastruktur in eine moderne Private Cloud-Architektur integriert.

Dieser Prozess nutzt die Flexibilität von ONTAP Storage für nahtlosen Datenzugriff und -Management. Sobald die VCF-Management-Domäne eingerichtet ist, können Administratoren zusätzliche vSphere-Umgebungen effizient in das VCF-Ecosystem importieren. Diese Integration verbessert die Ressourcenauslastung, vereinfacht das Private Cloud-Management und sorgt für einen reibungslosen Übergang bei minimaler Unterbrechung bestehender Workloads.

Die technischen Details zur Konvertierung einer vCenter-Instanz entnehmen Sie bitte den folgenden Lösungen.

* link:vmw-vcf-mgmt-nfs.html["Konvertieren einer vorhandenen vCenter-Instanz in eine VCF Management Domain (NFS)"]
* link:vmw-vcf-mgmt-fc.html["Konvertieren Sie vCenter Instanz (FC-Datastore) in VCF Management Domain"]

