---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-vm-data-collector.html 
keywords: vmware, getting, started, overview, netapp, vm, data, collector, vmdc 
summary:  
---
= VM Data Collector (VMDC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ein wichtiger Bestandteil des richtigen Dimensionierungsmodus und der Projektion möglicher Optimierungsmöglichkeiten ist das Verständnis des aktuellen Zustands der VMware Umgebung.



== Einführung

Virtual Machine Data Collector (VMDC) ist ein kostenloses, leichtes und einfaches GUI-basiertes Toolkit für VMware-Umgebungen, mit dem Benutzer detaillierte Inventarinformationen über ihre virtuellen Maschinen (VMs), Hosts, Speicher und Netzwerke sammeln können.

Weitere Informationen zum Virtual Machine Data Collector finden Sie unter link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmdc.html["Virtual Machine Data Collector-Dokumentation"].



== VMDC-Funktionen

VMDC ist nur ein Sprungbrett, um schnelle und sofortige Statistiken für die Projektion von Optimierungsmöglichkeiten für VMware-Core-Lizenzierung zusammen mit vCPU und RAM zu sammeln. NetApp Dateninfrastruktureinblicke, für die die Installation von aus und Datensammlern erforderlich ist, sollten der naheliegendste nächste Schritt beim Verständnis der detaillierten VM-Topologie sein. Hierbei sollten VMs anhand von Annotationen gruppiert werden, um die richtige Größe für die Workloads festzulegen und die Infrastruktur zukunftssicher zu machen.

Stichprobe der mit VMDC gesammelten Kennzahlen:

* VM-Informationen
+
** VM-Name
** VM-Energiezustand
** VM CPU-Informationen
** VM-Arbeitsspeicherinformationen
** VM-Standort
** Informationen zum VM-Netzwerk
** Und vieles mehr


* VM-Performance
+
** Performance-Daten für VMs in ausgewähltem Intervall
** VM-Lese-/Schreibinformationen
** VM IOPS-Informationen
** VM-Latenz
** Und vieles mehr


* ESXi-Host-Informationen
+
** Informationen zum Host-Datacenter
** Informationen zum Host-Cluster
** Informationen zum Hostmodell
** Host CPU-Informationen
** Host-Speicherinformationen
** Und vieles mehr



