---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-tools-for-vmware.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= ONTAP Tools für VMware (OTV)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für VMware vSphere bieten ein lückenloses Lifecycle Management für Virtual Machines in VMware Umgebungen, die NetApp Storage-Systeme nutzen.



== Einführung

So können Administratoren den Storage direkt innerhalb von vCenter Server managen und das Storage- und Datenmanagement für VMware Umgebungen vereinfachen. Das Plug-in-Tool VMware vSphere Client wurde entwickelt, um Plug-in-Funktionen in den vSphere Client zu integrieren, ohne dass es in vCenter Server ausgeführt werden muss. Dies sorgt für eine Isolierung von Plug-ins und ermöglicht die horizontale Skalierung von Plug-ins in großen vSphere Umgebungen.



== Komponenten des ONTAP-Tools

* *Virtual Storage Console (VSC)* die VSC umfasst die in den vSphere-Client integrierte Schnittstelle, über die Sie Speicher-Controller hinzufügen, Datenspeicher bereitstellen, die Leistung von Datastores überwachen und ESXi-Hosteinstellungen anzeigen und aktualisieren können.
* *VASA Provider* der VMware vSphere APIs for Storage Awareness (VASA) Provider für ONTAP sendet Informationen über den von VMware vSphere verwendeten Storage an den vCenter Server, wodurch die Bereitstellung von VMware Virtual Volumes (VVols) Datastores, die Erstellung und Nutzung von Storage-Funktionsprofilen, Compliance-Überprüfung und Performance-Monitoring ermöglicht wird.
* *Storage Replication Adapter (SRA)* Wenn SRA aktiviert ist und zusammen mit VMware Site Recovery Manager (SRM) verwendet wird, erleichtert SRA die Wiederherstellung von vCenter Server-Datastores und virtuellen Maschinen im Falle eines Ausfalls und ermöglicht so die Konfiguration geschützter Standorte und Recovery-Standorte für die Disaster Recovery.


Weitere Informationen zu NetApp ONTAP-Tools für VMware finden Sie unter https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP-Tools für VMware vSphere - Dokumentation"].
