---
sidebar: sidebar 
permalink: vmware/vmw-vcf-draas-bxp.html 
keywords: vmware, vcf, dr, disaster recovery, draas, bluexp 
summary:  
---
= Disaster Recovery mit BlueXP  DRaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp BlueXP  Disaster Recovery als Service (DRaaS) implementiert Disaster Recovery durch Replizierung auf Blockebene von einem primären Standort zu einem Disaster Recovery-Standort.

BlueXP  DRaaS ist eine effektive und wirtschaftliche Methode, um Workloads vor Standortausfällen und Problemen der Datenintegrität, einschließlich Ransomware-Angriffen, zu schützen. Darüber hinaus erweitert NetApp BlueXP  DRaaS diese Strategie durch die Bereitstellung einer gemanagten, Cloud-basierten Disaster-Recovery-Lösung, die für eine schnelle Recovery bei minimalen Ausfallzeiten bei Notfällen sorgt.

Technische Details finden Sie in den folgenden Lösungen.

* link:vmw-dr-draas-vmfs.html["DR, die BlueXP  DRaaS für VMFS-Datastores verwendet"]
* link:vmw-dr-draas-nfs.html["DR unter Verwendung von BlueXP  DRaaS für NFS-Datastores"]

