---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= Migration von VMs zu ONTAP-gestützten Datastores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Migration von VMware-Workloads zu NetApp ONTAP vereinfacht das Datenmanagement und verbessert die Performance mithilfe der erweiterten Storage-Funktionen von ONTAP wie Deduplizierung, Komprimierung und effizienten Snapshots.



== Einführung

Diese Migration ermöglicht eine nahtlose Integration, verbesserte Datensicherung und mehr Flexibilität beim Management virtualisierter Umgebungen. So wird ein reibungsloser Übergang mit minimalen Ausfallzeiten gewährleistet.

Weitere Informationen zur Migration von VMware-Workloads in ONTAP-gestützte Datastores finden Sie im link:https://docs.netapp.com/us-en/netapp-solutions/vmware/migrate-vms-to-ontap-datastore.html["Migrieren Sie VMs zu ONTAP Datastores"].



== Anwendungsfälle

Bei Überlegungen zur Migration zu ONTAP-gestützten Datastores gibt es zahlreiche Optionen für die Migration von Quelle und Ziel.

* Migration von Storage-Systemen von Drittanbietern (einschließlich vSAN) zu ONTAP Datastores.
* Migration von VMs im selben vSphere-Cluster
* Migration von VMs über mehrere vSphere-Cluster hinweg
* Migration von VMs über vCenter Server in derselben SSO-Domäne hinweg
* Migration von VMs zwischen vCenter Servern in unterschiedlichen SSO-Domänen
* Migration von VMs zwischen Datacenter-Standorten
* Migration von Storage-Systemen von Drittanbietern (einschließlich vSAN) zu ONTAP Datastores.
* Migration von VMs in einer Hybrid Cloud-Umgebung

