---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-data-infrastructure-insights.html 
keywords: vmware, getting, started, overview, netapp, data, infrastructure, insights, dii 
summary:  
---
= Einblicke in die Dateninfrastruktur (DII)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Data Infrastructure Insights ist ein Tool für das Monitoring Ihrer Cloud-Infrastruktur, mit dem Sie Ihre gesamte Infrastruktur im Blick haben.



== Einführung

Es überwacht nicht nur alle Ressourcen, die in Public Clouds und privaten Datacentern liegen, sondern hilft auch dabei, Fehler aufzuspüren und den Ressourceneinsatz zu optimieren.

Weitere Informationen über Einblicke in Dateninfrastrukturen finden Sie unter link:https://docs.netapp.com/us-en/data-infrastructure-insights/index.html["Data Infrastructure Insights Documentation"].



== Einblicke Aus Dateninfrastrukturen

* Data Infrastructure Insights ermöglicht das Monitoring in der Hybrid-Multi-Cloud, wodurch Sie Infrastruktur und Workloads vollständig beobachten können.
* Datensammler für heterogene Infrastrukturen und Workloads einschließlich Kubernetes
* Offener Telegraf-Kollektor und offene APIs für eine einfache Integration
* Umfassende Warn- und Benachrichtigungen
* Maschinelles Lernen für intelligente Erkenntnisse
* Optimierte Ressourcenauslastung
* Integrierte oder anpassbare Dashboards mit erweiterten Filtern zur Reduzierung von Anzeigerauschen bei der Beantwortung von Fragen
* Der Zustand Ihrer ONTAP Storage-Vorgänge erkennen 
* Schutz Ihrer wertvollsten Geschäftsdaten – Daten – vor Ransomware oder Datenvernichtung

