---
sidebar: sidebar 
permalink: vmware/vmware_vcf_aff_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS auf FC als VCF Principal Datastore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Szenario wird die Implementierung von VMFS Datastores mit einem Fibre Channel Back-End (FC) für Management- und Workload-Domänen demonstriert.

Autor: Suresh Thoppay



== Szenarioübersicht

VCF-Hauptspeicher bezieht sich auf alle Speichertypen, die im Rahmen des VCF-Domäneneinrichts bereitgestellt, konvertiert oder importiert werden. In diesem Dokument werden die folgenden Szenarien behandelt.

[cols="20% 20% 20% 20% 20%"]
|===
| Speichertyp | Management Domain – Standardcluster | Verwaltungsdomäne – Zusätzlicher Cluster | VI Workload Domain – Standardcluster | VI Workload Domain – zusätzlicher Cluster 


| VMFS auf FC | *Import-Tool* | *Import Tool, SDDC API* | Ja. | Ja. 
|===


== Voraussetzungen

Dieses Szenario erfordert die folgenden Komponenten und Konfigurationen:

* Ein ONTAP Storage-System mit FC-Ports, die mit FC-Switches verbunden sind.
* SVM wurde mit FC-Leben erstellt.
* VSphere mit FC HBAs, die mit FC-Switches verbunden sind.
* Das Zoning für ein einzelnes Initiator-Ziel ist auf FC-Switches konfiguriert.
+

NOTE: Nutzen Sie die logische SVM-FC-Schnittstelle in der Zonenkonfiguration statt physischer FC-Ports in ONTAP Systemen.



NetApp empfiehlt Multipath für FC LUNs.



== Implementierungsschritte



=== Management Domain – Standardcluster

FC Principal Storage auf dem anfänglichen Cluster wird nur mit dem VCF Brownfield-Importtool unterstützt. Wenn VCF mit dem Cloudbuilder-Tool (bis Version 5.2.x) bereitgestellt wird, wird nur VSAN unterstützt. Weitere Informationen finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["Konvertieren vorhandener vSphere Umgebung in Management-Domäne"].



=== Verwaltungsdomäne – Zusätzlicher Cluster

Der zusätzliche vSphere-Cluster auf der Management-Domain kann mit folgenden Optionen bereitgestellt werden: * Sie haben einen zusätzlichen Cluster in der vSphere-Umgebung und verwenden Sie das VCF Brownfield-Importtool, um die vSphere-Umgebung in die Management-Domäne zu konvertieren. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["ONTAP Tools für VMware vSphere"], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager oder ONTAP API"] Kann verwendet werden, um den VMFS-Datastore in vSphere-Cluster bereitzustellen. * Verwenden Sie SDDC API, um zusätzliche Cluster bereitzustellen. Auf den vSphere-Hosts sollte der VMFS-Datenspeicher konfiguriert sein. Verwenden Sie https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager oder ONTAP API"] diese Funktion, um eine LUN für vSphere-Hosts bereitzustellen. * Verwenden Sie SDDC Manager UI, um zusätzliche Cluster bereitzustellen. Aber diese Option erzeugt nur VSAN Datenspeicher bis Version 5.2.x.



=== VI Workload Domain – Standardcluster

Nachdem die Managementdomäne ausgeführt wurde, kann die VI Workload-Domäne über die SDDC Manager-Benutzeroberfläche erstellt werden *. Auf den vSphere-Hosts sollte der VMFS-Datenspeicher konfiguriert sein. Verwenden Sie System Manager oder ONTAP API zur Bereitstellung von LUNs für vSphere Hosts. * Importieren Sie eine bestehende vSphere-Umgebung als neue VI-Workload-Domäne. ONTAP-Tools für VMware vSphere, System Manager oder ONTAP API können zur Bereitstellung des VMFS-Datastore im vSphere-Cluster verwendet werden.



=== VI Workload Domain – zusätzlicher Cluster

Sobald der VI-Workload ausgeführt wird, können mithilfe der folgenden Optionen zusätzliche Cluster mit VMFS auf FC LUN implementiert werden.

* Zusätzliche Cluster in der vSphere-Umgebung wurden mit dem VCF Brownfield-Importtool importiert. ONTAP-Tools für VMware vSphere, System Manager oder ONTAP API können zur Bereitstellung des VMFS-Datastore im vSphere-Cluster verwendet werden.
* Verwenden der SDDC Manager-UI oder -API zur Implementierung zusätzlicher Cluster Auf den vSphere-Hosts sollte der VMFS-Datenspeicher konfiguriert sein. Verwenden Sie System Manager oder ONTAP API zur Bereitstellung von LUNs für vSphere Hosts.




== Weitere Informationen

Informationen zum Konfigurieren von ONTAP-Speichersystemen finden Sie im link:https://docs.netapp.com/us-en/ontap["ONTAP 9-Dokumentation"] Zentrieren.

Informationen zum Konfigurieren von VCF finden Sie unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Dokumentation zu VMware Cloud Foundation"].
