---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_mgmt_stretchcluster.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, iscsi 
summary:  
---
= Stretch-Cluster mit ONTAP für VCF-Managementdomänen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Szenario zeigen wir, wie Sie mit den ONTAP-Tools für VMware vSphere (OTV) ein Stretch-Cluster für ein VCF-Management und Workload-Domänen konfigurieren.

Autor: Suresh Thoppay



== Szenarioübersicht

Die Stretch-Cluster-Lösung kann im Standard-Cluster oder in zusätzlichen Clustern in VCF-Management- oder Workload-Domänen implementiert werden. VMFS auf FC wird sowohl für den Haupt- als auch für ergänzende Datastores unterstützt. VMFS auf iSCSI wird nur mit ergänzenden Datastores unterstützt. Weitere Informationen zur Unterstützung von VMFS auf NVMe-of mit SnapMirror Active Sync finden Sie auf IMT.

.Hauptspeicher in der Management-Domäne
[%collapsible]
====
Ab VCF 5.2 kann die Management-Domain mit dem VCF Import Tool ohne VSAN bereitgestellt werden. Die Konvertierungsoption des VCF-Importtools ermöglicht eine vorhandene vCenter-Bereitstellung in eine Management-Domäne. Alle Cluster in vCenter werden Teil der Management-Domäne. Für jede Cluster muss ein eigener verteilter Switch zur Konvertierung zur Verfügung stehen. Bis das VCF-Importtool mehrere Netzwerkprofile unterstützt, sollten Sie Stretch-VLANs für das vMotion-Netzwerk verwenden.

. VSphere-Hosts bereitstellen
. VCenter Server auf lokalem Datastore implementieren (vCenter muss gleichzeitig auf vSphere Hosts vorhanden sein, die in Management-Domäne umgewandelt werden)
. Implementieren Sie ONTAP-Tools für VMware vSphere
. Deploy SnapCenter Plug-in for VMware vSphere (optional)
. Datastore erstellen (FC-Zonenkonfiguration sollte vorhanden sein)
. Migrieren Sie die VMs zum neu erstellten Datastore
. Sichern des vSphere-Clusters



NOTE: Wenn das Cluster erweitert oder schrumpft, müssen Sie die Host-Cluster-Beziehung auf ONTAP-Tools aktualisieren, damit das Cluster die Änderungen an der Quelle oder dem Ziel anzeigt.

====
.Zusätzlicher Speicher in der Management Domain
[%collapsible]
====
Sobald die Management-Domäne hochgefahren ist und ausgeführt wird, können mit ONTAP Tools zusätzliche Datastores erstellt werden, sodass die Erweiterung von Konsistenzgruppen ausgelöst wird.


TIP: Wenn ein vSphere-Cluster geschützt ist, werden alle Datastores im Cluster geschützt.

Wenn die VCF-Umgebung mit dem Cloud Builder Tool bereitgestellt wird, implementieren Sie zur Erstellung des ergänzenden Storage mit iSCSI ONTAP-Tools zur Erstellung des iSCSI-Datenspeichers und zum Schutz des vSphere-Clusters.


NOTE: Wenn das Cluster erweitert oder schrumpft, müssen Sie die Host-Cluster-Beziehung auf ONTAP-Tools aktualisieren, damit das Cluster die Änderungen an der Quelle oder dem Ziel anzeigt.

====


== Weitere Informationen

Informationen zum Konfigurieren von ONTAP-Speichersystemen finden Sie im link:https://docs.netapp.com/us-en/ontap["ONTAP 9-Dokumentation"] Zentrieren.

Informationen zum Konfigurieren von VCF finden Sie unter link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["Dokumentation zu VMware Cloud Foundation"].



== Video-Demo für diese Lösung

.Stretch-Cluster für VCF mit ONTAP Tools
video::569a91a9-2679-4414-b6dc-b25d00ff0c5a[panopto,width=360]