---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= Konvertieren Sie mit VMware vSphere Metro Storage Cluster die aktive SM-Synchronisierung von asymmetrisch in symmetrisch aktiv/aktiv
:allow-uri-read: 


link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["NetApp SnapMirror Active Sync (SM Active Sync)"] Ist eine robuste Lösung zur Erreichung des Recovery Time Objective (RTO) von null und des Recovery Point Objective (RPO) von null in einer virtualisierten Umgebung. link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["VMware vSphere Metro Storage-Cluster (vMSC)"] Ist eine Cluster-Lösung, die stark gestreckt ist auf verschiedene Fehlerdomänen und die Verteilung von Virtual Machines (VMs) auf zwei geografisch getrennte Standorte ermöglicht, wodurch kontinuierliche Verfügbarkeit auch bei Ausfall eines Standorts sichergestellt wird. Die Kombination von vMSC mit SM Active Sync gewährleistet Datenkonsistenz und sofortige Failover-Funktionen zwischen zwei Standorten. Diese Einrichtung ist besonders für geschäftskritische Applikationen unerlässlich, bei denen Datenverluste oder Ausfallzeiten nicht akzeptabel sind.

SM Active Sync, ehemals bekannt als SnapMirror Business Continuity (SMBC), ermöglicht Business-Services auch bei einem vollständigen Standortausfall den Betrieb weiter und unterstützt Applikationen bei einem transparenten Failover mithilfe einer sekundären Kopie. Ab ONTAP 9.15.1 unterstützt SM Active Sync eine symmetrische aktiv/aktiv-Funktion. Symmetrische aktiv/aktiv-Lösung ermöglicht I/O-Vorgänge beim Lesen und Schreiben von beiden Kopien einer geschützten LUN mit bidirektionaler synchroner Replizierung, sodass beide LUN-Kopien lokal für I/O-Vorgänge sorgen können. Dieses Dokument zeigt Ihnen die Schritte zur Umwandlung von SM Active Sync asymmetrisch aktiv/aktiv in SM Active Sync symmetrisch aktiv/aktiv in einer VMware Stretch-Cluster-Umgebung, mit anderen Worten, konvertiert eine SM Active Sync von einer automatischen Failover-Richtlinie in eine automatisierte Failover-Duplex-Richtlinie. Weitere Informationen zur Einrichtung des vMSC mit SnapMirror Active Sync (SM-AS) unter Verwendung von System Manager und ONTAP Tools finden Sie unter link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vmsc-with-smas.html["VMware vSphere Metro Storage-Cluster mit SnapMirror Active Sync"].



== Voraussetzungen

* NetApp Storage-Systeme: Stellen Sie sicher, dass zwei NetApp Storage-Cluster (Quelle und Ziel) mit SnapMirror Lizenzen vorhanden sind.
* Netzwerk-Konnektivität: Überprüfung der Netzwerk-Konnektivität mit niedriger Latenz zwischen den Quell- und Zielsystemen
* Cluster- und SVM-Peering: Einrichten von Cluster-Peering und Storage Virtual Machine (SVM) Peering zwischen den Quell- und Ziel-Clustern.
* ONTAP-Version: Stellen Sie sicher, dass auf beiden Clustern eine Version von ONTAP ausgeführt wird, die synchrone Replikation unterstützt. Für SM Active Sync, ONTAP 9.15.1 und höher, ist erforderlich.
* VMware vMSC-Infrastruktur: Dank eines erweiterten Clusters können Subsysteme über geografische Grenzen hinweg bereitgestellt werden. Für den vSphere Cluster an beiden Standorten werden dabei nur eine einzige und eine gemeinsame Basis-Infrastrukturgruppe bereitgestellt. Es dehnt Netzwerk und Speicher zwischen Standorten aus.
* Verwenden Sie ONTAP-Tools ab Version 10.2, um die Verwendung von NetApp SnapMirror zu vereinfachen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["ONTAP Tools für VMware vSphere 10."]
* Zwischen dem primären und dem sekundären Cluster muss eine synchrone SnapMirror-Beziehung mit einem RPO von null vorhanden sein.
* Die Zuordnung aller LUNs auf dem Ziel-Volume muss aufgehoben werden, bevor die RTO-SnapMirror-Beziehung null erstellt werden kann.
* SnapMirror Active Sync unterstützt nur SAN-Protokolle (nicht NFS/CIFS). Stellen Sie sicher, dass für den NAS-Zugriff keine Komponente der Konsistenzgruppe bereitgestellt ist.




== Schritte zur Konvertierung von asymmetrischer zu symmetrischer SM aktiver Synchronisierung

Im folgenden Beispiel ist die Auswahl ectrz1 der primäre Standort und die Auswahl ectrz2 der sekundäre Standort.

. Führen Sie am sekundären Standort ein SnapMirror Update der bestehenden Beziehung durch.
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. Überprüfen Sie, ob das SnapMirror-Update erfolgreich abgeschlossen wurde.
+
....
selectrz2::> snapmirror show
....
. Halten Sie jede der synchronen Beziehungen mit einem RPO von null an.
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. Löschen Sie jede synchrone RPO-Beziehung von null.
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. Geben Sie die Quell-SnapMirror-Beziehung frei, behalten Sie aber die gemeinsamen Snapshots bei.
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. Erstellen Sie eine synchrone SnapMirror-Beziehung von null RTO mit der Richtlinie für AutoatedFailoverDuplex.
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. Wenn die vorhandenen Hosts lokal das primäre Cluster sind, fügen Sie den Host zum sekundären Cluster hinzu, und stellen Sie die Verbindung mit dem entsprechenden Zugriff auf jedes Cluster her.
. Löschen Sie am sekundären Standort die LUN-Zuordnungen der Initiatorgruppen, die Remote-Hosts zugeordnet sind.
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. Ändern Sie am primären Standort die Initiatorkonfiguration für vorhandene Hosts, um den proximalen Pfad für Initiatoren auf dem lokalen Cluster festzulegen.
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. Fügen Sie eine neue Initiatorgruppe und einen neuen Initiator für die neuen Hosts hinzu und legen Sie die Host-Nähe für die Host-Affinität zu ihrem lokalen Standort fest. Aktivieren Sie die igroup-Replikation, um die Konfiguration zu replizieren und die Hostlokalität auf dem Remote-Cluster zu invertieren.
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. Ermitteln Sie die Pfade auf den Hosts und überprüfen Sie, ob die Hosts über einen aktiv/optimierten Pfad zur Storage-LUN vom bevorzugten Cluster verfügen.
. Implementieren Sie die Applikation und verteilen Sie die VM-Workloads über Cluster hinweg.
. Synchronisieren Sie die Konsistenzgruppe erneut.
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. Wiederherstellen aller Pfade zu den LUNs durch erneute Überprüfung der Host-LUN-I/O-Pfade

