---
sidebar: sidebar 
permalink: vmware/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: Auf dieser Seite finden Sie Videos und Tutorials. 
---
= Virtualisierungsvideos und -Demos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich die folgenden Videos und Demos an, in denen die spezifischen Funktionen von Hybrid Cloud-, Virtualisierungs- und Container-Lösungen vorgestellt werden.

.NetApp ONTAP Tools für VMware vSphere
[%collapsible%open]
====
.ONTAP Tools für VMware - Übersicht
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.Bereitstellung von VMware iSCSI-Datenspeichern mit ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Bereitstellung von VMware NFS-Datenspeichern mit ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.SnapCenter Plug-in für VMware vSphere
[%collapsible%open]
====
Die NetApp SnapCenter Software ist eine unkomplizierte Enterprise-Plattform, die die Koordination und das Management der Datensicherung für alle Applikationen, Datenbanken und Filesysteme sicher gestaltet.

Das SnapCenter Plug-in für VMware vSphere ermöglicht Ihnen Backup-, Wiederherstellungs- und Anschlussvorgänge für VMs sowie Backup- und Mount-Vorgänge für Datastores, die bei SnapCenter direkt in VMware vCenter registriert sind.

Weitere Informationen zum NetApp SnapCenter Plug-in für VMware vSphere finden Sie im link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["Überblick über NetApp SnapCenter Plug-in für VMware vSphere"].

.SnapCenter Plug-in für VMware vSphere – Voranforderungen für eine Lösung
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.SnapCenter Plug-in für VMware vSphere – Implementierung
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.SnapCenter Plug-in für VMware vSphere – Backup-Workflow
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.SnapCenter Plug-in für VMware vSphere – Workflow wiederherstellen
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - SQL Restore-Workflow
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.3-2-1 Datensicherungslösungen
[%collapsible%open]
====
3-2-1-1 Datensicherungslösungen kombinieren primäre und sekundäre Backups vor Ort mithilfe von SnapMirror Technologie mit replizierten Kopien in Objekt-Storage mithilfe von BlueXP Backup und Recovery.

.3-2-1 Datensicherung für VMFS Datastores mit SnapCenter Plug-in für VMware vSphere und BlueXP Backup und Recovery für Virtual Machines
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.VMware Cloud on AWS mit AWS FSX ONTAP
[%collapsible%open]
====
.Windows Guest Connected Storage mit FSX ONTAP über iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Linux Guest Connected Storage with FSX ONTAP Using NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.TCO-Einsparungen mit VMware Cloud on AWS mit Amazon FSX ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Ergänzender Datastore für VMware Cloud on AWS mit Amazon FSX ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMware HCX Deployment and Configuration Setup für VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMotion MigrationDemonstration mit VMware HCX für VMC und FSX ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Demo für kalte Migration mit VMware HCX für VMC und FSX ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure VMware-Services auf Azure mit Azure NetApp Files (ANF)
[%collapsible%open]
====
.Übersicht über die Azure VMware Lösung zusätzlichen Datastore mit Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Azure VMware Lösung für DR mit Cloud Volumes ONTAP, SnapCenter und JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Demonstration zur Cold-Migration mit VMware HCX für AVS und ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMotion-Demo mit VMware HCX für AVS und ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Massenmigration mit VMware HCX für AVS und ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation mit NetApp ONTAP
[%collapsible%open]
====
.NFS-Datenspeicher als Principal Storage für VCF Workload Domains
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.ISCSI-Datenspeicher als ergänzender Speicher für VCF-Management-Domänen
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp mit VMware Tanzu
[%collapsible%open]
====
Mit VMware Tanzu können Kunden ihre Kubernetes-Umgebung über vSphere oder VMware Cloud Foundation implementieren, managen und managen. Mit diesem VMware Portfolio können Kunden alle relevanten Kubernetes Cluster über eine einzige Kontrollebene managen. Dazu wählen sie die für sie am besten geeignete VMware Tanzu Edition.

Weitere Informationen zu VMware Tanzu finden Sie im https://tanzu.vmware.com/tanzu["VMware Tanzu Overview"^]. Diese Überprüfung behandelt Anwendungsfälle, verfügbare Ergänzungen und mehr über VMware Tanzu.

.Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 1
video::ZtbXeOJKhrc[youtube,width=360]
.Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 2
video::FVRKjWH7AoE[youtube,width=360]
.Verwendung von VVols mit NetApp und VMware Tanzu Basic, Teil 3
video::Y-34SUtTTtU[youtube,width=360]
====
.NetApp Cloud Insights
[%collapsible%open]
====
NetApp Cloud Insights ist eine umfassende Monitoring- und Analyseplattform, die für Transparenz und Kontrolle der On-Premises- und Cloud-Infrastruktur konzipiert ist.

.NetApp Cloud Insights – Beobachtbarkeit für das moderne Datacenter
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====