---
sidebar: sidebar 
permalink: vmware/vsphere_ontap_auto_block_iscsi.html 
keywords: vSphere, datastore, VMFS, iSCSI, ONTAP tools, vlan, network interface, service policy 
summary: Auf dieser Seite finden Sie Schritte zur Bereitstellung eines NetApp ONTAP Storage iSCSI VMFS-Datenspeichers in einer VMware vSphere Umgebung. 
---
= VSphere VMFS Datenspeicher – iSCSI-Storage-Back-End mit ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Abschnitt wird die Erstellung eines VMFS-Datenspeichers mit ONTAP iSCSI-Speicher behandelt.

Verwenden Sie für die automatische Bereitstellung das folgende Skript: <<Ansible>>.



== Was Sie brauchen

* Grundkenntnisse für das Management einer vSphere Umgebung und einer ONTAP
* ONTAP Storage-Systeme (FAS/AFF/CVO/ONTAP Select/ASA) mit {ontap_Version}
* ONTAP-Anmeldedaten (SVM-Name, Benutzer-ID und Passwort)
* ONTAP Netzwerkport, SVM und LUN-Informationen für iSCSI
* link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-429C4DDD-5EC0-4DBD-8EA8-76082AB7ADEC.html++["Ein ausgefülltes iSCSI-Konfigurationsarbeitsblatt"]
* Anmeldedaten für vCenter Server
* Informationen zu vSphere Hosts
+
** {vsphere_Version}


* IP-Informationen zum iSCSI VMkernel Adapter
* Netzwerk-Switch(e)
+
** Mit Netzwerk-Daten-Ports des ONTAP Systems und verbundenen vSphere Hosts
** Für iSCSI konfigurierte VLANs
** (Optional) Link Aggregation konfiguriert für ONTAP Netzwerkdatenports


* ONTAP Tool für VMware vSphere – implementiert, konfiguriert und betriebsbereit




== Schritte

. Prüfen Sie die Kompatibilität mit dem https://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool (IMT)"].
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-7D444A0D-02CE-4A21-8017-CB1DC99EFD9A.html++["Vergewissern Sie sich, dass die iSCSI-Konfiguration unterstützt wird."]
. Führen Sie die folgenden Aufgaben für ONTAP und vSphere aus.




== ONTAP Aufgaben

. link:https://docs.netapp.com/us-en/ontap-cli-98/system-license-show.html["Überprüfen Sie die ONTAP Lizenz für iSCSI"].
+
.. Verwenden Sie die `system license show` Befehl, um zu überprüfen, ob iSCSI aufgeführt ist.
.. Nutzung `license add -license-code <license code>` Um die Lizenz hinzuzufügen.


. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-ED75D939-C45A-4546-8B22-6B765FF6083F.html++["Vergewissern Sie sich, dass das iSCSI-Protokoll auf der SVM aktiviert ist."]
. Vergewissern Sie sich, dass auf der SVM logische iSCSI-Netzwerk-Schnittstellen verfügbar sind.
+

NOTE: Wenn über die GUI eine SVM erstellt wird, werden auch iSCSI-Netzwerkschnittstellen erstellt.

. Verwenden Sie die `Network interface` Befehl zum Anzeigen oder Ändern der Netzwerkschnittstelle.
+

TIP: Es werden zwei iSCSI-Netzwerkschnittstellen pro Node empfohlen.

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-CEE760DF-A059-4018-BE6C-6B3A034CB377.html++["Erstellen Sie eine iSCSI-Netzwerkschnittstelle."] Sie können die Service-Richtlinie für Standarddatenblöcke verwenden.
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-BBC2D94B-DD3A-4029-9FCE-F71F9C157B53.html++["Überprüfen Sie, ob der Daten-iscsi-Service in der Service-Richtlinie enthalten ist."] Verwenden Sie können `network interface service-policy show` Zu überprüfen.
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DE59CF49-3A5F-4F38-9F17-E2C16B567DC0.html++["Vergewissern Sie sich, dass Jumbo Frames aktiviert sind."]
. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-D4DAC7DB-A6B0-4696-B972-7327EE99FD72.html++["Erstellen und Zuordnen der LUN."] Überspringen Sie diesen Schritt, wenn Sie ONTAP-Tools für VMware vSphere verwenden. Wiederholen Sie diesen Schritt für jede LUN.




== Aufgaben für VMware vSphere

. Stellen Sie sicher, dass mindestens eine NIC für das iSCSI-VLAN verfügbar ist. Zwei NICs werden bevorzugt, um eine bessere Performance und Fehlertoleranz zu schaffen.
. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-B2AA3EEE-2334-45FE-9A0F-1172FDDCC6A8.html++["Ermitteln Sie die Anzahl der physischen NICs, die auf dem vSphere-Host verfügbar sind."]
. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-C476065E-C02F-47FA-A5F7-3B3F2FD40EA8.html++["Konfigurieren Sie den iSCSI-Initiator."] Ein typischer Anwendungsfall ist ein Software-iSCSI-Initiator.
. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-660423B1-3D35-4F85-ADE5-FE1D6BF015CF.html++["Stellen Sie sicher, dass der TCPIP-Stack für iSCSI verfügbar ist"].
. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-0D31125F-DC9D-475B-BC3D-A3E131251642.html++["Vergewissern Sie sich, dass iSCSI-Portgruppen verfügbar sind"].
+
** In der Regel verwenden wir einen einzelnen virtuellen Switch mit mehreren Uplink-Ports.
** Verwenden Sie 1:1-Adapterzuordnung.


. Vergewissern Sie sich, dass die iSCSI-VMkernel-Adapter für die Anzahl der NICs aktiviert sind und IP-Adressen zugewiesen sind.
. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-D9B862DF-476A-4BCB-8CA5-DE6DB2A1A981.html++["Binden Sie den iSCSI-Software-Adapter an die iSCSI-VMkernel-Adapter."]
. link:++https://docs.netapp.com/vapp-98/topic/com.netapp.doc.vsc-iag/GUID-D7CAD8AF-E722-40C2-A4CB-5B4089A14B00.html++["Stellen Sie den VMFS-Datenspeicher mit ONTAP Tools bereit"]. Wiederholen Sie diesen Schritt für alle Datenspeicher.
. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-0520FD37-D7AD-4FBA-9A2E-E5F8211FCBBB.html++["Prüfen Sie, ob die Hardware-Beschleunigung unterstützt wird."]




== Was kommt als Nächstes?

Nach Abschluss dieser Aufgaben kann der VMFS-Datenspeicher für die Bereitstellung von Virtual Machines genutzt werden.

.Ansible Playbook
[source]
----
## Disclaimer: Sample script for reference purpose only.

- hosts: '{{ vsphere_host }}'
  name: Play for vSphere iSCSI Configuration
  connection: local
  gather_facts: false
  tasks:
    # Generate Session ID for vCenter
    - name: Generate a Session ID for vCenter
      uri:
        url: "https://{{ vcenter_hostname }}/rest/com/vmware/cis/session"
        validate_certs: false
        method: POST
        user: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
        force_basic_auth: yes
        return_content: yes
      register: vclogin

    # Generate Session ID for ONTAP tools with vCenter
    - name: Generate a Session ID for ONTAP tools with vCenter
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/security/user/login"
        validate_certs: false
        method: POST
        return_content: yes
        body_format: json
        body:
          vcenterUserName: "{{ vcenter_username }}"
          vcenterPassword: "{{ vcenter_password }}"
      register: login

    # Get existing registered ONTAP Cluster info with ONTAP tools
    - name: Get ONTAP Cluster info from ONTAP tools
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters"
        validate_certs: false
        method: Get
        return_content: yes
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
      register: clusterinfo

    - name: Get ONTAP Cluster ID
      set_fact:
        ontap_cluster_id: "{{ clusterinfo.json | json_query(clusteridquery) }}"
      vars:
        clusteridquery: "records[?ipAddress == '{{ netapp_hostname }}' && type=='Cluster'].id | [0]"

    - name: Get ONTAP SVM ID
      set_fact:
        ontap_svm_id: "{{ clusterinfo.json | json_query(svmidquery) }}"
      vars:
        svmidquery: "records[?ipAddress == '{{ netapp_hostname }}' && type=='SVM' && name == '{{ svm_name }}'].id | [0]"

    - name: Get Aggregate detail
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters/{{ ontap_svm_id }}/aggregates"
        validate_certs: false
        method: GET
        return_content: yes
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
          cluster-id: "{{ ontap_svm_id }}"
      when: ontap_svm_id != ''
      register: aggrinfo

    - name: Select Aggregate with max free capacity
      set_fact:
        aggr_name: "{{ aggrinfo.json | json_query(aggrquery) }}"
      vars:
        aggrquery: "max_by(records, &freeCapacity).name"

    - name: Convert datastore size in MB
      set_fact:
        datastoreSizeInMB: "{{ iscsi_datastore_size | human_to_bytes/1024/1024 | int }}"

    - name: Get vSphere Cluster Info
      uri:
        url: "https://{{ vcenter_hostname }}/api/vcenter/cluster?names={{ vsphere_cluster }}"
        validate_certs: false
        method: GET
        return_content: yes
        body_format: json
        headers:
          vmware-api-session-id: "{{ vclogin.json.value }}"
      when: vsphere_cluster != ''
      register: vcenterclusterid

    - name: Create iSCSI VMFS-6 Datastore with ONTAP tools
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/3.0/admin/datastore"
        validate_certs: false
        method: POST
        return_content: yes
        status_code: [200]
        body_format: json
        body:
          traditionalDatastoreRequest:
            name: "{{ iscsi_datastore_name }}"
            datastoreType: VMFS
            protocol: ISCSI
            spaceReserve: Thin
            clusterID:  "{{ ontap_cluster_id }}"
            svmID: "{{ ontap_svm_id }}"
            targetMoref: ClusterComputeResource:{{ vcenterclusterid.json[0].cluster }}
            datastoreSizeInMB: "{{ datastoreSizeInMB | int }}"
            vmfsFileSystem: VMFS6
            aggrName: "{{ aggr_name }}"
            existingFlexVolName: ""
            volumeStyle: FLEXVOL
            datastoreClusterMoref: ""
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
      when: ontap_cluster_id != '' and ontap_svm_id != '' and aggr_name != ''
      register: result
      changed_when: result.status == 200
----