---
sidebar: sidebar 
permalink: ai/a400-thinksystem-conclusion.html 
keywords: acknowledgements, additional information 
summary: 'Diese flexible Scale-out-Architektur von NetApp und Lenovo eignet sich ideal für den Einstieg in KI der mittleren Enterprise-Klasse. NetApp Storage bietet die gleiche oder bessere Performance wie lokaler SSD-Storage und bietet Datenanalysten, Data Engineers und IT-Entscheidungsträgern die folgenden Vorteile:' 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die hier validierte NetApp und Lenovo Lösung ist eine flexible Scale-out-Architektur, die sich ideal für den Einstieg in Enterprise-KI eignet.

NetApp Storage bietet die gleiche oder bessere Performance wie lokaler SSD-Storage und bietet Datenanalysten, Data Engineers und IT-Entscheidungsträgern folgende Vorteile:

* Problemlose gemeinsame Nutzung von Daten zwischen KI-Systemen, Big-Data-Analysen und anderen geschäftskritischen Systemen Diese gemeinsame Nutzung von Daten verringert den Infrastruktur-Overhead, verbessert die Performance und optimiert das Datenmanagement im gesamten Unternehmen.
* Unabhängiges skalierbares Computing und Storage-System, um Kosten zu minimieren und die Ressourcenauslastung zu verbessern.
* Optimierte Entwicklungs- und Implementierungs-Workflows mithilfe integrierter Snapshots und Klone für sofortige und platzsparende Benutzer-Workspaces, integrierte Versionskontrolle und automatisierte Implementierung
* Datensicherung der Enterprise-Klasse für Disaster Recovery und Business Continuance.




== Danksagungen

* Karthikeyan Nagalingam, Technical Marketing Engineer, NetApp
* Jarrett Upton, Admin, AI Lab Systems, Lenovo




== Wo Sie weitere Informationen finden

Weitere Informationen zu den in diesem Dokument beschriebenen Daten finden Sie in den folgenden Dokumenten bzw. auf den folgenden Websites:

* Produktseite zu NetApp All-Flash-Arrays
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx["https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx"^]

* Seite „NetApp AFF A400“
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html["https://docs.netapp.com/us-en/ontap-systems/a400/index.html"]

* Produktseite für NetApp ONTAP Datenmanagement-Software
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx["http://www.netapp.com/us/products/data-management-software/ontap.aspx"^]

* MLPerf
+
https://mlperf.org/["https://mlperf.org"^]

* TensorFlow-Benchmark
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* NVIDIA SMI (nvidia-smi)
+
https://developer.nvidia.com/nvidia-system-management-interface["https://developer.nvidia.com/nvidia-system-management-interface"]


