---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, version history, additional information 
summary: KI-gestützte Automatisierung und Edge-Computing sind eine führende Vorgehensweise, um Unternehmen bei der digitalen Transformation zu unterstützen und ihre betriebliche Effizienz und Sicherheit zu maximieren. Mithilfe von Edge Computing werden Daten wesentlich schneller verarbeitet, da sie nicht mehr zum und von einem Datacenter entfernt werden müssen. Somit sinken die Kosten für den Datentransfer in Datacenter oder in die Cloud. 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-edge-architecture-sizing-options.html["Früher: Optionen zur Dimensionierung der Architektur."]

[role="lead"]
KI-gestützte Automatisierung und Edge-Computing sind eine führende Vorgehensweise, um Unternehmen bei der digitalen Transformation zu unterstützen und ihre betriebliche Effizienz und Sicherheit zu maximieren. Mithilfe von Edge Computing werden Daten wesentlich schneller verarbeitet, da sie nicht mehr zum und von einem Datacenter entfernt werden müssen. Somit sinken die Kosten für den Datentransfer in Datacenter oder in die Cloud. Niedrigere Latenz und eine höhere Geschwindigkeit können von Vorteil sein, wenn Unternehmen Entscheidungen mithilfe von im Edge-Bereich bereitgestellten KI-Inferenzmodellen in nahezu Echtzeit treffen müssen.

NetApp Storage-Systeme bieten die gleiche oder eine bessere Performance wie lokaler SSD-Storage und bieten Data Scientists, Data Engineers, KI/ML-Entwickler und Business- oder IT-Entscheidungsträger die folgenden Vorteile:

* Problemlose gemeinsame Nutzung von Daten zwischen KI-Systemen, Big-Data-Analysen und anderen geschäftskritischen Systemen Diese gemeinsame Nutzung von Daten verringert den Infrastruktur-Overhead, verbessert die Performance und optimiert das Datenmanagement im gesamten Unternehmen.
* Unabhängig skalierbare Computing- und Storage-Ressourcen minimieren Kosten und verbessern die Ressourcenauslastung.
* Optimierte Entwicklungs- und Implementierungs-Workflows mithilfe integrierter Snapshot Kopien und Klone für sofortige und platzsparende Benutzer-Workspaces, integrierte Versionskontrolle und automatisierte Implementierung
* Datensicherung der Enterprise-Klasse für Disaster Recovery und Business Continuity Die in diesem Dokument vorgestellte NetApp und Lenovo Lösung ist eine flexible Scale-out-Architektur, die sich ideal für Edge-Implementierungen von KI-Inferenz der Enterprise-Klasse eignet.




== Danksagungen

* J.J. Falkanger, Sr Manager, HPC & AI Solutions, Lenovo
* Dave Arnette, Technical Marketing Engineer, NetApp
* Joey Parnell, Tech Lead E-Series KI-Lösungen, NetApp
* Cody Harryman, QA Engineer, NetApp




== Wo Sie weitere Informationen finden

Weitere Informationen zu den in diesem Dokument beschriebenen Daten finden Sie in den folgenden Dokumenten bzw. auf den folgenden Websites:

* Produktseite zu NetApp AFF A-Series Arrays
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* NetApp ONTAP Datenmanagement-Software: Informationsbibliothek unter ONTAP 9
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: NetApp EF-Series Introduction
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* NetApp E-Series SANtricity Software Datenblatt
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* NetApp persistenter Storage für Container – NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp Cloud Sync
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* TensorFlow-Benchmark
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Lenovo ThinkSystem SE350 Edge Server
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Lenovo ThinkSystem DM5100F Unified Flash Storage Array
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array^["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"^]





== Versionsverlauf

|===
| Version | Datum | Versionsverlauf des Dokuments 


| Version 1.0 | März 2021 | Erste Version 


| Version 2.0 | Oktober 2021 | Aktualisiert mit EF und MLPerf Inferenz v1.1 
|===