---
sidebar: sidebar 
permalink: ai/ai-protopia-test-and-validation-plan.html 
keywords: validation scenarios, obfuscation, batch inferencing job 
summary: Dieser Abschnitt bietet einen Überblick über die drei in dieser Lösung validierten Szenarien. 
---
= Test- und Validierungsplan
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-technology-overview.html["Zurück: Technologieübersicht."]

[role="lead"]
Für dieses Lösungsdesign wurden die folgenden drei Szenarien validiert:

* Eine Inferenz mit und ohne Protopia obfuscation in einem JupyterLab Workspace, der mithilfe des NetApp DataOps Toolkit für Kubernetes orchestriert wurde.
* Einen Job zur Batch-Inferenz mit und ohne Protopia obfuscation auf Kubernetes mit einem Daten-Volume, das mithilfe des NetApp DataOps Toolkit für Kubernetes orchestriert wurde.
* Ein Inferenz-Task unter Verwendung einer NVIDIA Triton Inferenz Server-Instanz, die mit dem NetApp DataOps Toolkit für Kubernetes orchestriert wurde. Vor dem Aufruf der Triton-Inferenz-API haben wir Protopia-Obfuscation auf das Bild angewendet, um die allgemeine Anforderung zu simulieren, dass alle über das Netzwerk übertragenen Daten obfuscated werden müssen. Dieser Workflow eignet sich für Anwendungsfälle, in denen Daten in einer vertrauenswürdigen Zone erfasst, jedoch zur Inferenz außerhalb dieser vertrauenswürdigen Zone weitergeleitet werden müssen. Ohne Protopia Obfuscation ist es nicht möglich, diese Art von Workflow ohne sensible Daten zu implementieren, die die vertrauenswürdige Zone verlassen.


link:ai-protopia-test-configuration.html["Als Nächstes: Testkonfiguration."]
