---
sidebar: sidebar 
permalink: ai/ai-protopia-solution-areas.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: Die digitale Bildverarbeitung bietet zahlreiche Vorteile, sodass viele Unternehmen das Beste aus ihren Daten in Verbindung mit visuellen Darstellungen machen können. Diese Lösung von NetApp und Protopia bietet ein einzigartiges Design zur KI-Inferenz zum Schutz und zur Privatisierung von KI/ML-Daten im ml/DL-Lebenszyklus. Kunden können damit die Kontrolle über sensible Daten behalten, Skalierungsmodelle und Effizienz in Public oder Hybrid-Cloud-Umgebungen nutzen, indem sie Bedenken im Zusammenhang mit dem Datenschutz ausräumen und die KI-Inferenz im Edge-Bereich implementieren. 
---
= Lösungsbereiche
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-overview.html["Zurück: Übersicht."]

[role="lead"]
Die digitale Bildverarbeitung bietet zahlreiche Vorteile, sodass viele Unternehmen das Beste aus ihren Daten in Verbindung mit visuellen Darstellungen machen können. Diese Lösung von NetApp und Protopia bietet ein einzigartiges Design zur KI-Inferenz zum Schutz und zur Privatisierung von KI/ML-Daten im ml/DL-Lebenszyklus. Kunden können damit die Kontrolle über sensible Daten behalten, Skalierungsmodelle und Effizienz in Public oder Hybrid-Cloud-Umgebungen nutzen, indem sie Bedenken im Zusammenhang mit dem Datenschutz ausräumen und die KI-Inferenz im Edge-Bereich implementieren.



== Umweltbewusstsein

Es gibt viele Möglichkeiten, wie Branchen die Vorteile der Geospatialanalytik in den Bereichen der Umweltgefahren nutzen können. Regierungen und das Ministerium für öffentliche Arbeiten können nützliche Einblicke in die öffentliche Gesundheit und die Wetterbedingungen erhalten, um die Öffentlichkeit bei einer Pandemie oder einer Naturkatastrophe wie Waldbränden besser beraten zu können. So können Sie beispielsweise einen COVID-positiven Patienten in öffentlichen Räumen, wie Flughäfen oder Krankenhäusern, identifizieren, ohne die Privatsphäre der betroffenen Person zu beeinträchtigen und die jeweiligen Behörden und die Öffentlichkeit in der Umgebung auf notwendige Sicherheitsmaßnahmen aufmerksam zu machen.



== Tragbare Geräte am Edge

Im Militär und auf Schlachtfeldern können Sie mithilfe der KI-Inferenz am Rand als tragbare Geräte den Status von Soldaten verfolgen, das Fahrverhalten überwachen und Behörden über die Sicherheit und die damit verbundenen Risiken im Zusammenhang mit der Annäherung an Militärfahrzeuge informieren, während die Privatsphäre von Soldaten geschützt und geschützt wird. Die Zukunft des Militärs wird mit dem Internet of Battlefield Things (IoBT) und dem Internet of Military Things (IoMT) High-Tech für tragbare Kampfausrüstung, die Soldaten helfen, Feinde zu identifizieren und besser im Kampf durch schnelle Edge-Computing. Der Schutz und der Schutz visueller Daten, die von Edge-Geräten wie Drohnen und tragbaren Getrieben erfasst werden, ist von entscheidender Bedeutung, um Hacker und Gegner vor Schach zu halten.



== Nicht kämpferische Evakuierungsvorgänge

Nichtkämpferische Evakuierungsmaßnahmen (NEO) werden vom DoD durchgeführt, um bei der Evakuierung von US-Bürgern und Staatsangehörigen, ziviler DoD-Mitarbeiter und designierten Personen (HN) und Drittstaatsangehörigen (TCNs) zu helfen, deren Leben in Gefahr für einen geeigneten sicheren Hafen sind. Die vorhandenen administrativen Kontrollen nutzen weitgehend manuelle Evakuierungsverfahren. Jedoch könnte die Genauigkeit, Sicherheit und Geschwindigkeit der Evakuierung von ee-Identifizierung, Evakuierung von ee-Tracking und Bedrohungsabschirmung durch den Einsatz hochautomatisierter KI/ML-Tools in Kombination mit AI/ML-Videobfuskationstechnologien verbessert werden.



== Gesundheitswesen und biomedizinische Forschung

Mithilfe der Bildverarbeitung werden Pathologien für die chirurgische Planung anhand von 3D-Bildern aus der Computertomographie (CT) oder der Magnetresonanztomographie (MRT) diagnostiziert. Die HIPAA-Datenschutzregeln regeln regeln die Art und Weise, in der Daten von Unternehmen für alle persönlichen Informationen und digitalen Bilder wie Fotos gesammelt, verarbeitet und gelöscht werden müssen. Damit die Daten gemäß den HIPAA Safe Harbor-Bestimmungen als teilbar gelten, müssen Fotos mit voller Fläche und vergleichbare Bilder entfernt werden. Automatisierte Techniken wie De-Identification oder Skull‐Abisolieralgorithmen, die zur Obscrung der Gesichtszüge eines Einzelnen aus strukturellen CT/MR-Bildern verwendet werden, sind zu einem wesentlichen Bestandteil des Datenfreigabeprozesses für biomedizinische Forschungseinrichtungen geworden.



== Cloud-Migration von KI/ML-Analysen

Enterprise-Kunden haben bisher KI/ML-Modelle lokal geschult und implementiert. Aus Skaleneffekten und Effizienzgründen erweitern diese Kunden zunehmend KI/ML-Funktionen in Public-, Hybrid- oder Multi-Cloud-Implementierungen. Sie sind jedoch an die gebunden, welche Daten anderen Infrastrukturen zugänglich sein können. NetApp Lösungen erfüllen die Anforderungen einer Reihe von Cybersicherheitsbedrohungen, die für erforderlich sind https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["Datensicherung"^] Die Sicherheitsbewertung und minimieren in Kombination mit der Protopia Datentransformation die Risiken, die mit der Migration von KI/ML-Workloads für die Bildverarbeitung in die Cloud verbunden sind.

Weitere Anwendungsfälle für Edge-Computing und KI-Inferenz in anderen Branchen finden Sie unter https://docs.netapp.com/us-en/netapp-solutions/ai/ai-edge-introduction.html["TR-4886 KI-Inferenzierung am Edge"^] Mit dem NetApp AI Blog https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["Intelligenz und Datenschutz"^].

link:ai-protopia-technology-overview.html["Weiter: Technologische Übersicht."]
