---
sidebar: sidebar 
permalink: ai/ai-protopia-where-to-find-additional-information,-acknowledgements,-and-version-history.html 
keywords:  
summary:  
---
= Wo finden Sie zusätzliche Informationen, Bestätigungen und Versionsverlauf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-conclusion.html["Zurück: Schlussfolgerung."]

[role="lead"]
Weitere Informationen zu den in diesem Dokument beschriebenen Daten finden Sie in den folgenden Dokumenten bzw. auf den folgenden Websites:

* NetApp ONTAP Datenmanagement-Software – ONTAP Informationsbibliothek
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* NetApp persistenter Storage für Container – NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* NetApp DataOps Toolkit
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Persistent Storage für Container – NetApp Astra Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Protopia AI – vertrauliche Inferenz
+
https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/["https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/"^]

* NetApp BlueXP Kopie und Synchronisierung
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* NVIDIA Triton Inferenz Server
+
https://developer.nvidia.com/nvidia-triton-inference-server["https://developer.nvidia.com/nvidia-triton-inference-server"^]

* NVIDIA Triton Inference Server Documentation
+
https://docs.nvidia.com/deeplearning/triton-inference-server/index.html["https://docs.nvidia.com/deeplearning/triton-inference-server/index.html"^]

* FaceBoxes in PyTorch
+
https://github.com/zisianw/FaceBoxes.PyTorch["https://github.com/zisianw/FaceBoxes.PyTorch"^]





== Danksagungen

* Mark Cates, Principal Product Manager, NetApp
* Sufian Ahmad, Technical Marketing Engineer, NetApp
* Hadi Esmaeilzadeh, Chief Technology Officer und Professor, Protopia AI




== Versionsverlauf

|===
| Version | Datum | Versionsverlauf Des Dokuments 


| Version 1.0 | Mai 2022 | Erste Version. 
|===