---
sidebar: sidebar 
permalink: ai/ai-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: 'Die Daten sind in drei Bundesstaaten unterwegs: Im Ruhezustand, während der Übertragung und im Computing. Ein wichtiger Bestandteil jedes KI-Inferenz-Services sollte der Schutz der Daten vor Bedrohungen während des gesamten Prozesses sein. Der Schutz von Daten während der Inferenz ist von großer Bedeutung, da der Prozess private Informationen über externe Kunden und das Unternehmen, das den Inferenzservice bereitstellt, offenlegen kann.' 
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-protopia-obfuscation-speed.html["Zurück: Obfuskationsgeschwindigkeit."]

Die Daten sind in drei Bundesstaaten unterwegs: Im Ruhezustand, während der Übertragung und im Computing. Ein wichtiger Bestandteil jedes KI-Inferenz-Services sollte der Schutz der Daten vor Bedrohungen während des gesamten Prozesses sein. Der Schutz von Daten während der Inferenz ist von großer Bedeutung, da der Prozess private Informationen über externe Kunden und das Unternehmen, das den Inferenzservice bereitstellt, offenlegen kann. Protopia AI ist eine nicht aufdringliche rein softwarebasierte Lösung für vertrauliche KI-Inferenz auf dem heutigen Markt. Mit Protopia werden KI nur die transformierten Informationen in den Datensätzen gespeist, die für die Durchführung der KI/ML-Aufgabe am wichtigsten sind – und nicht mehr. Diese stochastische Transformation ist keine Form der Maskierung und basiert auf mathematisch veränderten Darstellung der Daten durch die Verwendung kuratierter Geräusche.

NetApp Storage-Systeme mit ONTAP-Funktionen bieten dieselbe oder bessere Performance wie lokaler SSD-Storage und bieten in Kombination mit dem NetApp DataOps Toolkit Data Scientists, Data Engineers, KI/ML-Entwickler und Entscheidungsträger in Unternehmen oder IT die folgenden Vorteile:

* Problemlose gemeinsame Nutzung von Daten zwischen KI-Systemen, Big-Data-Analysen und anderen geschäftskritischen Systemen Diese gemeinsame Nutzung von Daten verringert den Infrastruktur-Overhead, verbessert die Performance und optimiert das Datenmanagement im gesamten Unternehmen.
* Unabhängig skalierbare Computing- und Storage-Ressourcen minimieren Kosten und verbessern die Ressourcenauslastung.
* Optimierte Entwicklungs- und Implementierungs-Workflows mithilfe integrierter Snapshot Kopien und Klone für sofortige und platzsparende Benutzer-Workspaces, integrierte Versionskontrolle und automatisierte Implementierung
* Datensicherung und Data Governance der Enterprise-Klasse für Disaster Recovery, Business Continuity und gesetzliche Vorschriften.
* Vereinfachtes Aufrufen von Datenmanagement-Prozessen; schnelle Erstellung von Snapshot Kopien von Arbeitsbereichen für Data Scientists zur Sicherung und Rückverfolgbarkeit über das NetApp DataOps Toolkit in Jupyter Notebooks.


Die Lösung von NetApp und Protopia bietet eine flexible Scale-out-Architektur, die sich ideal für KI-Inferenz-Implementierungen der Enterprise-Klasse eignet. Sie ermöglicht Datensicherung und Datenschutz für sensible Informationen, bei denen vertrauliche KI-Inferenz-Anforderungen mit verantwortlichen AI-Praktiken sowohl in On-Premises- als auch in Hybrid-Cloud-Implementierungen erfüllt werden können.

link:ai-protopia-where-to-find-additional-information,-acknowledgements,-and-version-history.html["Weiter: Wo finden Sie zusätzliche Informationen, Danksagungen und Versionsverlauf."]
