---
sidebar: sidebar 
permalink: ai/ai-sent-support-center-analytics.html 
keywords: tr-4910, tr4910, 4910, sentiment, analysis, customer value, support center, artificial intelligence 
summary: Dieser technische Bericht bietet Orientierungshilfen für Kunden, um eine Sentimentanalyse in einem globalen Support Center der Enterprise-Klasse durchzuführen. Dazu werden Datenmanagement-Technologien von NetApp mit einem NVIDIA Software-Framework genutzt, wobei Transfer-Learning und umgangssprachlich KI verwendet werden. 
---
= TR-4910: Sentiment Analysis from Customer Communications with NetApp AI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Rick Huang, Sathish Thyagarajan und David Arnette, NetApp Diego Sosa-Coba, SFL Scientific

[role="lead"]
Dieser technische Bericht bietet Orientierungshilfen für Kunden, um eine Sentimentanalyse in einem globalen Support Center der Enterprise-Klasse durchzuführen. Dazu werden Datenmanagement-Technologien von NetApp mit einem NVIDIA Software-Framework genutzt, wobei Transfer-Learning und umgangssprachlich KI verwendet werden. Diese Lösung ist für alle Branchen geeignet, die aus aufgezeichneten sprach- oder Textdateien, die Chat-Protokolle, E-Mails und andere Text- oder Audiokommunikation darstellen, Kundeneinblicke gewinnen möchten. Wir implementierten eine End-to-End-Pipeline, um die automatische Spracherkennung, Sentimentanalyse in Echtzeit und das Deep-Learning-Modell mit natürlicher Sprache zu demonstrieren – Umschulungsfunktionen auf einem GPU-beschleunigten Computing-Cluster mit NetApp All-Flash-Storage mit Cloud-Integration. Mit dem globalen Support Center können riesige, hochmoderne Sprachmodelle trainiert und optimiert werden, um Inferenz schnell durchzuführen. Das System bietet eine außergewöhnlich hohe Kundenzufriedenheit, und eine objektive, langfristige Beurteilung der Mitarbeiterleistung.

Sentimentanalyse ist ein Studienfeld innerhalb der natürlichen Sprachverarbeitung (NLP), durch das positive, negative oder neutrale Gefühle aus dem Text extrahiert werden. Konvergente KI-Systeme sind auf eine nahezu globale Ebene der Integration angestiegen, da immer mehr Menschen mit ihnen interagieren. Sentiment-Analyse hat eine Vielzahl von Anwendungsbeispielen: Von der Ermittlung der Mitarbeiterleistung im Support-Center in Gesprächen mit Anrufern und der Bereitstellung geeigneter automatischer Chatbot-Antworten bis zur Prognose des Aktienpreises eines Unternehmens auf der Grundlage der Wechselwirkungen zwischen den Vertretern des Unternehmens und den Zuschauern bei vierteljährlichen Ergebnisgesprächen. Darüber hinaus kann die Sentiment-Analyse verwendet werden, um die Meinung des Kunden über die Produkte, Dienstleistungen oder Unterstützung der Marke zu bestimmen.

Diese End-to-End-Lösung verwendet NLP-Modelle, um eine hochrangige Sentimentanalyse durchzuführen, die analytische Frameworks für Support-Center ermöglicht. Audioaufzeichnungen werden in geschriebenen Text verarbeitet, und die Stimmung wird aus jedem Satz im Gespräch extrahiert. Ergebnisse, die in einem Dashboard zusammengefasst werden, können so erstellt werden, dass Gesprächsgefühlen sowohl historisch als auch in Echtzeit analysiert werden können. Diese Lösung kann mit anderen Lösungen mit ähnlichen Datenmodalitäten und Ausgabeanforderungen verallgemeinert werden. Mit den entsprechenden Daten können andere Anwendungsfälle durchgeführt werden. So können beispielsweise die Ergebnisaufrufe des Unternehmens anhand derselben End-to-End-Pipeline auf die Stimmung analysiert werden. Auch andere Formen von NLP-Analysen, wie zum Beispiel Topic Modeling und Named Entity Recognition (NER), sind aufgrund der flexiblen Natur der Pipeline möglich.

Diese KI-Implementierungen wurden von NVIDIA RIVA, dem NVIDIA TAO Toolkit und dem gemeinsam arbeiteten NetApp DataOps Toolkit ermöglicht. Die NVIDIA Tools werden verwendet, um hoch performante KI-Lösungen mithilfe von vordefinierten Modellen und Pipelines schnell zu implementieren. Das NetApp DataOps Toolkit vereinfacht verschiedene Datenmanagement-Aufgaben und beschleunigt so die Entwicklung.



== Mehrwert für den Kunden

Unternehmen sehen den Nutzen einer Mitarbeiterbewertung und eines Tools zur Reaktion auf Kundenverhalten bei Text-, Audio- und Videogesprächen für die Sentimentanalyse. Manager profitieren von den Informationen, die in der Konsole dargestellt werden, und können so auf beiden Seiten des Gesprächs eine Bewertung der Mitarbeiter und die Kundenzufriedenheit durchführen.

Darüber hinaus managt das NetApp DataOps Toolkit die Versionierung und Zuweisung von Daten innerhalb der Infrastruktur des Kunden. Dies führt zu häufigen Updates der im Dashboard verfügbaren Analysen, ohne dass dabei unhandliche Storage-Kosten entstehen.
