---
sidebar: sidebar 
permalink: ai/ai-sent-deploying-support-center-sentiment-analysis.html 
keywords: deploy, NetApp DataOps Toolkit, NGC Configuration, NVIDIA RIVA Server, NVIDIA TAO Toolkit, Export TAO models to RIVA 
summary: Dieser Abschnitt beschreibt die detaillierten Schritte, die zur Implementierung dieser Lösung erforderlich sind. 
---
= Bereitstellung der Sentimentanalyse des Support Centers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-sent-design-considerations.html["Früher: Designüberlegungen."]

[role="lead"]
Zum Einsatz der Lösung gehören die folgenden Komponenten:

. NetApp DataOps Toolkit
. NGC-Konfiguration
. NVIDIA RIVA Server
. NVIDIA TAO Toolkit
. Exportieren Sie TAO-Modelle nach RIVA


Um eine Implementierung durchzuführen, gehen Sie wie folgt vor:



== NetApp DataOps Toolkit: Die Stimmungsanalyse im Support Center

Um die zu verwenden https://github.com/NetApp/netapp-dataops-toolkit["NetApp DataOps Toolkit"^], Vervollständigen Sie die folgenden Schritte:

. PIP installieren Sie das Toolkit.
+
....
python3 -m pip install netapp-dataops-traditional
....
. Konfigurieren des Datenmanagements
+
....
netapp_dataops_cli.py config
....




== NGC-Konfiguration: Support Center-Sentiment-Analyse

Zur Einrichtung https://ngc.nvidia.com/setup/installers/cli["NVIDIA NGC"^], Vervollständigen Sie die folgenden Schritte:

. NGC herunterladen
+
....
wget -O ngccli_linux.zip https://ngc.nvidia.com/downloads/ngccli_linux.zip && unzip -o ngccli_linux.zip && chmod u+x ngc
....
. Fügen Sie Ihr aktuelles Verzeichnis zum Pfad hinzu.
+
....
echo "export PATH=\"\$PATH:$(pwd)\"" >> ~/.bash_profile && source ~/.bash_profile
....
. Sie müssen NGC-CLI für Ihren Gebrauch konfigurieren, damit Sie die Befehle ausführen können. Geben Sie bei der entsprechenden Aufforderung den folgenden Befehl ein, einschließlich Ihres API-Schlüssels.
+
....
ngc config set
....


Für nicht Linux-basierte Betriebssysteme finden Sie unter https://ngc.nvidia.com/setup/installers/cli["Hier"^].



== NVIDIA RIVA Server: Support Center Sentiment Analyse

Zur Einrichtung https://docs.nvidia.com/deeplearning/riva/user-guide/docs/quick-start-guide.html["NVIDIA RIVA"^], Vervollständigen Sie die folgenden Schritte:

. Laden Sie DIE RIVA-Dateien von NGC herunter.
+
....
ngc registry resource download-version nvidia/riva/riva_quickstart:1.4.0-beta
....
. RIVA-Setup initialisieren (`riva_init.sh`).
. Starten Sie DEN RIVA-Server (`riva_start.sh`).
. Starten Sie DEN RIVA-Client (`riva_start_client.sh`).
. Installieren Sie im RIVA-Client die Audio-Processing-Library ( https://ffmpeg.org/download.html["FFMPEG"^])
+
....
apt-get install ffmpeg
....
. Starten Sie den https://jupyter-server.readthedocs.io/en/latest/["Jupyter"^] Server:
. Führen Sie das RIVA Inferenz Pipeline Notebook aus.




== NVIDIA TAO Toolkit: Sentimentanalyse im Supportcenter

Gehen Sie wie folgt vor, um das NVIDIA TAO Toolkit einzurichten:

. Vorbereiten und Aktivieren eines https://docs.python.org/3/library/venv.html["Virtualisierten Umgebung von"^] Für TAO Toolkit.
. Installieren Sie den https://docs.nvidia.com/tao/tao-toolkit/text/tao_toolkit_quick_start_guide.html["Erforderliche Pakete"^].
. Ziehen Sie das während des Trainings und der Feinabstimmung verwendete Bild manuell ab.
+
....
docker pull nvcr.io/nvidia/tao/tao-toolkit-pyt:v3.21.08-py3
....
. Starten Sie den https://jupyter-server.readthedocs.io/en/latest/["Jupyter"^] Server:
. Führen Sie das TAO Fine-Tuning Notebook aus.




== Export von TAO-Modellen nach RIVA: Sentimentanalyse im Supportzentrum

Zu verwenden https://docs.nvidia.com/tao/tao-toolkit/text/riva_tao_integration.html["TAO Toolkit Modelle in RIVA"^], Vervollständigen Sie die folgenden Schritte:

. Speichern Sie Modelle im TAO Fine-Tuning Notebook.
. Kopieren Sie TAO-trainierte Modelle in das RIVA-Modellverzeichnis.
. Starten Sie DEN RIVA-Server (`riva_start.sh`).




== Hürden auf dem Weg zur Implementierung

Bitte beachten Sie folgende Punkte bei der Entwicklung Ihrer eigenen Lösung:

* Das NetApp DataOps Toolkit wird zuerst installiert, um sicherzustellen, dass das Storage-System optimal läuft.
* NVIDIA NGC muss vor allem installiert sein, weil es das Herunterladen von Bildern und Modellen authentifiziert.
* RIVA muss vor dem TAO Toolkit installiert werden. Die RIVA-Installation konfiguriert den Docker-Daemon so, dass Bilder nach Bedarf abgerufen werden.
* DGX und Docker müssen über Internetzugang verfügen, um die Modelle herunterladen zu können.


link:ai-sent-validation-results.html["Weiter: Validierungsergebnisse."]
