---
sidebar: sidebar 
permalink: ai/ai-sent-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Wo Sie weitere Informationen finden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-sent-conclusion.html["Zurück: Schlussfolgerung."]

[role="lead"]
Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* Interaktive 3D-Demos
+
http://www.netapp.com/ai["www.netapp.com/ai"^]

* Direkter Austausch mit einem NetApp KI-Experten
+
https://www.netapp.com/artificial-intelligence/["https://www.netapp.com/artificial-intelligence/"^]

* NVDIA Base Command Platform mit NetApp – Lösungsüberblick
+
https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf["https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf"^]

* Infografik: NetApp for AI 10 gute Gründe
+
https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf["https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf"^]

* AI im Gesundheitswesen: Deep Learning zur Identifizierung von COVID-19 Läsionen in Lungen-CT-Scans Whitepaper
+
https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf["https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf"^]

* KI im Gesundheitswesen: Whitepaper zur Überwachung der Gesichtsmaske in Einstellungen für das Gesundheitswesen
+
https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf["https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf"^]

* KI im Gesundheitswesen: Technischer Bericht zur diagnostischen Bildgebung
+
https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf["https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf"^]

* AI für den Einzelhandel: NetApp Convertional AI mit NVIDIA RIVA
+
https://docs.netapp.com/us-en/netapp-solutions/ai/cainvidia_executive_summary.html["https://docs.netapp.com/us-en/netapp-solutions/ai/cainvidia_executive_summary.html"^]

* NetApp ONTAP AI – Lösungsüberblick
+
https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf["https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf"^]

* NetApp DataOps Toolkit – Lösungsüberblick
+
https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf["https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf"^]

* NetApp AI Control Plane – Lösungsüberblick
+
https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf["https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf"^]

* Wie Sie ganze Branchen mithilfe von KI-eBook „Daten verändern“
+
https://www.netapp.com/us/media/na-337.pdf["https://www.netapp.com/us/media/na-337.pdf"^]

* NetApp EF-Series KI – Lösungsüberblick
+
https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf["https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf"^]

* Lösungsüberblick: NetApp AI und Lenovo ThinkSystem für KI-Inferenz
+
https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf["https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf"^]

* NetApp AI und Lenovo ThinkSystem für Enterprise-KI und -ML – Lösungsüberblick
+
https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf["https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf"^]

* NetApp und NVIDIA – Definieren Sie, was möglich ist, mit KI-Video
+
https://www.youtube.com/watch?v=38xw65SteUc["https://www.youtube.com/watch?v=38xw65SteUc"^]


