---
sidebar: sidebar 
permalink: ai/aicp_performance_testing.html 
keywords: Performance, Testing, benchmark, Tensorflow, Docker 
summary: Bei der Erstellung dieser Lösung haben wir einen einfachen Performance-Vergleich durchgeführt. Wir haben mithilfe von Kubernetes mehrere standardmäßige NetApp Benchmark-Aufgaben durchgeführt. Die Benchmark-Ergebnisse wurden mit den Ausführung von Exekutionen verglichen, die über einen einfachen Docker Run-Befehl ausgeführt wurden. 
---
= Performance-Tests
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Bei der Erstellung dieser Lösung haben wir einen einfachen Performance-Vergleich durchgeführt. Wir haben mithilfe von Kubernetes mehrere standardmäßige NetApp KI-Benchmark-Jobs ausgeführt. Die Benchmark-Ergebnisse wurden mit Ausführungsvorgängen verglichen, die über einen einfachen Docker Run-Befehl ausgeführt wurden. Wir haben keine spürbaren Unterschiede in der Performance gesehen. Daher kamen wir zu dem Schluss, dass die Verwendung von Kubernetes zur Orchestrierung von Training-Jobs in Container-KI keine negative Auswirkung auf die Performance hat. Die Ergebnisse unseres Performance-Vergleichs finden Sie in der folgenden Tabelle.

|===
| Benchmark | Datensatz | Docker Run (Images/Sek.) | Kubernetes (Bilder/Sek.) 


| TensorFlow mit einem Node | Synthetische Daten | 6,667.2475 | 6,661.93125 


| TensorFlow mit einem Node | ImageNet | 6,570.2025 | 6,530.59125 


| Synchrones verteiltes TensorFlow mit zwei Knoten | Synthetische Daten | 13,213.70625 | 13,218.288125 


| Synchrones verteiltes TensorFlow mit zwei Knoten | ImageNet | 12,941.69125 | 12,881.33875 
|===