---
sidebar: sidebar 
permalink: ai/aicp_example_notebooks_and_pipelines.html 
keywords: Jupyter Notebook, Kubeflow Pipeline, NetApp DataOps Toolkit 
summary: Open Source MLOPS with NetApp – Verwenden Sie das NetApp DataOps Toolkit mit Kubeflow 
---
= Verwenden Sie das NetApp DataOps Toolkit mit Kubeflow
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s["Das NetApp Data Science Toolkit für Kubernetes"] Kann in Verbindung mit Kubeflow verwendet werden. Die Verwendung des NetApp Data Science Toolkit und Kubeflow bietet folgende Vorteile:

* Data Scientists können fortschrittliche NetApp-Datenmanagement-Vorgänge, wie das Erstellen von Snapshots und Klonen, direkt von einem Jupyter Notebook aus durchführen.
* Erweiterte NetApp Datenmanagement-Operationen wie das Erstellen von Snapshots und Klonen können mithilfe des Kubeflow Pipelines-Frameworks in automatisierte Workflows integriert werden.


Siehe https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s/Examples/Kubeflow["Kubeflow Beispiele"] Im Abschnitt zum NetApp Data Science Toolkit GitHub Repository finden Sie weitere Informationen zur Verwendung des Toolkit mit Kubeflow.
