---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: Open Source-MLOps mit NetApp – Architektur 
---
= Der Netapp Architektur Sind
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Diese Lösung ist nicht von bestimmter Hardware abhängig. Die Lösung ist mit jeder physischen NetApp Storage Appliance, jeder softwaredefinierten Instanz oder jedem Cloud-Service kompatibel, der von Trident unterstützt wird. Beispiele hierfür sind ein NetApp AFF Storage-System, Amazon FSX für NetApp ONTAP, Azure NetApp Files oder eine NetApp Cloud Volumes ONTAP Instanz. Darüber hinaus kann die Lösung auf jedem Kubernetes-Cluster implementiert werden, solange die verwendete Kubernetes-Version von Kubeflow und NetApp Astra Trident unterstützt wird. Eine Liste der von Kubeflow unterstützten Kubernetes-Versionen finden Sie im https://www.kubeflow.org/docs/started/getting-started/["Offizielle Dokumentation von Kubeflow"^]. Eine Liste der von Trident unterstützten Kubernetes-Versionen finden Sie im https://docs.netapp.com/us-en/trident/index.html["Trident Dokumentation"^]. In den folgenden Tabellen finden Sie Einzelheiten zur Umgebung, die zur Validierung der Lösung verwendet wurde.

|===
| Software-Komponente | Version 


| Apache Airflow | 2.0.1 


| Apache Airflow Helm Chart | 8.0.8 


| Kubeflow | 1.7, bereitgestellt über link:https://www.deploykf.org["Einsatz KF"] 0.1.1 


| Kubernetes | 1.26 


| NetApp Astra Trident | 23.07 
|===


== Unterstützung

NetApp bietet keine Enterprise-Unterstützung für Apache Airflow, Kubeflow oder Kubernetes. Wenn Sie an einer vollständig unterstützten MLOPS-Plattform interessiert sind, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["Kontakt zu NetApp"] Über vollständig unterstützte MLOps-Lösungen die NetApp gemeinsam mit Partnern anbietet.
