---
sidebar: sidebar 
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html 
keywords: Trident, Kubernetes, Storageclass 
summary: Auf dieser Seite werden die Aufgaben beschrieben, die Sie abschließen müssen, um NetApp Trident in Ihrem Kubernetes Cluster zu installieren und zu konfigurieren. 
---
= Implementierung und Konfiguration von NetApp Trident
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die Aufgaben beschrieben, die Sie abschließen müssen, um NetApp Trident in Ihrem Kubernetes Cluster zu installieren und zu konfigurieren.



== Voraussetzungen

Bevor Sie die in diesem Abschnitt beschriebenen Bereitstellungsaufgaben ausführen, gehen wir davon aus, dass Sie bereits die folgenden Aufgaben ausgeführt haben:

. Sie verfügen bereits über ein funktionierendes Kubernetes Cluster und führen eine von Trident unterstützte Version von Kubernetes aus. Eine Liste der unterstützten Versionen finden Sie im https://docs.netapp.com/us-en/trident/["Trident Dokumentation"^].
. Sie verfügen bereits über eine funktionierende NetApp Storage Appliance, softwaredefinierte Instanz oder Cloud-Storage-Service, die von Trident unterstützt wird.




== Installation Von Trident

Um NetApp Trident in Ihrem Kubernetes-Cluster zu installieren und zu konfigurieren, führen Sie die folgenden Aufgaben über den Jump-Host der Implementierung aus:

. Trident lässt sich mit einer der folgenden Methoden implementieren:
+
** Wenn Sie zur Implementierung Ihres Kubernetes-Clusters NVIDIA DeepOps verwendet haben, können Sie Trident auch mit NVIDIA DeepOps in Ihrem Kubernetes-Cluster implementieren. Folgen Sie zur Implementierung von Trident mit DeepOps dem https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident["Trident Implementierungsanleitungen"] Auf der NVIDIA DeepOps GitHub Website.
** Wenn Sie NVIDIA DeepOps nicht zur Implementierung Ihres Kubernetes-Clusters verwendet haben oder Trident einfach manuell implementieren möchten, können Sie Trident anhand der implementieren https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["Implementierungsanleitungen"^] In der Trident Dokumentation. Erstellen Sie mindestens ein Trident Back-End und mindestens eine Kubernetes StorageClass. Sie erhalten weitere Informationen zur Konfiguration https://docs.netapp.com/us-en/trident/trident-use/backends.html["Back-Ends"^] Und https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["StorageClasses"^] Siehe verlinkte Unterabschnitte bei NetApp Docs.
+

NOTE: Wenn Sie die NetApp AI Control Plane Lösung auf einem ONTAP AI POD implementieren, lesen Sie link:aicp_example_trident_backends_for_ontap_ai_deployments.html["Beispiel Trident Back-Ends für ONTAP KI-Implementierungen"] Beispiele für verschiedene Trident Back-Ends, die Sie möglicherweise erstellen möchten, und link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["Beispiel: Kubernetes Storageclasses für ONTAP AI Implementierungen"] Für einige Beispiele für verschiedene Kubernetes StorageClasses, die Sie vielleicht erstellen möchten.




