---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NetApp AI Pod mit NVIDIA DGX Systemen – Fazit 
---
= NetApp AI Pod mit NVIDIA DGX Systemen – Fazit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_storage.html["Früher: NetApp KI-Pod mit NVIDIA DGX-Systemen – Leitfaden für Storage-Systemdesign und Größenbestimmung"]



== Schlussfolgerung

Die DGX-BasePOD-Architektur ist eine Deep-Learning-Plattform der nächsten Generation, für die gleichermaßen fortschrittliche Storage- und Datenmanagementfunktionen erforderlich sind. Durch die Kombination von DGX BasePOD mit NetApp AFF Systemen kann diese Architektur in nahezu jeder Größenordnung implementiert werden: Von einem einzelnen DGX A100 in Kombination mit einem AFF A250 Storage-System bis zu 48 DGX A100-Systeme auf einem AFF A800 Cluster mit 24 Nodes. In Verbindung mit der erstklassigen Cloud-Integration und den softwaredefinierten Funktionen von NetApp ONTAP unterstützt AFF eine breite Palette an Daten-Pipelines, die Edge, Core und Cloud einschließen und für den Erfolg von DL-Projekten sorgen.

link:aipod_nv_additional_information.html["Weiter: NetApp AI Pod mit NVIDIA DGX Systemen - weitere Informationen."]
