---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NetApp AIPod mit NVIDIA DGX Systemen – Weitere Informationen 
---
= NetApp AIPod mit NVIDIA DGX Systemen – Zusammenfassung und weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["Zurück: NetApp AIPod mit NVIDIA DGX Systemen – Lösungsvalidierung und Leitfaden zur Größenbestimmung"]



== Schlussfolgerung

Die DGX-BasePOD-Architektur ist eine Deep-Learning-Plattform der nächsten Generation, für die gleichermaßen fortschrittliche Storage- und Datenmanagementfunktionen erforderlich sind. Durch die Kombination von DGX BasePOD mit NetApp AFF Systemen kann der NetApp AIPod mit der DGX Systemarchitektur in nahezu jeder Größenordnung auf bis zu 48 DGX H100 Systemen auf einem AFF A900-Cluster mit 24 Nodes implementiert werden. In Verbindung mit der erstklassigen Cloud-Integration und den softwaredefinierten Funktionen von NetApp ONTAP unterstützt AFF eine breite Palette an Daten-Pipelines, die Edge, Core und Cloud einschließen und für den Erfolg von DL-Projekten sorgen.



== Weitere Informationen

Weitere Informationen zu den in diesem Dokument beschriebenen Daten finden Sie in den folgenden Dokumenten bzw. auf den folgenden Websites:

* NetApp ONTAP Datenmanagement-Software – ONTAP Informationsbibliothek
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A900 Storage-Systeme –
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* NetApp ONTAP RDMA-Informationen-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps Toolkit
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* NetApp GPUDirect Storage-Blog-
+
https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/["https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/"]

* NVIDIA DGX BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX H100-SYSTEME
+
https://www.nvidia.com/en-us/data-center/dgx-h100/["https://www.nvidia.com/en-us/data-center/dgx-h100/"^]

* NVIDIA Networking
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA Magnum IO GPUDirect Storage
+
https://docs.nvidia.com/gpudirect-storage["https://docs.nvidia.com/gpudirect-storage"]

* NVIDIA Base-Befehl
+
https://www.nvidia.com/en-us/data-center/base-command/["https://www.nvidia.com/en-us/data-center/base-command/"]

* NVIDIA Base Command Manager
+
https://www.nvidia.com/en-us/data-center/base-command/manager["https://www.nvidia.com/en-us/data-center/base-command/manager"]

* NVIDIA AI Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== Danksagungen

Dieses Dokument ist die Arbeit der NetApp Solutions und ONTAP Engineering Teams - David Arnette, Olga Kornievskaia, Dustin Fischer, Srikanth Kaligotla, Mohit Kumar und Rajeev Badrinath. Zudem möchten sie sich bei NVIDIA und dem NVIDIA DGX BasePOD Engineering-Team für die fortgesetzte Unterstützung bedanken.
