---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NetApp AIPod mit NVIDIA DGX Systemen – Weitere Informationen 
---
= NetApp AIPod mit NVIDIA DGX Systemen – Zusammenfassung und weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["Zurück: NetApp AIPod mit NVIDIA DGX Systemen – Lösungsvalidierung und Leitfaden zur Größenbestimmung"]



== Schlussfolgerung

Die DGX-BasePOD-Architektur ist eine Deep-Learning-Plattform der nächsten Generation, für die gleichermaßen fortschrittliche Storage- und Datenmanagementfunktionen erforderlich sind. Durch die Kombination von DGX BasePOD mit NetApp AFF Systemen kann die NetApp AIPod Architektur in nahezu jeder Größenordnung implementiert werden – von einer einzelnen GPU in einem OEM-Server in Kombination mit einem AFF A250 Storage-System bis zu 48 DGX H100 Systeme auf einem AFF A900-Cluster mit 24 Nodes. In Verbindung mit der erstklassigen Cloud-Integration und den softwaredefinierten Funktionen von NetApp ONTAP unterstützt AFF eine breite Palette an Daten-Pipelines, die Edge, Core und Cloud einschließen und für den Erfolg von DL-Projekten sorgen.



== Weitere Informationen

Weitere Informationen zu den in diesem Dokument beschriebenen Daten finden Sie in den folgenden Dokumenten bzw. auf den folgenden Websites:

* NetApp ONTAP Datenmanagement-Software – ONTAP Informationsbibliothek
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A900 Storage-Systeme –
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* NetApp ONTAP RDMA-Informationen-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps Toolkit
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* ONTAP AI – NetApp Validated Architectures mit NVIDIA DGX A100 Systemen
+
https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html["https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html"^]

* NVIDIA BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX A100 SYSTEME
+
https://www.nvidia.com/en-us/data-center/dgx-a100/["https://www.nvidia.com/en-us/data-center/dgx-a100/"^]

* NVIDIA Networking
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA AI Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== Danksagungen

Dieses Dokument ist die Arbeit der NetApp Solutions und ONTAP Engineering Teams - David Arnette, Olga Kornievskaia, Dustin Fischer, Srikanth Kaligotla, Mohit Kumar und Rajeev Badrinath. Die Autoren bedanken sich außerdem bei NVIDIA und dem BasePOD-Engineering-Team für die fortgesetzte Unterstützung.
