---
sidebar: sidebar 
permalink: ai/aks-anf_click-through_rate_prediction_use_case_summary.html 
keywords: use case, terabyte click log, random forest, training 
summary: Auf dieser Seite sind die Vorteile von Azure NetApp Files bei Schulungen mit verteilter oder großer Schulungseinheiten zusammengefasst. 
---
= Anwendungsbeispiel für die Click-Through-Rate-Prognose
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_cloud_resource_requirements.html["Früher: Anforderungen an Cloud-Ressourcen."]

[role="lead"]
Dieser Anwendungsfall basiert auf dem öffentlich zugänglichen http://["Terabyte Auf Protokolle Klicken"^] Datensatz von https://["Criteo AI Lab"^]. Aufgrund der jüngsten Fortschritte BEI ML-Plattformen und -Applikationen wird jetzt viel Aufmerksamkeit auf das Lernen in großen Umgebungen gerichtet. Die Klickrate (Klickrate, CTR) ist definiert als die durchschnittliche Anzahl der Klickrate pro hundert Online-Werbeeindrücke (ausgedrückt als Prozentsatz). Es wird in verschiedenen Branchen und Anwendungsfällen, darunter digitales Marketing, Einzelhandel, E-Commerce und Service-Provider, häufig als wichtige Metrik eingeführt. Beispiele für die Verwendung von CTR als wichtige Kennzahl für potenziellen Kundenverkehr sind:

* *Digital Marketing:* in https://["Google Analytics"^], CTR kann verwendet werden, um zu messen, wie gut ein Werbetreibender oder Kaufmann die Keywords, Anzeigen und kostenlose Angebote durchführen. Ein hoher CTR ist ein guter Hinweis darauf, dass Benutzer Ihre Anzeigen und Inserate hilfreich und relevant finden. CTR trägt auch zu Ihrem Keyword erwartet CTR, die eine Komponente von ist https://["Anzeigeneinstufung"^].
* *E-Commerce:* Neben der Nutzung https://["Google Analytics"^], Es gibt mindestens einige Besucherstatistiken in einem E-Commerce-Backend. Obwohl diese Statistiken auf den ersten Blick nicht nützlich erscheinen, sind sie in der Regel leicht zu lesen und können genauer als andere Informationen sein. Datensätze von Erstanbietern, die sich aus diesen Statistiken zusammensetzt, sind vertraulich und daher am wichtigsten für E-Commerce-Verkäufer, Käufer und Plattformen. Diese Datensätze können zur Festlegung von Benchmarks verwendet und mit dem Ergebnis vom letzten Jahr und von gestern verglichen werden, indem eine Zeitreihe zur weiteren Analyse erstellt wird.
* *Einzelhandel:* stationäre Einzelhändler können die Anzahl der Besucher und die Anzahl der Kunden mit dem CTR korrelieren. Die Anzahl der Kunden kann aus ihrer Verkaufsgeschichte ersichtlich werden. Die CTR von den Webseiten des Einzelhändlers oder Werbeverkehr kann zu den oben genannten Verkäufen führen. Treueprogramme sind ein weiterer Anwendungsfall, weil Kunden von Online-Anzeigen oder anderen Websites umgeleitet werden könnten, um Belohnungen zu verdienen. Einzelhändler können Kunden über Treueprogramme gewinnen und Verhaltensweisen aus Verkaufsprogrammen aufzeichnen, um ein Empfehlungssystem zu entwickeln, das nicht nur das Kaufverhalten der Verbraucher in verschiedenen Kategorien prognostiziert, sondern auch Coupons personalisiert und Abgänge verringert.
* *Service-Provider:* Telekommunikationsunternehmen und Internet-Service-Provider haben eine Fülle an Telemetriedaten von Erstbenutzern für aufschlussreiche KI-, ML- und Analytics-Anwendungsfälle. So kann ein Telekommunikationsanbieter beispielsweise täglich die Protokolle der Top-Level-Domain-Historie seiner mobilen Abonnenten nutzen, um vorhandene Modelle zu optimieren, um eine aktuelle Segmentierung der Zielgruppe zu erstellen, das Kundenverhalten vorherzusagen und mit Werbetreibenden zusammenzuarbeiten, um Anzeigen in Echtzeit zu platzieren, um ein besseres Online-Erlebnis zu ermöglichen. In einem solchen datengesteuerten Marketing-Workflow ist CTR eine wichtige Kennzahl, um Konvertierungen widerzuspiegeln.


Im Rahmen des digitalen Marketings http://["Criteo Terabyte Klicken Sie Auf Protokolle"^] Sind jetzt der Referenzdatensatz zur Bewertung der Skalierbarkeit VON ML-Plattformen und -Algorithmen. Mit der Prognose der Klickrate kann ein Werbetreibender die Besucher auswählen, die am ehesten auf die Werbeanzeigen antworten, seinen Browserverlauf analysieren und die relevantesten Werbeanzeigen basierend auf den Interessen des Benutzers anzeigen.

Die in diesem technischen Bericht bereitgestellte Lösung hebt die folgenden Vorteile hervor:

* Vorteile von Azure NetApp Files bei verteilten oder umfassenden Schulungen
* RAPIDS CUDA-fähige Datenverarbeitung (cuDF, cuPy usw.) und ML-Algorithmen (cuML)
* Das Parallel Computing Framework für verteilte Schulungen


Ein umfassender Workflow auf Basis VON RAPIDS AI und Azure NetApp Files zeigt eine drastische Verbesserung des Trainings für zufällige Waldmodelle im zwei Größenordnungen. Diese Verbesserung ist im Vergleich zum herkömmlichen Pandas-Ansatz signifikant, wenn es um real-world click Logs mit 45GB strukturierter tabellarischer Daten (im Durchschnitt) jeden Tag geht. Dies entspricht einem DataFrame mit etwa zwanzig Milliarden Zeilen. In diesem technischen Bericht werden die Einrichtung einer Cluster-Umgebung, die Installation eines Framework und einer Bibliothek, das Laden und die Verarbeitung von Daten, das konventionelle oder verteilte Training, die Visualisierung und das Monitoring demonstriert und die kritischen Ergebnisse der End-to-End-Laufzeit verglichen.

link:aks-anf_install_and_set_up_the_aks_cluster.html["Als nächstes: Installieren und einrichten Sie das aks Cluster."]
