---
sidebar: sidebar 
permalink: ai/aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html 
keywords: toolkit, dataops, kubernetes, abstraction, python, jupyterlab 
summary: Das NetApp DataOps Toolkit für Kubernetes abstrahiert Storage-Ressourcen und Kubernetes-Workloads bis auf die Ebene des Data Science Workspace. Diese Funktionen sind in einer einfachen, benutzerfreundlichen Oberfläche zusammengestellt, die für Data Scientists und Data Engineers konzipiert wurde. 
---
= Datensatz- und Modellversionierung mit NetApp DataOps Toolkit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Das NetApp DataOps Toolkit für Kubernetes abstrahiert Storage-Ressourcen und Kubernetes-Workloads bis auf die Ebene des Data Science Workspace. Diese Funktionen sind in einer einfachen, benutzerfreundlichen Oberfläche zusammengestellt, die für Data Scientists und Data Engineers konzipiert wurde. Mit der bekannten Form eines Python-Programms ermöglicht das Toolkit Data Scientists und Ingenieuren die Bereitstellung und Zerstörung von JupyterLab-Arbeitsbereichen in nur wenigen Sekunden. Diese Workspaces können Storage-Kapazität im Terabyte- oder sogar Petabyte-Bereich enthalten. Data Scientists können all ihre Trainingsdatensätze direkt in ihren Projektarbeitsbereichen speichern. Die Tage für das separate Management von Workspaces und Daten-Volumes sind vorbei.

Weitere Informationen finden Sie im Toolkit https://github.com/NetApp/netapp-data-science-toolkit["GitHub Repository"^].
