---
sidebar: sidebar 
permalink: ai/cainvidia_executive_summary.html 
keywords: WP-7328, wp7328, 7328, Executive Summary, NVIDIA, Jarvis, 
summary:  
---
= WP-7328: NetApp Convergentional AI mit NVIDIA Jarvis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, Sung-Han Lin, NetApp Davide Onofrio, NVIDIA

[role="lead"]
Die NVIDIA DGX-Systemfamilie besteht aus den weltweit ersten integrierten Systemen für künstliche Intelligenz (KI), die speziell für Enterprise-KI entwickelt wurden. NetApp AFF Storage-Systeme bieten extrem hohe Performance und branchenführende Funktionen für das Hybrid-Cloud-Datenmanagement. NetApp und NVIDIA haben gemeinsam die NetApp ONTAP AI Referenzarchitektur entwickelt, eine sofort einsatzbereite Lösung für KI- und ML-Workloads (Machine Learning) mit Performance, Zuverlässigkeit und Support der Enterprise-Klasse.

Dieses Whitepaper gibt Kunden eine Orientierungshilfe beim Aufbau konversationaler KI-Systeme zur Unterstützung verschiedener Anwendungsfälle in verschiedenen Branchen. Es enthält Informationen über die Bereitstellung des Systems mit NVIDIA Jarvis. Die Tests wurden mit einer NVIDIA DGX Station und einem NetApp AFF A220 Storage-System durchgeführt.

Die Zielgruppe für die Lösung umfasst die folgenden Gruppen:

* Enterprise-Architekten, die Lösungen für die Entwicklung von KI-Modellen und -Software für umgangssprachlich KI-Anwendungsfälle wie einen virtuellen Einzelhandelsassistent entwerfen
* Data Scientists, die nach effizienten Möglichkeiten suchen, Ziele bei der Sprachmodellierung zu erreichen
* Dateningenieure, die für die Pflege und Verarbeitung von Textdaten wie Kundenfragen und Dialogtranskripte verantwortlich sind
* Führungskräfte und IT-Entscheidungsträger, die daran interessiert sind, die konvergente KI-Erfahrung zu verändern und mit KI-Initiativen die kürzeste Markteinführungszeit zu erreichen


link:cainvidia_solution_overview.html["Weiter: Lösungsübersicht"]
