---
sidebar: sidebar 
permalink: ai/cainvidia_conclusion.html 
keywords: Conclusion 
summary:  
---
= Schlussfolgerung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Ein echtes Conversational KI-System engagiert sich in einem menschlichen Dialog, versteht Kontext und bietet intelligente Antworten. Solche KI-Modelle sind oft riesig und sehr komplex. Mit NVIDIA GPUs und NetApp Storage können große, moderne Sprachmodelle trainiert und optimiert werden, um Inferenz schnell auszuführen. Dies ist ein wichtiger Schritt in Richtung einer Beendigung des Handels zwischen einem KI-Modell, das schnell ist, als ein großes und komplexes Modell. GPU-optimierte Modelle zur Sprachverständnisfunktion können für Branchen wie Gesundheitswesen, Einzelhandel und Finanzdienstleistungen in KI-Applikationen integriert werden und unterstützen digitale Sprachassistenten in intelligenten Lautsprechern und Kundenservices. Diese hochwertigen konvergenten KI-Systeme ermöglichen Unternehmen in verschiedenen Branchen, ihren Kundeneinbezug als bisher unerreichbare, personalisierte Services bereitzustellen.

Jarvis ermöglicht die Bereitstellung von Anwendungsbeispielen wie virtuellen Assistenten, digitalen Avataren, multimodalen Sensor Fusion (CV fusioned with ASR/NLP/TTS) oder jedem ASR/NLP/TTS/CV-Einzelanwendungsfall, wie z.B. Transkription. Wir haben einen virtuellen Einzelhandelsassistent aufgebaut, der Fragen zu Wetter, Points of Interest und Bestandspreisen beantworten kann. Wir haben auch demonstriert, wie sich das natürliche Sprachverständnis des konvergenten KI-Systems verbessern lässt, indem wir die Gesprächsgeschichte mit Cloud Sync archivieren und Nemo-Modelle mit neuen Daten trainieren.

link:cainvidia_acknowledgments.html["Weiter: Danksagungen"]
