---
sidebar: sidebar 
permalink: ai/cainvidia_jarvis_deployment.html 
keywords: Jarvis, Deployment, NVIDIA, 
summary:  
---
= Jarvis-Bereitstellung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sie können sich anmelden für https://developer.nvidia.com/nvidia-jarvis-early-access["Jarvis Early Access-Programm"^] Um Zugriff auf Jarvis-Container auf NVIDIA GPU Cloud (NGC) zu erhalten. Nachdem Sie die Anmeldedaten von NVIDIA erhalten haben, können Sie Jarvis mithilfe der folgenden Schritte bereitstellen:

. Anmelden bei NGC
. Setzen Sie Ihr Unternehmen auf NGC: `ea-2-jarvis`.
. Lokalisieren Sie Jarvis EA v0.2 Assets: Jarvis Container sind in `Private Registry` > `Organization Containers`.
. Wählen Sie Jarvis: Navigieren Sie zu `Model Scripts` Und klicken `Jarvis Quick Start`
. Überprüfen Sie, ob alle Ressourcen ordnungsgemäß funktionieren.
. Finden Sie die Dokumentation zum Erstellen Ihrer eigenen Anwendungen: PDFs finden Sie unter `Model Scripts` > `Jarvis Documentation` > `File Browser`.


link:cainvidia_customize_states_and_flows_for_retail_use_case.html["Weiter: Passen Sie die Staaten und Abläufe für den Einzelhandel an"]
