---
sidebar: sidebar 
permalink: ai/dataops-toolkit.html 
keywords:  
summary:  
---
= NetApp DataOps Toolkit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Das NetApp DataOps Toolkit ist ein Python-basiertes Tool zur Vereinfachung des Managements von Entwicklungs-/Trainings-Workspaces und Inferenzservern, die durch hochleistungsfähigen, horizontal skalierbaren NetApp Storage gesichert werden. Die wichtigsten Funktionen:

* Schnelle Bereitstellung neuer JupyterLab Workspaces mit hoher Kapazität, die durch hochperformanten horizontal skalierbaren NetApp Storage unterstützt werden
* Schnelle Bereitstellung neuer NVIDIA Triton Inferenz Server Instanzen, die durch NetApp Storage der Enterprise-Klasse unterstützt werden
* Nahezu sofortiges Klonen von JupyterLab Workspaces mit hoher Kapazität, um Experimente oder schnelle Iterationen zu ermöglichen.
* Nahezu sofortige Sicherung von Snapshots von JupyterLab Workspaces mit hoher Kapazität für Backup und/oder Rückverfolgbarkeit/Baselining.
* Hochperformante Daten-Volumes mit hoher Kapazität und nahezu sofortiger Bereitstellung, Klonen und Snapshots


link:https://github.com/NetApp/netapp-dataops-toolkit["NetApp DataOps Toolkit"^]
