---
sidebar: sidebar 
permalink: ai/ddlnexus_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx for NetApp ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: MLOps für die Hybrid-Multi-Cloud mit Domino Data Lab und NetApp – erste Einrichtung 
---
= Ersteinrichtung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Abschnitt werden die ersten Einrichtungsaufgaben beschrieben, die für den Einsatz von Domino Nexus mit NetApp Datenservices in einer hybriden Umgebung mit einem On-Premises-Datacenter und AWS durchgeführt werden müssen.



== Voraussetzungen

Bevor Sie die in diesem Abschnitt beschriebenen Schritte ausführen, gehen wir davon aus, dass Sie bereits die folgenden Aufgaben ausgeführt haben:

* Sie haben Ihre lokale NetApp ONTAP Storage-Plattform bereits implementiert und konfiguriert. Weitere Informationen finden Sie im link:https://www.netapp.com/support-and-training/documentation/["NetApp Produktdokumentation"].
* Sie haben bereits eine Amazon FSX for NetApp ONTAP-Instanz in AWS bereitgestellt. Weitere Informationen finden Sie im link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSX for NetApp ONTAP Produktseite"].
* Sie haben bereits ein Kubernetes-Cluster in Ihrem lokalen Datacenter bereitgestellt. Weitere Informationen finden Sie im link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino Administratorhandbuch"].
* Sie haben bereits einen Amazon EKS-Cluster in AWS bereitgestellt. Weitere Informationen finden Sie im link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino Administratorhandbuch"].
* Sie haben NetApp Astra Trident in Ihrem Kubernetes-Cluster vor Ort installiert. Außerdem haben Sie diese Trident Instanz zur Verwendung Ihrer lokalen NetApp ONTAP Storage-Plattform beim Bereitstellen und Managen von Storage-Ressourcen konfiguriert. Weitere Informationen finden Sie im link:https://docs.netapp.com/us-en/trident/index.html["NetApp Astra Trident – Dokumentation"].
* Sie haben NetApp Astra Trident in Ihrem Amazon EKS Cluster installiert. Außerdem haben Sie diese Trident Instanz konfiguriert, um Ihre Amazon FSX for NetApp ONTAP Instanz beim Bereitstellen und Managen von Storage-Ressourcen zu verwenden. Weitere Informationen finden Sie im link:https://docs.netapp.com/us-en/trident/index.html["NetApp Astra Trident – Dokumentation"].
* Zwischen dem On-Premises-Datacenter und der Virtual Private Cloud (VPC) in AWS muss eine bidirektionale Netzwerkverbindung hergestellt werden. Weitere Informationen zu den verschiedenen Optionen zur Implementierung finden Sie im link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html["Amazon Virtual Private Network (VPN)-Dokumentation"].




== Domino Enterprise AI Platform in AWS installieren

Befolgen Sie die Anweisungen unter, um die Domino Enterprise MLOPS Platform in AWS zu installieren link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/["Domino Administratorhandbuch"]. Sie müssen Domino in demselben Amazon EKS-Cluster bereitstellen, den Sie zuvor bereitgestellt haben. Außerdem muss NetApp Astra Trident bereits in diesem EKS-Cluster installiert und konfiguriert sein. Sie müssen in der Installationsdatei von Domino.yml eine von Trident gemanagte Storage-Klasse als Shared Storage-Klasse angeben.


NOTE: Siehe link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes["Referenzhandbuch für die Domino-Installation"] Für Details, wie Sie eine freigegebene Speicherklasse in Ihrer domino.yml-Installationsdatei angeben.


NOTE: link:https://www.netapp.com/media/79922-tr-4952.pdf["Technischer Bericht TR-4952"] Erklärt die Implementierung von Domino in AWS mit Amazon FSX für NetApp ONTAP und kann als nützliche Referenz bei der Fehlerbehebung dienen.



== Aktivieren Sie Domino Nexus

Als Nächstes müssen Sie Domino Nexus aktivieren. Siehe link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/["Domino Administratorhandbuch"] Entsprechende Details.



== Implementieren Sie eine Domino Datenebene in Ihrem lokalen Datacenter

Als Nächstes müssen Sie eine Domino Datenebene in Ihrem lokalen Datacenter implementieren. Sie müssen diese Datenebene im zuvor bereitgestellten On-Premises-Kubernetes-Cluster implementieren. Außerdem muss NetApp Astra Trident bereits in diesem Kubernetes-Cluster installiert und konfiguriert sein. Siehe link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/["Domino Administratorhandbuch"] Entsprechende Details.
