---
sidebar: sidebar 
permalink: ai/hcaios_where_to_find_additional_information.html 
keywords: NetApp Additional Information 
summary:  
---
= Weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Folgende Ressourcen enthalten ausführlichere Informationen zu den Angaben in diesem Dokument:

* Cnvrg.io ( https://cnvrg.io["https://cnvrg.io"^]):
+
** Cnvrg-KERN (kostenlose ML-Plattform)
+
https://cnvrg.io/platform/core[]

** Cnvrg Dokumentation
+
https://app.cnvrg.io/docs["https://app.cnvrg.io/docs"^]



* NVIDIA DGX-1-Server:
+
** NVIDIA DGX-1-Server
+
https://www.nvidia.com/en-us/data-center/dgx-1/[]

** NVIDIA Tesla V100 Tensor Core GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[]

** NVIDIA GPU CLOUD (NGC)
+
https://www.nvidia.com/en-us/gpu-cloud/[]

** NetApp FlashAdvantage für AFF
+
https://www.netapp.com/pdf.html?item=/media/19894-ds-3733.pdf[]

** ONTAP 9.x Dokumentation
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[]

** Technischer Bericht von NetApp FlexGroup
+
https://www.netapp.com/pdf.html?item=/media/7337-tr4557pdf.pdf[]



* Persistenter NetApp Storage für Container:
+
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[]



* NetApp Interoperabilitäts-Matrix:
+
** NetApp Interoperabilitäts-Matrix-Tool
+
https://mysupport.netapp.com/matrix/#welcome[]



* ONTAP KI-Netzwerk:
+
** Switches der Cisco Nexus 3232C-Serie
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[]

** Switches der Mellanox Spectrum 2000-Serie
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[]



* ML-Rahmen und Werkzeuge:
+
** DALI
+
https://github.com/NVIDIA/DALI[]

** TensorFlow: Ein Open-Source Machine Learning Framework für alle
+
https://www.tensorflow.org/[]

** Horovod: Ubers Open-Source Distributed Deep Learning Framework for TensorFlow
+
https://eng.uber.com/horovod/[]

** NVIDIA-Blog: Enabling GPUs in the Container Runtime Ecosystem
+
https://devblogs.nvidia.com/gpu-containers-runtime/[]

** Docker
+
https://docs.docker.com[]

** Kubernetes
+
https://kubernetes.io/docs/home/[]

** NVIDIA DeepOps
+
https://github.com/NVIDIA/deepops[]

** Kubeflow
+
http://www.kubeflow.org/[]

** Jupyter Notebook Server
+
http://www.jupyter.org/[]



* Datensatz und Benchmarks:
+
** Röntgendatensatz der NIH Thoraxröntgenaufnahme
+
https://nihcc.app.box.com/v/ChestXray-NIHCC[]

** Xiaosong Wang, Yifan Peng, Le Lu, Zhiyong Lu, Mohammadhadi Bagheri, Ronald Summers, ChestX-ray8: Thorax-Röntgendatenbank im Krankenhausmaßstab und Benchmarks auf schwach überwachte Klassifizierung und Lokalisierung allgemeiner Thorax-Erkrankungen, IEEE CVPR, S. 3462-3471, 2017TR-4841-0620



