---
sidebar: sidebar 
permalink: ai/hcaios_abstract.html 
keywords: NetApp Abstract ML AI 
summary:  
---
= Zusammenfassung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Das explosionsartige Wachstum der Daten und das exponentielle Wachstum von maschinellem Lernen (ML) und künstlicher Intelligenz (KI) haben sich konvergiert, um eine neue Wirtschaft mit einzigartigen Herausforderungen bei Entwicklung und Implementierung zu schaffen. In der Regel werden riesige Datenmengen in einem kostengünstigen Data Lake gespeichert, in dem hochperformante KI-Computing-Ressourcen wie GPUs nicht effizient darauf zugreifen können. In diesem Bericht stellen wir eine neuartige Lösung vor, in der Data Science-Fachleute ein Data Hub implementieren und mit nur einem Klick einen Cache von Datensätzen in Nähe ihrer Compute-Ressourcen erstellen – unabhängig von ihrem Standort. So können KI-Fachleute das High-Performance-Modelltraining durch optimierte Zusammenarbeit mit einem neuen Datensatz-Version-Hub einfacher durchführen.

link:hcaios_acknowledgments.html["Weiter: Danksagungen"]
