---
sidebar: sidebar 
permalink: ai/hcaios_ontap_ai_deployment.html 
keywords: ONTAP AI, Deployment, networking, compute, storage 
summary:  
---
= ONTAP AI Implementierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Für die Implementierung von ONTAP AI sind die Installation und Konfiguration von Netzwerk-, Computing- und Storage-Hardware erforderlich. Spezifische Anweisungen für die Implementierung der ONTAP AI-Infrastruktur liegen nicht im Umfang dieses Dokuments vor. Detaillierte Informationen zur Bereitstellung finden Sie unter https://www.netapp.com/us/media/nva-1121-deploy.pdf["NVA-1121-DEPLOY: NetApp ONTAP AI, Powered by NVIDIA"^].

Für diese Lösungsvalidierung wurde ein einzelnes Volume erstellt und auf dem DGX-1-System gemountet. Dieser Mount-Punkt wurde dann in die Container eingebunden, um die Daten für das Training zugänglich zu machen. Bei umfangreichen Implementierungen automatisiert NetApp Trident die Erstellung und das Mounten von Volumes, um den administrativen Overhead zu beseitigen und Ressourcen für Endbenutzer zu managen.
