---
sidebar: sidebar 
permalink: ai/hciai_edge_virtual_infrastructure_with_automated_deployment.html 
keywords:  
summary:  
---
= Implementierung von VMware Virtual Infrastructure auf NetApp HCI mit nde (automatisierte Implementierung)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Voraussetzungen für die nde Implementierung

Konsultieren Sie die https://library.netapp.com/ecm/ecm_download_file/ECMLP2798490["Checkliste für Voraussetzungen für NetApp HCI"^] Vor der Implementierung müssen die Anforderungen und Empfehlungen für NetApp HCI angezeigt werden.

. Anforderungen und Konfiguration von Netzwerk und Switches
. Erforderliche VLAN-IDs vorbereiten
. Switch-Konfiguration
. IP-Adresse für NetApp HCI und VMware
. DNS und Anforderungen für die Zeitabhaltung
. Abschließende Vorbereitungen




== Ausführung der nde

Bevor Sie die nde ausführen, müssen Sie das Rack und den Stack aller Komponenten, die Konfiguration der Netzwerk-Switches und die Überprüfung aller Voraussetzungen abschließen. Nde lassen sich durch Verbindung mit der Managementadresse eines einzelnen Storage-Nodes ausführen, wenn nde plant, alle Adressen automatisch zu konfigurieren.

Nde führt die folgenden Aufgaben aus, um ein HCI-System online zu schalten:

. Installiert den Storage-Node (NetApp Element Software) auf mindestens zwei Storage-Nodes
. Installiert den VMware Hypervisor auf mindestens zwei Computing-Nodes
. Installiert VMware vCenter zum Management des gesamten NetApp HCI Stacks
. Installiert und konfiguriert den NetApp Storage Management-Node (mNode) und den NetApp Monitoring Agent.
+

NOTE: Bei dieser Validierung werden alle Adressen automatisch mit nde konfiguriert. Sie können zudem in Ihrer Umgebung DHCP einrichten oder jedem Storage Node und jedem Computing Node manuell IP-Adressen zuweisen. Diese Schritte werden in diesem Leitfaden nicht erläutert.

+
Wie bereits erwähnt, verwendet diese Validierung eine 2-Kabel-Konfiguration für Computing-Nodes.

+
Detaillierte Schritte für die nde werden in diesem Dokument nicht behandelt.

+
Eine Schritt-für-Schritt-Anleitung zum Abschließen der Bereitstellung der NetApp HCI Basis-Plattform finden Sie im http://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html?cp=3_0["Implementierungsleitfaden"^].

. Melden Sie sich nach Abschluss von nde im vCenter an und erstellen Sie eine verteilte Portgruppe `NetApp HCI VDS 01-NFS_Network` Soll das NFS-Netzwerk von ONTAP Select und der Applikation verwendet werden.


link:hciai_edge_netapp_h615cmanual_deployment.html["Als Nächstes konfigurieren Sie NetApp H615c (manuelle Implementierung)"]
