---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= Anwendungsfälle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Auch wenn heute kein KI-gestützter Einsatz ist, entwickelt sich das Unternehmen zunehmend mit neuen Funktionen, die Kunden auf die immensen Vorteile der KI zugreifen können. Für die Einführung von KI benötigen Applikationen eine Infrastruktur, die ihnen die Ressourcen bietet, die sie für einen optimalen Betrieb und die Weiterentwicklung benötigen.

Bei KI-gestützten Applikationen fungieren Edge-Standorte als Hauptquelle für Daten. Verfügbare Daten können für Schulungen genutzt werden, wenn sie über einen Zeitraum von mehreren Edge-Standorten erfasst werden, um einen Trainingdatensatz zu bilden. Das trainierte Modell kann dann zurück an den Edge-Standorten implementiert werden, an denen die Daten erfasst wurden. So lassen sich Inferenz schneller durchführen, ohne dass wiederholt Produktionsdaten auf eine dedizierte Inferenzplattform übertragen werden müssen.

Die NetApp HCI AI Inferenzlösung mit NetApp H615c Computing-Nodes mit NVIDIA T4-GPUs und Cloud-vernetzten NetApp Storage-Systemen wurde von NetApp und NVIDIA entwickelt und verifiziert. NetApp HCI vereinfacht die Implementierung von KI-Inferenzlösungen im Edge-Datacenter, indem es Ambiguität beseitigt und damit die Komplexität des Designs und das Ende von Unsicherheiten beseitigt. Mit dieser Lösung erhalten IT-Abteilungen eine präskriptive Architektur, die folgende Vorteile bietet:

* Ermöglicht KI-Inferenz im Edge-Datacenter
* Optimiert die Nutzung von GPU-Ressourcen
* Bietet eine Kubernetes-basierte Plattform zur Inferenz für Flexibilität und Skalierbarkeit
* Sie vereinfacht das Design


Edge-Datacenter managen und verarbeiten Daten an Standorten, die sich sehr nahe am Erzeugungspunkt befinden. Diese Nähe erhöht die Effizienz und verringert die beim Umgang mit Daten involvierte Latenz. In vielen vertikalen Märkten wurden die Vorteile eines Edge Datacenters erkannt und dieser verteilte Ansatz für die Datenverarbeitung wird stark umgesetzt.

In der folgenden Tabelle sind die Edge-Branchen und -Applikationen aufgeführt.

|===
| Vertikale Märkte | Applikationen Unterstützt 


| Medizinisch | Computergestützte Diagnostik unterstützt medizinisches Personal bei der Früherkennung von Krankheiten 


| Öl und Gas | Autonome Inspektion von Remote-Produktionsstätten, Video- und Bildanalysen 


| Luftverkehr | Unterstützung bei der Flugsicherung und Videofeed-Analysen in Echtzeit 


| Media und Entertainment | Audio-/Video-Content-Filterung für familienfreundliche Inhalte 


| Geschäftsanalysen | Markenbekanntheit zur Analyse des Markenauftritts in Live-Stream-Fernsehveranstaltungen 


| E-Commerce | Intelligente Bündelung von Lieferanten Angebote, um ideale Händler-und Lager-Kombinationen zu finden 


| Einzelhandel | Automatisierte Kasse, um Artikel zu erkennen, die ein Kunde in den Warenkorb gelegt hat, und die digitale Zahlung zu erleichtern 


| Smart City | Verbesserung des Verkehrsflusses, Optimierung des Parkplatzes und Verbesserung der Fußgänger- und Radfahrersicherheit 


| Fertigung | Qualitätskontrolle, Montage-Leitungsüberwachung und Fehlererkennung 


| Kundendienst | Automatisierung des Kundenservice zur Analyse und Bewertung von Anfragen (Telefon, E-Mail und Social Media) 


| Landwirtschaft | Intelligente Farm-Betrieb und Aktivitätenplanung, um Dünger- und Herbizidanwendung zu optimieren 
|===


== Zielgruppe

Die Zielgruppe für die Lösung umfasst die folgenden Gruppen:

* Data Scientists
* IT-Architekten
* Field Consultants
* Professional Services
* IT Manager zu erreichen
* Andere Unternehmen benötigen eine Infrastruktur, die IT-Innovationen und stabile Daten- und Applikations-Services am Edge-Standort bietet


link:hciai_edge_architecture.html["Als Nächstes: Architektur"]
