---
sidebar: sidebar 
permalink: ai/mlops_fsxn_intro.html 
keywords: FSxN, AWS S3, SageMaker, MLOps, NetApp ONTAP 
summary: Dies ist die Einführungsseite zum Abschnitt FSxN MLOps. 
---
= AWS FSX for NetApp ONTAP (FSxN) für MLOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt wird die praktische Anwendung der Entwicklung von KI-Infrastrukturen erläutert und der Aufbau einer MLOps-Pipeline mithilfe von FSxN durchgängig dargestellt. Sie umfasst drei umfassende Beispiele und hilft Ihnen, Ihre MLOps-Anforderungen über diese leistungsstarke Datenmanagement-Plattform zu erfüllen.

*Autor(en):*
Jian Jian (Ken), Senior Data & Applied Scientist, NetApp

Die Schwerpunkte dieser Artikel liegen auf:

. link:./mlops_fsxn_s3_integration.html["Teil 1 – Integration von AWS FSX for NetApp ONTAP (FSxN) als privater S3-Bucket in AWS SageMaker"]
. link:./mlops_fsxn_sagemaker_integration_training.html["Teil 2 – Nutzung von AWS FSX for NetApp ONTAP (FSxN) als Datenquelle für das Modelltraining in SageMaker"]
. link:./mlops_fsxn_cictcd.html["Teil 3 – Aufbau Einer vereinfachten MLOPS-Pipeline (CI/CT/CD)"]


Am Ende dieses Abschnitts haben Sie ein fundiertes Verständnis dafür gewonnen, wie Sie FSxN zur Optimierung von MLOPS-Prozessen nutzen können.
