---
sidebar: sidebar 
permalink: ai/mlops_fsxn_intro.html 
keywords: FSx ONTAP, FSx ONTAP, AWS S3, SageMaker, MLOps, NetApp ONTAP 
summary: Dies ist die Einführungsseite zum Abschnitt FSX ONTAP MLOPs. 
---
= Amazon FSX for NetApp ONTAP (FSX ONTAP) für MLOps
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Abschnitt wird die praktische Anwendung der Entwicklung von KI-Infrastrukturen erläutert, indem der Aufbau einer MLOps-Pipeline mithilfe von FSX ONTAP vollständig demonstriert wird. Sie umfasst drei umfassende Beispiele und hilft Ihnen, Ihre MLOps-Anforderungen über diese leistungsstarke Datenmanagement-Plattform zu erfüllen.

Die Schwerpunkte dieser Artikel liegen auf:

. link:./mlops_fsxn_s3_integration.html["Teil 1 – Integration von Amazon FSX for NetApp ONTAP (FSX ONTAP) als privaten S3-Bucket in AWS SageMaker"]
. link:./mlops_fsxn_sagemaker_integration_training.html["Teil 2 – Nutzung von Amazon FSX for NetApp ONTAP (FSX ONTAP) als Datenquelle für Modelltraining in SageMaker"]
. link:./mlops_fsxn_cictcd.html["Teil 3 – Aufbau Einer vereinfachten MLOPS-Pipeline (CI/CT/CD)"]


Am Ende dieses Abschnitts haben Sie ein fundiertes Verständnis darüber gewonnen, wie Sie FSX ONTAP zur Optimierung von MLOPS-Prozessen nutzen können.
