---
sidebar: sidebar 
permalink: ai/mlrun_where_to_find_additional_information.html 
keywords: NetApp Find Additional Information 
summary:  
---
= Weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Folgende Ressourcen enthalten ausf端hrlichere Informationen zu den Angaben in diesem Dokument:

* NetApp AI Control Plane:
+
** Technischer Bericht: NetApp AI Control Plane
+
https://["https://www.netapp.com/us/media/tr-4798.pdf"^]



* Persistenter NetApp Storage f端r Container:
+
** NetApp Trident
+
https://["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]



* ML-Rahmen und Werkzeuge:
+
** TensorFlow: Ein Open-Source Machine Learning Framework f端r alle https://["https://www.tensorflow.org/"^]
** Docker
+
https://["https://docs.docker.com"^]

** Kubernetes
+
https://["https://kubernetes.io/docs/home/"^]

** Kubeflow
+
http://["http://www.kubeflow.org/"^]

** Jupyter Notebook Server
+
http://["http://www.jupyter.org/"^]



* Iguazio Data Science Platform
+
** Iguazio Data Science Platform Dokumentation
+
https://["https://www.iguazio.com/docs/"^]

** Serverlose Nuclio-Funktion
+
https://["https://nuclio.io/"^]

** MLRun opensource Pipeline-Orchestrierungs-Framework
+
https://["https://www.iguazio.com/open-source/mlrun/"^]



* NVIDIA DGX-1-Systeme
+
** NVIDIA DGX-1-Systeme
+
https://["https://www.nvidia.com/en-us/data-center/dgx-1/"^]

** NVIDIA Tesla V100 Tensor Core GPU
+
https://["https://www.nvidia.com/en-us/data-center/tesla-v100/"^]

** NVIDIA GPU Cloud
+
https://["https://www.nvidia.com/en-us/gpu-cloud/"^]



* NetApp AFF Systeme
+
** AFF Datenblatt
+
https://["https://www.netapp.com/us/media/ds-3582.pdf"^]

** NetApp Flash Advantage f端r AFF
+
https://["https://www.netapp.com/us/media/ds-3733.pdf"^]

** ONTAP 9.x Dokumentation
+
https://["https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

** Technischer Bericht von NetApp FlexGroup
+
https://["https://www.netapp.com/us/media/tr-4557.pdf"^]



* NetApp ONTAP AI
+
** Design-Leitfaden: ONTAP AI mit DGX-1 und Cisco Networking
+
https://["https://www.netapp.com/us/media/nva-1121-design.pdf"^]

** ONTAP AI mit DGX-1 und Cisco Networking Deployment Guide
+
https://["https://www.netapp.com/us/media/nva-1121-deploy.pdf"^]

** Design-Leitfaden: ONTAP AI mit DGX-1 und Mellanox Networking
+
https://["https://www.netapp.com/us/media/nva-1138-design.pdf"^]



* ONTAP KI-Netzwerke
+
** Switches der Cisco Nexus 3232C-Serie
+
https://["https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html"^]

** Mellanox Scale-out SN2000 Ethernet Switch-Serie
+
https://["https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000"^]




