---
sidebar: sidebar 
permalink: ai/nva-1153-design-link.html 
keywords:  
summary:  
---
= NVA-1153-DESIGN: NetApp ONTAP AI mit NVIDIA DGX A100-Systemen und Mellanox Spectrum Ethernet-Switches
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


David Arnette und Sung-Han Lin, NetApp

[role="lead"]
NVA-1153-DESIGN beschreibt eine NetApp Verifizierte Architektur für Machine-Learning- (ML) und AI-Workloads (künstliche Intelligenz) mit NetApp AFF A800 Storage-Systemen, NVIDIA DGX A100-Systemen und NVIDIA Mellanox Spectrum SN3700V 200-GB-Ethernet-Switches. Dieses Design verfügt über RDMA over Converged Ethernet (RoCE) für die Compute-Cluster Interconnect-Fabric und bietet Unternehmen eine vollständig ethernet-basierte Architektur für hochperformante Workloads. Dieses Dokument enthält außerdem Benchmark-Testergebnisse für die implementierte Architektur.

link:https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf["NVA-1153-DESIGN: NetApp ONTAP AI mit NVIDIA DGX A100-Systemen und Mellanox Spectrum Ethernet-Switches"^]
