---
sidebar: sidebar 
permalink: ai/nva-1156-design-link.html 
keywords:  
summary:  
---
= NVA-1156-DESIGN: NetApp EF-Series AI mit NVIDIA DGX A100-Systemen und BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Abdel Sadek, Tim Chau, Joe McCormick und David Arnette, NetApp

[role="lead"]
NVA-1156-DESIGN beschreibt eine NetApp Verified Architecture für Machine-Learning- (ML) und AI-Workloads (künstliche Intelligenz) mit NetApp EF600 NVMe-Storage-Systemen, dem BeeGFS Parallel Filesystem, NVIDIA DGX A100-Systemen und NVIDIA Mellanox Quantum QM8700 200 Gbps IB-Switches. Dieses Design verfügt über 200 Gbit/s InfiniBand (IB) für die Storage- und Compute-Cluster Interconnect-Fabric und bietet damit eine vollständig auf IB basierende Architektur für hochperformante Workloads. Dieses Dokument enthält außerdem Benchmark-Testergebnisse für die implementierte Architektur.

link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NVA-1156-DESIGN: NetApp EF-Series AI mit NVIDIA DGX A100-Systemen und BeeGFS"^]
