---
sidebar: sidebar 
permalink: ai/nvaie_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise with NetApp and VMware – Initial Setup 
---
= Ersteinrichtung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die anfänglichen Einrichtungsaufgaben beschrieben, die durchgeführt werden müssen, um NVIDIA AI Enterprise mit NetApp und VMware zu nutzen.



== Voraussetzungen

Bevor Sie die in diesem Abschnitt beschriebenen Schritte durchführen, gehen wir davon aus, dass Sie VMware vSphere und NetApp ONTAP bereits implementiert haben. Siehe link:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html["NVIDIA AI Enterprise Product Support Matrix"] Weitere Informationen zu unterstützten vSphere Versionen finden Sie unter. Siehe link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html["Dokumentation der Lösungen von NetApp und VMware"] Finden Sie Einzelheiten zur Implementierung von VMware vSphere mit NetApp ONTAP.



== NVIDIA AI Enterprise Host Software installieren

Befolgen Sie zum Installieren der NVIDIA AI Enterprise Host-Software die Anweisungen in Abschnitt 1-4 in link:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html["NVIDIA AI Enterprise Quick Start Guide"].
