---
sidebar: sidebar 
permalink: ai/osrunai_executive_summary.html 
keywords:  
summary:  
---
= TR-4858: NetApp Orchestrierungslösung mit Run:AI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Rick Huang, David Arnette, Sung-Han Lin, NetApp Yaron Goldberg, Run:AI

[role="lead"]
NetApp AFF Storage-Systeme bieten extrem hohe Performance und branchenführende Funktionen für das Hybrid-Cloud-Datenmanagement. NetApp und Run:KI haben gemeinsam die einzigartigen Funktionen der NetApp ONTAP KI Lösung für künstliche Intelligenz (KI) und ml-Workloads (Machine Learning) vorgestellt, die Performance, Zuverlässigkeit und Support der Enterprise-Klasse bieten. Ausführung:die KI-Orchestrierung von KI-Workloads bietet eine Kubernetes-basierte Plattform für Planung und Ressourcenauslastung, die Forscher beim Management und bei der Optimierung der GPU-Auslastung unterstützt. Zusammen mit NVIDIA DGX-Systemen bieten die kombinierte Lösung von NetApp, NVIDIA und Run:AI einen Infrastruktur-Stack, der speziell für KI-Enterprise-Workloads entwickelt wurde. Dieser technische Bericht gibt Kunden eine Orientierungshilfe beim Aufbau konversationaler KI-Systeme zur Unterstützung verschiedener Anwendungsfälle und Branchen. Er enthält Informationen zur Implementierung von Run:AI und einem NetApp AFF A800 Storage-System. Er dient als Referenzarchitektur, um KI-Initiativen so schnell und erfolgreich zu implementieren.

Die Zielgruppe für die Lösung umfasst die folgenden Gruppen:

* Enterprise-Architekten, die Lösungen für die Entwicklung von KI-Modellen und -Software für Kubernetes-basierte Anwendungsfälle wie containerisierte Microservices entwerfen
* Data Scientists, die nach effizienten Möglichkeiten suchen, Modelle in einer Cluster-Umgebung mit mehreren Teams und Projekten effizient zu entwickeln
* Data Engineers, die für die Wartung und den Betrieb von Produktionsmodellen verantwortlich sind
* Führungskräfte und IT-Entscheidungsträger, die die optimale Auslastung von Kubernetes-Cluster-Ressourcen schaffen und mit KI-Initiativen die kürzeste Markteinführungszeit erreichen möchten

