---
sidebar: sidebar 
permalink: ai/osrunai_netapp_ontap_ai_and_ai_control_plane.html 
keywords:  
summary:  
---
= NetApp ONTAP AI und KI Control Plane
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die NetApp ONTAP KI-Architektur mit NVIDIA DGX-Systemen und Cloud-vernetzten NetApp Storage-Systemen. Diese Referenzarchitektur bietet IT-Abteilungen folgende Vorteile:

* Sie vereinfacht das Design
* Computing und Storage können unabhängig voneinander skaliert werden
* Kunden können mit einer kleinen Konfiguration starten und nahtlos skalieren
* Bietet eine Reihe von Storage-Optionen für diverse Performance- und KostenpunkteNetApp ONTAP AI integriert DGX-Systeme und NetApp AFF A800 Storage-Systeme nahtlos in hochmoderne Netzwerke. Mithilfe von NetApp ONTAP AI und DGX-Systemen können Komplexität und Unsicherheiten bei der Systemaufsetzung beseitigt werden, was den Einsatz von KI-Projekten vereinfacht. Kunden können mit einer kleinen Installation starten und ihre Systeme unterbrechungsfrei erweitern. Gleichzeitig erhalten sie intelligente Datenmanagement-Funktionen, mit denen sich Daten zwischen Datenaufnahme, zentraler Datenplattform und Cloud frei verschieben lassen.


NetApp AI Control Plane ist eine Daten- und Experimentmanagementlösung für Data Scientists und Data Engineers, eine Full-Stack-KI, ML und Deep Learning (DL). Beim zunehmenden Einsatz von KI sehen sich Unternehmen vielen Herausforderungen gegenüber, darunter Workload-Skalierbarkeit und Datenverfügbarkeit. NetApp AI Control Plane begegnet diesen Herausforderungen mit Funktionalitäten, beispielsweise dem schnellen Klonen eines Daten-Namespace wie bei einer Git-Reversion. KI-Trainings-Workflows definieren und implementieren, bei denen die nahezu sofortige Erstellung von Daten- und Modellbasiden für die Rückverfolgbarkeit und Versionierung integriert ist. Mit der NetApp AI Control Plane können Sie Daten nahtlos über Standorte und Regionen hinweg replizieren und rasch Jupyter Notebook-Workspaces mit Zugriff auf riesige Datensätze bereitstellen.

link:osrunai_run_ai_platform_for_ai_workload_orchestration.html["Next: KI-Plattform für KI-Workload-Orchestrierung"].
