---
sidebar: sidebar 
permalink: ai/osrunai_run_ai_platform_for_ai_workload_orchestration.html 
keywords:  
summary:  
---
= Run:KI-Plattform zur Orchestrierung von KI-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


* Schnellere Innovationen Mithilfe von Run:KI-Ressourcen-Pooling, Warteschlangen und Priorisierungsmechanismen werden zusammen mit dem NetApp Storage-System Forscher nicht mehr von den Problemen beim Infrastruktur-Management befreit und können sich ausschließlich auf die Datenwissenschaft konzentrieren. Run:KI und NetApp Kunden steigern die Produktivität, indem sie genau so viele Workloads ohne Engpässe bei Computing oder Daten-Pipeline ausführen.
* Höhere Teamproduktivität – Run:AI Fairness-Algorithmen garantieren, dass alle Benutzer und Teams einen gerechten Anteil an Ressourcen erhalten. Richtlinien für vorrangige Projekte können voreingestellt werden, und die Plattform ermöglicht die dynamische Zuweisung von Ressourcen von einem Benutzerteam zum anderen, sodass Benutzer rechtzeitig auf begehrte GPU-Ressourcen zugreifen können.
* Verbesserte GPU-Auslastung. Run:AI Scheduler ermöglicht Benutzern das einfache Verwenden von fraktionalen GPUs, Integer-GPUs und mehreren Nodes von GPUs für verteiltes Training auf Kubernetes. Auf diese Weise werden KI-Workloads je nach Anforderungen und nicht nach Kapazität ausgeführt. Data-Science-Teams können mehr KI-Experimente in der gleichen Infrastruktur ausführen.


link:osrunai_solution_technology_overview.html["Als Nächstes: Lösungstechnologie"].
