---
sidebar: sidebar 
permalink: ai/osrunai_software_requirements.html 
keywords:  
summary:  
---
= Softwareanforderungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Diese Lösung wurde mit einer grundlegenden Kubernetes-Implementierung validiert, bei der der Run:AI Operator installiert ist. Kubernetes wurde mit dem implementiert https://github.com/NVIDIA/deepops["NVIDIA DeepOps"^] Deployment Engine: Hier werden alle erforderlichen Komponenten für eine produktionsbereite Umgebung implementiert. DeepOps wird automatisch implementiert https://netapp.io/persistent-storage-provisioner-for-kubernetes/["NetApp Trident"^] Zur persistenten Storage-Integration in die Umgebung k8s wurden StandardStorage-Klassen erstellt, sodass Container Storage aus dem AFF A800 Storage-System nutzen können. Weitere Informationen zu Trident mit Kubernetes zu ONTAP AI finden Sie unter https://www.netapp.com/us/media/tr-4798.pdf["TR-4798"^].

 The following table lists the software components that are required to implement the solution as tested.
|===
| Software | Version oder sonstige Informationen 


| NetApp ONTAP Datenmanagement-Software | 9,6p4 


| Cisco NX-OS Switch-Firmware | 7.0(3)I6(1) 


| NVIDIA DGX-BETRIEBSSYSTEM | 4.0.4 – Ubuntu 18.04 LTS 


| Kubernetes-Version | 1.17 


| Trident Version | 20.04.0 


| Ausführen:AI-CLI | V2.1.13 


| Run:AI Orchestration Kubernetes Operator Version | 1.0.39 


| Docker-Container-Plattform | 18.06.1-ce [e68fc7a] 
|===
Weitere Software-Anforderungen für Run:AI finden Sie unter https://docs.run.ai/Administrator/Cluster-Setup/Run-AI-GPU-Cluster-Prerequisites/["Run:AI-GPU-Cluster-Voraussetzungen"^].
