---
sidebar: sidebar 
permalink: ai/rag_introduction.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Enterprise RAG mit NVIDIA Nemo und NetApp – Einführung 
---
= Erweiterte Generation (RAG) für Enterprise Retrieval mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Mike Oglesby, NetApp
Sathisch Thyagarajan, NetApp

[role="lead"]
Generative KI verändert das Sucherlebnis in Unternehmen grundlegend. Datenbenutzer in einem Unternehmen können damit ihre Datenbestände überall erkennen, ob vor Ort oder in der Public Cloud. Ob generative KI von Entwicklern zur Erstellung von Code für die Entwicklung einer modernen Webanwendung verwendet wird, oder um Animationen mit realen Physik- und Bewegungsdaten zu erstellen, verwenden Unternehmen generative KI und vortrainierte Large Language Models (LLMs), um transformative KI-Anwendungen zu entwickeln, neue Produktfunktionen zu entwickeln, die Produktivität der technischen Entwicklung zu verbessern und die Kundenerfahrung zu verbessern.

Generative KI und LLMs allein können jedoch keinen geschäftlichen Nutzen garantieren. Um einen konkreten geschäftlichen Nutzen zu erzielen, muss die generative KI kuratierte Daten für hochwertige Geschäftsergebnisse nutzen. Große Unternehmen wenden sich daher einem aufstrebenden und essentiellen Rahmen zu, dem sogenannten Retrieval Augmented Generation (RAG). In dieser Lösung stellen wir eine Architektur für Unternehmen vor, die eine RAG-Pipeline aufbauen möchten. Mit dieser Lösung können Sie den Wert Ihrer privaten Daten ausschöpfen, indem Sie Kontextinformationen über eine private RAG-Pipeline abrufen.
