---
sidebar: sidebar 
permalink: ai/rag_nemo_ingest_netapp_data.html 
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Enterprise RAG mit NetApp - vorhandene NetApp-Daten mit Nemo Retriever aufnehmen 
---
= Vorhandene NetApp-Daten mit Nemo Retriever aufnehmen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Der Nemo Embedding Microservice, der Teil von NVIDIA Nemo Retriever ist, kann zur Datenaufnahme in den RAG-Vektorspeicher/die Wissensdatenbank genutzt werden. In diesem Abschnitt werden die Aufgaben beschrieben, die ausgeführt werden müssen, um Daten aus vorhandenen NetApp-Datenquellen aufzunehmen.



== Datenaufnahme mit NVIDIA Sample-Chat-bot

Sie können vorhandene Dateien über die vom NVIDIA Enterprise RAG LLM Operator bereitgestellte Chat-bot-Beispielwebanwendung aufnehmen. In diesem Abschnitt wird der Prozess zur Aufnahme vorhandener Dateien mit der Chat bot-Webanwendung beschrieben link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f718b504-d89b-497e-bd25-b13400d0bfbf&start=57["Demovideo."]



== Programmgesteuerte Datenaufnahme

Mit dem RAG-Abfrageserver, der vom NVIDIA Enterprise RAG LLM Operator bereitgestellt wird, können große Datenmengen programmgesteuert aufgenommen werden.

Die API des RAG-Abfrageservers wird automatisch über einen Kubernetes-Service offengelegt, wie in der Ausgabe des folgenden Befehls dargestellt.

[source]
----
$ kubectl -n rag-sample get service chain-server
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
chain-server   ClusterIP   10.233.28.129   <none>        8081/TCP   59d
----
Standardmäßig ist der Servicetyp ClusterIP, sodass auf den API-Endpunkt nur im Kubernetes-Cluster zugegriffen werden kann. Der Servicetyp kann durch Ändern der geändert werden `query.service.type` Feld in Ihrer Helm-Pipeline-Konfiguration (z. B. helmpipeline_App.yaml).

Auf das API-Server-Swagger-Schema kann unter zugegriffen werden `<chain_server_url>:<chain_server_api_port>/docs``.
