---
sidebar: sidebar 
permalink: ai/runai-ld_executive_summary.html 
keywords: azure, lane, detection, training, solution, design 
summary: Seit Mai 2019 bietet Microsoft einen nativen Portal-Service auf Basis von Azure für NFS- und SMB-Fileservices der Enterprise-Klasse basierend auf NetApp ONTAP Technologie. 
---
= TR-4896: Distributed Training in Azure: Lane Detection - Lösungsdesign
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Muneer Ahmad und Verron Martina, NetApp Ronen dar, RUN:AI

[role="lead"]
Seit Mai 2019 bietet Microsoft einen nativen Portal-Service auf Basis von Azure für NFS- und SMB-Fileservices der Enterprise-Klasse basierend auf NetApp ONTAP Technologie. Ziel dieser Entwicklung ist eine strategische Partnerschaft zwischen Microsoft und NetApp, mit der auch die Ausweitung der Reichweite erstklassiger ONTAP-Datenservices auf Azure möglich ist.

NetApp, ein führender Anbieter von Cloud-Datenservices, hat sich zusammengeschlossen: KI, ein Unternehmen, das KI-Infrastruktur virtualisiert, ermöglicht schnellere KI-Experimente mit voller GPU-Auslastung. Dank dieser Partnerschaft können Teams die KI beschleunigen, indem sie zahlreiche Experimente parallel ausführen und dabei schnell auf Daten zugreifen – und dabei grenzenlose Computing-Ressourcen nutzen. RUN: KI ermöglicht volle GPU-Auslastung durch automatisiertes Ressourcenzuweisung. Mit der bewährten Architektur von Azure NetApp Files kann jedes Experiment mit maximaler Geschwindigkeit ausgeführt werden, indem die Hindernisse für die Datenpipeline beseitigt werden.

NetApp und RUN: KI haben gemeinsam ihre Kräfte vereint und bieten Kunden eine zukunftssichere Plattform für ihren KI-Einsatz in Azure. Von Analysen und High-Performance-Computing (HPC) bis hin zu autonomen Entscheidungen (bei denen Kunden ihre IT-Investitionen optimieren können, indem sie nur das zahlen, was sie benötigen, und zwar zum richtigen Zeitpunkt), bietet die Allianz zwischen NetApp und RUN: KI ermöglicht ein einheitliches Arbeiten in der Azure Cloud.
