---
sidebar: sidebar 
permalink: ai/tr-4799.html 
keywords:  
summary:  
---
= TR-4799-DESIGN: NetApp ONTAP AI Referenzarchitektur für Workloads für das autonome Fahren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


David Arnette und Sung-Han Lin, NetApp

[role="lead"]
Die NVIDIA DGX-Systemfamilie ist die weltweit erste integrierte Plattform für künstliche Intelligenz (KI), die speziell für Enterprise-KI entwickelt wurde. NetApp AFF Storage-Systeme bieten extrem hohe Performance und branchenführende Funktionen für das Hybrid-Cloud-Datenmanagement. NetApp und NVIDIA haben gemeinsam die NetApp ONTAP AI Referenzarchitektur entwickelt, um Kunden eine sofort einsatzbereite Lösung zur Unterstützung von KI- und ML-Workloads (Machine Learning) mit Performance, Zuverlässigkeit und Support der Enterprise-Klasse zu bieten.

link:https://www.netapp.com/pdf.html?item=/media/8554-tr4799designpdf.pdf["TR-4799-DESIGN: NetApp ONTAP AI Referenzarchitektur für Workloads für das autonome Fahren"^]
