---
sidebar: sidebar 
permalink: ai/tr-4785-link.html 
keywords:  
summary:  
---
= TR-4785: KI Deployment with NetApp E-Series and BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nagalakshmi Raju, Daniel Landes, Nathan Swartz, Amine Bennani, NetApp

Applikationen für künstliche Intelligenz (KI), Machine Learning (ML) und Deep Learning (DL) umfassen große Datensätze und hohe Berechnungen. Um diese Workloads erfolgreich auszuführen, benötigen Sie eine flexible Infrastruktur, die sowohl die Storage- als auch die Compute-Nodes nahtlos horizontal skalieren kann. Dieser Bericht enthält die Schritte zur Ausführung eines KI-Trainingsmodells in einem verteilten Modus, das eine nahtlose horizontale Skalierung von Computing- und Storage-Nodes ermöglicht. Außerdem enthält der Bericht verschiedene Performance-Kennzahlen, um zu zeigen, wie eine Lösung, die NetApp E-Series Storage mit dem parallelen Filesystem BeeGFS kombiniert, eine flexible, kostengünstige und einfache Lösung für KI-Workloads bietet.

link:https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf"^]
