---
sidebar: sidebar 
permalink: ai/vector-database-introduction.html 
keywords: vector database 
summary: Einführung in die Vektordatenbanklösung für NetApp 
---
= Einführung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt enthält eine Einführung in die Vektordatenbanklösung für NetApp.



== Einführung

Vektordatenbanken bewältigen effektiv die Herausforderungen, die für die komplexe semantische Suche in Large Language Models (LLMs) und generativer künstlicher Intelligenz (KI) entwickelt wurden. Im Gegensatz zu herkömmlichen Datenmanagementsystemen sind Vektordatenbanken in der Lage, verschiedene Datentypen zu verarbeiten und zu durchsuchen, darunter Bilder, Videos, Text, Audio und anderen Formen unstrukturierter Daten, indem der Inhalt der Daten selbst statt anhand von Etiketten oder Tags verwendet wird.

Die Grenzen von Relational Database Management Systems (RDBMS) sind gut dokumentiert, insbesondere ihre Probleme mit hochdimensionalen Datendarstellungen und unstrukturierten Daten, wie sie in KI-Anwendungen üblich sind. RDBMS erfordert oft einen zeitaufwändigen und fehleranfälligen Prozess der Abflachung von Daten in besser verwaltbare Strukturen, was zu Verzögerungen und Ineffizienzen bei der Suche führt. Vektor-Datenbanken sind jedoch darauf ausgelegt, diese Probleme zu umgehen. Sie bieten eine effizientere und genauere Lösung für das Management und die Suche durch komplexe und hochdimensionale Daten und erleichtern so den Fortschritt von KI-Applikationen.

Dieses Dokument dient als umfassender Leitfaden für Kunden, die derzeit Vektordatenbanken verwenden oder deren Verwendung planen. Darin werden Best Practices für die Nutzung von Vektordatenbanken auf Plattformen wie NetApp ONTAP, NetApp StorageGRID, Amazon FSX ONTAP for NetApp ONTAP und SnapCenter erläutert. Die hier bereitgestellten Inhalte decken eine Reihe von Themen ab:

* Richtlinien für die Infrastruktur von Vektordatenbanken wie Milvus, die von NetApp Storage über NetApp ONTAP und StorageGRID Objekt-Storage bereitgestellt werden.
* Validierung der Milvus-Datenbank in AWS FSX ONTAP durch Datei- und Objektspeicher.
* Geht auf die Dualität von File-Objekten von NetApp ein und demonstriert seine Nützlichkeit für Daten in Vektordatenbanken und anderen Applikationen.
* SnapCenter, das NetApp Produkt für Datensicherungsmanagement, bietet Backup- und Restore-Funktionen für Vektordatenbankdaten.
* Wie die Hybrid Cloud von NetApp Datenreplizierung und -Schutz in On-Premises- und Cloud-Umgebungen bietet.
* Bietet Einblicke in die Performance-Validierung von Vektordatenbanken wie Milvus und pgvektor auf NetApp ONTAP.
* Zwei spezifische Anwendungsfälle: Retrieval Augmented Generation (RAG) mit Large Language Models (LLM) und ChatAI des NetApp IT Teams. Damit werden praktische Beispiele für die beschriebenen Konzepte und Praktiken vorgestellt.

