---
sidebar: sidebar 
permalink: ai/vector-database-solution-with-netapp.html 
keywords: vector database, milvus, usecases 
summary: Dies ist eine abstrakte Seite für die Vektordatenbank-Lösung mit NetApp. 
---
= Vector Datenbanklösung mit NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Karthikeyan Nagalingam und Rodrigo Nascimento, NetApp

[role="lead"]
Dieses Dokument bietet eine eingehende Erforschung der Implementierung und des Managements von Vektordatenbanken wie Milvus und pgvecto einer Open-Source-PostgreSQL-Erweiterung unter Verwendung von NetApp Storage-Lösungen. Es enthält Details zu den Infrastrukturrichtlinien für die Verwendung von NetApp ONTAP und StorageGRID Objekt-Storage und validiert die Anwendung der Milvus Datenbank in AWS FSX für NetApp ONTAP. Dieses Dokument dokumentiert die Dualität von NetApp in Bezug auf File-Objekte und sein Utility für Vektordatenbanken und Applikationen, die Vektoreinbetten unterstützen. Er hebt die Fähigkeiten von SnapCenter hervor, dem Enterprise Management-Produkt von NetApp, bei dem Backup- und Restore-Funktionen für Vektordatenbanken angeboten werden, die für Datenintegrität und Verfügbarkeit sorgen. In diesem Dokument wird die Hybrid-Cloud-Lösung von NetApp näher erörtert, in der die Rolle der Lösung für Datenreplizierung und -Sicherung in On-Premises- und Cloud-Umgebungen erörtert wird. Sie enthält Einblicke in die Performance-Validierung von Vektordatenbanken auf NetApp ONTAP und schließt mit zwei praktischen Anwendungsfällen zu generativer KI ab: RAG mit LLM und dem internen ChatAI von NetApp. Dieses Dokument dient als umfassender Leitfaden zur Nutzung von NetApp Storage-Lösungen für das Management von Vektordatenbanken.

Die Referenzarchitektur konzentriert sich auf Folgendes:

. link:./vector-database-introduction.html["Einführung"]
. link:./vector-database-solution-overview.html["Lösungsüberblick"]
. link:./vector-database-vector-database.html["Vektordatenbank"]
. link:./vector-database-technology-requirement.html["Technologieanforderungen"]
. link:./vector-database-deployment-procedure.html["Bereitstellungsverfahren"]
. link:./vector-database-solution-verification-overview.html["Übersicht Über Die Lösungsüberprüfung"]
+
** link:./vector-database-milvus-cluster-setup.html["Milvus Cluster-Einrichtung mit Kubernetes vor Ort"]
** link:./vector-database-milvus-with-Amazon-FSxN-for-NetApp-ONTAP.html["Milvus mit Amazon FSxN für NetApp ONTAP – Datei- und Objektdualität"]
** link:./vector-database-protection-using-snapcenter.html["Sicherung von Vector Datenbanken mit NetApp SnapCenter."]
** link:./vector-database-disaster-recovery-using-netapp-snapmirror.html["Disaster Recovery mit NetApp SnapMirror"]
** link:./vector-database-performance-validation.html["Performance-Validierung"]


. link:./vector-database-instaclustr-with-pgvector.html["Vector Database mit Instaclustr unter Verwendung von PostgreSQL: Pgvektor"]
. link:./vector-database-use-cases.html["Anwendungsfälle Für Vector Database"]
. link:./vector-database-conclusion.html["Schlussfolgerung"]
. link:./vector-database-values-yaml.html["Anhang A: Values.yaml"]
. link:./vector-database-prepare-data-netapp-new-py.html["Anhang B: prepare_data_netapp_new.py"]
. link:./vector-database-verify-data-netapp-py.html["Anhang C: verify_data_netapp.py"]
. link:./vector-database-docker-compose-xml.html["Anhang D: docker-compose.yml"]

