---
sidebar: sidebar 
permalink: ai/wp-dgxc.html 
keywords: NetApp AI, AI, Artificial Intelligence, Data Management, Supercomputing 
summary: NVIDIA DGX Cloud mit NetApp Cloud Volumes ONTAP/ANF 
---
= NetApp Cloud-Datenservices für NVIDIA DGX Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Dave Arnette und Sathish Thyagarajan, NetApp

[role="lead"]
Erweitertes Datenmanagement für erstklassiges SuperComputing



== Einführung

In diesem Dokument wird beschrieben, wie Kunden mit NetApp Cloud Volumes/ANF erweiterte Datenmanagementfunktionen in Kombination mit NVIDIA DGX Cloud zur Optimierung und Optimierung der KI-Datenpipeline bereitstellen können.



=== Partnerschaft: NVIDIA, Microsoft und NetApp

DGX Cloud bietet Unternehmen über einen Webbrowser sofortigen Zugriff auf einen KI-Supercomputer.  Mit DGX Cloud können Unternehmen umfangreiche KI-Trainings mit mehreren Nodes nutzen, um das komplexe Modelldesign zu beschleunigen. Wenn Unternehmen sich für eine Erweiterung auf eine lokale Infrastruktur entscheiden, können sie alle Ressourcen konsolidieren und eine Hybrid Cloud erstellen, die NetApp BlueXP™ und die NVIDIA Base Command Platform nutzt. Die Software bietet Entwicklern eine konsistente Ansicht über eine einzige Konsole.



=== NVIDIA DGX Cloud

~NVIDIA, um uns zu liefern, welche Inhalte hier hinzugefügt werden sollen



=== Microsoft Azure



=== NetApp BlueXP™



=== Azure NetApp Files



=== NetApp Datei-Objekt-Dualität



== Architektur und Konfiguration



=== Lösungsdesign/Übersicht



=== Architekturzeichnung



=== CVO/ANF-Implementierung

BlueXP nutzen



=== Konfiguration für Datei-/Objekt-Dualität

Automatisierung über Ansible?



=== Verbindung zu DGXC



== Schlussfolgerung
