---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-conclusion.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: Hierbei handelt es sich um die NetApp ONTAP-Lösung zur Konfiguration, Härtung und Validierung eines ONTAP-basierten Cyber-Vault 
---
= Fazit der ONTAP Cyber Vault PowerShell Lösung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Durch die Nutzung von Air-Gap-Technologie mit robusten Härtungsmethoden von ONTAP können Sie mit NetApp eine sichere, isolierte Storage-Umgebung schaffen, die widerstandsfähig gegen neue Cyberbedrohungen ist. All dies geschieht unter Beibehaltung der Flexibilität und Effizienz der vorhandenen Storage-Infrastruktur. Durch diesen sicheren Zugriff können Unternehmen ihre strengen Sicherheits- und Betriebszeitziele erreichen, wobei die bestehenden Mitarbeiter-, Prozess- und Technologierahmen nur minimal verändert werden.

ONTAP Cyber Vault verwendet native Funktionen in ONTAP. Das ist ein einfacher Ansatz für zusätzlichen Schutz, um unveränderliche und nicht löschbare Kopien Ihrer Daten zu erstellen. Wenn Sie die allgemeine Sicherheitslage um den ONTAP-basierten Cyber-Vault von NetApp erweitern, werden Sie:

* Erstellen Sie eine Umgebung, die getrennt und getrennt zu den Produktions- und Backup-Netzwerken ist, und beschränken Sie den Benutzerzugriff darauf.

