---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening 
permalink: /cyber-vault/ontap-cyber-vault-interoperability.html 
summary: Interoperabilität mit Cyber-Vaults 
---
= Interoperabilität mit Cyber-Vaults
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit ONTAP Hardware und Software kann eine Cyber-Vault-Konfiguration erstellt werden.



== Hardware-Empfehlungen von ONTAP

Alle physischen ONTAP Unified Arrays können für eine Implementierung von Cyber-Vaults genutzt werden.

* FAS Hybrid Storage bietet die kostengünstigste Lösung.
* Die AFF C-Serie bietet den effizientesten Stromverbrauch und die höchste Dichte.
* Die AFF A-Series ist die Plattform mit der höchsten Performance und bietet das beste RTO. Mit der kürzlichen Ankündigung unserer neuesten AFF A-Series bietet diese Plattform die beste Storage-Effizienz ohne Performance-Kompromisse.




== ONTAP Software-Empfehlungen

Ab ONTAP 9.14.1 können Sie in der SnapMirror-Richtlinie der SnapMirror-Beziehung Aufbewahrungszeiträume für bestimmte SnapMirror-Labels festlegen, sodass die replizierten Snapshot Kopien vom Quell- zum Ziel-Volume für den in der Regel angegebenen Aufbewahrungszeitraum beibehalten werden. Wenn kein Aufbewahrungszeitraum angegeben wird, wird die Standardaufbewahrungsfrist des Ziel-Volume verwendet.

Ab.13.1 können Sie in einer SnapLock Vault-Beziehung sofort eine gesperrte Snapshot Kopie auf dem SnapLock Volume als Ziel-FlexClone wiederherstellen, indem Sie einen ONTAP 9 mit der Option „nicht SnapLock“ für den SnapLock-Typ erstellen und die Snapshot Kopie als „Parent-Snapshot“ angeben, wenn Sie den Volume-Klon-Erstellungsvorgang ausführen. Erfahren Sie mehr über link:../../ontap/volumes/create-flexclone-task.html?q=volume+clone["Erstellung eines FlexClone Volume mit einem SnapLock-Typ"^].



== MetroCluster-Konfiguration

Bei MetroCluster Konfigurationen sollten Sie die folgenden Aspekte beachten:

* Sie können eine SnapVault-Beziehung nur zwischen den synchronen Quell-SVMs und nicht zwischen einer SVM mit Sync-Source-Synchronisierung und einer SVM erstellen.
* Sie können eine SnapVault-Beziehung von einem Volume auf einer Quell-SVM zu einer datenServing-SVM erstellen.
* Es ist möglich, eine SnapVault-Beziehung zwischen einem Volume auf einer Datenservice-SVM und einem DP-Volume auf einer SVM mit synchronem Quell-Volume zu erstellen.

