---
sidebar: sidebar 
permalink: automation/automation_introduction.html 
summary: Mit der Automatisierung von NetApp Lösungen können Kunden die Implementierung, Konfiguration und Ausführung vieler gängiger Infrastrukturaufgaben und Applikationsaufgaben automatisieren. 
keywords: netapp, solutions, automation, ansible, terraform 
---
= Automatisierung der NetApp Lösung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit der Automatisierung von NetApp Lösungen können Kunden die Implementierung, Konfiguration und Ausführung vieler gängiger Infrastrukturaufgaben und Applikationsaufgaben automatisieren.



== Einführung

Bei der Bereitstellung von Lösungen, die für die geschäftlichen Herausforderungen von heute eingesetzt werden, bietet NetApp Lösungen mit folgenden Zielen:

* Validierte Implementierungs- und Konfigurationsschritte
* Leicht nutzbare Lösungen anbieten,
* Bereitstellung einer Lösung mit vorhersehbaren Ergebnissen, einfache Wiederholung und Skalierbarkeit im gesamten Unternehmen des Kunden.


Um diese Ziele zu erreichen, ist es von entscheidender Bedeutung, dass die Implementierung und Konfiguration von Infrastruktur und/oder Applikationen, die über unsere Lösungen bereitgestellt werden, durch Automatisierung vereinfacht wird. NetApp hat es sich zum Ziel gesetzt, den Lösungsverbrauch durch Automatisierung zu vereinfachen.

NetApp Lösungen nutzen Open-Source-Automatisierungs-Tools wie Red hat Ansible, HashiCorp Terraform oder Microsoft PowerShell, und können so die Applikationsbereitstellung, Cloud-Bereitstellung, Konfigurationsmanagement und viele andere gängige IT-Aufgaben automatisieren. Die Lösungen von NetApp nutzen öffentlich verfügbare Automatisierungsartefakte und bieten die von NetApp erstellte Automatisierung, um die allgemeine Implementierung einer Lösung zu vereinfachen.

Sofern Automatisierungsfunktionen zur Verfügung stehen, führt das Begleitmaterial zu Lösungen den Benutzer mithilfe der spezifischen Automatisierungstools durch den Prozess der Automatisierung der Lösung oder der Lösungsschritte.
