---
sidebar: sidebar 
permalink: ehc/gcp/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= NetApp Funktionen für die Google Cloud Platform GSCVE
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
Erfahren Sie mehr über die Funktionen, die NetApp für die Google Cloud Platform (GCP) bietet Google Cloud Virtualization Engine (GCVE) – von NetApp als Storage-Gerät mit Gastverbunden oder als zusätzlicher NFS Datastore für die Migration von Workflows, Erweiterung/Bursting in die Cloud, Backup/Restore und Disaster Recovery.

Springen Sie zum Abschnitt zum gewünschten Inhalt, indem Sie eine der folgenden Optionen auswählen:

* link:#config["GCVE wird in GCP konfiguriert"]
* link:#datastore["NetApp Storage-Optionen für GCVE"]
* link:#solutions["NetApp/VMware Cloud-Lösungen"]




== GCVE wird in GCP konfiguriert

Wie bei lokalen Systemen ist die Planung einer Cloud-basierten Virtualisierungsumgebung eine entscheidende Voraussetzung für eine erfolgreiche, sofort einsatzbereite Umgebung zum Erstellen von VMs und Migrationen.

In diesem Abschnitt wird beschrieben, wie Sie GCVE einrichten und managen und in Kombination mit den verfügbaren Optionen zum Verbinden von NetApp Storage verwenden.


NOTE: Der in-Guest-Speicher ist die einzige unterstützte Methode zum Verbinden von Cloud Volumes ONTAP und Cloud Volumes Services mit GCVE.

Der Einrichtungsvorgang kann in die folgenden Schritte unterteilt werden:

* Bereitstellen und Konfigurieren von GCVE
* Aktivieren Sie den privaten Zugriff auf GCVE


Details anzeigen link:gcp-setup.html["Konfigurationsschritte für GCVE"].



== NetApp Storage-Optionen für GCVE

NetApp Storage kann in GCP GCVE auf verschiedene Weise genutzt werden – entweder als „Raten“ verbunden oder als zusätzlicher NFS-Datenspeicher.

Besuchen Sie link:ehc-support-configs.html["Unterstützte NetApp Storage-Optionen"] Finden Sie weitere Informationen.

Google Cloud unterstützt NetApp Storage in den folgenden Konfigurationen:

* Cloud Volumes ONTAP (CVO) als Storage mit Gastzugriff
* Cloud Volumes Service (CVS) als Storage mit Gastverbunden
* Cloud Volumes Service (CVS) als zusätzlicher NFS Datastore


Details anzeigen link:gcp-guest.html["Speicheroptionen für die Gastverbindung für GCVE"].

Weitere Informationen link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Unterstützung von NetApp Cloud Volumes Service Datastores für die Google Cloud VMware Engine"^]



== Anwendungsfälle Für Lösungen

Mit Cloud-Lösungen von NetApp und VMware können viele Anwendungsfälle problemlos in Azure AVS implementiert werden. se-Fälle werden für jeden der von VMware definierten Cloud-Bereiche definiert:

* Schutz (sowohl Disaster Recovery als auch Backup/Restore)
* Erweitern
* Migrieren


link:gcp-solutions.html["Informieren Sie sich über die NetApp Lösungen für Google Cloud GCVE"]
